(() => {
'use strict';
const $=s=>document.querySelector(s);const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));let csrf='',threads=[],active='',loading=false;
async function req(url,opt={}){const r=await fetch(url,{cache:'no-store',headers:{Accept:'application/json',...(opt.body?{'Content-Type':'application/json','X-CSRF-Token':csrf}:{}),...(opt.headers||{})},...opt});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.message||'Request failed.');return d}async function post(body){return req('api/agent-workspace.php',{method:'POST',body:JSON.stringify({...body,csrf_token:csrf})})}
function status(t,ms=0){const e=$('#canvasStatus');if(!e)return;e.textContent=t||'';e.style.display=t?'block':'none';if(ms)setTimeout(()=>{if(e.textContent===t)e.style.display='none'},ms)}
function fmt(v){if(!v)return'';try{return new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}).format(new Date(String(v).replace(' ','T')))}catch{return String(v)}}
function renderThreads(){const root=$('#threadList');root.innerHTML=threads.map(t=>`<button class="thread ${t.public_id===active?'active':''}" data-thread="${esc(t.public_id)}"><strong>${esc(t.title||'Conversation')}</strong><small>${Number(t.message_count||0)} messages · ${esc(fmt(t.last_message_at||t.created_at))}</small></button>`).join('')||'<div class="empty">No conversations.</div>';root.querySelectorAll('[data-thread]').forEach(b=>b.onclick=()=>openThread(b.dataset.thread))}
function structuredCard(data,skill,sources=[]){if(data==null)return'<div class="empty">No structured result for this response.</div>';const arr=Array.isArray(data)?data:[data];return `<div class="result-card"><h3>${esc(skill||'Agent result')}</h3><span class="pill">${arr.length} record${arr.length===1?'':'s'}</span></div>`+arr.slice(0,30).map((row,i)=>{if(row===null||typeof row!=='object')return`<div class="result-card"><div>${esc(row)}</div></div>`;const entries=Object.entries(row).filter(([,v])=>v===null||['string','number','boolean'].includes(typeof v)).slice(0,14);return`<div class="result-card"><h3>${esc(row.name||row.title||row.business_name||row.display_name||`Result ${i+1}`)}</h3><div class="kv">${entries.map(([k,v])=>`<b>${esc(k.replace(/_/g,' '))}</b><span>${esc(v)}</span>`).join('')}</div></div>`}).join('')+(sources.length?`<div class="result-card"><h3>Sources</h3><div>${sources.map(s=>`<span class="pill">${esc(s)}</span>`).join(' ')}</div></div>`:'')}
function renderMessages(messages){const root=$('#canvasMessages');if(!messages.length){root.innerHTML='<div class="empty">Start a conversation with Gelato. Your messages and operational results will remain available here.</div>';$('#resultBody').innerHTML='<div class="empty">Structured Agent results will appear here.</div>';return}root.innerHTML=messages.map(m=>`<article class="msg ${m.role==='user'?'user':'agent'}"><div><div class="bubble">${esc(m.content)}</div><div class="meta">${m.role==='user'?'You':'Gelato'} · ${esc(m.channel||'text')}${m.skill?' · '+esc(m.skill):''} · ${esc(fmt(m.created_at))}</div></div></article>`).join('');root.scrollTop=root.scrollHeight;const structured=[...messages].reverse().find(m=>m.structured!=null);$('#resultBody').innerHTML=structured?structuredCard(structured.structured,structured.skill,structured.sources||[]):'<div class="empty">No structured result in this conversation yet.</div>'}
async function load(){if(loading)return;loading=true;try{const d=await req('api/agent-workspace.php?action=bootstrap');csrf=d.csrf;threads=d.threads||[];active=active||d.activeThread||'';window.GelatoGlobalAgent?.selectThread?.(active);renderThreads();if(active)await openThread(active)}finally{loading=false}}
async function openThread(id){const d=await req('api/agent-workspace.php?action=thread&id='+encodeURIComponent(id));if(!d.thread)throw new Error('Conversation not found.');active=id;window.GelatoGlobalAgent?.selectThread?.(id);$('#threadTitle').textContent=d.thread.title||'Restaurant Agent';$('#threadMeta').textContent=`${d.messages?.length||0} messages · permission-scoped`;renderMessages(d.messages||[]);const list=await req('api/agent-workspace.php?action=threads');threads=list.threads||threads;renderThreads();$('#canvasSide').classList.remove('open')}
async function newThread(){const d=await post({action:'new_thread'});threads.unshift(d.thread);await openThread(d.thread.public_id);$('#canvasInput').focus()}
async function submit(){const e=$('#canvasInput'),text=e.value.trim();if(!text||!window.GelatoGlobalAgent)return;e.value='';status('Gelato is working…');try{await window.GelatoGlobalAgent.send(text,false)}catch(err){status(err.message,4000)}}
$('#newThread').onclick=()=>newThread().catch(e=>status(e.message,4000));$('#canvasSend').onclick=submit;$('#canvasInput').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();submit()}});$('#canvasMic').onclick=()=>window.GelatoGlobalAgent?.talkOnce();$('#mobileThreads').onclick=()=>$('#canvasSide').classList.toggle('open');
window.addEventListener('gelato-agent-ready',()=>load().catch(e=>status(e.message,5000)));window.addEventListener('gelato-agent-response',async e=>{try{if(e.detail?.threadId===active){await openThread(active);const r=e.detail.result||{};if(r.data!=null)$('#resultBody').innerHTML=structuredCard(r.data,r.skill,r.sources||[])}status('',0)}catch(err){status(err.message,4000)}});
if(window.GelatoGlobalAgent?.user)load().catch(e=>status(e.message,5000));
})();