(()=>{'use strict';
const cfg=window.DAILY_MANAGER_CONFIG||{};const $=id=>document.getElementById(id);const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));const money=n=>'$'+Number(n||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2});const num=(n,d=0)=>Number(n||0).toLocaleString(undefined,{minimumFractionDigits:d,maximumFractionDigits:d});const state={brief:null,locations:[],permissions:{view:true,manage:!!cfg.canManage}};
function toast(m){const el=$('toast');el.textContent=m;el.classList.remove('hidden');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.add('hidden'),3200)}
function today(){const d=new Date();return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,10)}
async function apiGet(){const q=new URLSearchParams({date:$('date').value||today(),phase:$('phase').value});if($('location').value)q.set('locationId',$('location').value);const r=await fetch('api/daily-manager.php?'+q.toString(),{headers:{Accept:'application/json'},cache:'no-store'});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.message||'Daily Manager Brief request failed.');return d}
async function apiPost(payload){const r=await fetch('api/daily-manager.php',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':cfg.csrf||'',Accept:'application/json'},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.message||'Daily Manager Brief action failed.');return d}
function sourceBadge(name,status){return `<span class="source ${status==='ready'?'':'bad'}">${esc(name)} · ${esc(status)}</span>`}
function renderSources(){const s=state.brief.sourceStatus||{};$('sources').innerHTML=Object.entries(s).map(([k,v])=>sourceBadge(k.replace(/(^.|_.)/g,x=>x.replace('_',' ').toUpperCase()),v)).join('')}
function kpi(label,value,detail=''){return `<article class="panel kpi"><span>${esc(label)}</span><strong>${esc(value)}</strong><small>${esc(detail)}</small></article>`}
function renderKpis(){const b=state.brief,a=b.sales.actual||{},f=b.sales.forecast||{},unacked=(b.exceptions||[]).filter(x=>!x.acknowledged),high=unacked.filter(x=>x.severity==='high').length;$('kpis').innerHTML=[kpi('Net sales',money(a.netSales||b.pos.paidSales||0),a.tickets?`${num(a.tickets)} tickets`:'Recorded today'),kpi('Forecast',f.projected_net_sales!=null?money(f.projected_net_sales):'Unknown',f.projected_covers!=null?`${num(f.projected_covers)} covers`:'No daily forecast'),kpi('Labor',`${num(b.labor.scheduledHours,1)} h`,`${num(b.labor.unassignedShifts)} unassigned`),kpi('Open tasks',num(b.tasks.open),`${num(b.tasks.blocked)} blocked · ${num(b.tasks.overdue)} overdue`),kpi('Open checks',num(b.pos.openChecks),`${num(b.pos.paidChecks)} paid`),kpi('Exceptions',num(unacked.length),`${high} high priority`)].join('')}
function renderNote(){const b=state.brief,phase=b.phase,log=b.log||{};const editable=state.permissions.manage&&(phase==='opening'||phase==='closing');$('noteTitle').textContent=phase==='opening'?'Opening manager note':phase==='closing'?'Closing manager note':'Opening / closing notes';$('saveNote').disabled=!editable;$('ackPhase').disabled=!editable;$('note').disabled=!editable;if(phase==='opening'){$('note').value=log.opening_note||'';$('ackPhase').checked=!!log.opening_acknowledged_at;$('noteMeta').textContent=log.opening_acknowledged_at?`Reviewed ${log.opening_acknowledged_at}${log.opening_acknowledged_by_name?' by '+log.opening_acknowledged_by_name:''}`:'Opening brief not yet marked reviewed.';}else if(phase==='closing'){$('note').value=log.closing_note||'';$('ackPhase').checked=!!log.closing_acknowledged_at;$('noteMeta').textContent=log.closing_acknowledged_at?`Reviewed ${log.closing_acknowledged_at}${log.closing_acknowledged_by_name?' by '+log.closing_acknowledged_by_name:''}`:'Closing brief not yet marked reviewed.';}else{$('note').value=[log.opening_note?`Opening: ${log.opening_note}`:'',log.closing_note?`Closing: ${log.closing_note}`:''].filter(Boolean).join('\n\n');$('ackPhase').checked=false;$('noteMeta').textContent='Switch to Opening or Closing to record a manager note or mark that phase reviewed.'}}
function exceptionHtml(e){const ack=e.acknowledged;return `<article class="exception ${esc(e.severity)} ${ack?'ack':''}"><div class="exception-head"><strong>${esc(e.title)}</strong><span class="chip ${esc(e.severity)}">${ack?'acknowledged':esc(e.severity)}</span></div><p>${esc(e.detail)}</p>${ack?`<div class="muted">Acknowledged ${esc(e.acknowledgement?.acknowledgedAt||'')}${e.acknowledgement?.actorName?' by '+esc(e.acknowledgement.actorName):''}${e.acknowledgement?.note?' · '+esc(e.acknowledgement.note):''}</div>`:state.permissions.manage?`<div class="ack-row"><input data-ack-note="${esc(e.key)}" maxlength="1200" placeholder="Optional manager note"><button class="btn" data-ack="${esc(e.key)}">Acknowledge</button></div>`:''}</article>`}
function renderExceptions(){const e=state.brief.exceptions||[];$('exceptions').innerHTML=e.length?e.map(exceptionHtml).join(''):'<div class="empty">No operating exceptions are recorded for this brief.</div>'}
function lines(rows){return rows.map(([a,b])=>`<div class="metric-line"><span>${esc(a)}</span><strong>${esc(b)}</strong></div>`).join('')}
function shortList(items,fn,empty='None recorded'){return items&&items.length?`<div class="list">${items.slice(0,7).map(x=>`<div class="item">${fn(x)}</div>`).join('')}</div>`:`<div class="empty">${esc(empty)}</div>`}
function module(title,body){return `<article class="module"><h3>${esc(title)}</h3>${body}</article>`}
function renderModules(){const b=state.brief,a=b.sales.actual||{},f=b.sales.forecast||{};const sales=module('Sales + demand',lines([['Actual net',money(a.netSales||0)],['Forecast net',f.projected_net_sales!=null?money(f.projected_net_sales):'Unknown'],['Covers',num(a.covers||0)],['Average check',a.averageCheck!=null?money(a.averageCheck):'—'],['Labor %',a.laborPercent!=null?num(a.laborPercent,1)+'%':'—']]));const labor=module('Labor coverage',lines([['Published shifts',num(b.labor.shiftCount)],['Scheduled hours',num(b.labor.scheduledHours,1)],['Unassigned',num(b.labor.unassignedShifts)],['Pending requests',num(b.labor.pendingRequests)],['Forecast hours',f.projected_labor_hours!=null?num(f.projected_labor_hours,1):'Unknown']]));const poscrm=module('POS + customer activity',lines([['Open checks',num(b.pos.openChecks)],['Paid checks',num(b.pos.paidChecks)],['Linked customers',num(b.crm.linkedCustomers)],['New customers',num(b.crm.newCustomers)],['Returning',num(b.crm.returningCustomers)]]));const tasks=module('Operating tasks',lines([['Open',num(b.tasks.open)],['Blocked',num(b.tasks.blocked)],['Critical',num(b.tasks.critical)],['Overdue',num(b.tasks.overdue)]])+shortList(b.tasks.items,x=>`<b>${esc(x.title)}</b><br>${esc(x.category||'task')} · ${esc(x.status)}${x.station?' · '+esc(x.station):''}`,'No open operating tasks.'));const inventory=module('Inventory risk',lines([['At/below reorder',num(b.inventory.lowCount)]])+shortList(b.inventory.items,x=>`<b>${esc(x.name)}</b><br>${num(x.on_hand_quantity,2)} ${esc(x.base_unit||'')} on hand · reorder ${num(x.reorder_point,2)}`,'No items at or below reorder point.'));const purchasing=module('Purchasing',lines([['Due today',num(b.purchasing.dueToday)],['Overdue',num(b.purchasing.overdue)]])+shortList(b.purchasing.orders,x=>`<b>${esc(x.order_number)}</b> · ${esc(x.vendor_name)}<br>${esc(x.expected_delivery_date)} · ${esc(x.status)} · ${money(x.total_amount)}`,'No due or overdue purchase orders.'));const handoffs=module('Shift handoffs',lines([['Open',num(b.handoffs.open)],['High priority',num(b.handoffs.highPriority)]])+shortList(b.handoffs.items,x=>`<b>${esc(x.title)}</b><br>${esc(x.priority)} · ${esc(x.location_name||'All locations')}`,'No active handoffs.'));$('modules').innerHTML=[sales,labor,poscrm,tasks,inventory,purchasing,handoffs].join('')}
function render(){const b=state.brief;$('eyebrow').textContent=`${b.location.name} · ${b.businessDate} · ${b.phase}`;$('headline').textContent=b.phase==='opening'?'Opening readiness':b.phase==='closing'?'Closing recap':'Live restaurant status';$('summary').textContent=b.summary;renderSources();renderKpis();renderNote();renderExceptions();renderModules()}
function renderLocations(){const current=$('location').value;$('location').innerHTML='<option value="">All locations</option>'+state.locations.map(l=>`<option value="${Number(l.id)}">${esc(l.name)}</option>`).join('');$('location').value=current}
async function load(){try{const d=await apiGet();state.brief=d.brief;state.locations=d.locations||[];state.permissions=d.permissions||state.permissions;renderLocations();render()}catch(e){toast(e.message)}}
$('refresh').addEventListener('click',load);$('date').addEventListener('change',load);$('location').addEventListener('change',load);$('phase').addEventListener('change',load);
$('saveNote').addEventListener('click',async()=>{const phase=$('phase').value;if(!['opening','closing'].includes(phase))return;try{const d=await apiPost({action:'phase.save',date:$('date').value,locationId:$('location').value||0,phase,note:$('note').value,acknowledge:$('ackPhase').checked});state.brief=d.brief;render();toast('Manager '+phase+' note saved.')}catch(e){toast(e.message)}});
$('exceptions').addEventListener('click',async e=>{const b=e.target.closest('[data-ack]');if(!b)return;const key=b.dataset.ack,n=document.querySelector(`[data-ack-note="${CSS.escape(key)}"]`);try{const d=await apiPost({action:'exception.ack',date:$('date').value,locationId:$('location').value||0,phase:$('phase').value,exceptionKey:key,note:n?n.value:''});state.brief=d.brief;render();toast('Operating exception acknowledged.')}catch(err){toast(err.message)}});
$('date').value=today();load();
})();