(()=>{'use strict';
const C=window.KDS_CONFIG||{};
const S={locationId:0,station:'',completed:false,data:null,timer:null,loading:false,selectedTicketId:'',lastBumpedId:'',started:false,leaving:false};
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const fmtAge=s=>{s=Math.max(0,Number(s)||0);const m=Math.floor(s/60),r=s%60;return m+':'+String(r).padStart(2,'0')};
const fmtQty=n=>{const v=Number(n)||0;return Number.isInteger(v)?String(v):v.toFixed(2).replace(/0+$/,'').replace(/\.$/,'')};
const label=s=>String(s||'').replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
const canUpdate=()=>Boolean(S.data?.permissions?.update);
function toast(message){const e=$('#toast');e.textContent=message;e.classList.remove('hidden');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.add('hidden'),2200)}
async function api(method='GET',body=null){let url='api/kds.php';if(method==='GET'){const q=new URLSearchParams();if(S.locationId)q.set('locationId',S.locationId);if(S.station)q.set('station',S.station);if(S.completed)q.set('completed','1');url+='?'+q.toString()}const options={method,headers:{Accept:'application/json'},cache:'no-store'};if(body){options.headers['Content-Type']='application/json';body.csrf=C.csrf;options.body=JSON.stringify(body)}const response=await fetch(url,options),json=await response.json().catch(()=>({ok:false,message:'Invalid server response.'}));if(!response.ok||!json.ok)throw new Error(json.message||'Kitchen request failed.');return json}
function stationOptions(selected=''){const stations=S.data?.board?.stations||[];return '<option value="">Unrouted</option>'+stations.map(s=>`<option value="${esc(s.public_id)}" ${String(selected)===String(s.public_id)?'selected':''}>${esc(s.name)}</option>`).join('')}
function renderLocations(){const el=$('#location'),locations=S.data?.locations||[];el.innerHTML=locations.map(l=>`<option value="${Number(l.id)}" ${Number(l.id)===Number(S.locationId)?'selected':''}>${esc(l.name)}</option>`).join('')}
function renderTabs(){const board=S.data?.board||{},counts=board.stationCounts||{},stations=board.stations||[];const tabs=[['','Expo / All',Number(counts.all||0)],['unrouted','Unrouted',Number(counts.unrouted||0)],...stations.map(s=>[String(s.public_id),String(s.name),Number(counts[s.public_id]||0)])];$('#tabs').innerHTML=tabs.map(([id,name,count])=>`<button class="tab ${S.station===id?'active':''}" data-station="${esc(id)}">${esc(name)} · ${count}</button>`).join('')}
function renderAlert(){const count=Number(S.data?.board?.metrics?.unrouted||0),el=$('#unroutedAlert');el.classList.toggle('show',count>0);el.innerHTML=count>0?`<strong>${count} unrouted kitchen item${count===1?'':'s'}.</strong> Route ${count===1?'it':'them'} before production can advance.`:''}
function renderAllDay(){const list=S.data?.board?.allDay||[],el=$('#allDay');if(!list.length){el.innerHTML='<div class="empty">No active fired items.</div>';return}el.innerHTML=list.map(row=>`<div class="all-day-row"><div><strong>${esc(row.name)}</strong><small>${fmtQty(row.queued)} queued · ${fmtQty(row.inProgress)} cooking · ${fmtQty(row.ready)} ready</small></div><div class="qty">${fmtQty(row.quantity)}</div></div>`).join('')}
function statusChip(item){const status=String(item.status||'');const klass=status==='ready'?'ready':status==='in_progress'?'progress':status==='held'?'held':'';return `<span class="chip ${klass}">${esc(label(status))}</span>`}
function itemActionButtons(item){if(!canUpdate())return'';const status=String(item.status||'');let out='';if(status==='held')out+='<button class="action" data-item-act="queued">Fire</button>';if(status==='queued')out+='<button class="action" data-item-act="in_progress">Start</button><button class="action alt" data-item-act="held">Hold</button>';if(status==='in_progress')out+='<button class="action good" data-item-act="ready">Ready</button>';if(status==='ready')out+='<button class="action good" data-item-act="completed">Complete</button><button class="action alt" data-item-act="in_progress">Undo</button>';if(status==='completed'&&item.recallable)out+='<button class="action warn" data-item-recall>Recall</button>';return out}
function renderItem(item){const context=[];if(item.seat_number!==null&&item.seat_number!==undefined)context.push(`Seat ${Number(item.seat_number)}`);if(item.course_key)context.push(label(item.course_key));if(item.station_name)context.push(String(item.station_name));const sla=item.late?'<span class="chip late">Late</span>':item.warning?'<span class="chip warn">SLA warning</span>':'';const route=canUpdate()&&!['completed','cancelled'].includes(String(item.status||''))?`<select class="route" data-route>${stationOptions(item.station_public_id||'')}</select>`:`<span class="fs-note">${item.station_name?esc(item.station_name):'Unrouted'}</span>`;return `<div class="kitem" data-item="${esc(item.public_id)}"><div class="kitem-top"><div><div class="kitem-name">${esc(fmtQty(item.quantity))}× ${esc(item.item_name_snapshot)}</div>${item.option_name_snapshot?`<div class="option">${esc(item.option_name_snapshot)}</div>`:''}</div><div class="age ${item.late?'late':item.warning?'warning':''}">${String(item.status)==='held'?'HOLD':fmtAge(item.ageSeconds)}</div></div>${item.special_instructions?`<div class="instructions">${esc(item.special_instructions)}</div>`:''}<div class="item-meta">${statusChip(item)}${context.map(v=>`<span class="chip">${esc(v)}</span>`).join('')}${!item.station_id&&!['completed','cancelled'].includes(String(item.status||''))?'<span class="chip unrouted">Needs routing</span>':''}${sla}</div><div class="item-controls">${route}<div class="item-actions">${itemActionButtons(item)}</div></div></div>`}
function ticketActions(ticket){if(!canUpdate())return'';const buttons=[];if(Number(ticket.held)>0)buttons.push('<button class="action" data-ticket-act="fire">Fire held</button>');if(Number(ticket.queued)>0){buttons.push('<button class="action alt" data-ticket-act="hold">Hold queued</button>');buttons.push('<button class="action" data-ticket-act="start">Start batch</button>')}if(Number(ticket.inProgress)>0)buttons.push('<button class="action good" data-ticket-act="ready">Ready batch</button>');if(!S.station&&ticket.readyToBump)buttons.push('<button class="action good" data-ticket-act="bump">Bump ticket</button>');if(!S.station&&Number(ticket.recallableCount)>0)buttons.push('<button class="action warn" data-ticket-act="recall">Recall ticket</button>');return buttons.join('')}
function ensureSelection(tickets){if(!tickets.length){S.selectedTicketId='';return}if(!tickets.some(t=>String(t.checkPublicId)===String(S.selectedTicketId)))S.selectedTicketId=String(tickets[0].checkPublicId)}
function renderBoard(){const tickets=S.data?.board?.tickets||[],el=$('#board');ensureSelection(tickets);if(!tickets.length){el.innerHTML='<div class="empty">No kitchen tickets in this view.</div>';return}el.innerHTML=tickets.map(ticket=>{const classes=['ticket'];if(String(ticket.checkPublicId)===String(S.selectedTicketId))classes.push('selected');if(ticket.late)classes.push('late');else if(ticket.warning)classes.push('warning');if(ticket.readyToBump)classes.push('bumpable');const headline=ticket.tableName?`${ticket.checkNumber} · ${ticket.tableName}`:ticket.checkNumber;const subtitle=[label(ticket.serviceMode),ticket.serverName?`Server ${ticket.serverName}`:null,`${Number(ticket.guestCount)} guest${Number(ticket.guestCount)===1?'':'s'}`].filter(Boolean).join(' · ');const meta=[];if(ticket.currentCourseKey)meta.push(`<span class="chip">Current ${esc(label(ticket.currentCourseKey))}</span>`);if(Number(ticket.held)>0)meta.push(`<span class="chip held">${Number(ticket.held)} held</span>`);if(Number(ticket.unrouted)>0)meta.push(`<span class="chip unrouted">${Number(ticket.unrouted)} unrouted</span>`);if(ticket.readyToBump)meta.push('<span class="chip ready">Expo ready</span>');else if(ticket.late)meta.push('<span class="chip late">Late</span>');else if(ticket.warning)meta.push('<span class="chip warn">SLA warning</span>');const actions=ticketActions(ticket);return `<article class="${classes.join(' ')}" data-ticket="${esc(ticket.checkPublicId)}" tabindex="-1"><div class="ticket-head"><div><strong>${esc(headline)}</strong><small>${esc(subtitle)}</small></div><div class="age ${ticket.late?'late':ticket.warning?'warning':''}">${Number(ticket.oldestAgeSeconds)>0?fmtAge(ticket.oldestAgeSeconds):'—'}</div></div>${meta.length?`<div class="ticket-meta">${meta.join('')}</div>`:''}<div class="ticket-items">${(ticket.items||[]).map(renderItem).join('')}</div>${actions?`<div class="ticket-actions">${actions}</div>`:''}</article>`}).join('')}
function render(){renderLocations();renderTabs();renderAlert();renderAllDay();renderBoard()}
async function load(){if(S.loading)return;S.loading=true;try{const data=await api();S.data=data;if(!S.locationId)S.locationId=Number(data.locationId)||0;render()}catch(e){toast(e.message)}finally{S.loading=false}}
async function post(body){try{const data=await api('POST',{locationId:S.locationId,station:S.station,completed:S.completed?1:0,...body});if(data.board)S.data.board=data.board;render();return data}catch(e){toast(e.message);throw e}}
function selectedTicket(){return (S.data?.board?.tickets||[]).find(t=>String(t.checkPublicId)===String(S.selectedTicketId))||null}
function selectRelative(delta){const tickets=S.data?.board?.tickets||[];if(!tickets.length)return;let i=tickets.findIndex(t=>String(t.checkPublicId)===String(S.selectedTicketId));if(i<0)i=0;else i=(i+delta+tickets.length)%tickets.length;S.selectedTicketId=String(tickets[i].checkPublicId);renderBoard();document.querySelector(`[data-ticket="${CSS.escape(S.selectedTicketId)}"]`)?.scrollIntoView({block:'nearest',inline:'nearest'})}
async function ticketAction(id,action){if(!id)return;const data=await post({action:'ticket.action',checkPublicId:id,ticketAction:action});if(action==='bump'){S.lastBumpedId=id;toast('Ticket bumped · R recalls')}if(action==='recall')toast('Ticket recalled to Expo');return data}
async function bumpSelected(){if(!canUpdate()){toast('Kitchen update permission required at this location.');return}if(S.station){toast('Whole-ticket bump is available in Expo / All.');return}const ticket=selectedTicket();if(!ticket){toast('No ticket selected.');return}if(!ticket.readyToBump){toast('Selected ticket is not ready to bump.');return}await ticketAction(String(ticket.checkPublicId),'bump').catch(()=>{})}
async function recallLast(){if(!canUpdate()){toast('Kitchen update permission required at this location.');return}if(S.station){toast('Recall the whole ticket from Expo / All.');return}if(!S.lastBumpedId){toast('No ticket has been bumped in this KDS session.');return}await ticketAction(S.lastBumpedId,'recall').catch(()=>{})}
async function startKds(){if(S.started)return;S.started=true;$('#launch').classList.add('hidden');try{if(document.documentElement.requestFullscreen)await document.documentElement.requestFullscreen()}catch(e){toast('Browser full-screen permission was blocked. Press Esc to return to the Kitchen Dashboard.')}}
function leaveToDashboard(){if(S.leaving)return;S.leaving=true;window.location.href=C.dashboardUrl||'kds-dashboard.php'}
document.addEventListener('click',async e=>{if(e.target.closest('#startKds')){await startKds();return}const tab=e.target.closest('[data-station]');if(tab){S.station=tab.dataset.station||'';S.selectedTicketId='';await load();return}const ticketCard=e.target.closest('[data-ticket]');if(ticketCard)S.selectedTicketId=String(ticketCard.dataset.ticket||'');const item=e.target.closest('[data-item]');const itemAct=e.target.closest('[data-item-act]');if(item&&itemAct){itemAct.disabled=true;await post({action:'item.transition',itemPublicId:item.dataset.item,status:itemAct.dataset.itemAct}).catch(()=>{});return}const recall=e.target.closest('[data-item-recall]');if(item&&recall){recall.disabled=true;await post({action:'item.recall',itemPublicId:item.dataset.item}).catch(()=>{});return}const ticketAct=e.target.closest('[data-ticket-act]');if(ticketCard&&ticketAct){ticketAct.disabled=true;await ticketAction(String(ticketCard.dataset.ticket),String(ticketAct.dataset.ticketAct)).catch(()=>{});return}if(ticketCard)renderBoard()});
document.addEventListener('change',async e=>{if(e.target.id==='location'){S.locationId=Number(e.target.value)||0;S.station='';S.selectedTicketId='';S.lastBumpedId='';await load();return}if(e.target.matches('[data-route]')){const item=e.target.closest('[data-item]');if(!item)return;await post({action:'item.reassign',itemPublicId:item.dataset.item,stationPublicId:e.target.value||null}).catch(()=>{})}});
document.addEventListener('keydown',async e=>{const tag=(e.target?.tagName||'').toLowerCase();if(['input','select','textarea'].includes(tag))return;if(!S.started){if(e.key==='Enter'){e.preventDefault();await startKds()}return}if(e.key==='Escape'){e.preventDefault();if(document.fullscreenElement&&document.exitFullscreen){await document.exitFullscreen().catch(()=>leaveToDashboard())}else leaveToDashboard();return}if(['ArrowRight','ArrowDown'].includes(e.key)){e.preventDefault();selectRelative(1);return}if(['ArrowLeft','ArrowUp'].includes(e.key)){e.preventDefault();selectRelative(-1);return}if(e.key==='Enter'||e.key.toLowerCase()==='b'){e.preventDefault();await bumpSelected();return}if(e.key.toLowerCase()==='r'){e.preventDefault();await recallLast();return}if(e.key.toLowerCase()==='h'){e.preventDefault();S.completed=!S.completed;$('#history').textContent=S.completed?'Hide recent completed':'Recent completed';S.selectedTicketId='';await load()}});
$('#refresh').addEventListener('click',load);$('#history').addEventListener('click',async()=>{S.completed=!S.completed;$('#history').textContent=S.completed?'Hide recent completed':'Recent completed';S.selectedTicketId='';await load()});
document.addEventListener('fullscreenchange',()=>{if(S.started&&!document.fullscreenElement)leaveToDashboard()});
load();S.timer=setInterval(load,5000);
})();