(()=>{'use strict';
const cfg=window.GELATO_POS_CONFIG||{};const $=id=>document.getElementById(id);const state={locationId:0,locations:[],settings:{},menu:[],openChecks:[],recentChecks:[],current:null,category:0,tenderType:'cash',permissions:{}};
const money=n=>'$'+Number(n||0).toFixed(2);const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function toast(message){const el=$('toast');el.textContent=message;el.classList.remove('hidden');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.add('hidden'),3300)}
async function getData(){const r=await fetch('api/pos.php?locationId='+encodeURIComponent(state.locationId||''),{headers:{Accept:'application/json'},cache:'no-store'});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.message||'POS request failed.');return d}
async function post(action,payload={}){const r=await fetch('api/pos.php',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':cfg.csrf||'',Accept:'application/json'},body:JSON.stringify({action,...payload})});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.message||'POS action failed.');return d}
async function crmGet(params){const r=await fetch('api/customer-crm.php?'+new URLSearchParams(params),{headers:{Accept:'application/json'},cache:'no-store'});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.message||'Customer lookup failed.');return d}
async function crmPost(action,payload={}){const r=await fetch('api/customer-crm.php',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':cfg.csrf||'',Accept:'application/json'},body:JSON.stringify({action,...payload})});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.message||'Customer link failed.');return d}
function show(id){$(id).classList.remove('hidden')}function hide(id){$(id).classList.add('hidden')}
function sync(d){state.locationId=Number(d.locationId||state.locationId||0);state.locations=d.locations||state.locations;state.settings=d.settings||state.settings;state.menu=d.menu||state.menu;state.openChecks=d.openChecks||state.openChecks;state.recentChecks=d.recentChecks||state.recentChecks;state.permissions=d.permissions||state.permissions;if(d.check!==undefined)state.current=d.check;render()}
async function load(keepCurrent=true){try{const currentId=keepCurrent&&state.current&&state.current.status==='open'?state.current.publicId:null;const d=await getData();sync(d);if(currentId){const r=await fetch('api/pos.php?locationId='+state.locationId+'&check='+encodeURIComponent(currentId),{headers:{Accept:'application/json'},cache:'no-store'});const x=await r.json();if(r.ok&&x.ok){state.current=x.check;state.permissions=x.permissions||state.permissions;render()}}}catch(e){toast(e.message)}}
function renderLocations(){const el=$('locationSelect');el.innerHTML=state.locations.map(l=>`<option value="${Number(l.id)}" ${Number(l.id)===Number(state.locationId)?'selected':''}>${esc(l.name)}</option>`).join('')}
function renderChecks(){const el=$('openChecks');if(!state.openChecks.length){el.innerHTML='<div class="empty">No open checks. Start a new order.</div>';return}el.innerHTML=state.openChecks.map(c=>`<button class="check-chip ${state.current&&state.current.publicId===c.public_id?'active':''}" data-check="${esc(c.public_id)}"><strong>${esc(c.check_number)}</strong><span>${esc(c.table_name||c.service_mode.replace('_',' '))} · ${money(c.total_amount)}</span></button>`).join('')}
function renderCategories(){const el=$('categories');if(!state.menu.length){el.innerHTML='';return}if(!state.category||!state.menu.some(s=>Number(s.id)===Number(state.category)))state.category=Number(state.menu[0].id);el.innerHTML=state.menu.map(s=>`<button class="category ${Number(s.id)===Number(state.category)?'active':''}" data-category="${Number(s.id)}">${esc(s.name)}</button>`).join('')}
function renderMenu(){const el=$('menuGrid');const section=state.menu.find(s=>Number(s.id)===Number(state.category));if(!section||!section.items.length){el.innerHTML='<div class="empty">No active priced items in this section.</div>';return}const disabled=!state.current||state.current.status!=='open';el.innerHTML=section.items.map(i=>`<article class="menu-card"><h3>${esc(i.name)}</h3><p>${esc(i.description||'')}</p><select id="price-${Number(i.id)}">${i.prices.map(p=>`<option value="${Number(p.id)}">${esc(p.optionName)} · ${money(p.amount)}</option>`).join('')}</select><button class="btn dark" data-add="${Number(i.id)}" ${disabled?'disabled':''}>Add to check</button></article>`).join('')}
function itemById(id){return state.current&&state.current.items?state.current.items.find(i=>Number(i.id)===Number(id)):null}
function kitchenItemByLine(id){const items=state.current?.kitchen?.items||[];return items.find(i=>Number(i.pos_check_item_id)===Number(id))||null}
function customerBlock(c){if(!state.permissions.customerLink||c.status!=='open')return c.customer?`<div class="customer-link"><div><strong>${esc(c.customer.displayName)}</strong><small>Customer attached</small></div></div>`:'';if(c.customer)return `<div class="customer-link"><div><strong>${esc(c.customer.displayName)}</strong><small>${esc(c.customer.email||c.customer.phone||'CRM customer')}</small></div><div><button class="mini" id="changeCustomer">Change</button> <button class="mini bad" id="detachCustomer">Remove</button></div></div>`;return '<div class="customer-link"><div><strong>Walk-in guest</strong><small>No customer attached</small></div><button class="mini" id="attachCustomer">Attach customer</button></div>'}
function renderTicket(){const c=state.current;if(!c){$('ticketHead').innerHTML='<div class="ticket-title"><h2>No open check</h2><span class="status">Ready</span></div><div class="meta">Create or select a check to start an order.</div>';$('ticketItems').innerHTML='<div class="empty">Your ticket appears here.</div>';$('ticketFoot').innerHTML='<div class="totals"><div class="total-row"><span>Subtotal</span><strong>$0.00</strong></div><div class="total-row grand"><span>Total</span><strong>$0.00</strong></div></div><div class="pay-grid"><button class="btn" disabled>Cash</button><button class="btn" disabled>Card terminal</button></div>';return}
 $('ticketHead').innerHTML=`<div class="ticket-title"><h2>${esc(c.checkNumber)}</h2><span class="status">${esc(c.status)}</span></div><div class="meta">${esc(c.locationName)} · ${esc(c.serviceMode.replace('_',' '))}${c.tableName?' · '+esc(c.tableName):''} · ${Number(c.guestCount)} guest${Number(c.guestCount)===1?'':'s'} · ${esc(c.openedBy)}</div>${customerBlock(c)}`;
 const active=c.status==='open';$('ticketItems').innerHTML=c.items.length?c.items.map(i=>{const k=kitchenItemByLine(i.id);const sent=!!k;const kitchenMeta=sent?`<div class="kitchen-line"><span class="kitchen-chip sent">Kitchen · ${esc(String(k.status||'sent').replace('_',' '))}</span>${k.station_name?`<span class="kitchen-chip">${esc(k.station_name)}</span>`:'<span class="kitchen-chip unrouted">Unrouted</span>'}</div>`:'';let actions='';if(active&&i.status==='active'){if(!sent)actions=`<div class="line-actions"><button class="mini" data-line="${Number(i.id)}" data-act="minus">−</button><button class="mini" data-line="${Number(i.id)}" data-act="plus">+</button><button class="mini" data-line="${Number(i.id)}" data-act="note">Note</button>${state.permissions.void?`<button class="mini bad" data-line="${Number(i.id)}" data-act="void">Void</button>`:''}</div>`;else if(state.permissions.void)actions=`<div class="line-actions"><button class="mini bad" data-line="${Number(i.id)}" data-act="void">Void sent item</button></div>`}return `<div class="line ${i.status!=='active'?'voided':''}"><div class="line-top"><div><strong>${esc(i.item_name_snapshot)}</strong><br><small>${esc(i.option_name_snapshot)} · ${Number(i.quantity)} × ${money(i.unit_price)}${i.special_instructions?'<br>Note: '+esc(i.special_instructions):''}</small>${kitchenMeta}</div><strong>${money(i.gross_amount)}</strong></div>${actions}</div>`}).join(''):'<div class="empty">Add menu items to this check.</div>';
 const kitchen=c.kitchen||{ready:false,sent:0,unsent:0,unrouted:0,items:[]};const canSend=active&&state.permissions.kdsAvailable&&kitchen.ready&&Number(kitchen.unsent)>0;const kitchenRow=state.permissions.kdsAvailable&&kitchen.ready?`<div class="total-row"><span>Kitchen</span><strong>${Number(kitchen.sent)} sent · ${Number(kitchen.unsent)} unsent${Number(kitchen.unrouted)>0?' · '+Number(kitchen.unrouted)+' unrouted':''}</strong></div>`:'';const payEnabled=active&&Number(c.balanceDue)>0&&c.items.some(i=>i.status==='active');$('ticketFoot').innerHTML=`<div class="totals"><div class="total-row"><span>Subtotal</span><strong>${money(c.subtotal)}</strong></div>${Number(c.discountAmount)>0?`<div class="total-row"><span>Discount</span><strong>−${money(c.discountAmount)}</strong></div>`:''}${Number(c.taxAmount)>0?`<div class="total-row"><span>Tax</span><strong>${money(c.taxAmount)}</strong></div>`:''}${Number(c.serviceChargeAmount)>0?`<div class="total-row"><span>Service charge</span><strong>${money(c.serviceChargeAmount)}</strong></div>`:''}${Number(c.tipAmount)>0?`<div class="total-row"><span>Tips</span><strong>${money(c.tipAmount)}</strong></div>`:''}${kitchenRow}<div class="total-row grand"><span>Total</span><strong>${money(c.totalAmount)}</strong></div>${active?`<div class="total-row balance"><span>Balance due</span><strong>${money(c.balanceDue)}</strong></div>`:''}</div><div class="pay-grid">${state.permissions.kdsAvailable&&active?`<button class="btn accent" id="kitchenSend" ${canSend?'':'disabled'}>Send to kitchen</button><button class="btn" id="kitchenHold" ${canSend?'':'disabled'}>Send held</button>`:''}<button class="btn dark" data-pay="cash" ${payEnabled?'':'disabled'}>Cash</button><button class="btn dark" data-pay="external_card" ${payEnabled?'':'disabled'}>Card terminal</button>${state.permissions.discount&&active?'<button class="btn" id="discountBtn">Discount</button>':'<span></span>'}${state.permissions.void&&active?'<button class="btn bad" id="cancelCheck">Cancel check</button>':'<span></span>'}</div>`}
function renderSettings(){if(!state.settings)return;$('taxRate').value=(Number(state.settings.taxRate||0)*100).toFixed(3);$('serviceRate').value=(Number(state.settings.serviceChargeRate||0)*100).toFixed(3);$('defaultMode').value=state.settings.defaultServiceMode||'dine_in';$('settingsBtn').style.display=state.permissions.manage?'':'none'}
function render(){renderLocations();renderChecks();renderCategories();renderMenu();renderTicket();renderSettings()}
async function selectCheck(publicId){try{const r=await fetch('api/pos.php?locationId='+state.locationId+'&check='+encodeURIComponent(publicId),{headers:{Accept:'application/json'},cache:'no-store'});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.message||'Could not load check.');sync(d)}catch(e){toast(e.message)}}
async function mutate(action,payload){try{const d=await post(action,payload);if(d.check)state.current=d.check;if(d.openChecks)state.openChecks=d.openChecks;if(d.recentChecks)state.recentChecks=d.recentChecks;if(d.settings)state.settings=d.settings;render();return d}catch(e){toast(e.message);throw e}}
async function searchCustomers(){if(!state.permissions.customerLink)return;const q=$('customerSearch').value.trim();try{const d=await crmGet({action:'search',scope:'pos',q,limit:'25'});const list=d.customers||[];$('customerResults').innerHTML=list.length?list.map(c=>`<button class="customer-result" data-attach-customer="${esc(c.publicId)}"><div><strong>${esc(c.displayName)}</strong><small>${esc(c.email||c.phone||'No contact channel')}</small></div><span class="mini">Attach</span></button>`).join(''):'<div class="empty">No matching customers.</div>'}catch(e){toast(e.message)}}
function openCustomerPicker(){if(!state.current||!state.permissions.customerLink)return;$('customerSearch').value='';$('customerResults').innerHTML='<div class="empty">Search the CRM to attach an existing customer.</div>';show('customerModal');setTimeout(()=>$('customerSearch').focus(),0)}
$('locationSelect').addEventListener('change',async e=>{state.locationId=Number(e.target.value);state.current=null;await load(false)});$('newCheck').addEventListener('click',()=>{if(!state.locationId)return toast('Create an active location first.');$('newMode').value=state.settings.defaultServiceMode||'dine_in';show('newModal')});$('createCheck').addEventListener('click',async()=>{try{await mutate('check.create',{locationId:state.locationId,serviceMode:$('newMode').value,guestCount:Number($('newGuests').value||1),tableName:$('newTable').value,notes:$('newNotes').value});hide('newModal');$('newTable').value='';$('newNotes').value=''}catch(e){}});
$('openChecks').addEventListener('click',e=>{const b=e.target.closest('[data-check]');if(b)selectCheck(b.dataset.check)});$('categories').addEventListener('click',e=>{const b=e.target.closest('[data-category]');if(!b)return;state.category=Number(b.dataset.category);renderCategories();renderMenu()});$('menuGrid').addEventListener('click',async e=>{const b=e.target.closest('[data-add]');if(!b||!state.current)return;const price=$('price-'+Number(b.dataset.add));if(!price)return;await mutate('item.add',{checkPublicId:state.current.publicId,priceId:Number(price.value),quantity:1})});
$('ticketHead').addEventListener('click',async e=>{if(e.target.id==='attachCustomer'||e.target.id==='changeCustomer')openCustomerPicker();if(e.target.id==='detachCustomer'&&state.current){try{const d=await crmPost('pos.detach',{checkPublicId:state.current.publicId});state.current.customer=d.customer||null;renderTicket();toast('Customer removed from check.')}catch(x){toast(x.message)}}});
$('ticketItems').addEventListener('click',async e=>{const b=e.target.closest('[data-line]');if(!b||!state.current)return;const item=itemById(Number(b.dataset.line));if(!item)return;const act=b.dataset.act;if(act==='minus'){const q=Math.max(.001,Number(item.quantity)-1);if(Number(item.quantity)<=1)return toast('Use Void to remove an ordered item.');await mutate('item.update',{checkPublicId:state.current.publicId,itemId:Number(item.id),quantity:q,specialInstructions:item.special_instructions||''})}if(act==='plus')await mutate('item.update',{checkPublicId:state.current.publicId,itemId:Number(item.id),quantity:Number(item.quantity)+1,specialInstructions:item.special_instructions||''});if(act==='note'){const note=prompt('Special instructions',item.special_instructions||'');if(note!==null)await mutate('item.update',{checkPublicId:state.current.publicId,itemId:Number(item.id),quantity:Number(item.quantity),specialInstructions:note})}if(act==='void'){const reason=prompt('Void reason');if(reason)await mutate('item.void',{checkPublicId:state.current.publicId,itemId:Number(item.id),reason})}});
$('ticketFoot').addEventListener('click',async e=>{if((e.target.id==='kitchenSend'||e.target.id==='kitchenHold')&&state.current){try{const held=e.target.id==='kitchenHold';const d=await mutate('kitchen.send',{checkPublicId:state.current.publicId,hold:held});const k=d.kitchen||state.current.kitchen||{};toast(held?'Items sent to kitchen on hold.':`Sent to kitchen${Number(k.unrouted)>0?' · '+Number(k.unrouted)+' unrouted':''}.`)}catch(x){}return}const pay=e.target.closest('[data-pay]');if(pay&&state.current){state.tenderType=pay.dataset.pay;$('payTitle').textContent=state.tenderType==='cash'?'Record cash':'Record external terminal payment';$('payAmount').value=Number(state.current.balanceDue).toFixed(2);$('payTip').value='0.00';$('cashReceived').value=Number(state.current.balanceDue).toFixed(2);$('terminalReference').value='';$('cashReceivedWrap').style.display=state.tenderType==='cash'?'grid':'none';$('referenceWrap').style.display=state.tenderType==='external_card'?'grid':'none';show('payModal');return}if(e.target.id==='discountBtn'&&state.current){const current=Number(state.current.discountAmount||0).toFixed(2);const raw=prompt('Discount amount',current);if(raw===null)return;const amount=Number(raw);if(!Number.isFinite(amount)||amount<0)return toast('Enter a valid discount amount.');let reason='';if(amount>0){reason=prompt('Discount reason',state.current.discountReason||'')||'';if(!reason)return toast('A discount reason is required.')}await mutate('discount.set',{checkPublicId:state.current.publicId,amount,reason})}if(e.target.id==='cancelCheck'&&state.current){const reason=prompt('Cancellation reason');if(reason){await mutate('check.cancel',{checkPublicId:state.current.publicId,reason});state.current=null;render()}}});
$('recordPayment').addEventListener('click',async()=>{if(!state.current)return;const amount=Number($('payAmount').value||0),tip=Number($('payTip').value||0),payload={checkPublicId:state.current.publicId,tenderType:state.tenderType,amount,tipAmount:tip};if(state.tenderType==='cash')payload.receivedAmount=Number($('cashReceived').value||0);else payload.externalReference=$('terminalReference').value;try{const d=await mutate('tender.record',payload);hide('payModal');if(d.check&&d.check.status==='paid')toast('Check paid and posted to Sales Intelligence.')}catch(e){}});
$('settingsBtn').addEventListener('click',()=>show('settingsModal'));$('saveSettings').addEventListener('click',async()=>{try{await mutate('settings.save',{locationId:state.locationId,taxRate:Number($('taxRate').value||0)/100,serviceChargeRate:Number($('serviceRate').value||0)/100,defaultServiceMode:$('defaultMode').value,makePrimary:$('makePrimary').checked});hide('settingsModal');toast('POS settings saved.')}catch(e){}});
$('customerSearchBtn').addEventListener('click',searchCustomers);$('customerSearch').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();searchCustomers()}});$('customerSearch').addEventListener('input',()=>{clearTimeout(searchCustomers.t);searchCustomers.t=setTimeout(searchCustomers,240)});$('customerResults').addEventListener('click',async e=>{const b=e.target.closest('[data-attach-customer]');if(!b||!state.current)return;try{const d=await crmPost('pos.attach',{checkPublicId:state.current.publicId,customerPublicId:b.dataset.attachCustomer});state.current.customer=d.customer||null;hide('customerModal');renderTicket();toast('Customer attached to check.')}catch(x){toast(x.message)}});
document.addEventListener('click',e=>{const b=e.target.closest('[data-close]');if(b)hide(b.dataset.close)});load(false);
})();