(() => {
'use strict';
const C=window.GELATO_TIME_CLOCK;if(!C)return;let state=null;let voiceEventId='';let voiceVerifiedUntil=0;let listening=false;let recognizer=null;let proactiveTimer=null;
const $=s=>document.querySelector(s);const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(m){const e=$('#toast');if(!e)return;e.textContent=m;e.classList.remove('hidden');setTimeout(()=>e.classList.add('hidden'),3000)}function status(m){const e=$('#agentStatus');if(!e)return;e.textContent=m;e.style.display=m?'block':'none'}
async function json(url,opt={}){const r=await fetch(url,{cache:'no-store',headers:{Accept:'application/json','Content-Type':'application/json','X-CSRF-Token':C.csrf,...(opt.headers||{})},...opt});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.message||'Request failed.');return d}
async function post(url,body){return json(url,{method:'POST',body:JSON.stringify({...body,csrf_token:C.csrf})})}
const fmt=t=>t?new Intl.DateTimeFormat('en-US',{weekday:'short',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}).format(new Date(String(t).replace(' ','T'))):'—';const duration=m=>`${Math.floor(m/60)}h ${m%60}m`;
async function load(){try{const date=$('#dateFilter')?.value||C.today||new Date().toISOString().slice(0,10);state=await json(`api/timeclock.php?action=bootstrap&date=${encodeURIComponent(date)}`);render()}catch(e){toast(e.message)}}
function render(){if(!state)return;const clock=state.self?.clock;$('#clockStatus')&&($('#clockStatus').textContent=clock?'Clocked in':'Off clock');$('#clockDetail')&&($('#clockDetail').textContent=clock?`Since ${fmt(clock.clocked_in_at)}${clock.shift_title?' · '+clock.shift_title:''}`:'Ready when your shift begins.');if($('#clockIn'))$('#clockIn').disabled=!!clock;if($('#clockOut'))$('#clockOut').disabled=!clock;const shifts=(state.self?.shifts||[]).filter(s=>new Date(String(s.ends_at).replace(' ','T'))>=new Date()).sort((a,b)=>String(a.starts_at).localeCompare(String(b.starts_at)));$('#nextShift')&&($('#nextShift').textContent=shifts[0]?new Intl.DateTimeFormat('en-US',{weekday:'short',hour:'numeric',minute:'2-digit'}).format(new Date(String(shifts[0].starts_at).replace(' ','T'))):'—');$('#nextShiftDetail')&&($('#nextShiftDetail').textContent=shifts[0]?`${shifts[0].title} · ${fmt(shifts[0].starts_at)}`:'No remaining shift this week.');$('#taskCount')&&($('#taskCount').textContent=String(state.self?.tasks?.length||0));$('#taskDetail')&&($('#taskDetail').textContent=(state.self?.tasks||[]).slice(0,3).map(t=>t.title).join(' · ')||'No open assigned tasks.');if(state.summary){const d=state.summary.actualMinutes-state.summary.scheduledMinutes;$('#laborDelta')&&($('#laborDelta').textContent=(d>=0?'+':'')+duration(Math.abs(d)));$('#laborDetail')&&($('#laborDetail').textContent=`${duration(state.summary.scheduledMinutes)} scheduled · ${duration(state.summary.actualMinutes)} actual · ${state.summary.clockedInEmployees} on clock`)}renderEntries();renderVoiceProfile()}
function renderEntries(){const root=$('#attendanceRows');if(!root)return;const rows=state.entries||[];root.innerHTML=rows.length?rows.map(r=>`<article class="row" data-timeclock-user-id="${Number(r.user_id)||0}"><strong>${esc(r.display_name)}</strong><span>${esc(r.shift_title||'Unscheduled')}</span><span>${fmt(r.clocked_in_at)}</span><span>${r.clocked_out_at?fmt(r.clocked_out_at):'<span class="pill good">On clock</span>'}</span><span>${esc(r.status)}</span></article>`).join(''):'<div class="muted" style="padding:18px">No time-clock entries for this date.</div>'}
function renderVoiceProfile(){const p=state.voiceProfile;const e=$('#voiceProfileStatus');if(!e)return;e.textContent=p?`${p.status==='active'?'Enrolled':'Disabled'} · ${p.sample_count||0} sample(s)${p.last_verified_at?' · last checked '+fmt(p.last_verified_at):''}`:'Not enrolled.'}
async function timeAction(action){try{await post('api/timeclock.php',{action});toast(action.replace('_',' ')+' complete');await load()}catch(e){toast(e.message)}}
async function captureFeatures(ms=3500,wantBlob=false){if(!navigator.mediaDevices?.getUserMedia)throw new Error('Microphone capture is not available in this browser.');const stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:false}});const ctx=new (window.AudioContext||window.webkitAudioContext)();const src=ctx.createMediaStreamSource(stream);const an=ctx.createAnalyser();an.fftSize=1024;an.smoothingTimeConstant=.35;src.connect(an);const bins=new Uint8Array(an.frequencyBinCount);const bands=new Float64Array(24);let frames=0;let recorder=null,chunks=[];if(wantBlob&&window.MediaRecorder){recorder=new MediaRecorder(stream);recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};recorder.start(200)}const meter=$('#voiceMeter i');const timer=setInterval(()=>{an.getByteFrequencyData(bins);let energy=0;for(let b=0;b<24;b++){const lo=Math.floor(b*bins.length/24),hi=Math.floor((b+1)*bins.length/24);let s=0;for(let i=lo;i<hi;i++)s+=bins[i];const v=s/Math.max(1,hi-lo)/255;bands[b]+=v;energy+=v}frames++;if(meter)meter.style.width=`${Math.min(100,Math.round(energy/24*180))}%`},80);await new Promise(r=>setTimeout(r,ms));clearInterval(timer);if(recorder&&recorder.state!=='inactive'){await new Promise(resolve=>{recorder.onstop=resolve;recorder.stop()})}stream.getTracks().forEach(t=>t.stop());await ctx.close();if(meter)meter.style.width='0';let v=Array.from(bands,x=>x/Math.max(1,frames));const n=Math.sqrt(v.reduce((s,x)=>s+x*x,0));if(n<.03)throw new Error('Voice sample was too quiet. Try again closer to the microphone.');v=v.map(x=>x/n);return {features:v,blob:wantBlob&&chunks.length?new Blob(chunks,{type:chunks[0].type||'audio/webm'}):null,durationMs:ms}}
async function enrollVoice(){if(!confirm('Enroll your voice for Gelato personalization? Voice recognition will not replace your login, permissions, or manager approvals.'))return;try{status('Recording enrollment sample… speak naturally for a few seconds.');const cap=await captureFeatures(4500,true);if(!cap.blob)throw new Error('This browser cannot create a voice recording.');const f=new FormData();f.append('action','enroll');f.append('consent','1');f.append('features',JSON.stringify(cap.features));f.append('durationMs',String(cap.durationMs));f.append('transcript','Employee voice enrollment sample');f.append('csrf_token',C.csrf);f.append('audio',cap.blob,'voice-enrollment.webm');const r=await fetch('api/voice-identity.php',{method:'POST',headers:{'X-CSRF-Token':C.csrf,Accept:'application/json'},body:f});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.message||'Enrollment failed.');toast(d.message);await load()}catch(e){toast(e.message)}finally{status('')}}
async function verifyVoice(){status('Voice check… speak the phrase “Hey Gelato, ready to work.”');try{const cap=await captureFeatures(3200,false);const d=await post('api/voice-identity.php',{action:'verify',features:cap.features});if(!d.match.matched||!d.match.sessionUserMatch)throw new Error('Voice did not match your enrolled profile. No identity or permissions were changed.');voiceEventId=d.match.eventId;voiceVerifiedUntil=Date.now()+14*60*1000;toast(`Voice recognized (${Math.round(d.match.confidence*100)}% match).`);return true}catch(e){voiceEventId='';voiceVerifiedUntil=0;toast(e.message);return false}finally{status('')}}
function haveVoice(){return !!voiceEventId&&Date.now()<voiceVerifiedUntil}
async function sendAgent(text,voice=false){if(!text.trim())return;status('Gelato is checking your restaurant context…');try{const pageContext=window.GelatoTimeclockAgentContext?.transportSnapshot?.()||{module:'timeclock',selectedDate:$('#dateFilter')?.value||C.today||null};const d=await post('api/timeclock-agent.php',{message:text,voice,voiceEventId:voice?voiceEventId:'',pageContext});status(d.answer);if(voice&&$('#speakAlerts')?.checked)speak(d.answer);await load();setTimeout(()=>status(''),7000)}catch(e){status(e.message)}}
function speak(text){if(!('speechSynthesis'in window))return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.rate=1;window.speechSynthesis.speak(u)}
function recognitionOnce(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){toast('Browser speech recognition is not available.');return;}const r=new SR();r.lang='en-US';r.interimResults=false;r.continuous=false;status('Listening for your command…');r.onresult=e=>{const text=[...e.results].map(x=>x[0].transcript).join(' ');sendAgent(text,true)};r.onerror=e=>toast('Speech recognition: '+e.error);r.onend=()=>{if(!listening)setTimeout(()=>status(''),900)};r.start()}
async function talkOnce(){if(!haveVoice()){const ok=await verifyVoice();if(!ok)return;}recognitionOnce()}
async function setListening(on){if(on&&!haveVoice()){const ok=await verifyVoice();if(!ok)return;}try{await post('api/proactive-agent.php',{action:'preferences',listeningEnabled:on,proactiveVoiceEnabled:!!$('#speakAlerts')?.checked,wakePhrase:'Hey Gelato'});listening=on;$('#listeningToggle')&&($('#listeningToggle').textContent=on?'Stop Listening':'Enable Listening Mode');if(on){startContinuous();startProactive();status('Listening Mode is on. Say “Hey Gelato…” for a command.');}else{stopContinuous();stopProactive();status('Listening Mode is off.');setTimeout(()=>status(''),2000)}}catch(e){toast(e.message)}}
function startContinuous(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){toast('Continuous speech recognition is not supported in this browser.');return;}stopContinuous();recognizer=new SR();recognizer.lang='en-US';recognizer.continuous=true;recognizer.interimResults=false;recognizer.onresult=e=>{for(let i=e.resultIndex;i<e.results.length;i++){if(!e.results[i].isFinal)continue;const text=e.results[i][0].transcript.trim();if(/^hey\s+gelato\b/i.test(text)){if(!haveVoice()){setListening(false);toast('Voice check expired. Re-enable Listening Mode to verify again.');return}sendAgent(text,true)}}};recognizer.onerror=e=>{if(!['no-speech','aborted'].includes(e.error))toast('Listening Mode: '+e.error)};recognizer.onend=()=>{if(listening)setTimeout(()=>{try{recognizer?.start()}catch{}},400)};try{recognizer.start()}catch{}}
function stopContinuous(){if(recognizer){try{recognizer.onend=null;recognizer.stop()}catch{}recognizer=null}}
function startProactive(){stopProactive();pollProactive();proactiveTimer=setInterval(pollProactive,45000)}function stopProactive(){if(proactiveTimer)clearInterval(proactiveTimer);proactiveTimer=null}
async function pollProactive(){if(!listening||!C.canProactive)return;try{const d=await json('api/proactive-agent.php');for(const ev of d.events||[]){status('Gelato: '+ev.message);if($('#speakAlerts')?.checked)speak(ev.message)}}catch(e){console.warn('Proactive Agent',e)}}
async function voiceSimple(action){try{const d=await post('api/voice-identity.php',{action});toast(d.message);voiceEventId='';voiceVerifiedUntil=0;if(listening)await setListening(false);await load()}catch(e){toast(e.message)}}
async function loadVoiceRoster(){try{const d=await json('api/voice-identity.php?action=roster');const root=$('#voiceRoster');root.innerHTML=d.staff.length?d.staff.map(s=>`<article class="row"><strong>${esc(s.display_name)}</strong><span class="pill ${s.voice_status==='active'?'good':''}">${esc(s.voice_status)}</span><span>${s.sample_count||0} samples</span><span>${s.enrolled_at?fmt(s.enrolled_at):'—'}</span><span>${s.last_verified_at?fmt(s.last_verified_at):'Never checked'}</span></article>`).join(''):'<div class="muted" style="padding:18px">No staff records.</div>'}catch(e){toast(e.message)}}
$('#refresh')?.addEventListener('click',load);$('#dateFilter')?.addEventListener('change',load);$('#clockIn')?.addEventListener('click',()=>timeAction('clock_in'));$('#clockOut')?.addEventListener('click',()=>timeAction('clock_out'));$('#breakToggle')?.addEventListener('click',()=>timeAction('break_start'));$('#enrollVoice')?.addEventListener('click',enrollVoice);$('#verifyVoice')?.addEventListener('click',verifyVoice);$('#disableVoice')?.addEventListener('click',()=>voiceSimple('disable'));$('#deleteVoice')?.addEventListener('click',()=>{if(confirm('Delete your enrolled voice profile and stored voice recordings?'))voiceSimple('delete')});$('#listeningToggle')?.addEventListener('click',()=>setListening(!listening));$('#talkButton')?.addEventListener('click',talkOnce);$('#loadVoiceRoster')?.addEventListener('click',loadVoiceRoster);window.addEventListener('beforeunload',()=>{stopContinuous();stopProactive()});load();
})();