<?php
declare(strict_types=1);
require_once __DIR__.'/includes/admin-control-core.php';

$user=app_require_auth();
if(!admin_control_allowed($user)){
    http_response_code(403);
    exit('Restaurant administration permission required.');
}
$pdo=app_pdo();
$organizationId=(int)$user['organization_id'];
$metrics=admin_dashboard_metrics($pdo,$organizationId);
$modules=admin_modules($user);
$grouped=[];
foreach($modules as $module)$grouped[$module['category']][]=$module;
$canOrders=admin_online_orders_allowed($user);
$recentOrders=$canOrders?array_slice(admin_online_orders($pdo,$organizationId,null,12),0,8):[];
$onlineInstalled=admin_table_exists($pdo,'online_orders');
$inboxInstalled=admin_table_exists($pdo,'customer_inbox_messages');
$locationsInstalled=admin_table_exists($pdo,'locations');
$initials=mb_strtoupper(mb_substr((string)($user['first_name']??''),0,1,'UTF-8').mb_substr((string)($user['last_name']??''),0,1,'UTF-8'),'UTF-8')?:'SF';
function admin_status_class(string $status): string{return strtolower(str_replace(' ','-',trim($status)));}
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><meta name="theme-color" content="#f3f2ed"><title>Restaurant Admin | <?=app_escape((string)$user['organization_name'])?></title><link rel="stylesheet" href="assets/css/admin-control.css?v=20260914-1"></head><body class="admin-control">
<header class="admin-top"><a class="admin-brand" href="admin.php"><span class="admin-logo">SF</span><span><strong>Restaurant Admin</strong><small><?=app_escape((string)$user['organization_name'])?> control center</small></span></a><nav class="admin-top-actions"><a class="admin-button hide-mobile" href="index.php" target="_blank" rel="noopener">Public site ↗</a><a class="admin-button hide-mobile" href="workspace.php">Workspace</a><?php if($canOrders):?><a class="admin-button dark" href="online-orders-admin.php">Online orders</a><?php endif;?></nav></header>
<main class="admin-shell">
<section class="admin-hero"><div class="admin-hero-main"><div class="admin-eyebrow">Restaurant Control Center</div><h1>Run the restaurant from one place.</h1><p>Online orders, customers, locations, promotions, POS, kitchen, operations and business intelligence now have one permission-aware admin home. Existing tools remain separate workspaces, but this page is the management layer that ties them together.</p><div class="admin-hero-links"><?php if($canOrders):?><a class="admin-button accent" href="online-orders-admin.php">View online orders</a><?php endif;?><?php if(app_has_permission('locations.manage',$user)):?><a class="admin-button" href="locations-admin.php">Manage locations</a><?php endif;?><?php if(app_has_permission('customer_promotions.manage',$user)):?><a class="admin-button" href="customer-promotions.php">Send promotion</a><?php endif;?><a class="admin-button quiet" href="online-order.php" target="_blank" rel="noopener">Preview ordering ↗</a></div></div><aside class="admin-hero-side"><div class="admin-user"><div class="admin-avatar"><?=app_escape($initials)?></div><div><strong><?=app_escape((string)$user['display_name'])?></strong><span><?=app_escape((string)$user['role_name'])?> · <?=app_escape((string)$user['email'])?></span></div></div><div class="admin-scope"><div class="admin-scope-row"><span>Organization</span><strong><?=app_escape((string)$user['organization_name'])?></strong></div><div class="admin-scope-row"><span>Admin modules</span><strong><?=number_format(count($modules))?></strong></div><div class="admin-scope-row"><span>Active locations</span><strong><?=number_format((int)$metrics['activeLocations'])?></strong></div><div class="admin-scope-row"><span>Online ordering</span><strong><?=$onlineInstalled?'Installed':'Upgrade needed'?></strong></div></div></aside></section>
<section class="admin-kpis"><article class="admin-kpi"><span>Online orders today</span><strong><?=number_format((int)$metrics['onlineOrdersToday'])?></strong><small>Submitted online orders on today’s POS business date.</small></article><article class="admin-kpi"><span>Online order value today</span><strong>$<?=number_format((float)$metrics['onlineOrderValueToday'],2)?></strong><small>Current ticket value, not booked revenue until payment closes.</small></article><article class="admin-kpi <?=((int)$metrics['openOnlineOrders']>0)?'attention':''?>"><span>Open online orders</span><strong><?=number_format((int)$metrics['openOnlineOrders'])?></strong><small><?=number_format((int)$metrics['readyOnlineOrders'])?> currently showing Ready in kitchen flow.</small></article><article class="admin-kpi"><span>Active customers</span><strong><?=number_format((int)$metrics['activeCustomers'])?></strong><small><?=number_format((int)$metrics['promotionReach'])?> signed-in customers currently eligible for Inbox promotions.</small></article></section>
<?php if($canOrders):?><section class="admin-section"><div class="admin-section-head"><div><div class="admin-eyebrow">Live Commerce</div><h2>Recent online orders</h2><p>Customer web orders are normal POS checks routed into the same kitchen workflow.</p></div><a class="admin-button dark" href="online-orders-admin.php">Open order center</a></div><div class="admin-panel"><?php if($recentOrders):?><div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>Order</th><th>Customer</th><th>Location</th><th>Status</th><th>Ready</th><th>Total</th></tr></thead><tbody><?php foreach($recentOrders as $order):?><tr><td class="admin-order-name"><strong><?=app_escape((string)$order['check_number'])?></strong><small><?=app_escape(substr((string)$order['submitted_at'],0,16))?></small></td><td><?=app_escape((string)$order['customer_name'])?></td><td><?=app_escape((string)$order['location_name'])?></td><td><span class="admin-status <?=app_escape(admin_status_class((string)$order['displayStatus']))?>"><?=app_escape((string)$order['displayStatus'])?></span></td><td><?=app_escape($order['requested_ready_at']?substr((string)$order['requested_ready_at'],0,16):'—')?></td><td class="admin-money">$<?=number_format((float)$order['total_amount'],2)?></td></tr><?php endforeach;?></tbody></table></div><div class="admin-order-card-grid"><?php foreach($recentOrders as $order):?><article class="admin-order-card"><div class="admin-order-card-head"><div><h3><?=app_escape((string)$order['check_number'])?></h3><p><?=app_escape((string)$order['customer_name'])?> · <?=app_escape((string)$order['location_name'])?></p></div><span class="admin-status <?=app_escape(admin_status_class((string)$order['displayStatus']))?>"><?=app_escape((string)$order['displayStatus'])?></span></div><div class="admin-order-card-meta"><div><span>Total</span><strong>$<?=number_format((float)$order['total_amount'],2)?></strong></div><div><span>Ready</span><strong><?=app_escape($order['requested_ready_at']?substr((string)$order['requested_ready_at'],11,5):'—')?></strong></div></div></article><?php endforeach;?></div><?php else:?><div class="admin-empty">No online orders are available yet.</div><?php endif;?></div></section><?php endif;?>
<section class="admin-section"><div class="admin-section-head"><div><div class="admin-eyebrow">Management</div><h2>Your admin tools</h2><p>Only modules permitted for your current role are shown.</p></div></div><div class="admin-module-groups"><?php foreach($grouped as $category=>$categoryModules):?><section><div class="admin-group-title"><?=app_escape((string)$category)?></div><div class="admin-modules"><?php foreach($categoryModules as $module):?><a class="admin-module" href="<?=app_escape((string)$module['href'])?>"><span class="admin-module-icon"><?=app_escape((string)$module['icon'])?></span><span><strong><?=app_escape((string)$module['name'])?></strong><p><?=app_escape((string)$module['description'])?></p></span></a><?php endforeach;?></div></section><?php endforeach;?></div></section>
<section class="admin-section"><div class="admin-section-head"><div><div class="admin-eyebrow">System Readiness</div><h2>Commerce + location foundation</h2></div></div><div class="admin-health-grid"><article class="admin-health"><div><strong>Online ordering</strong><small>Customer ordering metadata and POS bridge.</small></div><span class="admin-health-badge <?=$onlineInstalled?'on':''?>"><?=$onlineInstalled?'Ready':'Run Upgrade'?></span></article><article class="admin-health"><div><strong>Customer Inbox</strong><small>Transactional messages and account promotions.</small></div><span class="admin-health-badge <?=$inboxInstalled?'on':''?>"><?=$inboxInstalled?'Ready':'Run Upgrade'?></span></article><article class="admin-health"><div><strong>Locations</strong><small>Location services, hours and online-order switches.</small></div><span class="admin-health-badge <?=$locationsInstalled?'on':''?>"><?=$locationsInstalled?'Ready':'Run Upgrade'?></span></article><article class="admin-health"><div><strong>Online locations</strong><small>Active locations currently enabled for web ordering.</small></div><span class="admin-health-badge <?=((int)$metrics['onlineLocations']>0)?'on':''?>"><?=number_format((int)$metrics['onlineLocations'])?> enabled</span></article></div></section>
</main></body></html>
