<?php
declare(strict_types=1);
require_once __DIR__.'/includes/public-site.php';
require_once __DIR__.'/includes/customer-account-core.php';
require_once __DIR__.'/includes/customer-inbox-core.php';
require_once __DIR__.'/includes/online-order-core.php';

app_boot_session();
$pdo=app_pdo();
$context=public_site_context($pdo);
$organizationId=(int)$context['organizationId'];
$settings=$context['settings'];
$account=customer_account_require($pdo,$organizationId);
$profile=customer_account_profile($pdo,$organizationId,(int)$account['id']);
$customerId=(int)$profile['id'];

if($_SERVER['REQUEST_METHOD']==='POST'){
    if(!app_verify_csrf($_POST['csrf_token']??null)){
        app_redirect('customer-account.php?account_error=expired#inbox');
    }
    $action=(string)($_POST['action']??'');
    try{
        if($action==='mark_all_read') customer_inbox_mark_read($pdo,$organizationId,$customerId,null);
        elseif($action==='mark_read') customer_inbox_mark_read($pdo,$organizationId,$customerId,(string)($_POST['message_id']??''));
        elseif($action==='dismiss_message') customer_inbox_dismiss($pdo,$organizationId,$customerId,(string)($_POST['message_id']??''));
        elseif($action==='save_inbox_preferences') customer_inbox_preferences_save($pdo,$organizationId,$customerId,isset($_POST['promotions_enabled']),(int)$account['id']);
        else throw new InvalidArgumentException('Unsupported account action.');
        app_redirect('customer-account.php?account_saved=1#inbox');
    }catch(Throwable $e){
        error_log('Customer account action failed: '.$e->getMessage());
        app_redirect('customer-account.php?account_error=1#inbox');
    }
}

$orders=customer_account_orders($pdo,$organizationId,$customerId,35);
$onlineOrders=online_order_ready($pdo)?online_order_customer_orders($pdo,$organizationId,$customerId,25):[];
$onlineCheckIds=array_fill_keys(array_map(static fn(array $row):string=>(string)$row['check_public_id'],$onlineOrders),true);
$otherOrders=array_values(array_filter($orders,static fn(array $row):bool=>!isset($onlineCheckIds[(string)$row['checkPublicId']])));
$inbox=customer_inbox_ready($pdo)?customer_inbox_messages($pdo,$organizationId,$customerId,50):[];
$unread=customer_inbox_ready($pdo)?customer_inbox_unread_count($pdo,$organizationId,$customerId):0;
$inboxPrefs=customer_inbox_ready($pdo)?customer_inbox_preferences($pdo,$organizationId,$customerId):['promotionsEnabled'=>true];
$metrics=$profile['metrics'];
$initials=mb_strtoupper(mb_substr((string)$profile['firstName'],0,1,'UTF-8').mb_substr((string)$profile['lastName'],0,1,'UTF-8'),'UTF-8');
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#0b0b09"><meta name="robots" content="noindex,nofollow"><title>My Account | <?=app_escape((string)$settings['restaurant_name'])?></title><link rel="stylesheet" href="assets/css/site.css?v=20260914-2"><link rel="stylesheet" href="assets/css/customer-account.css?v=20260914-2"></head><body class="customer-page">
<?php public_site_render_header($settings,''); ?>
<main class="customer-main"><div class="shell customer-dashboard"><aside class="customer-sidebar"><div class="customer-avatar"><?=app_escape($initials?:'SF')?></div><h1><?=app_escape((string)$profile['displayName'])?></h1><p><?=app_escape((string)$profile['email'])?><?php if($profile['phone']):?><br><?=app_escape((string)$profile['phone'])?><?php endif;?></p><nav class="customer-nav"><a class="primary" href="online-order.php">Order online</a><a href="customer-account.php#inbox">Inbox<?php if($unread>0):?><span class="customer-nav-badge"><?=number_format($unread)?></span><?php endif;?></a><a href="customer-account.php#orders">Order history</a><a href="customer-account.php#profile">Profile</a><form class="customer-inline-form" method="post" action="customer-logout.php"><input type="hidden" name="csrf_token" value="<?=app_escape(app_csrf_token())?>"><button type="submit">Sign out</button></form></nav></aside><section class="customer-content">
<div class="customer-hero-panel"><div class="eyebrow"><?=isset($_GET['welcome'])?'Account Created':'Customer Account'?></div><h2><?=isset($_GET['welcome'])?'Welcome to Stonefellows.':'Good to see you again.'?></h2><p>Your account connects online ordering, restaurant history and your Stonefellows Inbox to one CRM customer identity. Promotions stay inside the account unless you separately opt in to email or SMS.</p><div class="customer-stats"><div class="customer-stat"><strong><?=number_format((int)$metrics['visits'])?></strong><span>Completed visits</span></div><div class="customer-stat"><strong>$<?=number_format((float)$metrics['lifetimeSpend'],2)?></strong><span>Recorded spend</span></div><div class="customer-stat"><strong><?=number_format($unread)?></strong><span>Unread Inbox</span></div></div><a class="customer-order-cta" href="online-order.php">Start pickup order</a></div>
<?php if(isset($_GET['submitted'])):?><div class="customer-message good">Your pickup order was submitted to Stonefellows. The confirmation is also in your Inbox.</div><?php endif;?><?php if(isset($_GET['account_saved'])):?><div class="customer-message good">Your Inbox was updated.</div><?php endif;?><?php if(isset($_GET['account_error'])):?><div class="customer-message bad">That account action could not be completed. Please try again.</div><?php endif;?>
<section class="customer-panel" id="inbox"><div class="customer-panel-head"><div><h3>Inbox<?php if($unread>0):?> <span class="customer-unread-title"><?=number_format($unread)?> unread</span><?php endif;?></h3><p>Order updates, rewards, announcements and Stonefellows promotions.</p></div><?php if($unread>0):?><form method="post" class="customer-inline-form"><input type="hidden" name="csrf_token" value="<?=app_escape(app_csrf_token())?>"><input type="hidden" name="action" value="mark_all_read"><button class="customer-small-button" type="submit">Mark all read</button></form><?php endif;?></div>
<?php if($inbox):?><div class="customer-inbox-list"><?php foreach($inbox as $message):$isUnread=empty($message['readAt']);?><article class="customer-inbox-message <?=$isUnread?'unread':''?>"><div class="customer-inbox-meta"><span class="customer-inbox-type"><?=app_escape(ucwords(str_replace('_',' ',(string)$message['type'])))?></span><?php if($message['locationName']):?><span><?=app_escape((string)$message['locationName'])?></span><?php endif;?><span><?=app_escape(substr((string)$message['deliveredAt'],0,16))?></span></div><h4><?=app_escape((string)$message['title'])?></h4><?php if($message['previewText']):?><p class="customer-inbox-preview"><?=app_escape((string)$message['previewText'])?></p><?php endif;?><p class="customer-inbox-body"><?=nl2br(app_escape((string)$message['bodyText']))?></p><?php if($message['promoCode']):?><div class="customer-promo-code"><span>Promo code</span><strong><?=app_escape((string)$message['promoCode'])?></strong></div><?php endif;?><div class="customer-inbox-actions"><?php if($message['ctaUrl']):?><a class="customer-small-button strong" href="<?=app_escape((string)$message['ctaUrl'])?>"><?=app_escape((string)($message['ctaLabel']?:'View'))?></a><?php endif;?><?php if($isUnread):?><form method="post"><input type="hidden" name="csrf_token" value="<?=app_escape(app_csrf_token())?>"><input type="hidden" name="action" value="mark_read"><input type="hidden" name="message_id" value="<?=app_escape((string)$message['publicId'])?>"><button class="customer-small-button" type="submit">Mark read</button></form><?php endif;?><form method="post"><input type="hidden" name="csrf_token" value="<?=app_escape(app_csrf_token())?>"><input type="hidden" name="action" value="dismiss_message"><input type="hidden" name="message_id" value="<?=app_escape((string)$message['publicId'])?>"><button class="customer-small-button quiet" type="submit">Dismiss</button></form></div></article><?php endforeach;?></div><?php else:?><div class="customer-empty">Your Inbox is empty. Order confirmations, restaurant updates and eligible promotions will appear here.</div><?php endif;?>
<form method="post" class="customer-inbox-preferences"><input type="hidden" name="csrf_token" value="<?=app_escape(app_csrf_token())?>"><input type="hidden" name="action" value="save_inbox_preferences"><label><input type="checkbox" name="promotions_enabled" value="1" <?=!empty($inboxPrefs['promotionsEnabled'])?'checked':''?>><span><strong>Inbox promotions</strong><small>Allow restaurant offers in this account Inbox. Turning this off does not block transactional order updates.</small></span></label><button class="customer-small-button" type="submit">Save preference</button></form></section>
<section class="customer-panel" id="orders"><div class="customer-panel-head"><div><h3>Online orders</h3><p>Pickup orders placed through your Stonefellows account.</p></div><a class="customer-small-button strong" href="online-order.php">New pickup order</a></div><?php if($onlineOrders):?><div class="customer-order-list"><?php foreach($onlineOrders as $order):?><article class="customer-order online"><div><strong><?=app_escape((string)$order['check_number'])?></strong><small><?=app_escape((string)$order['location_name'])?> · submitted <?=app_escape(substr((string)$order['submitted_at'],0,16))?><br>Estimated ready <?=app_escape(substr((string)$order['requested_ready_at'],0,16))?> · pay at pickup</small></div><div class="amount">$<?=number_format((float)$order['total_amount'],2)?><span class="status"><?=app_escape((string)$order['displayStatus'])?></span></div></article><?php endforeach;?></div><?php else:?><div class="customer-empty">You have not placed an online pickup order yet.</div><?php endif;?><?php if($otherOrders):?><div class="customer-history-divider">Other restaurant history</div><div class="customer-order-list"><?php foreach($otherOrders as $order):?><article class="customer-order"><div><strong><?=app_escape((string)$order['checkNumber'])?></strong><small><?=app_escape(ucwords(str_replace('_',' ',(string)$order['orderType'])))?> · <?=app_escape((string)$order['businessDate'])?><?php if($order['label']):?> · <?=app_escape((string)$order['label'])?><?php endif;?></small></div><div class="amount">$<?=number_format((float)$order['totalAmount'],2)?><span class="status"><?=app_escape((string)$order['status'])?></span></div></article><?php endforeach;?></div><?php endif;?></section>
<section class="customer-panel" id="profile"><div class="customer-panel-head"><div><h3>Customer profile</h3><p>This is the identity linked to the merchant CRM.</p></div></div><div class="customer-profile-grid"><div class="customer-detail"><span>Name</span><strong><?=app_escape((string)$profile['displayName'])?></strong></div><div class="customer-detail"><span>Email</span><strong><?=app_escape((string)$profile['email'])?></strong></div><div class="customer-detail"><span>Phone</span><strong><?=app_escape((string)($profile['phone']?:'Not added'))?></strong></div><div class="customer-detail"><span>Customer since</span><strong><?=app_escape(substr((string)$profile['createdAt'],0,10))?></strong></div></div><p class="customer-note" style="margin:16px 0 0">Internal CRM notes and staff-only tags are never exposed in the customer portal. Email and SMS marketing consent remain separately recorded in the CRM consent history.</p></section>
</section></div></main>
<?php public_site_render_footer($settings); ?><script src="assets/js/site.js?v=20260914"></script><script src="assets/js/public-shell.js?v=20260915-1"></script>
</body></html>
