<?php
declare(strict_types=1);
require_once __DIR__.'/includes/bootstrap.php';
require_once __DIR__.'/includes/glasses-vision-lab.php';
require_once __DIR__.'/includes/glasses-vision-active-learning.php';
require_once __DIR__.'/includes/glasses-vision-dataset-intelligence.php';
require_once __DIR__.'/includes/glasses-vision-training-media.php';
require_once __DIR__.'/includes/glasses-vision-curation.php';
require_once __DIR__.'/includes/glasses-vision-balance.php';
require_once __DIR__.'/includes/glasses-vision-annotation-qa.php';
require_once __DIR__.'/includes/glasses-vision-training-release.php';
require_once __DIR__.'/includes/glasses-vision-training-qualification.php';
require_once __DIR__.'/includes/glasses-vision-lineage.php';
require_once __DIR__.'/includes/glasses-vision-feedback.php';
require_once __DIR__.'/includes/glasses-vision-failure-analysis.php';
require_once __DIR__.'/includes/glasses-vision-mining.php';
$user=app_require_auth();if(!app_has_permission('glasses.view',$user)){http_response_code(403);exit('AR glasses permission required.');}
$pdo=app_pdo();$error='';try{$catalog=glasses_vision_lab_catalog($pdo,$user);$catalog['activeLearning']=glasses_vision_active_learning_catalog($pdo,(int)$user['organization_id']);$catalog['datasetIntelligence']=glasses_vision_dataset_intelligence_catalog($pdo,(int)$user['organization_id']);$catalog['trainingMedia']=glasses_vision_training_media_catalog($pdo,(int)$user['organization_id']);$catalog['curation']=glasses_vision_curation_catalog($pdo,(int)$user['organization_id']);$catalog['balance']=glasses_vision_balance_catalog($pdo,(int)$user['organization_id']);$catalog['annotationQa']=glasses_vision_annotation_qa_catalog($pdo,(int)$user['organization_id']);$catalog['trainingReleases']=glasses_vision_training_release_catalog($pdo,(int)$user['organization_id']);$catalog['trainingQualification']=glasses_vision_training_qualification_catalog($pdo,(int)$user['organization_id']);$catalog['lineage']=glasses_vision_lineage_catalog($pdo,(int)$user['organization_id']);$catalog['productionFeedback']=glasses_vision_feedback_catalog($pdo,(int)$user['organization_id']);$catalog['failureAnalysis']=glasses_vision_failure_analysis_catalog($pdo,(int)$user['organization_id']);$catalog['hardExampleMining']=glasses_vision_mining_catalog($pdo,(int)$user['organization_id']);}catch(Throwable $e){$catalog=['ready'=>false,'assignments'=>[],'missions'=>[],'samples'=>[],'datasets'=>[],'users'=>[],'devices'=>[],'canManage'=>false];$error='Vision Lab could not load. Run Upgrade if this installation is behind.';error_log('[gelato-vision-lab-page] '.$e->getMessage());}
$boot=['apiUrl'=>'api/glasses-vision-lab.php','mediaApiUrl'=>'api/glasses-vision-media.php','csrfToken'=>app_csrf_token(),'catalog'=>$catalog];
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Vision Lab | Restaurant Admin</title><link rel="stylesheet" href="assets/css/admin-control.css?v=20260914-1"><link rel="stylesheet" href="assets/css/glasses-vision-lab.css?v=20260928-v6"></head>
<body class="admin-control vl-page"><header class="admin-top"><a class="admin-brand" href="admin.php"><span class="admin-logo">SF</span><span><strong>Restaurant Admin</strong><small>Vision Lab</small></span></a><nav class="admin-top-actions"><a class="admin-button" href="glasses-vision-operations.php">Vision Operations</a><a class="admin-button" href="glasses-learning.php">Learning Analytics</a><a class="admin-button" href="glasses-vision-models.php">Models</a><a class="admin-button" href="admin.php">Admin</a></nav></header>
<main class="admin-shell vl-shell"><section class="vl-hero"><div><div class="admin-eyebrow">AR Glasses · Vision Lab V7</div><h1>Curated Dataset Builder &amp; Group-Aware Split Governance</h1><p>Curate approved evidence with an immutable decision ledger, then create deterministic train/validation/test plans that keep related capture and build lineage together instead of splitting individual filenames.</p></div><div class="vl-rule"><strong>Training boundary</strong><span>Vision model training and employee training remain separate. Lab actions never advance KDS, validate a production item, or alter POS state.</span></div></section>
<?php if($error):?><div class="vl-alert"><?=app_escape($error)?></div><?php endif;?>
<section class="vl-panel"><div class="vl-head"><div><div class="admin-eyebrow">Curated Dataset Builder</div><h2>Include/exclude evidence &amp; build leakage-proof splits</h2></div><div><button id="vlCurationOpen" class="admin-button dark" type="button">Open dataset</button> <button id="vlSplitPlan" class="admin-button" type="button">Generate group split</button></div></div><div id="vlCurationSummary" class="vl-curation-summary"></div><div id="vlCurationRows" class="vl-table"></div><div id="vlSplitPlans" class="vl-plans"></div></section>
<section class="vl-panel"><div class="vl-head"><div><div class="admin-eyebrow">Dataset Balance &amp; Diversity Optimizer</div><h2>Find class, hard-example, negative &amp; environment imbalance</h2></div><button id="vlBalanceAnalyze" class="admin-button dark" type="button">Analyze balance</button></div><div id="vlBalance" class="vl-balance"><div class="vl-empty">Choose a dataset to calculate deterministic balance and diversity recommendations.</div></div></section>
<section class="vl-panel"><div class="vl-head"><div><div class="admin-eyebrow">Annotation QA &amp; Agreement</div><h2>Completeness, box consistency, reviewer agreement &amp; adjudication</h2></div><button id="vlAnnotationQaAnalyze" class="admin-button dark" type="button">Analyze annotations</button></div><div id="vlAnnotationQa" class="vl-annotation-qa"><div class="vl-empty">Analyze a dataset or the full reviewed corpus for annotation quality.</div></div></section>
<section class="vl-panel"><div class="vl-head"><div><div class="admin-eyebrow">Training Release Builder</div><h2>Build deterministic governed YOLO packages</h2></div><button id="vlTrainingReleaseBuild" class="admin-button dark" type="button">Build training release</button></div><div id="vlTrainingReleases" class="vl-training-releases"><div class="vl-empty">Frozen curated datasets can be packaged with their governed split, provenance, and per-file SHA-256 hashes.</div></div></section>\n<section class="vl-panel"><div class="vl-head"><div><div class="admin-eyebrow">Pre-Training Qualification Gate</div><h2>Require corpus readiness before model training</h2></div><button id="vlQualificationRun" class="admin-button dark" type="button">Run qualification</button></div><div id="vlQualification" class="vl-qualification"><div class="vl-empty">Qualification checks the exact release corpus for coverage, diversity, leakage, annotation agreement, and hard visual blockers.</div></div></section>\n<section class="vl-panel"><div class="vl-head"><div><div class="admin-eyebrow">Dataset Lineage &amp; Model Traceability</div><h2>Trace exact training evidence through production</h2></div><div><button id="vlLineageModel" class="admin-button dark" type="button">Trace model</button> <button id="vlLineageSample" class="admin-button" type="button">Trace sample</button> <button id="vlLineageDiff" class="admin-button" type="button">Compare datasets</button></div></div><div id="vlLineage" class="vl-lineage"><div class="vl-empty">Trace a model back to every image that trained it, inspect why a sample was included, or compare two dataset versions.</div></div></section>\n<section class="vl-panel"><div class="vl-head"><div><div class="admin-eyebrow">Production Error &amp; Outcome Ledger</div><h2>Capture real kitchen vision failures with exact model lineage</h2></div><button id="vlFeedbackSync" class="admin-button dark" type="button">Sync corrections</button></div><div id="vlProductionFeedback" class="vl-production-feedback"><div class="vl-empty">Human observation corrections become immutable production-error evidence tied to the exact model, station, device, menu item and build session.</div></div></section>
<section class="vl-panel"><div class="vl-head"><div><div class="admin-eyebrow">Lineage-Aware Failure Analysis</div><h2>Find concentrated production failures and trace them to training ancestry</h2></div><button id="vlFailureAnalyze" class="admin-button dark" type="button">Analyze failures</button></div><div id="vlFailureAnalysis" class="vl-failure-analysis"><div class="vl-empty">Analyze production errors by model, class, station, device, menu item, confidence and environment, with exact training lineage.</div></div></section>
<section class="vl-panel"><div class="vl-head"><div><div class="admin-eyebrow">Hard Example &amp; Counterexample Mining</div><h2>Mine high-value production failures without auto-training</h2></div><button id="vlMiningRun" class="admin-button dark" type="button">Mine examples</button></div><div id="vlHardExampleMining" class="vl-hard-example-mining"><div class="vl-empty">Mine false negatives, confident mistakes, counterexamples and difficult corrections with deterministic scoring and diversity caps.</div></div></section>
<section class="vl-panel"><div class="vl-head"><div><div class="admin-eyebrow">Training Media</div><h2>Governed visual evidence &amp; quality</h2></div><div><button id="vlMediaRefresh" class="admin-button" type="button">Refresh media</button> <button id="vlMediaExport" class="admin-button" type="button">Export manifest</button> <button id="vlMediaExpire" class="admin-button" type="button">Run retention cleanup</button></div></div><div id="vlMediaQuality" class="vl-media-quality"></div><div id="vlMediaLibrary" class="vl-media-library"></div></section>
<section class="vl-panel"><div class="vl-head"><div><div class="admin-eyebrow">Dataset Intelligence</div><h2>Coverage, readiness &amp; collection planning</h2></div><div><button id="vlAnalyze" class="admin-button dark" type="button">Analyze dataset</button> <button id="vlPlan" class="admin-button" type="button">Generate collection plan</button></div></div><div id="vlIntelligence" class="vl-intelligence"></div><div id="vlPlans" class="vl-plans"></div></section>
<section class="vl-panel"><div class="vl-head"><div><div class="admin-eyebrow">Active Learning</div><h2>Prioritized training opportunities</h2></div><div><span id="vlActiveSummary"></span> <button id="vlScan" class="admin-button dark" type="button">Scan production signals</button></div></div><div id="vlActiveLearning" class="vl-active-learning"></div></section>
<section class="vl-grid"><section class="vl-panel"><div class="vl-head"><div><div class="admin-eyebrow">Assignments</div><h2>Who is wearing which glasses?</h2></div><button id="vlAssign" class="admin-button dark" type="button">Assign glasses</button></div><div id="vlAssignments"></div></section>
<section class="vl-panel"><div class="vl-head"><div><div class="admin-eyebrow">Training Missions</div><h2>Directed evidence collection</h2></div><button id="vlMission" class="admin-button dark" type="button">New mission</button></div><div id="vlMissions"></div></section></section>
<section class="vl-panel"><div class="vl-head"><div><div class="admin-eyebrow">Review Queue</div><h2>Production evidence awaiting ground truth</h2></div><div><span id="vlQueueCount"></span> <button id="vlImportCorrected" class="admin-button" type="button">Import corrected evidence</button></div></div><div class="vl-table"><table><thead><tr><th>Source</th><th>Mission</th><th>Operator</th><th>Label</th><th>Status</th><th>Review</th></tr></thead><tbody id="vlSamples"></tbody></table></div></section>
<section class="vl-panel"><div class="vl-head"><div><div class="admin-eyebrow">Datasets</div><h2>Immutable versioned training sets</h2></div><button id="vlDataset" class="admin-button dark" type="button">New dataset</button></div><div id="vlDatasets" class="vl-datasets"></div></section>
<section class="vl-panel vl-boundary"><div><div class="admin-eyebrow">Model Training</div><h2>What this Lab governs</h2></div><p>Wearer/operator attribution, sample review, annotation/reviewer/adjudicator identity, mission progress, dataset inclusion, split assignment, immutable hashes and contributor coverage. Browser capture remains local by default. V5 adds an explicit opt-in upload path to private storage with retention/deletion governance; no frame is retained server-side unless the operator chooses to upload it.</p></section>
</main><div id="vlToast" class="vl-toast" hidden></div><script>window.GELATO_VISION_LAB=<?=json_encode($boot,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE|JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT)?>;</script><script src="assets/js/glasses-vision-lab.js?v=20260928-v6"></script><script src="assets/js/glasses-vision-balance.js?v=20260928-v6-3"></script><script src="assets/js/glasses-vision-annotation-qa.js?v=20260928-v6-4"></script><script src="assets/js/glasses-vision-training-release.js?v=20260928-v6-5"></script><script src="assets/js/glasses-vision-training-qualification.js?v=20260928-v6-6"></script><script src="assets/js/glasses-vision-lineage.js?v=20260928-v6-7"></script><script src="assets/js/glasses-vision-feedback.js?v=20260928-v7-1"></script><script src="assets/js/glasses-vision-failure-analysis.js?v=20260928-v7-2"></script><script src="assets/js/glasses-vision-mining.js?v=20260928-v7-3"></script><script src="js/universal-admin-page-shell.js?v=20260915-2"></script></body></html>
