<?php
declare(strict_types=1);
require_once __DIR__.'/includes/bootstrap.php';
require_once __DIR__.'/includes/glasses-vision-lab.php';
require_once __DIR__.'/includes/glasses-vision-active-learning.php';
require_once __DIR__.'/includes/glasses-vision-dataset-intelligence.php';
require_once __DIR__.'/includes/glasses-vision-training-media.php';
$user=app_require_auth();if(!app_has_permission('glasses.view',$user)){http_response_code(403);exit('AR glasses permission required.');}
$pdo=app_pdo();$error='';try{$catalog=glasses_vision_lab_catalog($pdo,$user);$catalog['activeLearning']=glasses_vision_active_learning_catalog($pdo,(int)$user['organization_id']);$catalog['datasetIntelligence']=glasses_vision_dataset_intelligence_catalog($pdo,(int)$user['organization_id']);$catalog['trainingMedia']=glasses_vision_training_media_catalog($pdo,(int)$user['organization_id']);}catch(Throwable $e){$catalog=['ready'=>false,'assignments'=>[],'missions'=>[],'samples'=>[],'datasets'=>[],'users'=>[],'devices'=>[],'canManage'=>false];$error='Vision Lab could not load. Run Upgrade if this installation is behind.';error_log('[gelato-vision-lab-page] '.$e->getMessage());}
$boot=['apiUrl'=>'api/glasses-vision-lab.php','mediaApiUrl'=>'api/glasses-vision-media.php','csrfToken'=>app_csrf_token(),'catalog'=>$catalog];
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Vision Lab | Restaurant Admin</title><link rel="stylesheet" href="assets/css/admin-control.css?v=20260914-1"><link rel="stylesheet" href="assets/css/glasses-vision-lab.css?v=20260928-v5"></head>
<body class="admin-control vl-page"><header class="admin-top"><a class="admin-brand" href="admin.php"><span class="admin-logo">SF</span><span><strong>Restaurant Admin</strong><small>Vision Lab</small></span></a><nav class="admin-top-actions"><a class="admin-button" href="glasses-vision-operations.php">Vision Operations</a><a class="admin-button" href="glasses-learning.php">Learning Analytics</a><a class="admin-button" href="glasses-vision-models.php">Models</a><a class="admin-button" href="admin.php">Admin</a></nav></header>
<main class="admin-shell vl-shell"><section class="vl-hero"><div><div class="admin-eyebrow">AR Glasses · Vision Lab V5</div><h1>Governed Training Media, Image Fingerprints &amp; Visual Dataset Quality</h1><p>Store explicitly opted-in training frames in private application storage, verify media integrity, detect exact and near duplicates, measure visual quality/diversity, and keep image retention auditable.</p></div><div class="vl-rule"><strong>Training boundary</strong><span>Vision model training and employee training remain separate. Lab actions never advance KDS, validate a production item, or alter POS state.</span></div></section>
<?php if($error):?><div class="vl-alert"><?=app_escape($error)?></div><?php endif;?>
<section class="vl-panel"><div class="vl-head"><div><div class="admin-eyebrow">Training Media</div><h2>Governed visual evidence &amp; quality</h2></div><div><button id="vlMediaRefresh" class="admin-button" type="button">Refresh media</button> <button id="vlMediaExpire" class="admin-button" type="button">Run retention cleanup</button></div></div><div id="vlMediaQuality" class="vl-media-quality"></div><div id="vlMediaLibrary" class="vl-media-library"></div></section>
<section class="vl-panel"><div class="vl-head"><div><div class="admin-eyebrow">Dataset Intelligence</div><h2>Coverage, readiness &amp; collection planning</h2></div><div><button id="vlAnalyze" class="admin-button dark" type="button">Analyze dataset</button> <button id="vlPlan" class="admin-button" type="button">Generate collection plan</button></div></div><div id="vlIntelligence" class="vl-intelligence"></div><div id="vlPlans" class="vl-plans"></div></section>
<section class="vl-panel"><div class="vl-head"><div><div class="admin-eyebrow">Active Learning</div><h2>Prioritized training opportunities</h2></div><div><span id="vlActiveSummary"></span> <button id="vlScan" class="admin-button dark" type="button">Scan production signals</button></div></div><div id="vlActiveLearning" class="vl-active-learning"></div></section>
<section class="vl-grid"><section class="vl-panel"><div class="vl-head"><div><div class="admin-eyebrow">Assignments</div><h2>Who is wearing which glasses?</h2></div><button id="vlAssign" class="admin-button dark" type="button">Assign glasses</button></div><div id="vlAssignments"></div></section>
<section class="vl-panel"><div class="vl-head"><div><div class="admin-eyebrow">Training Missions</div><h2>Directed evidence collection</h2></div><button id="vlMission" class="admin-button dark" type="button">New mission</button></div><div id="vlMissions"></div></section></section>
<section class="vl-panel"><div class="vl-head"><div><div class="admin-eyebrow">Review Queue</div><h2>Production evidence awaiting ground truth</h2></div><div><span id="vlQueueCount"></span> <button id="vlImportCorrected" class="admin-button" type="button">Import corrected evidence</button></div></div><div class="vl-table"><table><thead><tr><th>Source</th><th>Mission</th><th>Operator</th><th>Label</th><th>Status</th><th>Review</th></tr></thead><tbody id="vlSamples"></tbody></table></div></section>
<section class="vl-panel"><div class="vl-head"><div><div class="admin-eyebrow">Datasets</div><h2>Immutable versioned training sets</h2></div><button id="vlDataset" class="admin-button dark" type="button">New dataset</button></div><div id="vlDatasets" class="vl-datasets"></div></section>
<section class="vl-panel vl-boundary"><div><div class="admin-eyebrow">Model Training</div><h2>What this Lab governs</h2></div><p>Wearer/operator attribution, sample review, annotation/reviewer/adjudicator identity, mission progress, dataset inclusion, split assignment, immutable hashes and contributor coverage. Browser capture remains local by default. V5 adds an explicit opt-in upload path to private storage with retention/deletion governance; no frame is retained server-side unless the operator chooses to upload it.</p></section>
</main><div id="vlToast" class="vl-toast" hidden></div><script>window.GELATO_VISION_LAB=<?=json_encode($boot,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE|JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT)?>;</script><script src="assets/js/glasses-vision-lab.js?v=20260928-v5"></script><script src="js/universal-admin-page-shell.js?v=20260915-2"></script></body></html>
