<?php
declare(strict_types=1);
require __DIR__.'/includes/bootstrap.php';
require_once __DIR__.'/includes/menu-manager-core.php';
require_once __DIR__.'/includes/menu-operations-core.php';
$user=app_require_permission('menu.view');
$pdo=app_pdo();
$ready=menu_manager_ready($pdo);
$operationsReady=menu_operations_ready($pdo);
$canManage=app_has_permission('menu.manage',$user);
$action=(string)($_GET['action']??'');
$autoOpenType=match($action){'add-food'=>'food','add-drink'=>'drink',default=>''};
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Menu Manager | Gelato</title><link rel="stylesheet" href="assets/css/menu-manager.css?v=20260915-1"><link rel="stylesheet" href="assets/css/menu-operations.css?v=20260915-1"><link rel="stylesheet" href="assets/css/canonical-media.css?v=20260915-1"></head>
<body>
<main class="mm-shell" id="menuManager" data-ready="<?=$ready?'1':'0'?>" data-manage="<?=$canManage?'1':'0'?>" data-auto-open-type="<?=app_escape($autoOpenType)?>" data-csrf="<?=app_escape(app_csrf_token())?>">
<section class="mm-hero"><div><span class="mm-eyebrow">Canonical restaurant menu</span><h1>Menu Manager</h1><p>Edit the menu once and distribute it to the public menu, Online Ordering, POS, KDS, Package Deals and Catering.</p></div><div class="mm-hero-actions"><?php if($canManage):?><button class="mm-btn primary" type="button" id="addFoodTop">+ Add Food</button><button class="mm-btn primary" type="button" id="addDrinkTop">+ Add Drink</button><button class="mm-btn" type="button" id="addCategoryTop">+ Category</button><?php endif;?><a class="mm-btn" href="menu.php" target="_blank" rel="noopener">View Public Menu ↗</a></div></section>
<?php if(!$ready):?><div class="mm-alert">Menu Manager is not installed yet. Run <strong>upgrade.php → Upgrade once</strong>.</div><?php endif;?>
<?php if($ready&&!$operationsReady):?><div class="mm-alert">Menu Operations is ready to install. Run <strong>upgrade.php → Upgrade once</strong> after deploying this release.</div><?php endif;?>
<section class="mm-stats" id="menuStats"></section>

<section class="menu-ops" id="menuOperations">
  <header class="menu-ops-head"><div><span class="mm-eyebrow">Live restaurant controls</span><h2>Menu Operations</h2><p>Manage 86s, size availability, prices, schedules, ordering and distribution from the same canonical menu. Every operational change is synchronized to the main Agent Brain.</p></div><div class="menu-ops-actions"><label>Location<select id="opsLocation"><option value="">Loading locations…</option></select></label><button class="mm-btn" type="button" id="opsRefresh">Refresh</button></div></header>
  <div class="ops-summary" id="opsSummary"></div>
  <?php if($canManage):?><div class="ops-tools"><button class="ops-btn" type="button" id="opsSelectAll">Select all / none</button><button class="ops-btn" type="button" id="opsBulkStatus">Bulk lifecycle</button><button class="ops-btn" type="button" id="opsBulkChannel">Bulk distribution</button><select id="opsMoveCategory"><option value="">Move selected to…</option></select><button class="ops-btn" type="button" id="opsBulkMove">Move items</button><select id="opsBulkPriceMode"><option value="percent">Price %</option><option value="fixed">Price $</option></select><input id="opsBulkPriceValue" type="number" step="0.01" value="0" aria-label="Bulk price adjustment"><button class="ops-btn" type="button" id="opsBulkPrice">Apply price change</button></div><?php endif;?>
  <div class="ops-status" id="opsStatus">Loading live menu operations…</div>
  <div class="ops-grid"><section class="ops-items"><h3>Location menu & size availability</h3><div id="opsItems"></div></section><aside class="ops-side"><h3>Image completeness</h3><div class="ops-health" id="opsHealth"></div><h3>Category order</h3><div id="opsCategoryOrder"></div><h3 style="margin-top:20px">Recent menu changes</h3><div id="opsEvents"></div></aside></div>
</section>

<section class="mm-toolbar"><label class="mm-search"><span>Search menu</span><input id="menuSearch" type="search" placeholder="Pizza, salad, fountain drink…"></label><label><span>Category</span><select id="categoryFilter"><option value="">All categories</option></select></label><label><span>Item type</span><select id="itemTypeFilter"><option value="">All items</option><option value="food">Food</option><option value="drink">Drinks</option></select></label><label class="mm-check"><input id="showArchived" type="checkbox"> Show archived</label></section>
<div class="mm-layout"><aside class="mm-categories"><div class="mm-panel-head"><div><span class="mm-eyebrow">Categories</span><strong>Menu sections</strong></div><?php if($canManage):?><button id="addCategory" class="mm-icon" type="button" aria-label="Add category">+</button><?php endif;?></div><div id="categoryList"></div></aside><section class="mm-items"><div class="mm-items-head"><div><span class="mm-eyebrow">Food & drink items</span><h2 id="itemsTitle">All Menu Items</h2></div><?php if($canManage):?><div style="display:flex;gap:8px;flex-wrap:wrap"><button class="mm-btn primary" id="addFood" type="button">+ Add Food</button><button class="mm-btn primary" id="addDrink" type="button">+ Add Drink</button></div><?php endif;?></div><div id="itemGrid" class="mm-item-grid"></div></section></div>
</main>

<dialog class="mm-category-dialog" id="categoryDialog"><form method="dialog" id="categoryForm"><div class="dialog-head"><div><span class="mm-eyebrow">Menu structure</span><h2 id="categoryDialogTitle">Add Category</h2></div><button value="cancel" aria-label="Close">×</button></div><input type="hidden" id="categoryId"><label><span>Category name</span><input id="categoryName" maxlength="160" required placeholder="Pizza"></label><label><span>Description</span><textarea id="categoryDescription" rows="3" maxlength="5000"></textarea></label><div class="dialog-grid"><label><span>Sort order</span><input id="categorySort" type="number" value="0"></label><label><span>Status</span><select id="categoryStatus"><option value="active">Active</option><option value="inactive">Inactive</option></select></label></div><div class="dialog-actions"><button class="mm-btn" value="cancel">Cancel</button><button class="mm-btn primary" id="saveCategory" type="button">Save Category</button></div></form></dialog>

<div class="food-builder" id="foodBuilder" aria-hidden="true"><header class="fb-header"><div><button class="fb-close" id="foodBuilderClose" type="button" aria-label="Close">×</button><div><span class="mm-eyebrow" id="builderEyebrow">Menu item builder</span><h2 id="foodBuilderTitle">New Menu Item</h2><p id="foodBuilderStatus">Draft · not saved</p></div></div><div class="fb-header-actions" id="foodLifecycleActions"></div></header><div class="fb-main"><nav class="fb-steps" id="foodSteps" aria-label="Food builder steps"></nav><section class="fb-canvas" id="foodCanvas"></section><aside class="fb-preview" id="foodPreview"></aside></div><footer class="fb-footer"><span id="foodSaveState">Changes are local until saved.</span><div><button class="mm-btn" id="foodPrevious" type="button">← Previous</button><button class="mm-btn" id="foodNext" type="button">Next →</button><?php if($canManage):?><button class="mm-btn primary" id="foodSave" type="button">Save Item</button><button class="mm-btn publish" id="foodPublish" type="button">Save & Publish</button><?php endif;?></div></footer></div>

<script>window.GELATO_MENU_MANAGER={csrf:<?=json_encode(app_csrf_token())?>,canManage:<?=json_encode($canManage)?>,autoOpen:<?=json_encode($autoOpenType==='food')?>,autoOpenType:<?=json_encode($autoOpenType)?>};</script><script src="assets/js/menu-manager.js?v=20260915-1"></script><script src="assets/js/menu-manager-drink.js?v=20260915-1"></script><script src="assets/js/menu-media.js?v=20260915-1"></script><script src="assets/js/menu-operations.js?v=20260915-1"></script><script src="js/universal-admin-page-shell.js?v=20260915-shell2"></script></body></html>