<?php
declare(strict_types=1);

$root=dirname(__DIR__);
function gws_assert(bool $condition,string $message): void {if(!$condition)throw new RuntimeException($message);}
function gws_file(string $path): string {global $root;$c=file_get_contents($root.'/'.$path);if($c===false)throw new RuntimeException('Missing '.$path);return $c;}

$api=gws_file('api/glasses-simulator.php');
$core=gws_file('includes/glasses-simulator.php');
$page=gws_file('glasses-simulator.php');
$js=gws_file('assets/js/glasses-web-simulator.js');
$css=gws_file('assets/css/glasses-web-simulator.css');

gws_assert(str_contains($api,"app_require_auth"),'Simulator API must require authenticated Gelato user.');
gws_assert(str_contains($api,"app_verify_request_csrf"),'Simulator mutations must verify CSRF.');
gws_assert(str_contains($core,"operational_location_allowed"),'Simulator must preserve location-scoped access.');
gws_assert(str_contains($core,"app_has_permission('glasses.manage'"),'Live writes must require glasses management.');
gws_assert(str_contains($core,"app_has_permission('kds.update'"),'Live writes must require KDS update permission.');
gws_assert(str_contains($core,'glasses_current_work'),'Simulator must use canonical glasses work projection.');
gws_assert(str_contains($core,'glasses_build_start'),'Simulator must use canonical build sessions.');
gws_assert(str_contains($core,'glasses_build_observe'),'Simulator detections must use canonical observation ledger.');
gws_assert(str_contains($core,'glasses_validation_evaluate'),'Simulator must use real product validation.');
gws_assert(str_contains($core,'glasses_handoff_to_expo'),'Simulator must preserve controlled Expo handoff.');
gws_assert(!str_contains($core,'UPDATE kds_order_items'),'Simulator core must not bypass KDS lifecycle with direct updates.');
gws_assert(str_contains($page,'lens-projection'),'Page must have a dedicated lens projection surface.');
gws_assert(str_contains($page,'detectionLayer'),'Page must expose ingredient outline layer.');
gws_assert(str_contains($js,"mode==='mock'"),'Simulator must have isolated mock mode.');
gws_assert(str_contains($js,"mode==='live'"),'Simulator must have real Gelato live mode.');
gws_assert(str_contains($js,"metadata:{source:'web_glasses_simulator'"),'Live simulated observations must be source-labelled.');
gws_assert(str_contains($js,"validation.status!=='ready_for_finishing'"),'Expo control must remain gated by product validation.');
gws_assert(str_contains($js,'function selectedItem()'),'Live simulator must allow explicit KDS work selection.');
gws_assert(str_contains($js,'resetSimulator'),'Simulator must support releasing local build UI state for the next ticket.');
gws_assert(str_contains($page,'workItemSelect'),'Page must expose KDS item selector.');
gws_assert(str_contains($page,'sceneFile')&&str_contains($page,'glassesFile'),'Simulator must support local artwork previews without server upload.');
gws_assert(str_contains($js,"bindLocalImage('sceneFile'"),'Simulator must bind local scene artwork preview.');
gws_assert(str_contains($css,'.hud-right'),'HUD must keep persistent projection on the right side.');
gws_assert(str_contains($css,'.detection-box'),'HUD must support ingredient bounding boxes.');
gws_assert(str_contains($page,'calibrationToggle'),'Simulator must expose calibration mode.');
gws_assert(str_contains($page,'safeAreaGuide')&&str_contains($page,'leftEyeGuide')&&str_contains($page,'rightEyeGuide'),'Simulator must expose safe-area and per-eye guides.');
gws_assert(str_contains($page,'presetSelect')&&str_contains($page,'savePreset'),'Simulator must expose layout presets.');
gws_assert(str_contains($js,"CAL_KEY='gelato.webGlassesSimulator.calibration.v1'"),'Calibration must persist in browser storage.');
gws_assert(str_contains($js,'bindRegionEditor'),'Calibration must support drag/resize region editing.');
gws_assert(str_contains($js,'leftEyeX')&&str_contains($js,'rightEyeY'),'Calibration must support per-eye alignment.');
gws_assert(str_contains($css,'.glasses-stage.calibrating .eye-guide'),'Calibration guides must be visible only while editing.');
gws_assert(str_contains($page,'svgGlassesLayer')&&str_contains($page,'outsideLensMask'),'Simulator must render a native SVG glasses frame with optical occlusion mask.');
gws_assert(str_contains($page,'frameModeSelect'),'Simulator must expose SVG, uploaded-image, and frameless modes.');
gws_assert(str_contains($page,'opticalMaskToggle'),'Simulator must expose independent lens-mask control.');
gws_assert(str_contains($js,"FRAME_MODE_KEY='gelato.webGlassesSimulator.frameMode.v1'"),'Frame mode must persist locally.');
gws_assert(str_contains($js,'function applyFrameMode()'),'Simulator must apply optical frame mode without touching kitchen state.');
gws_assert(str_contains($js,"frameMode='image'"),'Loading custom glasses artwork must switch to image mode.');
gws_assert(str_contains($css,'.svg-glasses-layer'),'SVG optical layer must be independently styled above the HUD.');
gws_assert(str_contains($page,'hudOrders')&&str_contains($page,'hudOrdersCount'),'HUD must expose Active Orders rail.');
gws_assert(str_contains($page,'hudNextCenter')&&str_contains($page,'hudLeaderLine'),'HUD must expose central NEXT instruction and leader line.');
gws_assert(str_contains($page,'hudBuildSteps')&&str_contains($page,'hudValidationMissing'),'HUD must expose build sequence and validation detail.');
gws_assert(str_contains($page,'autoPlayBuild')&&str_contains($page,'lowConfidenceDetection'),'Simulator must expose deterministic demo controls.');
gws_assert(str_contains($js,'function renderOrdersQueue'),'HUD must render station KDS queue.');
gws_assert(str_contains($js,'function renderNextInstruction'),'HUD must render next required component.');
gws_assert(str_contains($js,'function renderBuildRail'),'HUD must render active build sequence.');
gws_assert(str_contains($js,'function renderValidationPanel'),'HUD must render missing/unexpected validation.');
gws_assert(str_contains($js,"presets['Pizza Line Reference']"),'Reference HUD layout preset must be seeded.');
gws_assert(str_contains($js,'function toggleAutoPlay'),'Mock demo must support scripted playback.');
gws_assert(str_contains($css,'.hud-orders-left')&&str_contains($css,'.hud-next-center'),'Reference HUD styling must preserve left rail and open center.');
gws_assert(str_contains($css,'.detection-box.low-confidence')&&str_contains($css,'.detection-box.unexpected'),'Detection overlays must communicate verification and unexpected states.');
gws_assert(str_contains($css,'.glasses-stage.calibrating .hud-orders-left')&&str_contains($css,'.glasses-stage.calibrating .hud-next-center'),'New HUD rails must honor calibration geometry.');
gws_assert(str_contains($css,'.glasses-stage.calibrating .hud-right-build')&&str_contains($css,'.glasses-stage.calibrating .hud-topbar'),'Build and status HUD regions must honor calibration geometry.');
gws_assert(str_contains($page,'syncBadge'),'Simulator must expose live station synchronization state.');
gws_assert(str_contains($api,"\$action==='work'")&&str_contains($api,"Cache-Control: no-store"),'Read-only GET work synchronization must be uncached.');
gws_assert(str_contains($js,'LIVE_SYNC_BASE_MS=1500'),'Live station synchronization must use bounded near-real-time polling.');
gws_assert(str_contains($js,'function liveWorkFingerprint'),'Live sync must suppress no-op renders/logs using work fingerprints.');
gws_assert(str_contains($js,'function syncLiveStationWork'),'Simulator must continuously synchronize station work in Live mode.');
gws_assert(str_contains($js,'visibilitychange'),'Live sync must pause when the simulator tab is hidden.');
gws_assert(str_contains($js,'LIVE_SYNC_MAX_BACKOFF_MS'),'Live sync must back off on repeated transport failures.');
gws_assert(str_contains($js,'activeBuildItem'),'Live sync must preserve active build selection across station refreshes.');
gws_assert(str_contains($js,'syncEpoch'),'Live sync must discard stale in-flight polls after mode/device changes.');
gws_assert(str_contains($js,'devicePublicId=state.device.publicId'),'Live sync requests must bind to the device selected when each poll begins.');
gws_assert(!str_contains($api,'app_verify_request_csrf($_GET'),'Read-only station synchronization must not pretend GET is a mutation.');
gws_assert(str_contains($css,'.sim-sync-badge.live')&&str_contains($css,'.sim-sync-badge.error'),'Simulator must visibly distinguish healthy and retrying synchronization.');
gws_assert(str_contains($page,'cameraVideo')&&str_contains($page,'sceneSourceSelect'),'Simulator must expose browser camera as a scene source.');
gws_assert(str_contains($page,'cameraDeviceSelect')&&str_contains($page,'cameraResolution'),'Simulator must expose camera device and resolution controls.');
gws_assert(str_contains($page,'cameraManualTarget')&&str_contains($page,'submitCameraTarget'),'Simulator must expose manual camera vision targeting.');
gws_assert(str_contains($js,'navigator.mediaDevices.getUserMedia'),'Browser camera runtime must use standards-based getUserMedia.');
gws_assert(str_contains($js,'function enumerateCameras'),'Camera runtime must enumerate available video inputs.');
gws_assert(str_contains($js,'function captureCameraFrame'),'Camera runtime must support local frame capture.');
gws_assert(str_contains($js,'function submitCameraTargetObservation'),'Camera runtime must submit targeted observations through canonical simulator flow.');
gws_assert(str_contains($js,"metadata:{source:'web_glasses_simulator_camera'"),'Camera observations must be source-labelled.');
gws_assert(str_contains($js,'cameraStream.getTracks().forEach'),'Camera stop must release hardware tracks.');
gws_assert(str_contains($js,'NotAllowedError')&&str_contains($js,'NotFoundError'),'Camera runtime must handle permission denial and missing hardware.');
gws_assert(str_contains($css,'.camera-target-marker')&&str_contains($css,'.camera-video'),'Camera preview and target overlay must be styled independently of HUD.');
gws_assert(str_contains($js,'function cameraPointerGeometry'),'Manual targets must map through rendered video geometry.');
gws_assert(str_contains($js,'videoX')&&str_contains($js,'videoY'),'Submitted camera boxes must use normalized video-frame coordinates.');
gws_assert(str_contains($js,"state.cameraTrack.enabled=!document.hidden"),'Camera capture must pause while the simulator tab is hidden.');
gws_assert(str_contains($page,'visionMode')&&str_contains($page,'visionFpsLimit'),'Simulator must expose Manual, Assisted and Automatic browser vision controls.');
gws_assert(str_contains($page,'visionConfidenceThreshold')&&str_contains($page,'visionMetrics'),'Simulator must expose automatic vision threshold and health telemetry.');
gws_assert(str_contains($page,'visionDetectionLayer'),'Simulator must expose a dedicated automatic vision overlay layer.');
gws_assert(str_contains($js,'const VISION_ADAPTERS'),'Browser vision must use a detector adapter contract rather than hard-coding vendor APIs.');
gws_assert(str_contains($js,"id:'fixture'"),'Browser vision must provide a deterministic detector fixture while the production model adapter is pending.');
gws_assert(str_contains($js,'function runVisionFrame'),'Browser vision must run a bounded continuous inference loop.');
gws_assert(str_contains($js,'function trackDetections'),'Browser vision must assign persistent tracking IDs across frames.');
gws_assert(str_contains($js,'VISION_TRACK_TTL_MS'),'Browser vision tracks must expire rather than persist stale detections.');
gws_assert(str_contains($js,'visionIntervalMs'),'Browser vision must apply an explicit FPS budget.');
gws_assert(str_contains($js,'visionConfidenceThreshold'),'Automatic vision must filter detections by operator-visible confidence threshold.');
gws_assert(str_contains($js,'function normalizedBoxToStage'),'Automatic detections must map normalized video boxes through rendered camera geometry.');
gws_assert(str_contains($js,"metadata:{source:'web_glasses_simulator_auto_vision'"),'Automatic browser observations must be source-labelled.');
gws_assert(str_contains($js,"visionMode()==='automatic'"),'Only Automatic mode may submit detector observations.');
gws_assert(str_contains($js,"visionMode()!=='manual'"),'Assisted and Automatic modes must share the detector loop while Manual remains isolated.');
gws_assert(str_contains($js,'visionSubmitted'),'Automatic vision must suppress duplicate component submissions for the active build.');
gws_assert(str_contains($js,'stopVisionRuntime'),'Browser vision must stop on camera/tab lifecycle transitions.');
gws_assert(str_contains($css,'.vision-auto-box')&&str_contains($css,'.vision-detection-layer'),'Automatic detections must have an independent tracked overlay.');
gws_assert(str_contains($page,'temporalValidationState')&&str_contains($page,'temporalEventList'),'Simulator must expose temporal multi-ingredient validation state and event history.');
gws_assert(str_contains($js,'VISION_STABLE_FRAMES=3'),'Temporal detections must require repeated-frame stability before mutation.');
gws_assert(str_contains($js,'VISION_REMOVAL_GRACE_MS=2200'),'Temporal removals must use a bounded absence grace period to reject detector flicker.');
gws_assert(str_contains($js,'VISION_REPLACEMENT_IOU'),'Temporal tracking must use spatial overlap when classifying replacement events.');
gws_assert(str_contains($js,'function bboxIou'),'Temporal tracking must calculate overlap for replacement inference.');
gws_assert(str_contains($js,'function processTemporalEvents'),'Automatic vision must reconcile stable additions and removals over time.');
gws_assert(str_contains($js,"submitTemporalObservation(lost,'removed'"),'Stable ingredient disappearance must use the canonical removed observation action.');
gws_assert(str_contains($js,"submitTemporalObservation(track,'added'"),'Stable ingredient appearance must use the canonical added observation action.');
gws_assert(str_contains($js,'function sequenceViolationFor'),'Temporal product validation must detect out-of-order required ingredients.');
gws_assert(str_contains($js,'temporalViolations'),'Sequence violations must remain explicit validation state rather than being silently ignored.');
gws_assert(str_contains($js,'function temporalAssessment'),'Temporal runtime must calculate complete-product readiness from missing, verify, unexpected, sequence and pending states.');
gws_assert(str_contains($js,'VISION_READY_STABLE_MS'),'Automatic product validation must require a stable-ready dwell period.');
gws_assert(str_contains($js,'function autoEvaluateTemporalReadiness'),'Temporal runtime must automatically invoke canonical product validation only after stable readiness.');
gws_assert(str_contains($js,"api('validation.evaluate'"),'Automatic temporal readiness must reuse canonical product validation.');
gws_assert(str_contains($js,"metadata:{source:'web_glasses_simulator_temporal_vision'"),'Temporal observations must be explicitly source-labelled.');
gws_assert(str_contains($js,"visionMode()==='automatic'&&!state.temporalGate?.ready"),'Expo handoff must remain blocked when automatic temporal validation is not ready.');
gws_assert(str_contains($js,'function clearTemporalRuntime'),'Temporal state must reset at build, mode and device boundaries.');
gws_assert(str_contains($css,'.temporal-event')&&str_contains($css,'.vision-auto-box.pending'),'Temporal events and pre-stable tracks must have visible, distinct UI states.');



echo "glasses-web-simulator-ok\n";
