<?php
declare(strict_types=1);

$root=dirname(__DIR__);
function gws_assert(bool $condition,string $message): void {if(!$condition)throw new RuntimeException($message);}
function gws_file(string $path): string {global $root;$c=file_get_contents($root.'/'.$path);if($c===false)throw new RuntimeException('Missing '.$path);return $c;}

$api=gws_file('api/glasses-simulator.php');
$core=gws_file('includes/glasses-simulator.php');
$page=gws_file('glasses-simulator.php');
$js=gws_file('assets/js/glasses-web-simulator.js');
$css=gws_file('assets/css/glasses-web-simulator.css');

gws_assert(str_contains($api,"app_require_auth"),'Simulator API must require authenticated Gelato user.');
gws_assert(str_contains($api,"app_verify_request_csrf"),'Simulator mutations must verify CSRF.');
gws_assert(str_contains($core,"operational_location_allowed"),'Simulator must preserve location-scoped access.');
gws_assert(str_contains($core,"app_has_permission('glasses.manage'"),'Live writes must require glasses management.');
gws_assert(str_contains($core,"app_has_permission('kds.update'"),'Live writes must require KDS update permission.');
gws_assert(str_contains($core,'glasses_current_work'),'Simulator must use canonical glasses work projection.');
gws_assert(str_contains($core,'glasses_build_start'),'Simulator must use canonical build sessions.');
gws_assert(str_contains($core,'glasses_build_observe'),'Simulator detections must use canonical observation ledger.');
gws_assert(str_contains($core,'glasses_validation_evaluate'),'Simulator must use real product validation.');
gws_assert(str_contains($core,'glasses_handoff_to_expo'),'Simulator must preserve controlled Expo handoff.');
gws_assert(!str_contains($core,'UPDATE kds_order_items'),'Simulator core must not bypass KDS lifecycle with direct updates.');
gws_assert(str_contains($page,'lens-projection'),'Page must have a dedicated lens projection surface.');
gws_assert(str_contains($page,'detectionLayer'),'Page must expose ingredient outline layer.');
gws_assert(str_contains($js,"mode==='mock'"),'Simulator must have isolated mock mode.');
gws_assert(str_contains($js,"mode==='live'"),'Simulator must have real Gelato live mode.');
gws_assert(str_contains($js,"metadata:{source:'web_glasses_simulator'"),'Live simulated observations must be source-labelled.');
gws_assert(str_contains($js,"validation.status!=='ready_for_finishing'"),'Expo control must remain gated by product validation.');
gws_assert(str_contains($js,'function selectedItem()'),'Live simulator must allow explicit KDS work selection.');
gws_assert(str_contains($js,'resetSimulator'),'Simulator must support releasing local build UI state for the next ticket.');
gws_assert(str_contains($page,'workItemSelect'),'Page must expose KDS item selector.');
gws_assert(str_contains($page,'sceneFile')&&str_contains($page,'glassesFile'),'Simulator must support local artwork previews without server upload.');
gws_assert(str_contains($js,"bindLocalImage('sceneFile'"),'Simulator must bind local scene artwork preview.');
gws_assert(str_contains($css,'.hud-right'),'HUD must keep persistent projection on the right side.');
gws_assert(str_contains($css,'.detection-box'),'HUD must support ingredient bounding boxes.');
gws_assert(str_contains($page,'calibrationToggle'),'Simulator must expose calibration mode.');
gws_assert(str_contains($page,'safeAreaGuide')&&str_contains($page,'leftEyeGuide')&&str_contains($page,'rightEyeGuide'),'Simulator must expose safe-area and per-eye guides.');
gws_assert(str_contains($page,'presetSelect')&&str_contains($page,'savePreset'),'Simulator must expose layout presets.');
gws_assert(str_contains($js,"CAL_KEY='gelato.webGlassesSimulator.calibration.v1'"),'Calibration must persist in browser storage.');
gws_assert(str_contains($js,'bindRegionEditor'),'Calibration must support drag/resize region editing.');
gws_assert(str_contains($js,'leftEyeX')&&str_contains($js,'rightEyeY'),'Calibration must support per-eye alignment.');
gws_assert(str_contains($css,'.glasses-stage.calibrating .eye-guide'),'Calibration guides must be visible only while editing.');
gws_assert(str_contains($page,'svgGlassesLayer')&&str_contains($page,'outsideLensMask'),'Simulator must render a native SVG glasses frame with optical occlusion mask.');
gws_assert(str_contains($page,'frameModeSelect'),'Simulator must expose SVG, uploaded-image, and frameless modes.');
gws_assert(str_contains($page,'opticalMaskToggle'),'Simulator must expose independent lens-mask control.');
gws_assert(str_contains($js,"FRAME_MODE_KEY='gelato.webGlassesSimulator.frameMode.v1'"),'Frame mode must persist locally.');
gws_assert(str_contains($js,'function applyFrameMode()'),'Simulator must apply optical frame mode without touching kitchen state.');
gws_assert(str_contains($js,"frameMode='image'"),'Loading custom glasses artwork must switch to image mode.');
gws_assert(str_contains($css,'.svg-glasses-layer'),'SVG optical layer must be independently styled above the HUD.');
gws_assert(str_contains($page,'hudOrders')&&str_contains($page,'hudOrdersCount'),'HUD must expose Active Orders rail.');
gws_assert(str_contains($page,'hudNextCenter')&&str_contains($page,'hudLeaderLine'),'HUD must expose central NEXT instruction and leader line.');
gws_assert(str_contains($page,'hudBuildSteps')&&str_contains($page,'hudValidationMissing'),'HUD must expose build sequence and validation detail.');
gws_assert(str_contains($page,'autoPlayBuild')&&str_contains($page,'lowConfidenceDetection'),'Simulator must expose deterministic demo controls.');
gws_assert(str_contains($js,'function renderOrdersQueue'),'HUD must render station KDS queue.');
gws_assert(str_contains($js,'function renderNextInstruction'),'HUD must render next required component.');
gws_assert(str_contains($js,'function renderBuildRail'),'HUD must render active build sequence.');
gws_assert(str_contains($js,'function renderValidationPanel'),'HUD must render missing/unexpected validation.');
gws_assert(str_contains($js,"presets['Pizza Line Reference']"),'Reference HUD layout preset must be seeded.');
gws_assert(str_contains($js,'function toggleAutoPlay'),'Mock demo must support scripted playback.');
gws_assert(str_contains($css,'.hud-orders-left')&&str_contains($css,'.hud-next-center'),'Reference HUD styling must preserve left rail and open center.');
gws_assert(str_contains($css,'.detection-box.low-confidence')&&str_contains($css,'.detection-box.unexpected'),'Detection overlays must communicate verification and unexpected states.');
gws_assert(str_contains($css,'.glasses-stage.calibrating .hud-orders-left')&&str_contains($css,'.glasses-stage.calibrating .hud-next-center'),'New HUD rails must honor calibration geometry.');
gws_assert(str_contains($css,'.glasses-stage.calibrating .hud-right-build')&&str_contains($css,'.glasses-stage.calibrating .hud-topbar'),'Build and status HUD regions must honor calibration geometry.');
gws_assert(str_contains($page,'syncBadge'),'Simulator must expose live station synchronization state.');
gws_assert(str_contains($api,"\$action==='work'")&&str_contains($api,"Cache-Control: no-store"),'Read-only GET work synchronization must be uncached.');
gws_assert(str_contains($js,'LIVE_SYNC_BASE_MS=1500'),'Live station synchronization must use bounded near-real-time polling.');
gws_assert(str_contains($js,'function liveWorkFingerprint'),'Live sync must suppress no-op renders/logs using work fingerprints.');
gws_assert(str_contains($js,'function syncLiveStationWork'),'Simulator must continuously synchronize station work in Live mode.');
gws_assert(str_contains($js,'visibilitychange'),'Live sync must pause when the simulator tab is hidden.');
gws_assert(str_contains($js,'LIVE_SYNC_MAX_BACKOFF_MS'),'Live sync must back off on repeated transport failures.');
gws_assert(str_contains($js,'activeBuildItem'),'Live sync must preserve active build selection across station refreshes.');
gws_assert(str_contains($js,'syncEpoch'),'Live sync must discard stale in-flight polls after mode/device changes.');
gws_assert(str_contains($js,'devicePublicId=state.device.publicId'),'Live sync requests must bind to the device selected when each poll begins.');
gws_assert(!str_contains($api,'app_verify_request_csrf($_GET'),'Read-only station synchronization must not pretend GET is a mutation.');
gws_assert(str_contains($css,'.sim-sync-badge.live')&&str_contains($css,'.sim-sync-badge.error'),'Simulator must visibly distinguish healthy and retrying synchronization.');
gws_assert(str_contains($page,'cameraVideo')&&str_contains($page,'sceneSourceSelect'),'Simulator must expose browser camera as a scene source.');
gws_assert(str_contains($page,'cameraDeviceSelect')&&str_contains($page,'cameraResolution'),'Simulator must expose camera device and resolution controls.');
gws_assert(str_contains($page,'cameraManualTarget')&&str_contains($page,'submitCameraTarget'),'Simulator must expose manual camera vision targeting.');
gws_assert(str_contains($js,'navigator.mediaDevices.getUserMedia'),'Browser camera runtime must use standards-based getUserMedia.');
gws_assert(str_contains($js,'function enumerateCameras'),'Camera runtime must enumerate available video inputs.');
gws_assert(str_contains($js,'function captureCameraFrame'),'Camera runtime must support local frame capture.');
gws_assert(str_contains($js,'function submitCameraTargetObservation'),'Camera runtime must submit targeted observations through canonical simulator flow.');
gws_assert(str_contains($js,"metadata:{source:'web_glasses_simulator_camera'"),'Camera observations must be source-labelled.');
gws_assert(str_contains($js,'cameraStream.getTracks().forEach'),'Camera stop must release hardware tracks.');
gws_assert(str_contains($js,'NotAllowedError')&&str_contains($js,'NotFoundError'),'Camera runtime must handle permission denial and missing hardware.');
gws_assert(str_contains($css,'.camera-target-marker')&&str_contains($css,'.camera-video'),'Camera preview and target overlay must be styled independently of HUD.');

echo "glasses-web-simulator-ok\n";
