<?php
declare(strict_types=1);

$root=dirname(__DIR__);
function gws_assert(bool $condition,string $message): void {if(!$condition)throw new RuntimeException($message);}
function gws_file(string $path): string {global $root;$c=file_get_contents($root.'/'.$path);if($c===false)throw new RuntimeException('Missing '.$path);return $c;}

$api=gws_file('api/glasses-simulator.php');
$core=gws_file('includes/glasses-simulator.php');
$page=gws_file('glasses-simulator.php');
$js=gws_file('assets/js/glasses-web-simulator.js');
$css=gws_file('assets/css/glasses-web-simulator.css');

gws_assert(str_contains($api,"app_require_auth"),'Simulator API must require authenticated Gelato user.');
gws_assert(str_contains($api,"app_verify_request_csrf"),'Simulator mutations must verify CSRF.');
gws_assert(str_contains($core,"operational_location_allowed"),'Simulator must preserve location-scoped access.');
gws_assert(str_contains($core,"app_has_permission('glasses.manage'"),'Live writes must require glasses management.');
gws_assert(str_contains($core,"app_has_permission('kds.update'"),'Live writes must require KDS update permission.');
gws_assert(str_contains($core,'glasses_current_work'),'Simulator must use canonical glasses work projection.');
gws_assert(str_contains($core,'glasses_build_start'),'Simulator must use canonical build sessions.');
gws_assert(str_contains($core,'glasses_build_observe'),'Simulator detections must use canonical observation ledger.');
gws_assert(str_contains($core,'glasses_validation_evaluate'),'Simulator must use real product validation.');
gws_assert(str_contains($core,'glasses_handoff_to_expo'),'Simulator must preserve controlled Expo handoff.');
gws_assert(!str_contains($core,'UPDATE kds_order_items'),'Simulator core must not bypass KDS lifecycle with direct updates.');
gws_assert(str_contains($page,'lens-projection'),'Page must have a dedicated lens projection surface.');
gws_assert(str_contains($page,'detectionLayer'),'Page must expose ingredient outline layer.');
gws_assert(str_contains($js,"mode==='mock'"),'Simulator must have isolated mock mode.');
gws_assert(str_contains($js,"mode==='live'"),'Simulator must have real Gelato live mode.');
gws_assert(str_contains($js,"metadata:{source:'web_glasses_simulator'"),'Live simulated observations must be source-labelled.');
gws_assert(str_contains($js,"validation.status!=='ready_for_finishing'"),'Expo control must remain gated by product validation.');
gws_assert(str_contains($js,'function selectedItem()'),'Live simulator must allow explicit KDS work selection.');
gws_assert(str_contains($js,'resetSimulator'),'Simulator must support releasing local build UI state for the next ticket.');
gws_assert(str_contains($page,'workItemSelect'),'Page must expose KDS item selector.');
gws_assert(str_contains($page,'sceneFile')&&str_contains($page,'glassesFile'),'Simulator must support local artwork previews without server upload.');
gws_assert(str_contains($js,"bindLocalImage('sceneFile'"),'Simulator must bind local scene artwork preview.');
gws_assert(str_contains($css,'.hud-right'),'HUD must keep persistent projection on the right side.');
gws_assert(str_contains($css,'.detection-box'),'HUD must support ingredient bounding boxes.');
gws_assert(str_contains($page,'calibrationToggle'),'Simulator must expose calibration mode.');
gws_assert(str_contains($page,'safeAreaGuide')&&str_contains($page,'leftEyeGuide')&&str_contains($page,'rightEyeGuide'),'Simulator must expose safe-area and per-eye guides.');
gws_assert(str_contains($page,'presetSelect')&&str_contains($page,'savePreset'),'Simulator must expose layout presets.');
gws_assert(str_contains($js,"CAL_KEY='gelato.webGlassesSimulator.calibration.v1'"),'Calibration must persist in browser storage.');
gws_assert(str_contains($js,'bindRegionEditor'),'Calibration must support drag/resize region editing.');
gws_assert(str_contains($js,'leftEyeX')&&str_contains($js,'rightEyeY'),'Calibration must support per-eye alignment.');
gws_assert(str_contains($css,'.glasses-stage.calibrating .eye-guide'),'Calibration guides must be visible only while editing.');
gws_assert(str_contains($page,'svgGlassesLayer')&&str_contains($page,'outsideLensMask'),'Simulator must render a native SVG glasses frame with optical occlusion mask.');
gws_assert(str_contains($page,'frameModeSelect'),'Simulator must expose SVG, uploaded-image, and frameless modes.');
gws_assert(str_contains($page,'opticalMaskToggle'),'Simulator must expose independent lens-mask control.');
gws_assert(str_contains($js,"FRAME_MODE_KEY='gelato.webGlassesSimulator.frameMode.v1'"),'Frame mode must persist locally.');
gws_assert(str_contains($js,'function applyFrameMode()'),'Simulator must apply optical frame mode without touching kitchen state.');
gws_assert(str_contains($js,"frameMode='image'"),'Loading custom glasses artwork must switch to image mode.');
gws_assert(str_contains($css,'.svg-glasses-layer'),'SVG optical layer must be independently styled above the HUD.');
gws_assert(str_contains($page,'hudOrders')&&str_contains($page,'hudOrdersCount'),'HUD must expose Active Orders rail.');
gws_assert(str_contains($page,'hudNextCenter')&&str_contains($page,'hudLeaderLine'),'HUD must expose central NEXT instruction and leader line.');
gws_assert(str_contains($page,'hudBuildSteps')&&str_contains($page,'hudValidationMissing'),'HUD must expose build sequence and validation detail.');
gws_assert(str_contains($page,'autoPlayBuild')&&str_contains($page,'lowConfidenceDetection'),'Simulator must expose deterministic demo controls.');
gws_assert(str_contains($js,'function renderOrdersQueue'),'HUD must render station KDS queue.');
gws_assert(str_contains($js,'function renderNextInstruction'),'HUD must render next required component.');
gws_assert(str_contains($js,'function renderBuildRail'),'HUD must render active build sequence.');
gws_assert(str_contains($js,'function renderValidationPanel'),'HUD must render missing/unexpected validation.');
gws_assert(str_contains($js,"presets['Pizza Line Reference']"),'Reference HUD layout preset must be seeded.');
gws_assert(str_contains($js,'function toggleAutoPlay'),'Mock demo must support scripted playback.');
gws_assert(str_contains($css,'.hud-orders-left')&&str_contains($css,'.hud-next-center'),'Reference HUD styling must preserve left rail and open center.');
gws_assert(str_contains($css,'.detection-box.low-confidence')&&str_contains($css,'.detection-box.unexpected'),'Detection overlays must communicate verification and unexpected states.');
gws_assert(str_contains($css,'.glasses-stage.calibrating .hud-orders-left')&&str_contains($css,'.glasses-stage.calibrating .hud-next-center'),'New HUD rails must honor calibration geometry.');
gws_assert(str_contains($css,'.glasses-stage.calibrating .hud-right-build')&&str_contains($css,'.glasses-stage.calibrating .hud-topbar'),'Build and status HUD regions must honor calibration geometry.');
gws_assert(str_contains($page,'syncBadge'),'Simulator must expose live station synchronization state.');
gws_assert(str_contains($api,"\$action==='work'")&&str_contains($api,"Cache-Control: no-store"),'Read-only GET work synchronization must be uncached.');
gws_assert(str_contains($js,'LIVE_SYNC_BASE_MS=1500'),'Live station synchronization must use bounded near-real-time polling.');
gws_assert(str_contains($js,'function liveWorkFingerprint'),'Live sync must suppress no-op renders/logs using work fingerprints.');
gws_assert(str_contains($js,'function syncLiveStationWork'),'Simulator must continuously synchronize station work in Live mode.');
gws_assert(str_contains($js,'visibilitychange'),'Live sync must pause when the simulator tab is hidden.');
gws_assert(str_contains($js,'LIVE_SYNC_MAX_BACKOFF_MS'),'Live sync must back off on repeated transport failures.');
gws_assert(str_contains($js,'activeBuildItem'),'Live sync must preserve active build selection across station refreshes.');
gws_assert(str_contains($js,'syncEpoch'),'Live sync must discard stale in-flight polls after mode/device changes.');
gws_assert(str_contains($js,'devicePublicId=state.device.publicId'),'Live sync requests must bind to the device selected when each poll begins.');
gws_assert(!str_contains($api,'app_verify_request_csrf($_GET'),'Read-only station synchronization must not pretend GET is a mutation.');
gws_assert(str_contains($css,'.sim-sync-badge.live')&&str_contains($css,'.sim-sync-badge.error'),'Simulator must visibly distinguish healthy and retrying synchronization.');
gws_assert(str_contains($page,'cameraVideo')&&str_contains($page,'sceneSourceSelect'),'Simulator must expose browser camera as a scene source.');
gws_assert(str_contains($page,'cameraDeviceSelect')&&str_contains($page,'cameraResolution'),'Simulator must expose camera device and resolution controls.');
gws_assert(str_contains($page,'cameraManualTarget')&&str_contains($page,'submitCameraTarget'),'Simulator must expose manual camera vision targeting.');
gws_assert(str_contains($js,'navigator.mediaDevices.getUserMedia'),'Browser camera runtime must use standards-based getUserMedia.');
gws_assert(str_contains($js,'function enumerateCameras'),'Camera runtime must enumerate available video inputs.');
gws_assert(str_contains($js,'function captureCameraFrame'),'Camera runtime must support local frame capture.');
gws_assert(str_contains($js,'function submitCameraTargetObservation'),'Camera runtime must submit targeted observations through canonical simulator flow.');
gws_assert(str_contains($js,"metadata:{source:'web_glasses_simulator_camera'"),'Camera observations must be source-labelled.');
gws_assert(str_contains($js,'cameraStream.getTracks().forEach'),'Camera stop must release hardware tracks.');
gws_assert(str_contains($js,'NotAllowedError')&&str_contains($js,'NotFoundError'),'Camera runtime must handle permission denial and missing hardware.');
gws_assert(str_contains($css,'.camera-target-marker')&&str_contains($css,'.camera-video'),'Camera preview and target overlay must be styled independently of HUD.');
gws_assert(str_contains($js,'function cameraPointerGeometry'),'Manual targets must map through rendered video geometry.');
gws_assert(str_contains($js,'videoX')&&str_contains($js,'videoY'),'Submitted camera boxes must use normalized video-frame coordinates.');
gws_assert(str_contains($js,"state.cameraTrack.enabled=!document.hidden"),'Camera capture must pause while the simulator tab is hidden.');
gws_assert(str_contains($page,'visionMode')&&str_contains($page,'visionFpsLimit'),'Simulator must expose Manual, Assisted and Automatic browser vision controls.');
gws_assert(str_contains($page,'visionConfidenceThreshold')&&str_contains($page,'visionMetrics'),'Simulator must expose automatic vision threshold and health telemetry.');
gws_assert(str_contains($page,'visionDetectionLayer'),'Simulator must expose a dedicated automatic vision overlay layer.');
gws_assert(str_contains($js,'const VISION_ADAPTERS'),'Browser vision must use a detector adapter contract rather than hard-coding vendor APIs.');
gws_assert(str_contains($js,"id:'fixture'"),'Browser vision must provide a deterministic detector fixture while the production model adapter is pending.');
gws_assert(str_contains($js,'function enqueueVisionFrame')&&str_contains($js,'function processFrameQueue')&&str_contains($js,'function scheduleVisionCapture'),'Browser vision must run through the bounded continuous frame pipeline.');
gws_assert(str_contains($js,'function trackDetections'),'Browser vision must assign persistent tracking IDs across frames.');
gws_assert(str_contains($js,'VISION_TRACK_TTL_MS'),'Browser vision tracks must expire rather than persist stale detections.');
gws_assert(str_contains($js,'visionIntervalMs'),'Browser vision must apply an explicit FPS budget.');
gws_assert(str_contains($js,'visionConfidenceThreshold'),'Automatic vision must filter detections by operator-visible confidence threshold.');
gws_assert(str_contains($js,'function normalizedBoxToStage'),'Automatic detections must map normalized video boxes through rendered camera geometry.');
gws_assert(str_contains($js,"metadata:{source:'web_glasses_simulator_auto_vision'"),'Automatic browser observations must be source-labelled.');
gws_assert(str_contains($js,"visionMode()==='automatic'"),'Only Automatic mode may submit detector observations.');
gws_assert(str_contains($js,"visionMode()!=='manual'"),'Assisted and Automatic modes must share the detector loop while Manual remains isolated.');
gws_assert(str_contains($js,'visionSubmitted'),'Automatic vision must suppress duplicate component submissions for the active build.');
gws_assert(str_contains($js,'stopVisionRuntime'),'Browser vision must stop on camera/tab lifecycle transitions.');
gws_assert(str_contains($css,'.vision-auto-box')&&str_contains($css,'.vision-detection-layer'),'Automatic detections must have an independent tracked overlay.');
gws_assert(str_contains($page,'temporalValidationState')&&str_contains($page,'temporalEventList'),'Simulator must expose temporal multi-ingredient validation state and event history.');
gws_assert(str_contains($js,'VISION_STABLE_FRAMES=3'),'Temporal detections must require repeated-frame stability before mutation.');
gws_assert(str_contains($js,'VISION_REMOVAL_GRACE_MS=2200'),'Temporal removals must use a bounded absence grace period to reject detector flicker.');
gws_assert(str_contains($js,'VISION_REPLACEMENT_IOU'),'Temporal tracking must use spatial overlap when classifying replacement events.');
gws_assert(str_contains($js,'function bboxIou'),'Temporal tracking must calculate overlap for replacement inference.');
gws_assert(str_contains($js,'function processTemporalEvents'),'Automatic vision must reconcile stable additions and removals over time.');
gws_assert(str_contains($js,"submitTemporalObservation(lost,'removed'"),'Stable ingredient disappearance must use the canonical removed observation action.');
gws_assert(str_contains($js,"submitTemporalObservation(track,'added'"),'Stable ingredient appearance must use the canonical added observation action.');
gws_assert(str_contains($js,'function sequenceViolationFor'),'Temporal product validation must detect out-of-order required ingredients.');
gws_assert(str_contains($js,'temporalViolations'),'Sequence violations must remain explicit validation state rather than being silently ignored.');
gws_assert(str_contains($js,'function temporalAssessment'),'Temporal runtime must calculate complete-product readiness from missing, verify, unexpected, sequence and pending states.');
gws_assert(str_contains($js,'VISION_READY_STABLE_MS'),'Automatic product validation must require a stable-ready dwell period.');
gws_assert(str_contains($js,'function autoEvaluateTemporalReadiness'),'Temporal runtime must automatically invoke canonical product validation only after stable readiness.');
gws_assert(str_contains($js,"api('validation.evaluate'"),'Automatic temporal readiness must reuse canonical product validation.');
gws_assert(str_contains($js,"temporalSource:'web_glasses_simulator_temporal_vision'"),'Temporal observations must retain explicit temporal pipeline provenance.');
gws_assert(str_contains($js,"visionMode()==='automatic'&&!state.temporalGate?.ready"),'Expo handoff must remain blocked when automatic temporal validation is not ready.');
gws_assert(str_contains($js,'function clearTemporalRuntime'),'Temporal state must reset at build, mode and device boundaries.');
gws_assert(str_contains($css,'.temporal-event')&&str_contains($css,'.vision-auto-box.pending'),'Temporal events and pre-stable tracks must have visible, distinct UI states.');
gws_assert(str_contains($core,"require_once __DIR__.'/glasses-vision-models.php'")&&str_contains($core,"require_once __DIR__.'/glasses-vision-profiles.php'"),'Simulator must reuse governed model assignment and vision profile services.');
gws_assert(str_contains($core,"\$action==='vision.model_assignment'")&&str_contains($core,'glasses_vision_model_assignment'),'Simulator must expose governed model assignment for the active device/build.');
gws_assert(str_contains($core,"\$action==='vision.profile'")&&str_contains($core,'glasses_vision_profile_for_build'),'Simulator must expose the active governed label profile.');
gws_assert(str_contains($page,'visionAdapterSelect')&&str_contains($page,'loadVisionModel'),'Simulator must expose fixture versus governed ONNX runtime selection.');
gws_assert(str_contains($page,'visionDetectorName')&&str_contains($page,'visionModelStatus'),'Simulator must expose detector identity and verified model state.');
gws_assert(str_contains($js,"const ORT_WEB_VERSION='1.30.0'"),'Browser ONNX runtime dependency must be explicitly version-pinned.');
gws_assert(str_contains($js,'BROWSER_MODEL_MAX_BYTES'),'Browser model downloads must enforce a hard artifact size ceiling.');
gws_assert(str_contains($js,'crypto.subtle.digest'),'Browser model activation must verify SHA-256 over downloaded bytes.');
gws_assert(str_contains($js,'pkg.artifactBytes')&&str_contains($js,'pkg.artifactSha256'),'Browser model activation must enforce the immutable package manifest.');
gws_assert(str_contains($js,"pkg.runtimeType!=='onnx'"),'Browser runtime must fail closed for non-ONNX governed assignments.');
gws_assert(str_contains($js,"gelato.browser_onnx_detector.v1"),'ONNX packages must declare an explicit browser inference metadata schema.');
gws_assert(str_contains($js,'ort.InferenceSession.create'),'Real browser inference must create an ONNX Runtime Web session from verified bytes.');
gws_assert(str_contains($js,'preprocessOnnxFrame'),'Real browser inference must preprocess live camera frames into model tensors.');
gws_assert(str_contains($js,'decodeYoloV8'),'Real browser inference must decode supported detector output into normalized detections.');
gws_assert(str_contains($js,'nmsDetections'),'Real browser inference must suppress overlapping duplicate detections.');
gws_assert(str_contains($js,'applyVisionProfile'),'Raw model labels must pass through the existing Gelato label-profile authority.');
gws_assert(str_contains($js,'blockedLabels'),'Blocked detector labels must fail closed in browser inference.');
gws_assert(str_contains($js,'profileMinimumConfidence'),'Per-label profile confidence policy must remain observable in browser detections.');
gws_assert(str_contains($js,"id:'onnx'"),'Browser vision adapter registry must include a real ONNX adapter.');
gws_assert(str_contains($js,'unloadGovernedVisionModel'),'Build/device boundaries must release governed browser model sessions.');
gws_assert(str_contains($css,'.vision-model-status'),'Governed model verification state must be visible in the simulator.');
gws_assert(str_contains($page,'datasetLabelMode')&&str_contains($page,'datasetClassSelect'),'Simulator must expose local dataset labeling controls.');
gws_assert(str_contains($page,'datasetCaptureSample')&&str_contains($page,'datasetExport'),'Simulator must support labeled frame capture and dataset export.');
gws_assert(str_contains($page,'datasetAnnotationLayer'),'Dataset boxes must render in a dedicated camera overlay layer.');
gws_assert(str_contains($js,'function startDatasetBox')&&str_contains($js,'function finishDatasetBox'),'Dataset labeling must support drag-defined bounding boxes.');
gws_assert(str_contains($js,'cameraPointerGeometry(event)'),'Dataset boxes must reuse camera/video geometry rather than screen-only coordinates.');
gws_assert(str_contains($js,"canvasToBlob(canvas,'image/jpeg'"),'Dataset samples must capture real camera frames as JPEG bytes.');
gws_assert(str_contains($js,'gelato.vision_training_dataset.v1'),'Dataset export must include a versioned Gelato training manifest.');
gws_assert(str_contains($js,"format:'yolo_detection'"),'Dataset export must declare YOLO object-detection format.');
gws_assert(str_contains($js,"images/train/frame-")&&str_contains($js,"labels/train/frame-"),'Dataset export must use YOLO image/label directory structure.');
gws_assert(str_contains($js,"name:'data.yaml'"),'Dataset export must include YOLO data.yaml.');
gws_assert(str_contains($js,'function zipStore'),'Dataset export must create a self-contained ZIP without a server upload dependency.');
gws_assert(str_contains($js,'function crc32'),'Dataset ZIP writer must provide valid CRC-32 entries.');
gws_assert(str_contains($js,'state.dataset.samples'),'Dataset samples must remain browser-local state.');
gws_assert(!str_contains($core,'vision_training_dataset'),'Dataset capture must not add a server-side mutation path.');
gws_assert(str_contains($css,'.dataset-annotation-layer')&&str_contains($css,'.dataset-box'),'Dataset annotations must have visible independent overlay styling.');
gws_assert(str_contains($page,'activeLearningEnabled')&&str_contains($page,'activeLearningCurrent'),'Simulator must expose a local hard-example capture/review queue.');
gws_assert(str_contains($page,'activeLearningAccept')&&str_contains($page,'activeLearningReclassify')&&str_contains($page,'activeLearningNegative'),'Hard examples must require explicit human acceptance, reclassification, or negative-frame review.');
gws_assert(str_contains($js,'captureHardExample'),'Vision runtime must capture hard examples through a bounded local candidate path.');
gws_assert(str_contains($js,'activeLearning.lastCaptureByKey')&&str_contains($js,'cooldownMs:10000'),'Hard-example capture must deduplicate repeated detector failures with a bounded cooldown.');
gws_assert(str_contains($js,'maxQueue:30'),'Active-learning browser memory must use a bounded candidate queue.');
gws_assert(str_contains($js,"captureHardExample('low_confidence'"),'Below-threshold detector outputs must be eligible as hard examples.');
gws_assert(str_contains($js,"captureHardExample('sequence_violation'"),'Temporal sequence violations must be eligible as hard examples.');
gws_assert(str_contains($js,"replacement?'replacement':'track_disappearance'"),'Stable disappearance/replacement events must be eligible as hard examples.');
gws_assert(str_contains($js,"captureHardExample('manual_low_confidence'"),'Manual low-confidence review must be eligible as a hard example.');
gws_assert(str_contains($js,'function candidateToDataset'),'Reviewed hard examples must enter the existing training dataset only through an explicit review step.');
gws_assert(str_contains($js,"mode==='negative'")&&str_contains($js,'annotations=[]'),'False-positive review must support negative/background training frames.');
gws_assert(str_contains($js,"schema:'gelato.vision_active_learning.v1'"),'YOLO export must identify reviewed active-learning samples with a versioned manifest contract.');
gws_assert(str_contains($js,'reviewOutcomes:reviewCounts'),'YOLO export must summarize active-learning human review outcomes.');
gws_assert(!str_contains($core,'vision_active_learning'),'Active-learning image capture must remain browser-local with no new server image mutation path.');
gws_assert(str_contains($css,'.active-learning-panel')&&str_contains($css,'.active-learning-row'),'Active-learning candidates must have visible review UI states.');
gws_assert(str_contains($page,'startShadowModel')&&str_contains($page,'completeShadowModel'),'Simulator must expose explicit live shadow start/complete controls.');
gws_assert(str_contains($page,'shadowModelStatus')&&str_contains($page,'shadowSummary'),'Simulator must expose challenger state and shadow evidence summary.');
gws_assert(str_contains($core,"\$action==='vision.shadow_assignment'")&&str_contains($core,'glasses_vision_shadow_assignment'),'Simulator must obtain shadow challengers through governed server assignment.');
gws_assert(str_contains($core,"\$action==='vision.shadow_report'")&&str_contains($core,'glasses_vision_shadow_report'),'Simulator must report shadow telemetry through a dedicated non-build action.');
gws_assert(str_contains($js,'function startShadowModel')&&str_contains($js,'function runShadowFrame'),'Browser runtime must load and execute a challenger beside the champion.');
gws_assert(str_contains($js,"shadow.champion?.publicId!==state.browserModel.package.publicId"),'Shadow runtime must verify its champion matches the currently authoritative browser model.');
gws_assert(str_contains($js,'compareShadowDetections'),'Shadow runtime must compare champion/challenger detections on the same frame.');
gws_assert(str_contains($js,"metadata:{source:'web_glasses_simulator_shadow',authoritative:false}"),'Shadow telemetry must explicitly declare itself non-authoritative.');
gws_assert(!str_contains($js,"shadowModel.session.run({[state.browserModel"),'Shadow model must not reuse or mutate champion session authority.');
gws_assert(str_contains($css,'.shadow-model-panel'),'Shadow evaluation must have a visible but distinct simulator UI.');







echo "glasses-web-simulator-ok\n";
