<?php
declare(strict_types=1);
require __DIR__.'/../includes/bootstrap.php';
require_once __DIR__.'/../includes/pos-core.php';
require_once __DIR__.'/../includes/kds-core.php';
require_once __DIR__.'/../includes/glasses-core.php';
require_once __DIR__.'/../includes/glasses-build.php';
require_once __DIR__.'/../includes/glasses-vision-lab.php';
require_once __DIR__.'/../includes/glasses-vision-operations.php';
function vl_assert(bool $c,string $m):void{if(!$c)throw new RuntimeException($m);}
$pdo=app_pdo();vl_assert(glasses_vision_lab_ready($pdo),'Vision Lab V2 migration must be installed.');
$slug='vl2-'.bin2hex(random_bytes(4));
$pdo->prepare("INSERT INTO organizations (name,status,timezone) VALUES (?,'active','America/Phoenix')")->execute(['Vision Lab '.$slug]);$org=(int)$pdo->lastInsertId();
$pdo->prepare("INSERT INTO locations (organization_id,name,city,state,status,is_primary,sort_order) VALUES (?,'Lab Kitchen','Phoenix','AZ','active',1,10)")->execute([$org]);$loc=(int)$pdo->lastInsertId();
foreach([['Admin','Trainer'],['Cook','Operator']] as $x){$pdo->prepare("INSERT INTO users (email,password_hash,first_name,last_name,display_name,status) VALUES (?,?,?,?,?,'active')")->execute([strtolower($x[0]).$slug.'@example.test',password_hash('CI-only-password',PASSWORD_DEFAULT),$x[0],$x[1],$x[0].' '.$x[1]]);$ids[]=(int)$pdo->lastInsertId();}
[$admin,$cook]=$ids;foreach([$admin,$cook] as $uid)$pdo->prepare("INSERT INTO organization_memberships (organization_id,user_id,primary_location_id,status) VALUES (?,?,?,'active')")->execute([$org,$uid,$loc]);
$station=kds_station_save($pdo,$org,$loc,['name'=>'Vision Line','slug'=>'vision-line','targetSeconds'=>300],$admin);
$pdo->prepare("INSERT INTO menu_sections (organization_id,name,slug,status,sort_order) VALUES (?,'Lab',?,'active',1)")->execute([$org,'lab-'.$slug]);$section=(int)$pdo->lastInsertId();
$pdo->prepare("INSERT INTO menu_items (organization_id,section_id,name,slug,is_active) VALUES (?,?,'Lab Sandwich',?,1)")->execute([$org,$section,'lab-sandwich-'.$slug]);$item=(int)$pdo->lastInsertId();
$pdo->prepare("INSERT INTO menu_item_prices (menu_item_id,option_name,size_code,amount,currency,sort_order) VALUES (?,'Regular','REG',10,'USD',1)")->execute([$item]);$price=(int)$pdo->lastInsertId();
$pdo->prepare("INSERT INTO ingredients (organization_id,canonical_name,slug,category,verification_status) VALUES (?,'Bacon',?,'food','verified')")->execute([$org,'bacon-'.$slug]);$ing=(int)$pdo->lastInsertId();
$pdo->prepare("INSERT INTO menu_item_ingredients (menu_item_id,ingredient_id,display_name,is_optional,can_remove,sort_order) VALUES (?,?,'Bacon',0,1,1)")->execute([$item,$ing]);$component=glasses_build_component_key('Bacon',$ing);
kds_route_save($pdo,$org,$loc,$item,(string)$station['public_id'],$admin);
$check=pos_create_check($pdo,$org,$loc,['serviceMode'=>'dine_in','tableName'=>'Lab','guestCount'=>1],$admin);$check=pos_add_item($pdo,$org,(string)$check['publicId'],$price,1,'',$admin);$line=(int)$check['items'][0]['id'];kds_send_check($pdo,$org,(string)$check['publicId'],$admin,false);
$q=$pdo->prepare("SELECT public_id FROM kds_order_items WHERE organization_id=? AND pos_check_item_id=?");$q->execute([$org,$line]);$kds=(string)$q->fetchColumn();
$grant=glasses_create_pairing_grant($pdo,$org,$loc,(string)$station['public_id'],$admin,10);$pair=glasses_pair_device($pdo,(string)$grant['pairingCode'],['hardwareIdentifier'=>'LAB-'.$slug,'displayName'=>'Lab AIR3','platform'=>'inmo_air3']);$device=glasses_authenticate_token($pdo,(string)$pair['deviceToken']);
$assignment=glasses_vision_lab_assign_device($pdo,$org,(string)$pair['device']['publicId'],$cook,'operator','manual',$admin);
vl_assert($assignment['userId']===$cook,'Glasses must be explicitly assigned to the cook.');
$session=glasses_build_start($pdo,$device,$kds,null);$sessionPublic=(string)$session['publicId'];
glasses_build_observe($pdo,$device,$sessionPublic,['observationKey'=>'vision-lab-obs','componentKey'=>$component,'displayName'=>'Bacon','observationAction'=>'added','quantity'=>1,'confidence'=>0.62,'trackingId'=>'lab-track','metadata'=>['detectorLabel'=>'bacon']]);
glasses_build_correct_observation($pdo,$device,$sessionPublic,['correctionKey'=>'vision-lab-correction','observationKey'=>'vision-lab-obs','resolution'=>'replace','targetComponentKey'=>$component,'correctedQuantity'=>1,'hasCorrectedQuantity'=>true,'reason'=>'Human verified bacon.']);
$rows=glasses_learning_dataset($pdo,$org,$loc,(string)$station['public_id'],30,true,100);
vl_assert(($rows['rows'][0]['operator']['userId']??null)===$cook,'Learning evidence must retain wearer/operator attribution.');
vl_assert(($rows['rows'][0]['humanReview']['correctorUserId']??null)===$cook,'Correction evidence must retain corrector attribution.');
$mission=glasses_vision_lab_create_mission($pdo,$org,['title'=>'Bacon hard examples','assignedUserId'=>$cook,'assignedDevicePublicId'=>(string)$pair['device']['publicId'],'locationId'=>$loc,'stationPublicId'=>(string)$station['public_id'],'targetSamples'=>10,'targetHardExamples'=>5,'sourceType'=>'active_learning'],$admin);
vl_assert($mission['assignedUserId']===$cook&&$mission['targetSamples']===10,'Mission must support explicit user/device targets.');
$import=glasses_vision_lab_import_corrected($pdo,$org,(string)$mission['publicId'],$admin,100);vl_assert($import['imported']===1,'Corrected production evidence must import into the Lab.');
$samples=glasses_vision_lab_samples($pdo,$org);vl_assert(count($samples)===1&&$samples[0]['operatorUserId']===$cook,'Imported sample must inherit wearer attribution.');
$sample=glasses_vision_lab_review_sample($pdo,$org,(string)$samples[0]['publicId'],['decision'=>'approve','notes'=>'Ground truth confirmed.'],$admin);vl_assert($sample['reviewStatus']==='approved'&&$sample['reviewerName']==='Admin Trainer','Reviewer identity must be separate from operator identity.');
$dataset=glasses_vision_lab_create_dataset($pdo,$org,['name'=>'Bacon Vision','versionLabel'=>'v1'],$admin);
glasses_vision_lab_add_dataset_sample($pdo,$org,(string)$dataset['publicId'],(string)$sample['publicId'],'train');
$frozen=glasses_vision_lab_freeze_dataset($pdo,$org,(string)$dataset['publicId'],$admin);
vl_assert($frozen['status']==='frozen'&&strlen((string)$frozen['datasetHash'])===64&&$frozen['rowCount']===1,'Dataset freeze must create immutable hash and row count.');
$coverage=glasses_vision_lab_dataset_coverage($pdo,$org,(string)$dataset['publicId']);vl_assert($coverage['contributors']>=2&&$coverage['splits']['train']===1,'Dataset coverage must expose contributor and split evidence.');
$blocked=false;try{glasses_vision_lab_add_dataset_sample($pdo,$org,(string)$dataset['publicId'],(string)$sample['publicId'],'test');}catch(InvalidArgumentException){$blocked=true;}vl_assert($blocked,'Frozen datasets must reject mutation.');
$ops=glasses_vision_ops_devices($pdo,$org);vl_assert(($ops[0]['wearer']['userId']??null)===$cook,'Vision Operations must expose current wearer assignment.');
$released=glasses_vision_lab_release_device($pdo,$org,(string)$assignment['publicId'],'shift ended',$admin);vl_assert($released['released']===true,'Glasses assignment must retain explicit release history.');
$catalog=glasses_vision_lab_catalog($pdo,['id'=>$admin,'organization_id'=>$org,'permissions'=>['*'],'is_owner_role'=>1]);vl_assert($catalog['ready']&&count($catalog['missions'])===1&&count($catalog['datasets'])===1,'Vision Lab catalog must expose assignments, missions and datasets.');
$page=file_get_contents(__DIR__.'/../glasses-vision-lab.php');$api=file_get_contents(__DIR__.'/../api/glasses-vision-lab.php');$js=file_get_contents(__DIR__.'/../assets/js/glasses-vision-lab.js');
vl_assert((str_contains($page,'Vision Lab V2')||str_contains($page,'Vision Lab V3')||str_contains($page,'Vision Lab V4')||str_contains($page,'Vision Lab V5')||str_contains($page,'Vision Lab V6')||str_contains($page,'Vision Lab V7')||str_contains($page,'Vision Lab V8')||str_contains($page,'Vision Lab V9'))&&str_contains($page,'Training Missions')&&str_contains($page,'Review Queue'),'Vision Lab must expose its core governed work areas.');
vl_assert(str_contains($api,'app_verify_request_csrf')&&str_contains($api,"sample.import_corrected"),'Vision Lab mutations must be CSRF protected and support corrected evidence intake.');
vl_assert(!str_contains($api,'kds_transition')&&!str_contains($api,'glasses_build_observe'),'Vision Lab must not mutate KDS or production build truth.');
vl_assert(str_contains($js,'data-dataset-add')&&str_contains($js,"dataset.add_sample")&&str_contains($page,'Import corrected evidence')&&str_contains($js,"sample.import_corrected"),'Vision Lab UI must support corrected-evidence intake and review-to-dataset flow.');
echo "vision-lab-v2-ok\n";
