<?php
declare(strict_types=1);
$root=dirname(__DIR__);
$required=['index.php','menu.php','gelato.php','about.php','contact.php','locations.php','workspace.php','login.php','public-site-settings.php','assets/css/site.css','assets/js/site.js','assets/images/README.md','includes/public-site.php','database/20260914_public_site_settings.sql'];foreach($required as $path)if(!is_file($root.'/'.$path))throw new RuntimeException('Missing required root public-site file: '.$path);if(is_dir($root.'/public'))throw new RuntimeException('Legacy /public directory must not exist.');
$helper=file_get_contents($root.'/includes/public-site.php')?:'';if(!str_contains($helper,'menu_database_sections'))throw new RuntimeException('Public site must use canonical menu database helper.');foreach(['index.php','menu.php','gelato.php'] as $path){$source=file_get_contents($root.'/'.$path)?:'';if(str_contains($source,'api/menu.php')||preg_match('/fetch\s*\(/',$source))throw new RuntimeException($path.' must not use authenticated menu API.');if(!str_contains($source,"__DIR__ . '/includes/public-site.php'"))throw new RuntimeException($path.' must load root public-site helper.');}
$workspace=file_get_contents($root.'/workspace.php')?:'';if(!str_contains($workspace,'app_require_auth'))throw new RuntimeException('workspace.php must remain authenticated.');$login=file_get_contents($root.'/login.php')?:'';if(!str_contains($login,'workspace.php'))throw new RuntimeException('Login must return staff to workspace.php.');
$settings=file_get_contents($root.'/public-site-settings.php')?:'';foreach(['app_require_auth','app_verify_csrf','public_pages.edit','public_site_settings','workspace.php'] as $needle)if(!str_contains($settings,$needle))throw new RuntimeException('Admin settings contract missing: '.$needle);
$css=file_get_contents($root.'/assets/css/site.css')?:'';foreach(['clamp(590px,74vh,710px)','.hero-copy h1','.gelato-section','background:transparent','var(--panel)'] as $needle)if(!str_contains($css,$needle))throw new RuntimeException('Visual contract missing: '.$needle);
$assets=file_get_contents($root.'/assets/images/README.md')?:'';foreach(['hero.jpg','card-pizza.jpg','gelato.jpg','story-one.jpg'] as $asset)if(!str_contains($assets,$asset))throw new RuntimeException('Missing image asset contract: '.$asset);
echo "PASS: Stonefellows root public-site contract verified.\n";
