<?php
declare(strict_types=1);
require __DIR__.'/../includes/bootstrap.php';
require __DIR__.'/../includes/scheduling-core.php';

function fail_sched(string $message,int $code):never{fwrite(STDERR,"FAIL {$code}: {$message}\n");exit($code);}function ok_sched(bool $value,string $message,int $code):void{if(!$value)fail_sched($message,$code);}
$pdo=app_pdo();
ok_sched(scheduling_core_ready($pdo),'scheduling schema unavailable',2);
$pdo->exec("INSERT INTO organizations (name,timezone) VALUES ('Scheduling CI Restaurant','America/Phoenix')");$org=(int)$pdo->lastInsertId();
$pdo->prepare("INSERT INTO locations (organization_id,name,status) VALUES (?,?,'active')")->execute([$org,'Main Restaurant']);$location=(int)$pdo->lastInsertId();
$pdo->prepare("INSERT INTO positions (organization_id,name,slug,status) VALUES (?,?,?,'active')")->execute([$org,'Cook','cook']);$position=(int)$pdo->lastInsertId();
$users=[];foreach([['alice@example.test','Alice','Cook'],['bob@example.test','Bob','Server'],['customer@example.test','Wholesale','Customer']] as $row){$pdo->prepare("INSERT INTO users (email,password_hash,first_name,last_name,display_name,status) VALUES (?,?,?,?,?,'active')")->execute([$row[0],'x',$row[1],$row[2],$row[1].' '.$row[2]]);$users[strtolower($row[1])]=(int)$pdo->lastInsertId();}
foreach(['alice','bob'] as $name){$pdo->prepare("INSERT INTO organization_memberships (organization_id,user_id,primary_location_id,job_title,status) VALUES (?,?,?,?,'active')")->execute([$org,$users[$name],$location,$name==='alice'?'Line Cook':'Server']);$membership=(int)$pdo->lastInsertId();$pdo->prepare("INSERT INTO user_positions (membership_id,position_id,is_primary,status,assigned_by) VALUES (?,?,1,'active',?)")->execute([$membership,$position,$users['alice']]);}
$pdo->prepare("INSERT INTO organization_memberships (organization_id,user_id,primary_location_id,job_title,status) VALUES (?,?,?,'Wholesale Customer','active')")->execute([$org,$users['wholesale'],$location]);
$staff=scheduling_staff($pdo,$org);ok_sched(count($staff)===2,'external wholesale customer leaked into staff list',3);
$profile=scheduling_profile_save($pdo,$org,$users['alice'],['preferredName'=>'Ali','employmentType'=>'hourly','minWeeklyHours'=>20,'preferredWeeklyHours'=>32,'maxWeeklyHours'=>40,'hourlyLaborCost'=>19.5,'skills'=>['pizza','prep']],$users['alice']);ok_sched(($profile['preferred_name']??'')==='Ali','profile save failed',4);
$aliceAvailability=scheduling_availability_replace($pdo,$org,$users['alice'],[['weekday'=>1,'start'=>'09:00','end'=>'17:00','type'=>'available'],['weekday'=>5,'start'=>'16:00','end'=>'23:00','type'=>'available']],$users['alice']);ok_sched(count($aliceAvailability)===2,'Alice availability save failed',5);
scheduling_availability_replace($pdo,$org,$users['bob'],[['weekday'=>1,'start'=>'09:00','end'=>'17:00','type'=>'available'],['weekday'=>5,'start'=>'16:00','end'=>'23:00','type'=>'available']],$users['alice']);
$week='2026-09-14';$shift=scheduling_shift_save($pdo,$org,['title'=>'Line Cook','startsAt'=>'2026-09-14 10:00:00','endsAt'=>'2026-09-14 16:00:00','userId'=>$users['alice'],'positionId'=>$position,'locationId'=>$location,'breakMinutes'=>30,'enforceAvailability'=>true],$users['alice']);ok_sched(!empty($shift['public_id']),'shift save failed',6);
$overlapBlocked=false;try{scheduling_shift_save($pdo,$org,['title'=>'Overlap','startsAt'=>'2026-09-14 15:00:00','endsAt'=>'2026-09-14 17:00:00','userId'=>$users['alice'],'enforceAvailability'=>true],$users['alice']);}catch(InvalidArgumentException){$overlapBlocked=true;}ok_sched($overlapBlocked,'overlapping shift was allowed',7);
$availabilityBlocked=false;try{scheduling_shift_save($pdo,$org,['title'=>'Late','startsAt'=>'2026-09-14 18:00:00','endsAt'=>'2026-09-14 20:00:00','userId'=>$users['alice'],'enforceAvailability'=>true],$users['alice']);}catch(InvalidArgumentException){$availabilityBlocked=true;}ok_sched($availabilityBlocked,'out-of-availability shift was allowed',8);
$exception=scheduling_exception_create($pdo,$org,$users['bob'],['date'=>'2026-09-18','type'=>'time_off','note'=>'CI request'],$users['bob'],false);ok_sched(($exception['status']??'')==='pending','employee time-off request should be pending',9);$pdo->prepare("UPDATE staff_availability_exceptions SET status='approved' WHERE organization_id=? AND public_id=?")->execute([$org,$exception['public_id']]);$check=scheduling_availability_check($pdo,$org,$users['bob'],'2026-09-18 17:00:00','2026-09-18 20:00:00');ok_sched(!$check['ok'],'approved time off did not block availability',10);
$rule=scheduling_coverage_rule_save($pdo,$org,['weekday'=>1,'start'=>'09:00','end'=>'17:00','minimumStaff'=>2,'targetStaff'=>2,'positionId'=>$position,'locationId'=>$location,'label'=>'Monday kitchen'],$users['alice']);ok_sched((int)$rule['minimum_staff']===2,'coverage rule save failed',11);
$category=$pdo->query("SELECT id FROM task_categories WHERE organization_id={$org} AND slug='prep' LIMIT 1")->fetchColumn();$pdo->prepare("INSERT INTO restaurant_tasks (organization_id,public_id,category_id,title,status,due_at,estimated_minutes,created_by,updated_by) VALUES (?,?,?,?, 'queued',?,?,?,?)")->execute([$org,'sched-ci-task',$category?:null,'Prep workload','2026-09-14 14:00:00',120,$users['alice'],$users['alice']]);
$summary=scheduling_summary($pdo,$org,$week);ok_sched((float)$summary['scheduledHours']===5.5,'scheduled labor hours incorrect',12);ok_sched((float)$summary['taskHours']===2.0,'task workload integration incorrect',13);ok_sched((int)$summary['coverageGaps']===1,'coverage gap detection incorrect',14);
$request=scheduling_request_create($pdo,$org,$users['alice'],['shiftId'=>$shift['public_id'],'type'=>'release','note'=>'CI release']);ok_sched(($request['status']??'')==='pending','release request not pending',15);scheduling_request_review($pdo,$org,$request['public_id'],'approved',$users['alice'],'approved in CI');$released=scheduling_shift_by_public_id($pdo,$org,$shift['public_id']);ok_sched(empty($released['user_id'])&&$released['status']==='open','approved release did not open shift',16);
$swapShift=scheduling_shift_save($pdo,$org,['title'=>'Friday PM','startsAt'=>'2026-09-18 16:00:00','endsAt'=>'2026-09-18 22:00:00','userId'=>$users['alice'],'positionId'=>$position,'locationId'=>$location,'enforceAvailability'=>true],$users['alice']);$swap=scheduling_request_create($pdo,$org,$users['alice'],['shiftId'=>$swapShift['public_id'],'type'=>'swap','targetUserId'=>$users['bob']]);$swapBlocked=false;try{scheduling_request_review($pdo,$org,$swap['public_id'],'approved',$users['alice']);}catch(InvalidArgumentException){$swapBlocked=true;}ok_sched($swapBlocked,'swap into approved time off was allowed',17);
$pdo->prepare("UPDATE staff_availability_exceptions SET status='rejected' WHERE organization_id=? AND public_id=?")->execute([$org,$exception['public_id']]);scheduling_request_review($pdo,$org,$swap['public_id'],'approved',$users['alice']);$swapped=scheduling_shift_by_public_id($pdo,$org,$swapShift['public_id']);ok_sched((int)$swapped['user_id']===$users['bob'],'approved swap did not reassign shift',18);
$events=(int)$pdo->query("SELECT COUNT(*) FROM schedule_events WHERE organization_id={$org}")->fetchColumn();ok_sched($events>=5,'schedule event history missing',19);
echo "staff=".count($staff)." scheduledHours={$summary['scheduledHours']} taskHours={$summary['taskHours']} coverageGaps={$summary['coverageGaps']} events={$events}\n";

require __DIR__.'/scheduling-agent-actions-contract.php';