<?php
declare(strict_types=1);
require __DIR__.'/../includes/bootstrap.php';
require __DIR__.'/../includes/timeclock-voice-core.php';
function tv_fail(string $m,int $c):never{fwrite(STDERR,"FAIL {$c}: {$m}\n");exit($c);}function tv_ok(bool $v,string $m,int $c):void{if(!$v)tv_fail($m,$c);} $pdo=app_pdo();tv_ok(tv_ready($pdo),'time clock/voice schema unavailable',2);
$pdo->exec("INSERT INTO organizations (name,timezone) VALUES ('Time Voice CI','America/Phoenix')");$org=(int)$pdo->lastInsertId();$pdo->prepare("INSERT INTO locations (organization_id,name,status) VALUES (?,?,'active')")->execute([$org,'Main']);$loc=(int)$pdo->lastInsertId();$pdo->prepare("INSERT INTO users (email,password_hash,first_name,last_name,display_name,status) VALUES ('voice@example.test','x','Voice','Worker','Voice Worker','active')")->execute();$uid=(int)$pdo->lastInsertId();$pdo->prepare("INSERT INTO organization_memberships (organization_id,user_id,primary_location_id,job_title,status) VALUES (?,?,?,'Cook','active')")->execute([$org,$uid,$loc]);
$week=scheduling_week_start();$today=date('Y-m-d');$start=date('Y-m-d H:i:s',time()-120);$end=date('Y-m-d H:i:s',time()+6*3600);$shift=scheduling_shift_save($pdo,$org,['title'=>'Cook','startsAt'=>$start,'endsAt'=>$end,'userId'=>$uid,'locationId'=>$loc,'breakMinutes'=>30],$uid);tv_ok(!empty($shift['id']),'shift setup failed',3);
$profileVector=[];for($i=1;$i<=24;$i++)$profileVector[]=$i/100;$profileVector=tv_voice_vector($profileVector);$pdo->prepare("INSERT INTO voice_identity_profiles (organization_id,user_id,status,consent_version,consented_at,enrolled_at,voiceprint_json,sample_count) VALUES (?,?,'active','v1',NOW(6),NOW(6),?,1)")->execute([$org,$uid,json_encode($profileVector)]);$match=tv_voice_match($pdo,$org,$uid,$profileVector,false);tv_ok($match['matched']&&$match['sessionUserMatch'],'enrolled voice did not match current employee',4);tv_ok(tv_voice_event_valid($pdo,$org,$uid,$match['eventId']),'voice match event was not valid',5);
$clock=tv_clock_in($pdo,$org,$uid,$uid,'voice','CI voice clock-in',$match['eventId']);tv_ok(($clock['status']??'')==='open','voice clock-in failed',6);$duplicateBlocked=false;try{tv_clock_in($pdo,$org,$uid,$uid,'manual');}catch(InvalidArgumentException){$duplicateBlocked=true;}tv_ok($duplicateBlocked,'duplicate clock-in was allowed',7);$breaks=tv_break_action($pdo,$org,$uid,$uid,'start','voice',$match['eventId']);tv_ok(count($breaks)===1&&empty($breaks[0]['ended_at']),'break start failed',8);$breaks=tv_break_action($pdo,$org,$uid,$uid,'end','voice',$match['eventId']);tv_ok(!empty($breaks[0]['ended_at']),'break end failed',9);$out=tv_clock_out($pdo,$org,$uid,$uid,'voice','CI clock-out',$match['eventId']);tv_ok(!empty($out['clocked_out_at'])&&$out['status']==='closed','clock-out failed',10);
$fakeEvent=tv_public_id('voice');$badVoice=false;try{tv_clock_in($pdo,$org,$uid,$uid,'voice','',$fakeEvent);}catch(RuntimeException){$badVoice=true;}tv_ok($badVoice,'voice action without recent match was allowed',11);
$clock2=tv_clock_in($pdo,$org,$uid,$uid,'manual');tv_ok(($clock2['status']??'')==='open','manual clock-in failed',12);$snapshot=tv_self_snapshot($pdo,$org,$uid);tv_ok(!empty($snapshot['clock']),'self snapshot did not include active clock',13);$summary=tv_daily_summary($pdo,$org,$today);tv_ok($summary['actualMinutes']>=0&&$summary['scheduledShifts']>=1,'labor summary failed',14);$events=(int)$pdo->query("SELECT COUNT(*) FROM attendance_events WHERE organization_id={$org}")->fetchColumn();tv_ok($events>=5,'attendance event history missing',15);
$other=[];for($i=24;$i>=1;$i--)$other[]=$i/100;$no=tv_voice_match($pdo,$org,$uid,$other,false);tv_ok(!$no['matched'],'dissimilar voice unexpectedly matched',16);
$pdo->prepare("INSERT INTO proactive_agent_preferences (organization_id,user_id,listening_enabled,proactive_voice_enabled) VALUES (?,?,1,1)")->execute([$org,$uid]);tv_ok((int)$pdo->query("SELECT listening_enabled FROM proactive_agent_preferences WHERE organization_id={$org} AND user_id={$uid}")->fetchColumn()===1,'proactive preferences failed',17);
echo "voiceMatch={$match['confidence']} attendanceEvents={$events} scheduledMinutes={$summary['scheduledMinutes']} actualMinutes={$summary['actualMinutes']}\n";