<?php
declare(strict_types=1);
require __DIR__.'/../includes/bootstrap.php';
require __DIR__.'/../includes/wholesale-commerce.php';
require __DIR__.'/../includes/wholesale-receivables.php';

function wr_assert(bool $ok,string $message):void{if(!$ok)throw new RuntimeException($message);}
function wr_close(float $a,float $b,float $epsilon=.011):bool{return abs($a-$b)<$epsilon;}
$pdo=app_pdo();wr_assert(wholesale_receivables_ready($pdo),'Wholesale W4 receivables migration missing.');wr_assert(wholesale_commerce_ready($pdo),'Wholesale commerce contract missing.');

$pdo->exec("INSERT INTO organizations (name,status,timezone) VALUES ('Wholesale Receivables CI','active','America/Phoenix')");$org=(int)$pdo->lastInsertId();
$pdo->exec("INSERT INTO users (email,password_hash,first_name,last_name,display_name,status) VALUES ('wr@example.test','x','Wholesale','Receivables','Wholesale Receivables CI','active')");$uid=(int)$pdo->lastInsertId();$pdo->prepare("INSERT INTO organization_memberships (organization_id,user_id,status) VALUES (?,?,'active')")->execute([$org,$uid]);
$pdo->prepare("INSERT INTO wholesale_accounts (organization_id,public_id,business_name,account_status,primary_email,payment_terms,created_by,updated_by) VALUES (?,'wacct-wr','W4 Market','active','ar@example.test','Net 30',?,?)")->execute([$org,$uid,$uid]);$accountId=(int)$pdo->lastInsertId();$account=wholesale_commerce_account($pdo,$org,$accountId);
$product=wholesale_commerce_save_product($pdo,$org,['name'=>'W4 Gelato','category'=>'Gelato'],$uid);$sku=wholesale_commerce_save_sku($pdo,$org,['productId'=>$product['public_id'],'sku'=>'W4-5L','name'=>'W4 5L Pan','sellUom'=>'pan','minimumQuantity'=>1,'quantityIncrement'=>1],$uid);$list=wholesale_commerce_save_price_list($pdo,$org,['name'=>'W4 Wholesale','minimumOrderAmount'=>0,'isDefault'=>true],$uid);wholesale_commerce_set_price($pdo,$org,['priceListId'=>$list['public_id'],'skuId'=>$sku['public_id'],'unitPrice'=>100,'effectiveFrom'=>'2026-01-01'],$uid);wholesale_commerce_assign_price_list($pdo,$org,$accountId,$list['public_id'],$uid);

$posChecksBefore=(int)$pdo->query('SELECT COUNT(*) FROM pos_checks')->fetchColumn();$posTendersBefore=(int)$pdo->query('SELECT COUNT(*) FROM pos_tenders')->fetchColumn();
$order=wholesale_commerce_create_order($pdo,$org,$account,['items'=>[['skuId'=>$sku['public_id'],'quantity'=>2]],'status'=>'confirmed','deliveryFee'=>15,'taxRatePercent'=>10,'fulfillmentType'=>'local_delivery'],$uid);$pdo->prepare("UPDATE wholesale_orders SET status='delivered',delivered_at=NOW(6) WHERE organization_id=? AND id=?")->execute([$org,(int)$order['id']]);
$draft=wholesale_receivables_create_invoice($pdo,$org,$order['publicId'],['issueDate'=>'2026-09-01'],$uid);wr_assert($draft['invoice']['status']==='draft','Invoice should start as draft.');wr_assert($draft['invoice']['dueDate']==='2026-10-01','Net 30 terms did not derive the due date.');wr_assert(wr_close((float)$draft['invoice']['total'],235),'Invoice did not snapshot server-authoritative Wholesale order totals.');wr_assert(count($draft['items'])===1&&wr_close((float)$draft['items'][0]['line_subtotal'],200),'Invoice line snapshot did not copy the canonical Wholesale order line.');wr_assert(count($draft['entries'])===0,'Draft invoice must not create A/R or recognized revenue entries.');
$q=$pdo->prepare("SELECT COUNT(*) FROM sales_periods WHERE organization_id=? AND source_provider='gelato_wholesale'");$q->execute([$org]);wr_assert((int)$q->fetchColumn()===0,'Draft invoice prematurely posted Wholesale revenue.');

$issued=wholesale_receivables_issue($pdo,$org,$draft['invoice']['id'],[],$uid);wr_assert($issued['invoice']['status']==='issued','Delivered Wholesale invoice did not issue.');wr_assert(wr_close((float)$issued['invoice']['balance'],235),'Issued invoice A/R balance is incorrect.');
$q=$pdo->prepare("SELECT COUNT(*) FROM wholesale_receivable_entries WHERE organization_id=? AND wholesale_invoice_id=(SELECT id FROM wholesale_invoices WHERE organization_id=? AND public_id=?) AND entry_type='invoice'");$q->execute([$org,$org,$draft['invoice']['id']]);wr_assert((int)$q->fetchColumn()===1,'Invoice issuance did not create exactly one receivable debit.');
$again=wholesale_receivables_issue($pdo,$org,$draft['invoice']['id'],[],$uid);wr_assert(wr_close((float)$again['invoice']['balance'],235),'Repeated invoice issue changed the A/R balance.');$q->execute([$org,$org,$draft['invoice']['id']]);wr_assert((int)$q->fetchColumn()===1,'Repeated invoice issue duplicated the receivable debit.');
$q=$pdo->prepare("SELECT tickets,gross_sales,net_sales,tax_amount,refunds_amount,service_charges_amount FROM sales_periods WHERE organization_id=? AND source_provider='gelato_wholesale' AND location_key='all' AND period_start='2026-09-01'");$q->execute([$org]);$sales=$q->fetch();wr_assert((bool)$sales,'Issued invoice did not post to Sales Intelligence.');wr_assert((int)$sales['tickets']===1&&wr_close((float)$sales['gross_sales'],200)&&wr_close((float)$sales['net_sales'],200)&&wr_close((float)$sales['tax_amount'],20)&&wr_close((float)$sales['service_charges_amount'],15),'Wholesale recognized revenue uses incorrect Sales Intelligence semantics.');
$q=$pdo->prepare("SELECT COUNT(*) FROM sales_item_periods sip JOIN sales_periods sp ON sp.id=sip.sales_period_id WHERE sip.organization_id=? AND sp.source_provider='gelato_wholesale' AND sp.period_start='2026-09-01'");$q->execute([$org]);wr_assert((int)$q->fetchColumn()===1,'Wholesale invoice items did not publish item-level Sales Intelligence.');

$partial=wholesale_receivables_record($pdo,$org,$draft['invoice']['id'],'payment',['amount'=>100,'effectiveDate'=>'2026-09-05','paymentMethod'=>'ACH','reference'=>'ACH-1'],$uid);wr_assert($partial['invoice']['status']==='partially_paid'&&wr_close((float)$partial['invoice']['balance'],135),'Partial payment did not reduce A/R correctly.');
$q=$pdo->prepare("SELECT COUNT(*) FROM sales_periods WHERE organization_id=? AND source_provider='gelato_wholesale' AND period_start='2026-09-05'");$q->execute([$org]);wr_assert((int)$q->fetchColumn()===0,'Cash settlement must not be posted as new Wholesale revenue.');
$paid=wholesale_receivables_record($pdo,$org,$draft['invoice']['id'],'payment',['amount'=>135,'effectiveDate'=>'2026-09-06','paymentMethod'=>'check','reference'=>'CHK-22'],$uid);wr_assert($paid['invoice']['status']==='paid'&&wr_close((float)$paid['invoice']['balance'],0),'Full payment did not close the invoice.');

$credit=wholesale_receivables_record($pdo,$org,$draft['invoice']['id'],'credit',['amount'=>47,'effectiveDate'=>'2026-09-10','note'=>'Customer quality credit'],$uid);wr_assert($credit['invoice']['status']==='credit_balance'&&wr_close((float)$credit['invoice']['balance'],-47),'Credit on a paid invoice did not create the customer credit balance.');
$q=$pdo->prepare("SELECT net_sales,tax_amount,refunds_amount,service_charges_amount FROM sales_periods WHERE organization_id=? AND source_provider='gelato_wholesale' AND period_start='2026-09-10'");$q->execute([$org]);$creditSales=$q->fetch();wr_assert($creditSales&&wr_close((float)$creditSales['net_sales'],-40)&&wr_close((float)$creditSales['tax_amount'],-4)&&wr_close((float)$creditSales['service_charges_amount'],-3)&&wr_close((float)$creditSales['refunds_amount'],40),'Credit did not proportionally reverse recognized revenue/tax/service charges.');
$refunded=wholesale_receivables_record($pdo,$org,$draft['invoice']['id'],'refund',['amount'=>47,'effectiveDate'=>'2026-09-11','paymentMethod'=>'ACH','reference'=>'REF-1'],$uid);wr_assert($refunded['invoice']['status']==='paid'&&wr_close((float)$refunded['invoice']['balance'],0),'Refund did not settle the customer credit balance.');
$q=$pdo->prepare("SELECT COUNT(*) FROM sales_periods WHERE organization_id=? AND source_provider='gelato_wholesale' AND period_start='2026-09-11'");$q->execute([$org]);wr_assert((int)$q->fetchColumn()===0,'Refund payout reduced recognized revenue a second time.');

// Aging uses positive receivable balances only and keeps customer credits separate.
$order2=wholesale_commerce_create_order($pdo,$org,$account,['items'=>[['skuId'=>$sku['public_id'],'quantity'=>2]],'status'=>'confirmed','deliveryFee'=>0,'taxRatePercent'=>0],$uid);$pdo->prepare("UPDATE wholesale_orders SET status='delivered',delivered_at=NOW(6) WHERE organization_id=? AND id=?")->execute([$org,(int)$order2['id']]);$old=(new DateTimeImmutable(date('Y-m-d')))->modify('-45 days')->format('Y-m-d');$inv2=wholesale_receivables_create_invoice($pdo,$org,$order2['publicId'],['issueDate'=>$old,'paymentTerms'=>'Due on receipt'],$uid);$inv2=wholesale_receivables_issue($pdo,$org,$inv2['invoice']['id'],[],$uid);$aging=wholesale_receivables_aging($pdo,$org);wr_assert(wr_close((float)$aging['receivables'],200)&&wr_close((float)$aging['days31to60'],200)&&(int)$aging['overdueInvoices']===1,'A/R aging did not place the 45-day overdue invoice in the 31–60 day bucket.');

// Revenue recognition is blocked before delivery even when a draft invoice exists.
$order3=wholesale_commerce_create_order($pdo,$org,$account,['items'=>[['skuId'=>$sku['public_id'],'quantity'=>1]],'status'=>'confirmed','deliveryFee'=>0,'taxRatePercent'=>0],$uid);$inv3=wholesale_receivables_create_invoice($pdo,$org,$order3['publicId'],['issueDate'=>date('Y-m-d'),'paymentTerms'=>'Due on receipt'],$uid);$blocked=false;try{wholesale_receivables_issue($pdo,$org,$inv3['invoice']['id'],[],$uid);}catch(InvalidArgumentException){$blocked=true;}wr_assert($blocked,'Undelivered Wholesale order was allowed to recognize invoice revenue.');

// An issued invoice with no settlement activity can be voided and its recognized revenue disappears.
$pdo->prepare("UPDATE wholesale_orders SET status='delivered',delivered_at=NOW(6) WHERE organization_id=? AND id=?")->execute([$org,(int)$order3['id']]);$inv3=wholesale_receivables_issue($pdo,$org,$inv3['invoice']['id'],[],$uid);$today=date('Y-m-d');$q=$pdo->prepare("SELECT COUNT(*) FROM sales_periods WHERE organization_id=? AND source_provider='gelato_wholesale' AND period_start=?");$q->execute([$org,$today]);wr_assert((int)$q->fetchColumn()>=1,'Issued current invoice did not create its Wholesale sales period.');$voided=wholesale_receivables_void($pdo,$org,$inv3['invoice']['id'],'Duplicate billing test',$uid);wr_assert($voided['invoice']['status']==='void'&&wr_close((float)$voided['invoice']['balance'],0),'Void did not neutralize the invoice receivable.');$q->execute([$org,$today]);wr_assert((int)$q->fetchColumn()===0,'Voided invoice remained in recognized Wholesale revenue.');

wr_assert((int)$pdo->query('SELECT COUNT(*) FROM pos_checks')->fetchColumn()===$posChecksBefore,'Wholesale A/R created synthetic POS checks.');wr_assert((int)$pdo->query('SELECT COUNT(*) FROM pos_tenders')->fetchColumn()===$posTendersBefore,'Wholesale A/R created synthetic POS tenders.');
$pdo->exec("INSERT INTO organizations (name,status,timezone) VALUES ('Wholesale Receivables Other','active','America/Phoenix')");$other=(int)$pdo->lastInsertId();$q=$pdo->prepare('SELECT COUNT(*) FROM wholesale_invoices WHERE organization_id=?');$q->execute([$other]);wr_assert((int)$q->fetchColumn()===0,'Wholesale receivables leaked across organizations.');

echo "wholesale-receivables contract passed\n";
