-- Gelato Vision Lab V9 Section 1 — Live Scene Understanding
SET NAMES utf8mb4;

CREATE TABLE glasses_vision_scene_snapshots (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  organization_id BIGINT UNSIGNED NOT NULL,
  public_id VARCHAR(80) NOT NULL,
  device_id BIGINT UNSIGNED NOT NULL,
  build_session_id BIGINT UNSIGNED NOT NULL,
  package_id BIGINT UNSIGNED NOT NULL,
  calibration_id BIGINT UNSIGNED NULL,
  frame_key VARCHAR(190) NOT NULL,
  frame_width INT UNSIGNED NOT NULL,
  frame_height INT UNSIGNED NOT NULL,
  pixel_format VARCHAR(40) NOT NULL,
  captured_at DATETIME(6) NOT NULL,
  assignment_key CHAR(64) NOT NULL,
  source_fingerprint CHAR(64) NOT NULL,
  scene_state VARCHAR(32) NOT NULL,
  context_json JSON NOT NULL,
  relationships_json JSON NOT NULL,
  summary_json JSON NOT NULL,
  scene_hash CHAR(64) NOT NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uq_glasses_vision_scene_public (organization_id,public_id),
  UNIQUE KEY uq_glasses_vision_scene_frame (organization_id,device_id,build_session_id,frame_key),
  KEY idx_glasses_vision_scene_build (organization_id,build_session_id,captured_at),
  KEY idx_glasses_vision_scene_model (organization_id,package_id,captured_at),
  CONSTRAINT fk_glasses_vision_scene_org FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
  CONSTRAINT fk_glasses_vision_scene_device FOREIGN KEY (device_id) REFERENCES glasses_devices(id) ON DELETE RESTRICT,
  CONSTRAINT fk_glasses_vision_scene_build FOREIGN KEY (build_session_id) REFERENCES glasses_build_sessions(id) ON DELETE RESTRICT,
  CONSTRAINT fk_glasses_vision_scene_package FOREIGN KEY (package_id) REFERENCES glasses_vision_model_packages(id) ON DELETE RESTRICT,
  CONSTRAINT fk_glasses_vision_scene_calibration FOREIGN KEY (calibration_id) REFERENCES glasses_station_calibrations(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE glasses_vision_scene_entities (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  organization_id BIGINT UNSIGNED NOT NULL,
  scene_snapshot_id BIGINT UNSIGNED NOT NULL,
  public_id VARCHAR(80) NOT NULL,
  entity_key VARCHAR(190) NOT NULL,
  entity_kind VARCHAR(32) NOT NULL,
  label VARCHAR(180) NOT NULL,
  normalized_label VARCHAR(180) NULL,
  component_key VARCHAR(160) NULL,
  tracking_id VARCHAR(190) NULL,
  source_type VARCHAR(32) NOT NULL DEFAULT 'vision_model',
  confidence DECIMAL(9,6) NULL,
  bbox_json JSON NULL,
  spatial_json JSON NOT NULL,
  attributes_json JSON NOT NULL,
  entity_hash CHAR(64) NOT NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uq_glasses_vision_scene_entity_public (organization_id,public_id),
  UNIQUE KEY uq_glasses_vision_scene_entity_key (scene_snapshot_id,entity_key),
  KEY idx_glasses_vision_scene_entity_kind (organization_id,scene_snapshot_id,entity_kind),
  KEY idx_glasses_vision_scene_entity_component (organization_id,component_key,created_at),
  CONSTRAINT fk_glasses_vision_scene_entity_org FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
  CONSTRAINT fk_glasses_vision_scene_entity_snapshot FOREIGN KEY (scene_snapshot_id) REFERENCES glasses_vision_scene_snapshots(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
