-- Gelato Vision Lab V8 Section 5 — Active Perception & Recovery Actions
SET NAMES utf8mb4;

CREATE TABLE glasses_vision_active_perception_actions (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  organization_id BIGINT UNSIGNED NOT NULL,
  public_id VARCHAR(80) NOT NULL,
  confidence_decision_id BIGINT UNSIGNED NOT NULL,
  device_id BIGINT UNSIGNED NOT NULL,
  build_session_id BIGINT UNSIGNED NOT NULL,
  package_id BIGINT UNSIGNED NOT NULL,
  context_drift_analysis_id BIGINT UNSIGNED NULL,
  calibration_selection_id BIGINT UNSIGNED NULL,
  action_key CHAR(64) NOT NULL,
  primary_action VARCHAR(48) NOT NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'issued',
  requires_human TINYINT(1) NOT NULL DEFAULT 0,
  instruction_json JSON NOT NULL,
  evidence_json JSON NOT NULL,
  action_hash CHAR(64) NOT NULL,
  expires_at DATETIME(6) NOT NULL,
  acknowledged_at DATETIME(6) NULL,
  completed_at DATETIME(6) NULL,
  completion_json JSON NULL,
  completion_hash CHAR(64) NULL,
  created_by BIGINT UNSIGNED NULL,
  resolved_by BIGINT UNSIGNED NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uq_glasses_vision_active_perception_public (organization_id,public_id),
  UNIQUE KEY uq_glasses_vision_active_perception_key (organization_id,action_key),
  KEY idx_glasses_vision_active_perception_device (organization_id,device_id,status,expires_at),
  KEY idx_glasses_vision_active_perception_decision (organization_id,confidence_decision_id,created_at),
  CONSTRAINT fk_glasses_vision_active_perception_org FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
  CONSTRAINT fk_glasses_vision_active_perception_decision FOREIGN KEY (confidence_decision_id) REFERENCES glasses_vision_confidence_decisions(id) ON DELETE RESTRICT,
  CONSTRAINT fk_glasses_vision_active_perception_device FOREIGN KEY (device_id) REFERENCES glasses_devices(id) ON DELETE RESTRICT,
  CONSTRAINT fk_glasses_vision_active_perception_build FOREIGN KEY (build_session_id) REFERENCES glasses_build_sessions(id) ON DELETE RESTRICT,
  CONSTRAINT fk_glasses_vision_active_perception_package FOREIGN KEY (package_id) REFERENCES glasses_vision_model_packages(id) ON DELETE RESTRICT,
  CONSTRAINT fk_glasses_vision_active_perception_analysis FOREIGN KEY (context_drift_analysis_id) REFERENCES glasses_vision_context_drift_analyses(id) ON DELETE SET NULL,
  CONSTRAINT fk_glasses_vision_active_perception_calibration FOREIGN KEY (calibration_selection_id) REFERENCES glasses_vision_calibration_selections(id) ON DELETE SET NULL,
  CONSTRAINT fk_glasses_vision_active_perception_creator FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_glasses_vision_active_perception_resolver FOREIGN KEY (resolved_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE glasses_vision_active_perception_events (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  organization_id BIGINT UNSIGNED NOT NULL,
  action_id BIGINT UNSIGNED NOT NULL,
  event_type VARCHAR(32) NOT NULL,
  event_hash CHAR(64) NOT NULL,
  evidence_json JSON NOT NULL,
  actor_user_id BIGINT UNSIGNED NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uq_glasses_vision_active_perception_event_hash (organization_id,event_hash),
  KEY idx_glasses_vision_active_perception_event (organization_id,action_id,id),
  CONSTRAINT fk_glasses_vision_active_perception_event_org FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
  CONSTRAINT fk_glasses_vision_active_perception_event_action FOREIGN KEY (action_id) REFERENCES glasses_vision_active_perception_actions(id) ON DELETE CASCADE,
  CONSTRAINT fk_glasses_vision_active_perception_event_actor FOREIGN KEY (actor_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
