-- Gelato Vision Lab V5 — Governed Training Media, Image Fingerprints & Visual Dataset Quality
SET NAMES utf8mb4;

CREATE TABLE glasses_vision_training_media (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  organization_id BIGINT UNSIGNED NOT NULL,
  public_id VARCHAR(80) NOT NULL,
  sample_id BIGINT UNSIGNED NULL,
  mission_id BIGINT UNSIGNED NULL,
  device_id BIGINT UNSIGNED NULL,
  operator_user_id BIGINT UNSIGNED NULL,
  build_session_id BIGINT UNSIGNED NULL,
  capture_group VARCHAR(120) NULL,
  burst_index INT UNSIGNED NULL,
  source_type VARCHAR(48) NOT NULL DEFAULT 'browser_training_capture',
  storage_relative_path VARCHAR(500) NOT NULL,
  mime_type VARCHAR(80) NOT NULL,
  byte_size BIGINT UNSIGNED NOT NULL,
  width INT UNSIGNED NOT NULL,
  height INT UNSIGNED NOT NULL,
  sha256 CHAR(64) NOT NULL,
  perceptual_hash CHAR(16) NULL,
  perceptual_hash_source VARCHAR(32) NULL,
  brightness_mean DECIMAL(8,5) NULL,
  contrast_mean DECIMAL(8,5) NULL,
  blur_score DECIMAL(10,4) NULL,
  exposure_state VARCHAR(24) NULL,
  camera_facing VARCHAR(24) NULL,
  camera_device_key VARCHAR(190) NULL,
  camera_width INT UNSIGNED NULL,
  camera_height INT UNSIGNED NULL,
  camera_fps DECIMAL(8,3) NULL,
  camera_pitch DECIMAL(9,4) NULL,
  camera_yaw DECIMAL(9,4) NULL,
  camera_roll DECIMAL(9,4) NULL,
  distance_bucket VARCHAR(24) NULL,
  occlusion_bucket VARCHAR(24) NULL,
  quality_state VARCHAR(24) NOT NULL DEFAULT 'review',
  quality_flags_json JSON NULL,
  annotation_json JSON NULL,
  metadata_json JSON NULL,
  consent_basis VARCHAR(64) NOT NULL,
  retention_until DATETIME(6) NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'active',
  created_by BIGINT UNSIGNED NOT NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  deleted_by BIGINT UNSIGNED NULL,
  deleted_at DATETIME(6) NULL,
  delete_reason VARCHAR(500) NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_glasses_vision_training_media_public (organization_id,public_id),
  KEY idx_glasses_vision_training_media_sha (organization_id,sha256,status),
  KEY idx_glasses_vision_training_media_phash (organization_id,perceptual_hash,status),
  KEY idx_glasses_vision_training_media_sample (organization_id,sample_id,status),
  KEY idx_glasses_vision_training_media_capture (organization_id,capture_group,burst_index,status),
  KEY idx_glasses_vision_training_media_retention (organization_id,status,retention_until),
  CONSTRAINT fk_glasses_vision_training_media_org FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
  CONSTRAINT fk_glasses_vision_training_media_sample FOREIGN KEY (sample_id) REFERENCES glasses_vision_training_samples(id) ON DELETE SET NULL,
  CONSTRAINT fk_glasses_vision_training_media_mission FOREIGN KEY (mission_id) REFERENCES glasses_vision_training_missions(id) ON DELETE SET NULL,
  CONSTRAINT fk_glasses_vision_training_media_device FOREIGN KEY (device_id) REFERENCES glasses_devices(id) ON DELETE SET NULL,
  CONSTRAINT fk_glasses_vision_training_media_operator FOREIGN KEY (operator_user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_glasses_vision_training_media_build FOREIGN KEY (build_session_id) REFERENCES glasses_build_sessions(id) ON DELETE SET NULL,
  CONSTRAINT fk_glasses_vision_training_media_creator FOREIGN KEY (created_by) REFERENCES users(id),
  CONSTRAINT fk_glasses_vision_training_media_deleter FOREIGN KEY (deleted_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE glasses_vision_training_media_events (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  organization_id BIGINT UNSIGNED NOT NULL,
  media_id BIGINT UNSIGNED NOT NULL,
  event_type VARCHAR(48) NOT NULL,
  evidence_json JSON NULL,
  actor_user_id BIGINT UNSIGNED NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  KEY idx_glasses_vision_training_media_events (organization_id,media_id,created_at),
  CONSTRAINT fk_glasses_vision_training_media_event_org FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
  CONSTRAINT fk_glasses_vision_training_media_event_media FOREIGN KEY (media_id) REFERENCES glasses_vision_training_media(id) ON DELETE CASCADE,
  CONSTRAINT fk_glasses_vision_training_media_event_actor FOREIGN KEY (actor_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
