-- Gelato Restaurant AI: Wholesale Purchasing Worksheet + Lifecycle/Tasting
SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS wholesale_planning_settings (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  organization_id BIGINT UNSIGNED NOT NULL,
  pan_liters DECIMAL(8,3) NOT NULL DEFAULT 5.000,
  default_serving_oz DECIMAL(6,2) NOT NULL DEFAULT 4.00,
  default_safety_stock_percent DECIMAL(6,2) NOT NULL DEFAULT 10.00,
  default_waste_percent DECIMAL(6,2) NOT NULL DEFAULT 5.00,
  weeks_per_month DECIMAL(6,3) NOT NULL DEFAULT 4.330,
  core_weekly_pans DECIMAL(10,2) NOT NULL DEFAULT 3.00,
  growth_weekly_pans DECIMAL(10,2) NOT NULL DEFAULT 6.00,
  key_weekly_pans DECIMAL(10,2) NOT NULL DEFAULT 12.00,
  updated_by BIGINT UNSIGNED NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uq_wholesale_planning_settings_org (organization_id),
  CONSTRAINT fk_wholesale_planning_settings_org FOREIGN KEY (organization_id) REFERENCES organizations(id),
  CONSTRAINT fk_wholesale_planning_settings_user FOREIGN KEY (updated_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS wholesale_purchase_worksheets (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  organization_id BIGINT UNSIGNED NOT NULL,
  wholesale_lead_id BIGINT UNSIGNED NOT NULL,
  customer_mode VARCHAR(32) NOT NULL DEFAULT 'adding_gelato',
  serving_size_oz DECIMAL(6,2) NOT NULL DEFAULT 4.00,
  servings_per_day DECIMAL(12,2) NOT NULL DEFAULT 0,
  service_days_per_week DECIMAL(6,2) NOT NULL DEFAULT 7.00,
  safety_stock_percent DECIMAL(6,2) NOT NULL DEFAULT 10.00,
  waste_percent DECIMAL(6,2) NOT NULL DEFAULT 5.00,
  menu_price_per_serving DECIMAL(12,2) NULL,
  current_dessert_units_per_day DECIMAL(12,2) NULL,
  gelato_capture_percent DECIMAL(6,2) NULL,
  existing_weekly_pans DECIMAL(12,2) NULL,
  freezer_pan_capacity DECIMAL(12,2) NULL,
  delivery_frequency VARCHAR(40) NULL,
  weekly_liters DECIMAL(14,4) NOT NULL DEFAULT 0,
  base_weekly_pans DECIMAL(14,4) NOT NULL DEFAULT 0,
  recommended_weekly_pans DECIMAL(14,4) NOT NULL DEFAULT 0,
  recommended_monthly_pans DECIMAL(14,4) NOT NULL DEFAULT 0,
  servings_per_pan DECIMAL(14,2) NOT NULL DEFAULT 0,
  projected_monthly_retail_revenue DECIMAL(14,2) NULL,
  projected_monthly_wholesale_spend DECIMAL(14,2) NULL,
  projected_monthly_gross_profit DECIMAL(14,2) NULL,
  account_tier VARCHAR(40) NOT NULL DEFAULT 'trial',
  selected_skus_json JSON NULL,
  starter_order_json JSON NULL,
  assumptions_json JSON NULL,
  notes TEXT NULL,
  calculated_at DATETIME(6) NULL,
  created_by BIGINT UNSIGNED NULL,
  updated_by BIGINT UNSIGNED NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uq_wholesale_purchase_worksheet_lead (wholesale_lead_id),
  KEY idx_wholesale_purchase_worksheet_org (organization_id, account_tier, updated_at),
  CONSTRAINT fk_wholesale_purchase_worksheet_org FOREIGN KEY (organization_id) REFERENCES organizations(id),
  CONSTRAINT fk_wholesale_purchase_worksheet_lead FOREIGN KEY (wholesale_lead_id) REFERENCES wholesale_leads(id) ON DELETE CASCADE,
  CONSTRAINT fk_wholesale_purchase_worksheet_creator FOREIGN KEY (created_by) REFERENCES users(id),
  CONSTRAINT fk_wholesale_purchase_worksheet_updater FOREIGN KEY (updated_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS wholesale_lifecycle (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  organization_id BIGINT UNSIGNED NOT NULL,
  wholesale_lead_id BIGINT UNSIGNED NOT NULL,
  lifecycle_stage VARCHAR(40) NOT NULL DEFAULT 'discovery',
  owner_user_id BIGINT UNSIGNED NULL,
  next_action VARCHAR(500) NULL,
  next_action_at DATETIME(6) NULL,
  trial_started_at DATETIME(6) NULL,
  active_at DATETIME(6) NULL,
  recurring_at DATETIME(6) NULL,
  paused_at DATETIME(6) NULL,
  lost_at DATETIME(6) NULL,
  lifecycle_notes TEXT NULL,
  created_by BIGINT UNSIGNED NULL,
  updated_by BIGINT UNSIGNED NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uq_wholesale_lifecycle_lead (wholesale_lead_id),
  KEY idx_wholesale_lifecycle_org_stage (organization_id, lifecycle_stage, next_action_at),
  KEY idx_wholesale_lifecycle_owner (organization_id, owner_user_id, next_action_at),
  CONSTRAINT fk_wholesale_lifecycle_org FOREIGN KEY (organization_id) REFERENCES organizations(id),
  CONSTRAINT fk_wholesale_lifecycle_lead FOREIGN KEY (wholesale_lead_id) REFERENCES wholesale_leads(id) ON DELETE CASCADE,
  CONSTRAINT fk_wholesale_lifecycle_owner FOREIGN KEY (owner_user_id) REFERENCES users(id),
  CONSTRAINT fk_wholesale_lifecycle_creator FOREIGN KEY (created_by) REFERENCES users(id),
  CONSTRAINT fk_wholesale_lifecycle_updater FOREIGN KEY (updated_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS wholesale_lifecycle_events (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  organization_id BIGINT UNSIGNED NOT NULL,
  wholesale_lead_id BIGINT UNSIGNED NOT NULL,
  from_stage VARCHAR(40) NULL,
  to_stage VARCHAR(40) NOT NULL,
  event_type VARCHAR(60) NOT NULL DEFAULT 'stage_changed',
  summary VARCHAR(500) NOT NULL,
  metadata_json JSON NULL,
  actor_user_id BIGINT UNSIGNED NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  KEY idx_wholesale_lifecycle_events_lead (organization_id, wholesale_lead_id, created_at),
  CONSTRAINT fk_wholesale_lifecycle_events_org FOREIGN KEY (organization_id) REFERENCES organizations(id),
  CONSTRAINT fk_wholesale_lifecycle_events_lead FOREIGN KEY (wholesale_lead_id) REFERENCES wholesale_leads(id) ON DELETE CASCADE,
  CONSTRAINT fk_wholesale_lifecycle_events_actor FOREIGN KEY (actor_user_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS wholesale_tastings (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  organization_id BIGINT UNSIGNED NOT NULL,
  wholesale_lead_id BIGINT UNSIGNED NOT NULL,
  public_id VARCHAR(80) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'scheduled',
  tasting_format VARCHAR(40) NOT NULL DEFAULT 'onsite',
  scheduled_at DATETIME(6) NULL,
  completed_at DATETIME(6) NULL,
  attendees VARCHAR(1000) NULL,
  flavors_json JSON NULL,
  overall_score DECIMAL(4,2) NULL,
  outcome VARCHAR(40) NULL,
  notes TEXT NULL,
  next_action VARCHAR(500) NULL,
  next_action_at DATETIME(6) NULL,
  created_by BIGINT UNSIGNED NULL,
  updated_by BIGINT UNSIGNED NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uq_wholesale_tastings_public (organization_id, public_id),
  KEY idx_wholesale_tastings_lead (organization_id, wholesale_lead_id, scheduled_at),
  KEY idx_wholesale_tastings_status (organization_id, status, scheduled_at),
  CONSTRAINT fk_wholesale_tastings_org FOREIGN KEY (organization_id) REFERENCES organizations(id),
  CONSTRAINT fk_wholesale_tastings_lead FOREIGN KEY (wholesale_lead_id) REFERENCES wholesale_leads(id) ON DELETE CASCADE,
  CONSTRAINT fk_wholesale_tastings_creator FOREIGN KEY (created_by) REFERENCES users(id),
  CONSTRAINT fk_wholesale_tastings_updater FOREIGN KEY (updated_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO wholesale_planning_settings (organization_id)
SELECT o.id FROM organizations o
WHERE NOT EXISTS (SELECT 1 FROM wholesale_planning_settings s WHERE s.organization_id=o.id);
