-- Gelato Vision Lab V8 Section 3 — Calibration Profile Runtime
SET NAMES utf8mb4;

CREATE TABLE glasses_vision_calibration_profiles (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  organization_id BIGINT UNSIGNED NOT NULL,
  public_id VARCHAR(80) NOT NULL,
  calibration_id BIGINT UNSIGNED NOT NULL,
  package_id BIGINT UNSIGNED NULL,
  location_id BIGINT UNSIGNED NOT NULL,
  station_id BIGINT UNSIGNED NOT NULL,
  profile_name VARCHAR(190) NOT NULL,
  device_platform VARCHAR(40) NOT NULL,
  frame_width INT UNSIGNED NOT NULL,
  frame_height INT UNSIGNED NOT NULL,
  pixel_format VARCHAR(40) NOT NULL,
  environment_json JSON NOT NULL,
  profile_hash CHAR(64) NOT NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'draft',
  created_by BIGINT UNSIGNED NULL,
  approved_by BIGINT UNSIGNED NULL,
  approved_at DATETIME(6) NULL,
  retired_by BIGINT UNSIGNED NULL,
  retired_at DATETIME(6) NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uq_glasses_vision_cal_profile_public (organization_id,public_id),
  UNIQUE KEY uq_glasses_vision_cal_profile_hash (organization_id,profile_hash),
  KEY idx_glasses_vision_cal_profile_scope (organization_id,location_id,station_id,status,created_at),
  CONSTRAINT fk_glasses_vision_cal_profile_org FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
  CONSTRAINT fk_glasses_vision_cal_profile_cal FOREIGN KEY (calibration_id) REFERENCES glasses_station_calibrations(id) ON DELETE RESTRICT,
  CONSTRAINT fk_glasses_vision_cal_profile_package FOREIGN KEY (package_id) REFERENCES glasses_vision_model_packages(id) ON DELETE SET NULL,
  CONSTRAINT fk_glasses_vision_cal_profile_location FOREIGN KEY (location_id) REFERENCES locations(id) ON DELETE CASCADE,
  CONSTRAINT fk_glasses_vision_cal_profile_station FOREIGN KEY (station_id) REFERENCES kds_stations(id) ON DELETE CASCADE,
  CONSTRAINT fk_glasses_vision_cal_profile_creator FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_glasses_vision_cal_profile_approver FOREIGN KEY (approved_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_glasses_vision_cal_profile_retirer FOREIGN KEY (retired_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE glasses_vision_calibration_profile_activations (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  organization_id BIGINT UNSIGNED NOT NULL,
  public_id VARCHAR(80) NOT NULL,
  profile_id BIGINT UNSIGNED NOT NULL,
  location_id BIGINT UNSIGNED NOT NULL,
  station_id BIGINT UNSIGNED NOT NULL,
  device_id BIGINT UNSIGNED NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'active',
  activation_hash CHAR(64) NOT NULL,
  rationale VARCHAR(2000) NOT NULL,
  activated_by BIGINT UNSIGNED NULL,
  activated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  deactivated_by BIGINT UNSIGNED NULL,
  deactivated_at DATETIME(6) NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_glasses_vision_cal_activation_public (organization_id,public_id),
  KEY idx_glasses_vision_cal_activation_scope (organization_id,location_id,station_id,device_id,status,activated_at),
  CONSTRAINT fk_glasses_vision_cal_activation_org FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
  CONSTRAINT fk_glasses_vision_cal_activation_profile FOREIGN KEY (profile_id) REFERENCES glasses_vision_calibration_profiles(id) ON DELETE RESTRICT,
  CONSTRAINT fk_glasses_vision_cal_activation_location FOREIGN KEY (location_id) REFERENCES locations(id) ON DELETE CASCADE,
  CONSTRAINT fk_glasses_vision_cal_activation_station FOREIGN KEY (station_id) REFERENCES kds_stations(id) ON DELETE CASCADE,
  CONSTRAINT fk_glasses_vision_cal_activation_device FOREIGN KEY (device_id) REFERENCES glasses_devices(id) ON DELETE CASCADE,
  CONSTRAINT fk_glasses_vision_cal_activation_actor FOREIGN KEY (activated_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_glasses_vision_cal_deactivation_actor FOREIGN KEY (deactivated_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
