-- Gelato AR Glasses Continuous Production Drift Detection & Environment Awareness
SET NAMES utf8mb4;

CREATE TABLE glasses_vision_drift_baselines (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  organization_id BIGINT UNSIGNED NOT NULL,
  package_id BIGINT UNSIGNED NOT NULL,
  location_id BIGINT UNSIGNED NOT NULL,
  station_id BIGINT UNSIGNED NULL,
  detector_name VARCHAR(120) NOT NULL,
  calibration_source_hash CHAR(64) NULL,
  menu_signature CHAR(64) NULL,
  ingredient_signature CHAR(64) NULL,
  frame_width INT UNSIGNED NULL,
  frame_height INT UNSIGNED NULL,
  pixel_format VARCHAR(40) NULL,
  sample_count INT UNSIGNED NOT NULL DEFAULT 0,
  brightness_mean DECIMAL(9,6) NULL,
  contrast_mean DECIMAL(9,6) NULL,
  camera_pitch_mean DECIMAL(10,5) NULL,
  camera_yaw_mean DECIMAL(10,5) NULL,
  camera_roll_mean DECIMAL(10,5) NULL,
  confidence_mean DECIMAL(9,6) NULL,
  latency_mean_ms DECIMAL(12,4) NULL,
  correction_rate DECIMAL(9,6) NULL,
  low_confidence_rate DECIMAL(9,6) NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'active',
  established_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uq_glasses_vision_drift_baseline (organization_id,package_id,location_id,station_id),
  KEY idx_glasses_vision_drift_baseline_scope (organization_id,detector_name,location_id,station_id,status),
  CONSTRAINT fk_glasses_vision_drift_baseline_org FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
  CONSTRAINT fk_glasses_vision_drift_baseline_package FOREIGN KEY (package_id) REFERENCES glasses_vision_model_packages(id) ON DELETE CASCADE,
  CONSTRAINT fk_glasses_vision_drift_baseline_location FOREIGN KEY (location_id) REFERENCES locations(id) ON DELETE CASCADE,
  CONSTRAINT fk_glasses_vision_drift_baseline_station FOREIGN KEY (station_id) REFERENCES kds_stations(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE glasses_vision_drift_samples (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  organization_id BIGINT UNSIGNED NOT NULL,
  assignment_id BIGINT UNSIGNED NOT NULL,
  rollout_id BIGINT UNSIGNED NULL,
  package_id BIGINT UNSIGNED NOT NULL,
  device_id BIGINT UNSIGNED NOT NULL,
  build_session_id BIGINT UNSIGNED NOT NULL,
  location_id BIGINT UNSIGNED NOT NULL,
  station_id BIGINT UNSIGNED NULL,
  sample_key VARCHAR(190) NOT NULL,
  calibration_source_hash CHAR(64) NULL,
  menu_signature CHAR(64) NULL,
  ingredient_signature CHAR(64) NULL,
  frame_width INT UNSIGNED NULL,
  frame_height INT UNSIGNED NULL,
  pixel_format VARCHAR(40) NULL,
  brightness_mean DECIMAL(9,6) NULL,
  contrast_mean DECIMAL(9,6) NULL,
  camera_pitch DECIMAL(10,5) NULL,
  camera_yaw DECIMAL(10,5) NULL,
  camera_roll DECIMAL(10,5) NULL,
  confidence_mean DECIMAL(9,6) NULL,
  latency_mean_ms DECIMAL(12,4) NULL,
  observation_count INT UNSIGNED NOT NULL DEFAULT 0,
  correction_count INT UNSIGNED NOT NULL DEFAULT 0,
  low_confidence_count INT UNSIGNED NOT NULL DEFAULT 0,
  drift_state VARCHAR(24) NOT NULL DEFAULT 'calibrating',
  drift_score DECIMAL(9,6) NOT NULL DEFAULT 0,
  reasons_json JSON NULL,
  metadata_json JSON NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uq_glasses_vision_drift_sample (assignment_id,sample_key),
  KEY idx_glasses_vision_drift_scope (organization_id,package_id,location_id,station_id,created_at),
  KEY idx_glasses_vision_drift_state (organization_id,drift_state,created_at),
  CONSTRAINT fk_glasses_vision_drift_sample_org FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
  CONSTRAINT fk_glasses_vision_drift_sample_assignment FOREIGN KEY (assignment_id) REFERENCES glasses_vision_model_assignments(id) ON DELETE CASCADE,
  CONSTRAINT fk_glasses_vision_drift_sample_rollout FOREIGN KEY (rollout_id) REFERENCES glasses_vision_model_rollouts(id) ON DELETE SET NULL,
  CONSTRAINT fk_glasses_vision_drift_sample_package FOREIGN KEY (package_id) REFERENCES glasses_vision_model_packages(id) ON DELETE CASCADE,
  CONSTRAINT fk_glasses_vision_drift_sample_device FOREIGN KEY (device_id) REFERENCES glasses_devices(id) ON DELETE CASCADE,
  CONSTRAINT fk_glasses_vision_drift_sample_build FOREIGN KEY (build_session_id) REFERENCES glasses_build_sessions(id) ON DELETE CASCADE,
  CONSTRAINT fk_glasses_vision_drift_sample_location FOREIGN KEY (location_id) REFERENCES locations(id) ON DELETE CASCADE,
  CONSTRAINT fk_glasses_vision_drift_sample_station FOREIGN KEY (station_id) REFERENCES kds_stations(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE glasses_vision_drift_incidents (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  organization_id BIGINT UNSIGNED NOT NULL,
  package_id BIGINT UNSIGNED NOT NULL,
  rollout_id BIGINT UNSIGNED NULL,
  location_id BIGINT UNSIGNED NOT NULL,
  station_id BIGINT UNSIGNED NULL,
  incident_key CHAR(64) NOT NULL,
  severity VARCHAR(24) NOT NULL,
  drift_state VARCHAR(24) NOT NULL,
  category VARCHAR(40) NOT NULL,
  reasons_json JSON NOT NULL,
  first_seen_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  last_seen_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  resolved_at DATETIME(6) NULL,
  metadata_json JSON NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_glasses_vision_drift_incident (organization_id,incident_key),
  KEY idx_glasses_vision_drift_incident_scope (organization_id,location_id,station_id,severity,resolved_at),
  CONSTRAINT fk_glasses_vision_drift_incident_org FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
  CONSTRAINT fk_glasses_vision_drift_incident_package FOREIGN KEY (package_id) REFERENCES glasses_vision_model_packages(id) ON DELETE CASCADE,
  CONSTRAINT fk_glasses_vision_drift_incident_rollout FOREIGN KEY (rollout_id) REFERENCES glasses_vision_model_rollouts(id) ON DELETE SET NULL,
  CONSTRAINT fk_glasses_vision_drift_incident_location FOREIGN KEY (location_id) REFERENCES locations(id) ON DELETE CASCADE,
  CONSTRAINT fk_glasses_vision_drift_incident_station FOREIGN KEY (station_id) REFERENCES kds_stations(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
