-- Gelato AR Glasses Vision Model Packages & Governed Runtime Rollout
SET NAMES utf8mb4;

CREATE TABLE glasses_vision_model_packages (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  organization_id BIGINT UNSIGNED NOT NULL,
  public_id VARCHAR(80) NOT NULL,
  detector_name VARCHAR(120) NOT NULL,
  model_name VARCHAR(160) NOT NULL,
  model_version VARCHAR(80) NOT NULL,
  runtime_type VARCHAR(40) NOT NULL,
  platform VARCHAR(40) NOT NULL,
  artifact_url VARCHAR(1000) NOT NULL,
  artifact_sha256 CHAR(64) NOT NULL,
  artifact_bytes BIGINT UNSIGNED NULL,
  minimum_sdk_version VARCHAR(80) NULL,
  minimum_app_version VARCHAR(80) NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'ready',
  notes VARCHAR(1000) NULL,
  metadata_json JSON NULL,
  created_by BIGINT UNSIGNED NULL,
  retired_by BIGINT UNSIGNED NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  retired_at DATETIME(6) NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_glasses_vision_model_public (organization_id,public_id),
  UNIQUE KEY uq_glasses_vision_model_version (organization_id,detector_name,model_name,model_version,platform,runtime_type),
  KEY idx_glasses_vision_model_detector (organization_id,detector_name,status,created_at),
  CONSTRAINT fk_glasses_vision_model_org FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
  CONSTRAINT fk_glasses_vision_model_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_glasses_vision_model_retired_by FOREIGN KEY (retired_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE glasses_vision_model_rollouts (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  organization_id BIGINT UNSIGNED NOT NULL,
  public_id VARCHAR(80) NOT NULL,
  detector_name VARCHAR(120) NOT NULL,
  target_package_id BIGINT UNSIGNED NOT NULL,
  baseline_package_id BIGINT UNSIGNED NULL,
  location_id BIGINT UNSIGNED NULL,
  station_id BIGINT UNSIGNED NULL,
  canary_percent DECIMAL(5,2) NOT NULL DEFAULT 0.00,
  status VARCHAR(24) NOT NULL DEFAULT 'draft',
  notes VARCHAR(1000) NULL,
  created_by BIGINT UNSIGNED NULL,
  activated_by BIGINT UNSIGNED NULL,
  paused_by BIGINT UNSIGNED NULL,
  rolled_back_by BIGINT UNSIGNED NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  activated_at DATETIME(6) NULL,
  paused_at DATETIME(6) NULL,
  rolled_back_at DATETIME(6) NULL,
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uq_glasses_vision_rollout_public (organization_id,public_id),
  KEY idx_glasses_vision_rollout_scope (organization_id,detector_name,status,location_id,station_id,updated_at),
  KEY idx_glasses_vision_rollout_target (organization_id,target_package_id,status),
  CONSTRAINT fk_glasses_vision_rollout_org FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
  CONSTRAINT fk_glasses_vision_rollout_target FOREIGN KEY (target_package_id) REFERENCES glasses_vision_model_packages(id),
  CONSTRAINT fk_glasses_vision_rollout_baseline FOREIGN KEY (baseline_package_id) REFERENCES glasses_vision_model_packages(id),
  CONSTRAINT fk_glasses_vision_rollout_location FOREIGN KEY (location_id) REFERENCES locations(id) ON DELETE CASCADE,
  CONSTRAINT fk_glasses_vision_rollout_station FOREIGN KEY (station_id) REFERENCES kds_stations(id) ON DELETE CASCADE,
  CONSTRAINT fk_glasses_vision_rollout_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_glasses_vision_rollout_activated_by FOREIGN KEY (activated_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_glasses_vision_rollout_paused_by FOREIGN KEY (paused_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_glasses_vision_rollout_rolled_back_by FOREIGN KEY (rolled_back_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE glasses_vision_model_rollout_events (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  organization_id BIGINT UNSIGNED NOT NULL,
  rollout_id BIGINT UNSIGNED NOT NULL,
  event_type VARCHAR(40) NOT NULL,
  previous_status VARCHAR(24) NULL,
  next_status VARCHAR(24) NULL,
  previous_canary_percent DECIMAL(5,2) NULL,
  next_canary_percent DECIMAL(5,2) NULL,
  metadata_json JSON NULL,
  actor_user_id BIGINT UNSIGNED NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  KEY idx_glasses_vision_rollout_events (organization_id,rollout_id,id),
  CONSTRAINT fk_glasses_vision_rollout_event_org FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
  CONSTRAINT fk_glasses_vision_rollout_event_rollout FOREIGN KEY (rollout_id) REFERENCES glasses_vision_model_rollouts(id) ON DELETE CASCADE,
  CONSTRAINT fk_glasses_vision_rollout_event_actor FOREIGN KEY (actor_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE glasses_vision_model_device_reports (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  organization_id BIGINT UNSIGNED NOT NULL,
  device_id BIGINT UNSIGNED NOT NULL,
  rollout_id BIGINT UNSIGNED NULL,
  package_id BIGINT UNSIGNED NULL,
  report_key VARCHAR(190) NOT NULL,
  report_type VARCHAR(40) NOT NULL,
  runtime_state VARCHAR(40) NULL,
  artifact_sha256 CHAR(64) NULL,
  error_code VARCHAR(120) NULL,
  message VARCHAR(1000) NULL,
  metadata_json JSON NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uq_glasses_vision_model_report (device_id,report_key),
  KEY idx_glasses_vision_model_reports_device (organization_id,device_id,created_at),
  KEY idx_glasses_vision_model_reports_rollout (organization_id,rollout_id,created_at),
  CONSTRAINT fk_glasses_vision_model_report_org FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
  CONSTRAINT fk_glasses_vision_model_report_device FOREIGN KEY (device_id) REFERENCES glasses_devices(id) ON DELETE CASCADE,
  CONSTRAINT fk_glasses_vision_model_report_rollout FOREIGN KEY (rollout_id) REFERENCES glasses_vision_model_rollouts(id) ON DELETE SET NULL,
  CONSTRAINT fk_glasses_vision_model_report_package FOREIGN KEY (package_id) REFERENCES glasses_vision_model_packages(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
