-- Gelato Vision Lab V3 — Active Learning Automation & Training Mission Generation
SET NAMES utf8mb4;

CREATE TABLE glasses_vision_active_learning_candidates (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  organization_id BIGINT UNSIGNED NOT NULL,
  public_id VARCHAR(80) NOT NULL,
  candidate_key CHAR(64) NOT NULL,
  candidate_type VARCHAR(48) NOT NULL,
  source_type VARCHAR(48) NOT NULL,
  source_reference VARCHAR(190) NOT NULL,
  observation_id BIGINT UNSIGNED NULL,
  device_id BIGINT UNSIGNED NULL,
  location_id BIGINT UNSIGNED NULL,
  station_id BIGINT UNSIGNED NULL,
  operator_user_id BIGINT UNSIGNED NULL,
  canonical_label VARCHAR(190) NULL,
  priority_score DECIMAL(9,4) NOT NULL DEFAULT 0,
  severity VARCHAR(24) NOT NULL DEFAULT 'normal',
  reason VARCHAR(1000) NOT NULL,
  evidence_json JSON NULL,
  suggested_title VARCHAR(190) NULL,
  suggested_targets_json JSON NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'open',
  mission_id BIGINT UNSIGNED NULL,
  queued_sample_id BIGINT UNSIGNED NULL,
  generated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  acted_by BIGINT UNSIGNED NULL,
  acted_at DATETIME(6) NULL,
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uq_glasses_active_learning_public (organization_id,public_id),
  UNIQUE KEY uq_glasses_active_learning_key (organization_id,candidate_key),
  KEY idx_glasses_active_learning_queue (organization_id,status,priority_score,generated_at),
  KEY idx_glasses_active_learning_type (organization_id,candidate_type,status),
  CONSTRAINT fk_glasses_active_learning_org FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
  CONSTRAINT fk_glasses_active_learning_observation FOREIGN KEY (observation_id) REFERENCES glasses_build_observations(id) ON DELETE CASCADE,
  CONSTRAINT fk_glasses_active_learning_device FOREIGN KEY (device_id) REFERENCES glasses_devices(id) ON DELETE SET NULL,
  CONSTRAINT fk_glasses_active_learning_location FOREIGN KEY (location_id) REFERENCES locations(id) ON DELETE SET NULL,
  CONSTRAINT fk_glasses_active_learning_station FOREIGN KEY (station_id) REFERENCES kds_stations(id) ON DELETE SET NULL,
  CONSTRAINT fk_glasses_active_learning_operator FOREIGN KEY (operator_user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_glasses_active_learning_mission FOREIGN KEY (mission_id) REFERENCES glasses_vision_training_missions(id) ON DELETE SET NULL,
  CONSTRAINT fk_glasses_active_learning_sample FOREIGN KEY (queued_sample_id) REFERENCES glasses_vision_training_samples(id) ON DELETE SET NULL,
  CONSTRAINT fk_glasses_active_learning_actor FOREIGN KEY (acted_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE glasses_vision_active_learning_scans (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  organization_id BIGINT UNSIGNED NOT NULL,
  public_id VARCHAR(80) NOT NULL,
  trigger_source VARCHAR(32) NOT NULL DEFAULT 'manual',
  created_candidates INT UNSIGNED NOT NULL DEFAULT 0,
  queued_samples INT UNSIGNED NOT NULL DEFAULT 0,
  source_counts_json JSON NULL,
  created_by BIGINT UNSIGNED NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uq_glasses_active_learning_scan_public (organization_id,public_id),
  KEY idx_glasses_active_learning_scans (organization_id,created_at),
  CONSTRAINT fk_glasses_active_learning_scan_org FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
  CONSTRAINT fk_glasses_active_learning_scan_actor FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
