-- Gelato Vision Lab V8 Section 1 — Production Model Health & Drift Ledger
SET NAMES utf8mb4;

CREATE TABLE glasses_vision_model_health_snapshots (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  organization_id BIGINT UNSIGNED NOT NULL,
  public_id VARCHAR(80) NOT NULL,
  package_id BIGINT UNSIGNED NOT NULL,
  location_id BIGINT UNSIGNED NULL,
  station_id BIGINT UNSIGNED NULL,
  device_id BIGINT UNSIGNED NULL,
  window_started_at DATETIME(6) NOT NULL,
  window_ended_at DATETIME(6) NOT NULL,
  source_fingerprint CHAR(64) NOT NULL,
  sample_count INT UNSIGNED NOT NULL DEFAULT 0,
  observation_count INT UNSIGNED NOT NULL DEFAULT 0,
  production_error_count INT UNSIGNED NOT NULL DEFAULT 0,
  correction_count INT UNSIGNED NOT NULL DEFAULT 0,
  low_confidence_count INT UNSIGNED NOT NULL DEFAULT 0,
  critical_drift_count INT UNSIGNED NOT NULL DEFAULT 0,
  warning_drift_count INT UNSIGNED NOT NULL DEFAULT 0,
  mean_confidence DECIMAL(9,6) NULL,
  mean_latency_ms DECIMAL(12,4) NULL,
  error_rate DECIMAL(9,6) NOT NULL DEFAULT 0,
  correction_rate DECIMAL(9,6) NOT NULL DEFAULT 0,
  low_confidence_rate DECIMAL(9,6) NOT NULL DEFAULT 0,
  health_state VARCHAR(24) NOT NULL,
  metrics_json JSON NOT NULL,
  snapshot_hash CHAR(64) NOT NULL,
  created_by BIGINT UNSIGNED NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uq_glasses_vision_health_public (organization_id,public_id),
  UNIQUE KEY uq_glasses_vision_health_identity (organization_id,package_id,location_id,station_id,device_id,window_started_at,window_ended_at,source_fingerprint),
  KEY idx_glasses_vision_health_scope (organization_id,package_id,location_id,station_id,device_id,window_ended_at),
  KEY idx_glasses_vision_health_state (organization_id,health_state,window_ended_at),
  CONSTRAINT fk_glasses_vision_health_org FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
  CONSTRAINT fk_glasses_vision_health_package FOREIGN KEY (package_id) REFERENCES glasses_vision_model_packages(id) ON DELETE RESTRICT,
  CONSTRAINT fk_glasses_vision_health_location FOREIGN KEY (location_id) REFERENCES locations(id) ON DELETE SET NULL,
  CONSTRAINT fk_glasses_vision_health_station FOREIGN KEY (station_id) REFERENCES kds_stations(id) ON DELETE SET NULL,
  CONSTRAINT fk_glasses_vision_health_device FOREIGN KEY (device_id) REFERENCES glasses_devices(id) ON DELETE SET NULL,
  CONSTRAINT fk_glasses_vision_health_creator FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
