-- Gelato Equipment Catalog + internal Agent Brain knowledge/skills
-- Existing installations: import once after database/20260912_floor_planner.sql.

SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS equipment_assets (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  organization_id BIGINT UNSIGNED NOT NULL,
  public_id VARCHAR(80) NOT NULL,
  name VARCHAR(180) NOT NULL,
  asset_type VARCHAR(80) NOT NULL DEFAULT 'other',
  purpose TEXT NULL,
  brand VARCHAR(160) NULL,
  manufacturer VARCHAR(160) NULL,
  model VARCHAR(160) NULL,
  serial_number VARCHAR(180) NULL,
  asset_tag VARCHAR(120) NULL,
  manufacture_year SMALLINT UNSIGNED NULL,
  purchase_date DATE NULL,
  install_date DATE NULL,
  expected_life_years DECIMAL(5,1) NULL,
  warranty_expires_on DATE NULL,
  purchase_price DECIMAL(12,2) NULL,
  replacement_cost DECIMAL(12,2) NULL,
  operational_status VARCHAR(40) NOT NULL DEFAULT 'active',
  condition_status VARCHAR(40) NOT NULL DEFAULT 'good',
  criticality VARCHAR(24) NOT NULL DEFAULT 'medium',
  location_name VARCHAR(180) NULL,
  floor_plan_public_id VARCHAR(80) NULL,
  floor_plan_component_id VARCHAR(120) NULL,
  width_inches DECIMAL(9,2) NULL,
  depth_inches DECIMAL(9,2) NULL,
  height_inches DECIMAL(9,2) NULL,
  capacity_text VARCHAR(255) NULL,
  utility_type VARCHAR(120) NULL,
  voltage VARCHAR(80) NULL,
  phase VARCHAR(40) NULL,
  amperage VARCHAR(80) NULL,
  btu_rating VARCHAR(80) NULL,
  water_requirement VARCHAR(255) NULL,
  drain_requirement VARCHAR(255) NULL,
  ventilation_requirement VARCHAR(255) NULL,
  maintenance_required TINYINT(1) NOT NULL DEFAULT 0,
  maintenance_interval_days INT UNSIGNED NULL,
  last_service_on DATE NULL,
  next_service_on DATE NULL,
  cleaning_notes TEXT NULL,
  maintenance_notes TEXT NULL,
  operating_notes TEXT NULL,
  safety_notes TEXT NULL,
  parts_consumables TEXT NULL,
  manual_url VARCHAR(600) NULL,
  notes TEXT NULL,
  created_by BIGINT UNSIGNED NULL,
  updated_by BIGINT UNSIGNED NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  archived_at DATETIME(6) NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_equipment_assets_org_public (organization_id, public_id),
  KEY idx_equipment_assets_org_type (organization_id, asset_type, archived_at),
  KEY idx_equipment_assets_org_status (organization_id, operational_status, archived_at),
  KEY idx_equipment_assets_next_service (organization_id, maintenance_required, next_service_on, archived_at),
  CONSTRAINT fk_equipment_assets_org FOREIGN KEY (organization_id) REFERENCES organizations(id),
  CONSTRAINT fk_equipment_assets_creator FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_equipment_assets_updater FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS equipment_service_contacts (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  organization_id BIGINT UNSIGNED NOT NULL,
  public_id VARCHAR(80) NOT NULL,
  company_name VARCHAR(180) NOT NULL,
  contact_name VARCHAR(180) NULL,
  specialty VARCHAR(255) NULL,
  phone VARCHAR(60) NULL,
  email VARCHAR(254) NULL,
  website VARCHAR(600) NULL,
  emergency_phone VARCHAR(60) NULL,
  account_number VARCHAR(160) NULL,
  contract_number VARCHAR(160) NULL,
  is_preferred TINYINT(1) NOT NULL DEFAULT 0,
  is_warranty_provider TINYINT(1) NOT NULL DEFAULT 0,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  notes TEXT NULL,
  created_by BIGINT UNSIGNED NULL,
  updated_by BIGINT UNSIGNED NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  archived_at DATETIME(6) NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_equipment_contacts_org_public (organization_id, public_id),
  KEY idx_equipment_contacts_org_status (organization_id, status, archived_at),
  CONSTRAINT fk_equipment_contacts_org FOREIGN KEY (organization_id) REFERENCES organizations(id),
  CONSTRAINT fk_equipment_contacts_creator FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_equipment_contacts_updater FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS equipment_asset_service_contacts (
  equipment_asset_id BIGINT UNSIGNED NOT NULL,
  service_contact_id BIGINT UNSIGNED NOT NULL,
  contact_role VARCHAR(40) NOT NULL DEFAULT 'service',
  is_primary TINYINT(1) NOT NULL DEFAULT 0,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (equipment_asset_id, service_contact_id, contact_role),
  KEY idx_equipment_asset_contacts_contact (service_contact_id),
  CONSTRAINT fk_equipment_asset_contacts_asset FOREIGN KEY (equipment_asset_id) REFERENCES equipment_assets(id) ON DELETE CASCADE,
  CONSTRAINT fk_equipment_asset_contacts_contact FOREIGN KEY (service_contact_id) REFERENCES equipment_service_contacts(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS equipment_service_events (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  organization_id BIGINT UNSIGNED NOT NULL,
  public_id VARCHAR(80) NOT NULL,
  equipment_asset_id BIGINT UNSIGNED NOT NULL,
  service_contact_id BIGINT UNSIGNED NULL,
  event_type VARCHAR(48) NOT NULL DEFAULT 'maintenance',
  status VARCHAR(32) NOT NULL DEFAULT 'completed',
  serviced_on DATE NOT NULL,
  technician_name VARCHAR(180) NULL,
  description TEXT NOT NULL,
  parts_used TEXT NULL,
  cost DECIMAL(12,2) NULL,
  downtime_minutes INT UNSIGNED NULL,
  next_due_on DATE NULL,
  created_by BIGINT UNSIGNED NULL,
  updated_by BIGINT UNSIGNED NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uq_equipment_service_events_org_public (organization_id, public_id),
  KEY idx_equipment_events_asset_date (equipment_asset_id, serviced_on),
  KEY idx_equipment_events_org_date (organization_id, serviced_on),
  CONSTRAINT fk_equipment_events_org FOREIGN KEY (organization_id) REFERENCES organizations(id),
  CONSTRAINT fk_equipment_events_asset FOREIGN KEY (equipment_asset_id) REFERENCES equipment_assets(id) ON DELETE CASCADE,
  CONSTRAINT fk_equipment_events_contact FOREIGN KEY (service_contact_id) REFERENCES equipment_service_contacts(id) ON DELETE SET NULL,
  CONSTRAINT fk_equipment_events_creator FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_equipment_events_updater FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Internal structured knowledge index used by authenticated agent skills.
-- It is intentionally separate from the public landing-page Knowledge Center so equipment/service data is never exposed publicly.
CREATE TABLE IF NOT EXISTS agent_knowledge_records (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  organization_id BIGINT UNSIGNED NOT NULL,
  public_id VARCHAR(100) NOT NULL,
  source_type VARCHAR(64) NOT NULL,
  source_public_id VARCHAR(100) NOT NULL,
  title VARCHAR(240) NOT NULL,
  content LONGTEXT NOT NULL,
  content_sha256 CHAR(64) NOT NULL,
  visibility VARCHAR(32) NOT NULL DEFAULT 'internal',
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  version INT UNSIGNED NOT NULL DEFAULT 1,
  updated_by BIGINT UNSIGNED NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uq_agent_knowledge_source (organization_id, source_type, source_public_id),
  KEY idx_agent_knowledge_org_visibility (organization_id, visibility, status),
  FULLTEXT KEY ft_agent_knowledge_title_content (title, content),
  CONSTRAINT fk_agent_knowledge_org FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
  CONSTRAINT fk_agent_knowledge_updater FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO permissions (permission_key, name, description, category) VALUES
  ('equipment.view', 'View equipment catalog', 'View equipment assets, service history, maintenance schedules, and linked service contacts.', 'Equipment'),
  ('equipment.edit', 'Edit equipment catalog', 'Create, edit, link, and archive equipment assets.', 'Equipment'),
  ('equipment.service', 'Manage equipment service', 'Record maintenance, repairs, inspections, costs, downtime, and next-service dates.', 'Equipment'),
  ('equipment.contacts', 'Manage service contacts', 'Create and edit equipment service companies, technicians, warranty providers, and emergency contacts.', 'Equipment'),
  ('agent.equipment_skills', 'Use equipment agent skills', 'Allow the authenticated AI agent to search equipment, maintenance, service history, and service contacts within the user permission boundary.', 'Agent')
ON DUPLICATE KEY UPDATE
  name = VALUES(name),
  description = VALUES(description),
  category = VALUES(category);
