CREATE TABLE IF NOT EXISTS glasses_production_pilots (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  organization_id BIGINT UNSIGNED NOT NULL,
  public_id VARCHAR(80) NOT NULL,
  name VARCHAR(160) NOT NULL,
  cohort_key VARCHAR(120) NOT NULL,
  release_label VARCHAR(120) NOT NULL,
  location_id BIGINT UNSIGNED NULL,
  station_id BIGINT UNSIGNED NULL,
  rollout_id BIGINT UNSIGNED NULL,
  required_adapter_id VARCHAR(120) NOT NULL DEFAULT 'air3.vendor.v1',
  require_vendor_adapter TINYINT(1) NOT NULL DEFAULT 1,
  status ENUM('draft','active','paused','stopped') NOT NULL DEFAULT 'draft',
  kill_switch TINYINT(1) NOT NULL DEFAULT 0,
  notes VARCHAR(1000) NULL,
  created_by BIGINT UNSIGNED NOT NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  activated_by BIGINT UNSIGNED NULL,
  activated_at DATETIME(6) NULL,
  paused_by BIGINT UNSIGNED NULL,
  paused_at DATETIME(6) NULL,
  stopped_by BIGINT UNSIGNED NULL,
  stopped_at DATETIME(6) NULL,
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uq_glasses_production_pilots_public (organization_id,public_id),
  UNIQUE KEY uq_glasses_production_pilots_cohort (organization_id,cohort_key),
  KEY idx_glasses_production_pilots_scope (organization_id,location_id,station_id,status),
  KEY idx_glasses_production_pilots_rollout (rollout_id),
  CONSTRAINT fk_glasses_production_pilots_org FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
  CONSTRAINT fk_glasses_production_pilots_location FOREIGN KEY (location_id) REFERENCES locations(id) ON DELETE SET NULL,
  CONSTRAINT fk_glasses_production_pilots_station FOREIGN KEY (station_id) REFERENCES kds_stations(id) ON DELETE SET NULL,
  CONSTRAINT fk_glasses_production_pilots_rollout FOREIGN KEY (rollout_id) REFERENCES glasses_vision_model_rollouts(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS glasses_production_pilot_devices (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  organization_id BIGINT UNSIGNED NOT NULL,
  pilot_id BIGINT UNSIGNED NOT NULL,
  device_id BIGINT UNSIGNED NOT NULL,
  status ENUM('enrolled','enabled','disabled','blocked','removed') NOT NULL DEFAULT 'enrolled',
  readiness_state ENUM('unknown','ready','blocked') NOT NULL DEFAULT 'unknown',
  readiness_json JSON NULL,
  enrolled_by BIGINT UNSIGNED NOT NULL,
  enrolled_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  evaluated_at DATETIME(6) NULL,
  enabled_by BIGINT UNSIGNED NULL,
  enabled_at DATETIME(6) NULL,
  disabled_by BIGINT UNSIGNED NULL,
  disabled_at DATETIME(6) NULL,
  removed_by BIGINT UNSIGNED NULL,
  removed_at DATETIME(6) NULL,
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uq_glasses_pilot_device (organization_id,pilot_id,device_id),
  KEY idx_glasses_pilot_device_status (organization_id,device_id,status),
  CONSTRAINT fk_glasses_pilot_device_org FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
  CONSTRAINT fk_glasses_pilot_device_pilot FOREIGN KEY (pilot_id) REFERENCES glasses_production_pilots(id) ON DELETE CASCADE,
  CONSTRAINT fk_glasses_pilot_device_device FOREIGN KEY (device_id) REFERENCES glasses_devices(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS glasses_production_pilot_events (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  organization_id BIGINT UNSIGNED NOT NULL,
  pilot_id BIGINT UNSIGNED NOT NULL,
  device_id BIGINT UNSIGNED NULL,
  event_type VARCHAR(80) NOT NULL,
  previous_status VARCHAR(40) NULL,
  next_status VARCHAR(40) NULL,
  reason VARCHAR(1000) NULL,
  metadata_json JSON NULL,
  actor_user_id BIGINT UNSIGNED NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  KEY idx_glasses_pilot_events (organization_id,pilot_id,created_at),
  CONSTRAINT fk_glasses_pilot_events_org FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
  CONSTRAINT fk_glasses_pilot_events_pilot FOREIGN KEY (pilot_id) REFERENCES glasses_production_pilots(id) ON DELETE CASCADE,
  CONSTRAINT fk_glasses_pilot_events_device FOREIGN KEY (device_id) REFERENCES glasses_devices(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
