-- Gelato Restaurant AI: staff profiles, availability, scheduling, labor coverage and shift requests
SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS staff_profiles (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  organization_id BIGINT UNSIGNED NOT NULL,
  user_id BIGINT UNSIGNED NOT NULL,
  preferred_name VARCHAR(160) NULL,
  employment_type VARCHAR(32) NOT NULL DEFAULT 'hourly',
  min_weekly_hours DECIMAL(6,2) NULL,
  preferred_weekly_hours DECIMAL(6,2) NULL,
  max_weekly_hours DECIMAL(6,2) NULL,
  hourly_labor_cost DECIMAL(10,2) NULL,
  availability_note VARCHAR(1000) NULL,
  skills_json JSON NULL,
  scheduling_notes TEXT NULL,
  created_by BIGINT UNSIGNED NULL,
  updated_by BIGINT UNSIGNED NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uq_staff_profile_org_user (organization_id,user_id),
  KEY idx_staff_profile_org_type (organization_id,employment_type),
  CONSTRAINT fk_staff_profile_org FOREIGN KEY (organization_id) REFERENCES organizations(id),
  CONSTRAINT fk_staff_profile_user FOREIGN KEY (user_id) REFERENCES users(id),
  CONSTRAINT fk_staff_profile_creator FOREIGN KEY (created_by) REFERENCES users(id),
  CONSTRAINT fk_staff_profile_updater FOREIGN KEY (updated_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS staff_availability (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  organization_id BIGINT UNSIGNED NOT NULL,
  user_id BIGINT UNSIGNED NOT NULL,
  weekday TINYINT UNSIGNED NOT NULL,
  start_time TIME NOT NULL,
  end_time TIME NOT NULL,
  availability_type VARCHAR(24) NOT NULL DEFAULT 'available',
  created_by BIGINT UNSIGNED NULL,
  updated_by BIGINT UNSIGNED NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uq_staff_availability_window (organization_id,user_id,weekday,start_time,end_time,availability_type),
  KEY idx_staff_availability_user_day (organization_id,user_id,weekday,start_time),
  CONSTRAINT fk_staff_availability_org FOREIGN KEY (organization_id) REFERENCES organizations(id),
  CONSTRAINT fk_staff_availability_user FOREIGN KEY (user_id) REFERENCES users(id),
  CONSTRAINT fk_staff_availability_creator FOREIGN KEY (created_by) REFERENCES users(id),
  CONSTRAINT fk_staff_availability_updater FOREIGN KEY (updated_by) REFERENCES users(id),
  CONSTRAINT chk_staff_availability_weekday CHECK (weekday BETWEEN 0 AND 6),
  CONSTRAINT chk_staff_availability_time CHECK (end_time > start_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS staff_availability_exceptions (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  organization_id BIGINT UNSIGNED NOT NULL,
  public_id VARCHAR(80) NOT NULL,
  user_id BIGINT UNSIGNED NOT NULL,
  exception_date DATE NOT NULL,
  start_time TIME NULL,
  end_time TIME NULL,
  exception_type VARCHAR(32) NOT NULL DEFAULT 'unavailable',
  status VARCHAR(24) NOT NULL DEFAULT 'approved',
  note VARCHAR(1000) NULL,
  requested_by BIGINT UNSIGNED NULL,
  reviewed_by BIGINT UNSIGNED NULL,
  reviewed_at DATETIME(6) NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uq_staff_exception_public (organization_id,public_id),
  KEY idx_staff_exception_user_date (organization_id,user_id,exception_date,status),
  CONSTRAINT fk_staff_exception_org FOREIGN KEY (organization_id) REFERENCES organizations(id),
  CONSTRAINT fk_staff_exception_user FOREIGN KEY (user_id) REFERENCES users(id),
  CONSTRAINT fk_staff_exception_requester FOREIGN KEY (requested_by) REFERENCES users(id),
  CONSTRAINT fk_staff_exception_reviewer FOREIGN KEY (reviewed_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS schedule_weeks (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  organization_id BIGINT UNSIGNED NOT NULL,
  week_start DATE NOT NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'draft',
  published_at DATETIME(6) NULL,
  published_by BIGINT UNSIGNED NULL,
  created_by BIGINT UNSIGNED NULL,
  updated_by BIGINT UNSIGNED NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uq_schedule_week_org_start (organization_id,week_start),
  KEY idx_schedule_week_status (organization_id,status,week_start),
  CONSTRAINT fk_schedule_week_org FOREIGN KEY (organization_id) REFERENCES organizations(id),
  CONSTRAINT fk_schedule_week_publisher FOREIGN KEY (published_by) REFERENCES users(id),
  CONSTRAINT fk_schedule_week_creator FOREIGN KEY (created_by) REFERENCES users(id),
  CONSTRAINT fk_schedule_week_updater FOREIGN KEY (updated_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS schedule_shifts (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  organization_id BIGINT UNSIGNED NOT NULL,
  public_id VARCHAR(80) NOT NULL,
  schedule_week_id BIGINT UNSIGNED NOT NULL,
  location_id BIGINT UNSIGNED NULL,
  position_id BIGINT UNSIGNED NULL,
  user_id BIGINT UNSIGNED NULL,
  title VARCHAR(180) NOT NULL,
  starts_at DATETIME(6) NOT NULL,
  ends_at DATETIME(6) NOT NULL,
  break_minutes INT UNSIGNED NOT NULL DEFAULT 0,
  status VARCHAR(24) NOT NULL DEFAULT 'scheduled',
  notes VARCHAR(1000) NULL,
  created_by BIGINT UNSIGNED NULL,
  updated_by BIGINT UNSIGNED NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  archived_at DATETIME(6) NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_schedule_shift_public (organization_id,public_id),
  KEY idx_schedule_shift_week (organization_id,schedule_week_id,starts_at),
  KEY idx_schedule_shift_user (organization_id,user_id,starts_at,status),
  KEY idx_schedule_shift_position (organization_id,position_id,starts_at,status),
  CONSTRAINT fk_schedule_shift_org FOREIGN KEY (organization_id) REFERENCES organizations(id),
  CONSTRAINT fk_schedule_shift_week FOREIGN KEY (schedule_week_id) REFERENCES schedule_weeks(id) ON DELETE CASCADE,
  CONSTRAINT fk_schedule_shift_location FOREIGN KEY (location_id) REFERENCES locations(id),
  CONSTRAINT fk_schedule_shift_position FOREIGN KEY (position_id) REFERENCES positions(id),
  CONSTRAINT fk_schedule_shift_user FOREIGN KEY (user_id) REFERENCES users(id),
  CONSTRAINT fk_schedule_shift_creator FOREIGN KEY (created_by) REFERENCES users(id),
  CONSTRAINT fk_schedule_shift_updater FOREIGN KEY (updated_by) REFERENCES users(id),
  CONSTRAINT chk_schedule_shift_time CHECK (ends_at > starts_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS schedule_shift_requests (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  organization_id BIGINT UNSIGNED NOT NULL,
  public_id VARCHAR(80) NOT NULL,
  shift_id BIGINT UNSIGNED NOT NULL,
  requester_user_id BIGINT UNSIGNED NOT NULL,
  request_type VARCHAR(24) NOT NULL,
  target_user_id BIGINT UNSIGNED NULL,
  proposed_shift_id BIGINT UNSIGNED NULL,
  note VARCHAR(1000) NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'pending',
  reviewed_by BIGINT UNSIGNED NULL,
  reviewed_at DATETIME(6) NULL,
  manager_note VARCHAR(1000) NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uq_shift_request_public (organization_id,public_id),
  KEY idx_shift_request_status (organization_id,status,created_at),
  KEY idx_shift_request_requester (organization_id,requester_user_id,status),
  CONSTRAINT fk_shift_request_org FOREIGN KEY (organization_id) REFERENCES organizations(id),
  CONSTRAINT fk_shift_request_shift FOREIGN KEY (shift_id) REFERENCES schedule_shifts(id),
  CONSTRAINT fk_shift_request_requester FOREIGN KEY (requester_user_id) REFERENCES users(id),
  CONSTRAINT fk_shift_request_target FOREIGN KEY (target_user_id) REFERENCES users(id),
  CONSTRAINT fk_shift_request_proposed FOREIGN KEY (proposed_shift_id) REFERENCES schedule_shifts(id),
  CONSTRAINT fk_shift_request_reviewer FOREIGN KEY (reviewed_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS labor_coverage_rules (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  organization_id BIGINT UNSIGNED NOT NULL,
  location_id BIGINT UNSIGNED NULL,
  position_id BIGINT UNSIGNED NULL,
  weekday TINYINT UNSIGNED NOT NULL,
  start_time TIME NOT NULL,
  end_time TIME NOT NULL,
  minimum_staff SMALLINT UNSIGNED NOT NULL DEFAULT 1,
  target_staff SMALLINT UNSIGNED NOT NULL DEFAULT 1,
  label VARCHAR(160) NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'active',
  created_by BIGINT UNSIGNED NULL,
  updated_by BIGINT UNSIGNED NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  KEY idx_coverage_rule_day (organization_id,weekday,start_time,status),
  CONSTRAINT fk_coverage_rule_org FOREIGN KEY (organization_id) REFERENCES organizations(id),
  CONSTRAINT fk_coverage_rule_location FOREIGN KEY (location_id) REFERENCES locations(id),
  CONSTRAINT fk_coverage_rule_position FOREIGN KEY (position_id) REFERENCES positions(id),
  CONSTRAINT fk_coverage_rule_creator FOREIGN KEY (created_by) REFERENCES users(id),
  CONSTRAINT fk_coverage_rule_updater FOREIGN KEY (updated_by) REFERENCES users(id),
  CONSTRAINT chk_coverage_rule_weekday CHECK (weekday BETWEEN 0 AND 6),
  CONSTRAINT chk_coverage_rule_time CHECK (end_time > start_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS schedule_events (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  organization_id BIGINT UNSIGNED NOT NULL,
  shift_id BIGINT UNSIGNED NULL,
  event_type VARCHAR(60) NOT NULL,
  summary VARCHAR(500) NOT NULL,
  metadata_json JSON NULL,
  actor_user_id BIGINT UNSIGNED NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  KEY idx_schedule_events_org (organization_id,event_type,created_at),
  KEY idx_schedule_events_shift (shift_id,created_at),
  CONSTRAINT fk_schedule_events_org FOREIGN KEY (organization_id) REFERENCES organizations(id),
  CONSTRAINT fk_schedule_events_shift FOREIGN KEY (shift_id) REFERENCES schedule_shifts(id) ON DELETE CASCADE,
  CONSTRAINT fk_schedule_events_actor FOREIGN KEY (actor_user_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO permissions (permission_key,name,description,category) VALUES
 ('staff.view','View staff','View restaurant staff profiles, positions and scheduling details.','Staff'),
 ('staff.manage','Manage staff','Edit staff scheduling profiles and manager-only labor data.','Staff'),
 ('schedule.view','View schedules','View the restaurant schedule, open shifts and coverage.','Scheduling'),
 ('schedule.manage','Manage schedules','Create, assign, publish and change shifts and coverage rules.','Scheduling'),
 ('schedule.self','Use employee scheduling','View own schedule, maintain availability and submit shift requests.','Scheduling'),
 ('schedule.agent','Use scheduling Agent skills','Allow Restaurant AI to read schedules and perform permitted scheduling actions.','Scheduling')
ON DUPLICATE KEY UPDATE name=VALUES(name),description=VALUES(description),category=VALUES(category);
