-- Gelato Vision Lab V8 Section 3 — Calibration Profile Runtime
SET NAMES utf8mb4;

CREATE TABLE glasses_vision_calibration_profiles (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  organization_id BIGINT UNSIGNED NOT NULL,
  public_id VARCHAR(80) NOT NULL,
  profile_key VARCHAR(160) NOT NULL,
  calibration_id BIGINT UNSIGNED NOT NULL,
  package_id BIGINT UNSIGNED NULL,
  location_id BIGINT UNSIGNED NOT NULL,
  station_id BIGINT UNSIGNED NOT NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'draft',
  priority INT NOT NULL DEFAULT 0,
  context_json JSON NOT NULL,
  guardrails_json JSON NOT NULL,
  profile_hash CHAR(64) NOT NULL,
  created_by BIGINT UNSIGNED NULL,
  activated_by BIGINT UNSIGNED NULL,
  activated_at DATETIME(6) NULL,
  retired_at DATETIME(6) NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uq_glasses_vision_cal_profile_public (organization_id,public_id),
  UNIQUE KEY uq_glasses_vision_cal_profile_identity (organization_id,profile_key,profile_hash),
  KEY idx_glasses_vision_cal_profile_scope (organization_id,location_id,station_id,status,priority),
  KEY idx_glasses_vision_cal_profile_package (organization_id,package_id,status,priority),
  CONSTRAINT fk_glasses_vision_cal_profile_org FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
  CONSTRAINT fk_glasses_vision_cal_profile_calibration FOREIGN KEY (calibration_id) REFERENCES glasses_station_calibrations(id) ON DELETE RESTRICT,
  CONSTRAINT fk_glasses_vision_cal_profile_package FOREIGN KEY (package_id) REFERENCES glasses_vision_model_packages(id) ON DELETE SET NULL,
  CONSTRAINT fk_glasses_vision_cal_profile_location FOREIGN KEY (location_id) REFERENCES locations(id) ON DELETE CASCADE,
  CONSTRAINT fk_glasses_vision_cal_profile_station FOREIGN KEY (station_id) REFERENCES kds_stations(id) ON DELETE CASCADE,
  CONSTRAINT fk_glasses_vision_cal_profile_creator FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_glasses_vision_cal_profile_activator FOREIGN KEY (activated_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE glasses_vision_calibration_selections (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  organization_id BIGINT UNSIGNED NOT NULL,
  public_id VARCHAR(80) NOT NULL,
  device_id BIGINT UNSIGNED NOT NULL,
  package_id BIGINT UNSIGNED NULL,
  context_drift_analysis_id BIGINT UNSIGNED NULL,
  selected_profile_id BIGINT UNSIGNED NULL,
  fallback_calibration_id BIGINT UNSIGNED NULL,
  selection_key CHAR(64) NOT NULL,
  match_score DECIMAL(9,6) NOT NULL DEFAULT 0,
  decision VARCHAR(32) NOT NULL,
  reasons_json JSON NOT NULL,
  context_fingerprint CHAR(64) NOT NULL,
  selection_hash CHAR(64) NOT NULL,
  created_by BIGINT UNSIGNED NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uq_glasses_vision_cal_selection_public (organization_id,public_id),
  UNIQUE KEY uq_glasses_vision_cal_selection_key (organization_id,selection_key),
  KEY idx_glasses_vision_cal_selection_device (organization_id,device_id,created_at),
  KEY idx_glasses_vision_cal_selection_profile (organization_id,selected_profile_id,created_at),
  CONSTRAINT fk_glasses_vision_cal_selection_org FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
  CONSTRAINT fk_glasses_vision_cal_selection_device FOREIGN KEY (device_id) REFERENCES glasses_devices(id) ON DELETE CASCADE,
  CONSTRAINT fk_glasses_vision_cal_selection_package FOREIGN KEY (package_id) REFERENCES glasses_vision_model_packages(id) ON DELETE SET NULL,
  CONSTRAINT fk_glasses_vision_cal_selection_analysis FOREIGN KEY (context_drift_analysis_id) REFERENCES glasses_vision_context_drift_analyses(id) ON DELETE SET NULL,
  CONSTRAINT fk_glasses_vision_cal_selection_profile FOREIGN KEY (selected_profile_id) REFERENCES glasses_vision_calibration_profiles(id) ON DELETE SET NULL,
  CONSTRAINT fk_glasses_vision_cal_selection_fallback FOREIGN KEY (fallback_calibration_id) REFERENCES glasses_station_calibrations(id) ON DELETE SET NULL,
  CONSTRAINT fk_glasses_vision_cal_selection_creator FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
