-- Gelato Vision Lab V7 Section 4 — Retraining Candidate Builder
SET NAMES utf8mb4;

CREATE TABLE glasses_vision_retraining_batches (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  organization_id BIGINT UNSIGNED NOT NULL,
  public_id VARCHAR(80) NOT NULL,
  mining_run_id BIGINT UNSIGNED NOT NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'draft',
  policy_json JSON NOT NULL,
  manifest_json JSON NOT NULL,
  batch_hash CHAR(64) NOT NULL,
  dataset_id BIGINT UNSIGNED NULL,
  created_by BIGINT UNSIGNED NULL,
  built_by BIGINT UNSIGNED NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  built_at DATETIME(6) NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_glasses_vision_retraining_batch_public (organization_id,public_id),
  UNIQUE KEY uq_glasses_vision_retraining_batch_hash (organization_id,batch_hash),
  KEY idx_glasses_vision_retraining_batch_run (organization_id,mining_run_id,created_at),
  CONSTRAINT fk_glasses_vision_retraining_batch_org FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
  CONSTRAINT fk_glasses_vision_retraining_batch_run FOREIGN KEY (mining_run_id) REFERENCES glasses_vision_mining_runs(id) ON DELETE RESTRICT,
  CONSTRAINT fk_glasses_vision_retraining_batch_dataset FOREIGN KEY (dataset_id) REFERENCES glasses_vision_dataset_versions(id) ON DELETE SET NULL,
  CONSTRAINT fk_glasses_vision_retraining_batch_creator FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_glasses_vision_retraining_batch_builder FOREIGN KEY (built_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE glasses_vision_retraining_batch_items (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  organization_id BIGINT UNSIGNED NOT NULL,
  batch_id BIGINT UNSIGNED NOT NULL,
  mined_candidate_id BIGINT UNSIGNED NOT NULL,
  production_error_id BIGINT UNSIGNED NOT NULL,
  training_sample_id BIGINT UNSIGNED NULL,
  training_media_id BIGINT UNSIGNED NULL,
  eligibility_status VARCHAR(24) NOT NULL,
  eligibility_reason VARCHAR(190) NULL,
  decision VARCHAR(24) NOT NULL DEFAULT 'pending',
  decision_reason VARCHAR(1000) NULL,
  evidence_hash CHAR(64) NOT NULL,
  reviewed_by BIGINT UNSIGNED NULL,
  reviewed_at DATETIME(6) NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uq_glasses_vision_retraining_item (organization_id,batch_id,mined_candidate_id),
  KEY idx_glasses_vision_retraining_item_state (organization_id,batch_id,eligibility_status,decision),
  KEY idx_glasses_vision_retraining_item_sample (organization_id,training_sample_id),
  KEY idx_glasses_vision_retraining_item_media (organization_id,training_media_id),
  CONSTRAINT fk_glasses_vision_retraining_item_org FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
  CONSTRAINT fk_glasses_vision_retraining_item_batch FOREIGN KEY (batch_id) REFERENCES glasses_vision_retraining_batches(id) ON DELETE CASCADE,
  CONSTRAINT fk_glasses_vision_retraining_item_candidate FOREIGN KEY (mined_candidate_id) REFERENCES glasses_vision_mined_candidates(id) ON DELETE RESTRICT,
  CONSTRAINT fk_glasses_vision_retraining_item_error FOREIGN KEY (production_error_id) REFERENCES glasses_vision_production_errors(id) ON DELETE RESTRICT,
  CONSTRAINT fk_glasses_vision_retraining_item_sample FOREIGN KEY (training_sample_id) REFERENCES glasses_vision_training_samples(id) ON DELETE SET NULL,
  CONSTRAINT fk_glasses_vision_retraining_item_media FOREIGN KEY (training_media_id) REFERENCES glasses_vision_training_media(id) ON DELETE SET NULL,
  CONSTRAINT fk_glasses_vision_retraining_item_reviewer FOREIGN KEY (reviewed_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
