CREATE TABLE IF NOT EXISTS glasses_training_programs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  organization_id BIGINT UNSIGNED NOT NULL,
  public_id VARCHAR(80) NOT NULL,
  name VARCHAR(180) NOT NULL,
  description VARCHAR(1200) NULL,
  mode ENUM('training','shadow','production_preflight') NOT NULL DEFAULT 'training',
  location_id BIGINT UNSIGNED NULL,
  station_id BIGINT UNSIGNED NULL,
  status ENUM('draft','active','paused','archived') NOT NULL DEFAULT 'draft',
  requirements_json JSON NULL,
  created_by BIGINT UNSIGNED NOT NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uq_glasses_training_program_public (organization_id,public_id),
  KEY idx_glasses_training_program_scope (organization_id,location_id,station_id,status),
  CONSTRAINT fk_glasses_training_program_org FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
  CONSTRAINT fk_glasses_training_program_location FOREIGN KEY (location_id) REFERENCES locations(id) ON DELETE SET NULL,
  CONSTRAINT fk_glasses_training_program_station FOREIGN KEY (station_id) REFERENCES kds_stations(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS glasses_training_assignments (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  organization_id BIGINT UNSIGNED NOT NULL,
  public_id VARCHAR(80) NOT NULL,
  program_id BIGINT UNSIGNED NOT NULL,
  training_assignment_id BIGINT UNSIGNED NULL,
  user_id BIGINT UNSIGNED NOT NULL,
  device_id BIGINT UNSIGNED NULL,
  location_id BIGINT UNSIGNED NULL,
  station_id BIGINT UNSIGNED NULL,
  supervisor_user_id BIGINT UNSIGNED NULL,
  mode ENUM('training','shadow','production_preflight') NOT NULL DEFAULT 'training',
  status ENUM('assigned','active','completed','cancelled') NOT NULL DEFAULT 'assigned',
  assigned_by BIGINT UNSIGNED NOT NULL,
  assigned_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  due_at DATETIME(6) NULL,
  completed_at DATETIME(6) NULL,
  notes VARCHAR(1200) NULL,
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uq_glasses_training_assignment_public (organization_id,public_id),
  KEY idx_glasses_training_assignment_user (organization_id,user_id,status),
  KEY idx_glasses_training_assignment_device (organization_id,device_id,status),
  CONSTRAINT fk_glasses_training_assignment_org FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
  CONSTRAINT fk_glasses_training_assignment_program FOREIGN KEY (program_id) REFERENCES glasses_training_programs(id) ON DELETE CASCADE,
  CONSTRAINT fk_glasses_training_assignment_generic FOREIGN KEY (training_assignment_id) REFERENCES training_assignments(id) ON DELETE SET NULL,
  CONSTRAINT fk_glasses_training_assignment_user FOREIGN KEY (user_id) REFERENCES users(id),
  CONSTRAINT fk_glasses_training_assignment_device FOREIGN KEY (device_id) REFERENCES glasses_devices(id) ON DELETE SET NULL,
  CONSTRAINT fk_glasses_training_assignment_location FOREIGN KEY (location_id) REFERENCES locations(id) ON DELETE SET NULL,
  CONSTRAINT fk_glasses_training_assignment_station FOREIGN KEY (station_id) REFERENCES kds_stations(id) ON DELETE SET NULL,
  CONSTRAINT fk_glasses_training_assignment_supervisor FOREIGN KEY (supervisor_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS glasses_training_sessions (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  organization_id BIGINT UNSIGNED NOT NULL,
  public_id VARCHAR(80) NOT NULL,
  assignment_id BIGINT UNSIGNED NOT NULL,
  user_id BIGINT UNSIGNED NOT NULL,
  device_id BIGINT UNSIGNED NOT NULL,
  location_id BIGINT UNSIGNED NULL,
  station_id BIGINT UNSIGNED NULL,
  supervisor_user_id BIGINT UNSIGNED NULL,
  mode ENUM('training','shadow','production_preflight') NOT NULL,
  status ENUM('active','completed','cancelled','interrupted') NOT NULL DEFAULT 'active',
  started_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  ended_at DATETIME(6) NULL,
  end_reason VARCHAR(500) NULL,
  context_json JSON NULL,
  created_by BIGINT UNSIGNED NOT NULL,
  active_device_id BIGINT UNSIGNED GENERATED ALWAYS AS (CASE WHEN status='active' THEN device_id ELSE NULL END) STORED,
  active_user_id BIGINT UNSIGNED GENERATED ALWAYS AS (CASE WHEN status='active' THEN user_id ELSE NULL END) STORED,
  PRIMARY KEY (id),
  UNIQUE KEY uq_glasses_training_session_public (organization_id,public_id),
  UNIQUE KEY uq_glasses_training_session_active_device (organization_id,active_device_id),
  UNIQUE KEY uq_glasses_training_session_active_user (organization_id,active_user_id),
  KEY idx_glasses_training_session_user (organization_id,user_id,status,started_at),
  KEY idx_glasses_training_session_device (organization_id,device_id,status,started_at),
  CONSTRAINT fk_glasses_training_session_org FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
  CONSTRAINT fk_glasses_training_session_assignment FOREIGN KEY (assignment_id) REFERENCES glasses_training_assignments(id) ON DELETE CASCADE,
  CONSTRAINT fk_glasses_training_session_user FOREIGN KEY (user_id) REFERENCES users(id),
  CONSTRAINT fk_glasses_training_session_device FOREIGN KEY (device_id) REFERENCES glasses_devices(id),
  CONSTRAINT fk_glasses_training_session_location FOREIGN KEY (location_id) REFERENCES locations(id) ON DELETE SET NULL,
  CONSTRAINT fk_glasses_training_session_station FOREIGN KEY (station_id) REFERENCES kds_stations(id) ON DELETE SET NULL,
  CONSTRAINT fk_glasses_training_session_supervisor FOREIGN KEY (supervisor_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
