-- Gelato Vision Lab V8 Section 4 — Adaptive Confidence & Decision Policy
SET NAMES utf8mb4;

CREATE TABLE glasses_vision_confidence_policies (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  organization_id BIGINT UNSIGNED NOT NULL,
  public_id VARCHAR(80) NOT NULL,
  policy_key VARCHAR(160) NOT NULL,
  detector_name VARCHAR(120) NOT NULL,
  package_id BIGINT UNSIGNED NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'draft',
  hard_floor DECIMAL(5,4) NOT NULL DEFAULT 0.5000,
  default_threshold DECIMAL(5,4) NOT NULL,
  class_rules_json JSON NOT NULL,
  context_rules_json JSON NOT NULL,
  guardrails_json JSON NOT NULL,
  policy_hash CHAR(64) NOT NULL,
  created_by BIGINT UNSIGNED NULL,
  activated_by BIGINT UNSIGNED NULL,
  activated_at DATETIME(6) NULL,
  retired_at DATETIME(6) NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uq_glasses_vision_conf_policy_public (organization_id,public_id),
  UNIQUE KEY uq_glasses_vision_conf_policy_identity (organization_id,policy_key,policy_hash),
  KEY idx_glasses_vision_conf_policy_scope (organization_id,detector_name,package_id,status,created_at),
  CONSTRAINT fk_glasses_vision_conf_policy_org FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
  CONSTRAINT fk_glasses_vision_conf_policy_package FOREIGN KEY (package_id) REFERENCES glasses_vision_model_packages(id) ON DELETE SET NULL,
  CONSTRAINT fk_glasses_vision_conf_policy_creator FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_glasses_vision_conf_policy_activator FOREIGN KEY (activated_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE glasses_vision_confidence_policy_events (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  organization_id BIGINT UNSIGNED NOT NULL,
  policy_id BIGINT UNSIGNED NOT NULL,
  event_type VARCHAR(32) NOT NULL,
  event_hash CHAR(64) NOT NULL,
  evidence_json JSON NOT NULL,
  actor_user_id BIGINT UNSIGNED NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uq_glasses_vision_conf_policy_event_hash (organization_id,event_hash),
  KEY idx_glasses_vision_conf_policy_event (organization_id,policy_id,id),
  CONSTRAINT fk_glasses_vision_conf_policy_event_org FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
  CONSTRAINT fk_glasses_vision_conf_policy_event_policy FOREIGN KEY (policy_id) REFERENCES glasses_vision_confidence_policies(id) ON DELETE CASCADE,
  CONSTRAINT fk_glasses_vision_conf_policy_event_actor FOREIGN KEY (actor_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE glasses_vision_confidence_decisions (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  organization_id BIGINT UNSIGNED NOT NULL,
  public_id VARCHAR(80) NOT NULL,
  policy_id BIGINT UNSIGNED NOT NULL,
  device_id BIGINT UNSIGNED NOT NULL,
  build_session_id BIGINT UNSIGNED NOT NULL,
  package_id BIGINT UNSIGNED NULL,
  context_drift_analysis_id BIGINT UNSIGNED NULL,
  calibration_selection_id BIGINT UNSIGNED NULL,
  decision_key CHAR(64) NOT NULL,
  detector_name VARCHAR(120) NOT NULL,
  normalized_label VARCHAR(160) NOT NULL,
  component_key VARCHAR(190) NULL,
  model_confidence DECIMAL(6,5) NOT NULL,
  label_floor DECIMAL(5,4) NOT NULL,
  effective_threshold DECIMAL(5,4) NOT NULL,
  decision VARCHAR(32) NOT NULL,
  evidence_json JSON NOT NULL,
  decision_hash CHAR(64) NOT NULL,
  created_by BIGINT UNSIGNED NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uq_glasses_vision_conf_decision_public (organization_id,public_id),
  UNIQUE KEY uq_glasses_vision_conf_decision_key (organization_id,decision_key),
  KEY idx_glasses_vision_conf_decision_scope (organization_id,detector_name,decision,created_at),
  CONSTRAINT fk_glasses_vision_conf_decision_org FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
  CONSTRAINT fk_glasses_vision_conf_decision_policy FOREIGN KEY (policy_id) REFERENCES glasses_vision_confidence_policies(id) ON DELETE RESTRICT,
  CONSTRAINT fk_glasses_vision_conf_decision_device FOREIGN KEY (device_id) REFERENCES glasses_devices(id) ON DELETE CASCADE,
  CONSTRAINT fk_glasses_vision_conf_decision_build FOREIGN KEY (build_session_id) REFERENCES glasses_build_sessions(id) ON DELETE CASCADE,
  CONSTRAINT fk_glasses_vision_conf_decision_package FOREIGN KEY (package_id) REFERENCES glasses_vision_model_packages(id) ON DELETE SET NULL,
  CONSTRAINT fk_glasses_vision_conf_decision_analysis FOREIGN KEY (context_drift_analysis_id) REFERENCES glasses_vision_context_drift_analyses(id) ON DELETE SET NULL,
  CONSTRAINT fk_glasses_vision_conf_decision_calibration FOREIGN KEY (calibration_selection_id) REFERENCES glasses_vision_calibration_selections(id) ON DELETE SET NULL,
  CONSTRAINT fk_glasses_vision_conf_decision_creator FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
