-- Gelato Vision Lab V7 Section 1 — Production Error & Outcome Ledger
SET NAMES utf8mb4;

CREATE TABLE glasses_vision_production_errors (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  organization_id BIGINT UNSIGNED NOT NULL,
  public_id VARCHAR(80) NOT NULL,
  event_key VARCHAR(190) NOT NULL,
  event_hash CHAR(64) NOT NULL,
  source_type VARCHAR(40) NOT NULL,
  error_type VARCHAR(40) NOT NULL,
  outcome VARCHAR(40) NOT NULL,
  build_session_id BIGINT UNSIGNED NULL,
  observation_id BIGINT UNSIGNED NULL,
  correction_id BIGINT UNSIGNED NULL,
  device_id BIGINT UNSIGNED NULL,
  location_id BIGINT UNSIGNED NULL,
  station_id BIGINT UNSIGNED NULL,
  menu_item_id BIGINT UNSIGNED NULL,
  model_package_id BIGINT UNSIGNED NULL,
  rollout_id BIGINT UNSIGNED NULL,
  predicted_component_key VARCHAR(160) NULL,
  expected_component_key VARCHAR(160) NULL,
  confidence DECIMAL(6,5) NULL,
  context_json JSON NOT NULL,
  actor_user_id BIGINT UNSIGNED NULL,
  occurred_at DATETIME(6) NOT NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uq_glasses_vision_prod_error_public (organization_id,public_id),
  UNIQUE KEY uq_glasses_vision_prod_error_event (organization_id,event_key),
  KEY idx_glasses_vision_prod_error_model (organization_id,model_package_id,error_type,occurred_at),
  KEY idx_glasses_vision_prod_error_scope (organization_id,location_id,station_id,menu_item_id,occurred_at),
  KEY idx_glasses_vision_prod_error_observation (organization_id,observation_id),
  KEY idx_glasses_vision_prod_error_correction (organization_id,correction_id),
  CONSTRAINT fk_glasses_vision_prod_error_org FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
  CONSTRAINT fk_glasses_vision_prod_error_session FOREIGN KEY (build_session_id) REFERENCES glasses_build_sessions(id) ON DELETE SET NULL,
  CONSTRAINT fk_glasses_vision_prod_error_observation FOREIGN KEY (observation_id) REFERENCES glasses_build_observations(id) ON DELETE SET NULL,
  CONSTRAINT fk_glasses_vision_prod_error_correction FOREIGN KEY (correction_id) REFERENCES glasses_observation_corrections(id) ON DELETE SET NULL,
  CONSTRAINT fk_glasses_vision_prod_error_device FOREIGN KEY (device_id) REFERENCES glasses_devices(id) ON DELETE SET NULL,
  CONSTRAINT fk_glasses_vision_prod_error_location FOREIGN KEY (location_id) REFERENCES locations(id) ON DELETE SET NULL,
  CONSTRAINT fk_glasses_vision_prod_error_station FOREIGN KEY (station_id) REFERENCES kds_stations(id) ON DELETE SET NULL,
  CONSTRAINT fk_glasses_vision_prod_error_menu_item FOREIGN KEY (menu_item_id) REFERENCES menu_items(id) ON DELETE SET NULL,
  CONSTRAINT fk_glasses_vision_prod_error_package FOREIGN KEY (model_package_id) REFERENCES glasses_vision_model_packages(id) ON DELETE SET NULL,
  CONSTRAINT fk_glasses_vision_prod_error_rollout FOREIGN KEY (rollout_id) REFERENCES glasses_vision_model_rollouts(id) ON DELETE SET NULL,
  CONSTRAINT fk_glasses_vision_prod_error_actor FOREIGN KEY (actor_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
