-- Gelato Restaurant AI: wholesale gelato pipeline + recipe intelligence
SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS wholesale_leads (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  organization_id BIGINT UNSIGNED NOT NULL,
  public_id VARCHAR(80) NOT NULL,
  business_name VARCHAR(200) NOT NULL,
  contact_name VARCHAR(180) NOT NULL,
  email VARCHAR(254) NOT NULL,
  phone VARCHAR(50) NULL,
  website VARCHAR(500) NULL,
  business_type VARCHAR(80) NULL,
  location_text VARCHAR(300) NULL,
  estimated_monthly_volume VARCHAR(120) NULL,
  order_frequency VARCHAR(120) NULL,
  package_sizes_json JSON NULL,
  flavors_interest TEXT NULL,
  private_label_interest TINYINT(1) NOT NULL DEFAULT 0,
  freezer_capacity VARCHAR(120) NULL,
  fulfillment_preference VARCHAR(80) NULL,
  desired_start_date DATE NULL,
  current_supplier VARCHAR(200) NULL,
  notes TEXT NULL,
  source VARCHAR(80) NOT NULL DEFAULT 'public_wholesale_form',
  pipeline_stage VARCHAR(40) NOT NULL DEFAULT 'new',
  estimated_value DECIMAL(12,2) NULL,
  probability_percent TINYINT UNSIGNED NOT NULL DEFAULT 10,
  assigned_to BIGINT UNSIGNED NULL,
  next_followup_at DATETIME(6) NULL,
  last_contact_at DATETIME(6) NULL,
  won_at DATETIME(6) NULL,
  lost_at DATETIME(6) NULL,
  loss_reason VARCHAR(500) NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  archived_at DATETIME(6) NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_wholesale_leads_org_public (organization_id, public_id),
  KEY idx_wholesale_leads_pipeline (organization_id, pipeline_stage, archived_at, updated_at),
  KEY idx_wholesale_leads_assigned (organization_id, assigned_to, next_followup_at),
  KEY idx_wholesale_leads_email (organization_id, email),
  CONSTRAINT fk_wholesale_leads_org FOREIGN KEY (organization_id) REFERENCES organizations(id),
  CONSTRAINT fk_wholesale_leads_assignee FOREIGN KEY (assigned_to) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS wholesale_lead_activities (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  organization_id BIGINT UNSIGNED NOT NULL,
  wholesale_lead_id BIGINT UNSIGNED NOT NULL,
  activity_type VARCHAR(50) NOT NULL DEFAULT 'note',
  summary VARCHAR(500) NOT NULL,
  details TEXT NULL,
  metadata_json JSON NULL,
  created_by BIGINT UNSIGNED NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  KEY idx_wholesale_activity_lead (wholesale_lead_id, created_at),
  KEY idx_wholesale_activity_org (organization_id, created_at),
  CONSTRAINT fk_wholesale_activity_org FOREIGN KEY (organization_id) REFERENCES organizations(id),
  CONSTRAINT fk_wholesale_activity_lead FOREIGN KEY (wholesale_lead_id) REFERENCES wholesale_leads(id) ON DELETE CASCADE,
  CONSTRAINT fk_wholesale_activity_user FOREIGN KEY (created_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS recipes (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  organization_id BIGINT UNSIGNED NOT NULL,
  public_id VARCHAR(80) NOT NULL,
  name VARCHAR(220) NOT NULL,
  category VARCHAR(100) NULL,
  description TEXT NULL,
  yield_quantity DECIMAL(10,2) NULL,
  yield_unit VARCHAR(80) NULL,
  ingredients_json JSON NULL,
  instructions_json JSON NULL,
  notes TEXT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  source_title VARCHAR(500) NULL,
  source_url VARCHAR(1000) NULL,
  source_domain VARCHAR(255) NULL,
  source_confidence DECIMAL(5,4) NULL,
  mapping_status VARCHAR(40) NOT NULL DEFAULT 'unmapped',
  mapping_notes TEXT NULL,
  mapped_at DATETIME(6) NULL,
  mapped_by BIGINT UNSIGNED NULL,
  created_by BIGINT UNSIGNED NULL,
  updated_by BIGINT UNSIGNED NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  archived_at DATETIME(6) NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_recipes_org_public (organization_id, public_id),
  KEY idx_recipes_org_status (organization_id, status, archived_at, updated_at),
  KEY idx_recipes_mapping (organization_id, mapping_status, updated_at),
  CONSTRAINT fk_recipes_org FOREIGN KEY (organization_id) REFERENCES organizations(id),
  CONSTRAINT fk_recipes_mapper FOREIGN KEY (mapped_by) REFERENCES users(id),
  CONSTRAINT fk_recipes_creator FOREIGN KEY (created_by) REFERENCES users(id),
  CONSTRAINT fk_recipes_updater FOREIGN KEY (updated_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS recipe_images (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  organization_id BIGINT UNSIGNED NOT NULL,
  recipe_id BIGINT UNSIGNED NOT NULL,
  file_id BIGINT UNSIGNED NOT NULL,
  image_role VARCHAR(40) NOT NULL DEFAULT 'source_recipe',
  is_primary TINYINT(1) NOT NULL DEFAULT 1,
  extracted_text LONGTEXT NULL,
  analysis_json JSON NULL,
  mapping_status VARCHAR(40) NOT NULL DEFAULT 'uploaded',
  mapped_source_url VARCHAR(1000) NULL,
  mapped_source_title VARCHAR(500) NULL,
  mapped_source_domain VARCHAR(255) NULL,
  mapped_confidence DECIMAL(5,4) NULL,
  created_by BIGINT UNSIGNED NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  KEY idx_recipe_images_recipe (recipe_id, is_primary, created_at),
  KEY idx_recipe_images_org (organization_id, created_at),
  CONSTRAINT fk_recipe_images_org FOREIGN KEY (organization_id) REFERENCES organizations(id),
  CONSTRAINT fk_recipe_images_recipe FOREIGN KEY (recipe_id) REFERENCES recipes(id) ON DELETE CASCADE,
  CONSTRAINT fk_recipe_images_file FOREIGN KEY (file_id) REFERENCES files(id),
  CONSTRAINT fk_recipe_images_creator FOREIGN KEY (created_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO permissions (permission_key, name, description, category) VALUES
  ('wholesale.view', 'View wholesale pipeline', 'View wholesale gelato leads, stages, activity, and projected value.', 'Wholesale'),
  ('wholesale.manage', 'Manage wholesale pipeline', 'Edit wholesale leads, move pipeline stages, assign follow-up, and record activity.', 'Wholesale'),
  ('wholesale.agent', 'Use wholesale Agent skills', 'Allow the private restaurant Agent to search and summarize wholesale pipeline records.', 'Wholesale'),
  ('recipes.view', 'View recipes', 'View the private recipe library and mapped online recipe sources.', 'Recipes'),
  ('recipes.edit', 'Edit recipes', 'Create and edit recipes, ingredients, instructions, yields, notes, and images.', 'Recipes'),
  ('recipes.ai_map', 'AI-map recipe images', 'Send uploaded recipe images to the configured AI provider to extract recipe details and map them to online recipe sources.', 'Recipes'),
  ('recipes.agent', 'Use recipe Agent skills', 'Allow the private restaurant Agent to search and reason over the recipe library.', 'Recipes')
ON DUPLICATE KEY UPDATE
  name = VALUES(name),
  description = VALUES(description),
  category = VALUES(category);
