-- Gelato Vision Lab V2 — User/Device Assignment, Training Missions & Dataset Governance
SET NAMES utf8mb4;

CREATE TABLE glasses_user_device_assignments (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  organization_id BIGINT UNSIGNED NOT NULL,
  public_id VARCHAR(80) NOT NULL,
  device_id BIGINT UNSIGNED NOT NULL,
  user_id BIGINT UNSIGNED NOT NULL,
  location_id BIGINT UNSIGNED NOT NULL,
  station_id BIGINT UNSIGNED NULL,
  assignment_role VARCHAR(40) NOT NULL DEFAULT 'operator',
  assignment_source VARCHAR(40) NOT NULL DEFAULT 'manual',
  assigned_by BIGINT UNSIGNED NULL,
  assigned_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  released_at DATETIME(6) NULL,
  release_reason VARCHAR(500) NULL,
  metadata_json JSON NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_glasses_user_device_assignment_public (organization_id,public_id),
  KEY idx_glasses_user_device_active (organization_id,device_id,released_at,assigned_at),
  KEY idx_glasses_user_assignment_user (organization_id,user_id,released_at,assigned_at),
  CONSTRAINT fk_glasses_user_assignment_org FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
  CONSTRAINT fk_glasses_user_assignment_device FOREIGN KEY (device_id) REFERENCES glasses_devices(id) ON DELETE CASCADE,
  CONSTRAINT fk_glasses_user_assignment_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_glasses_user_assignment_location FOREIGN KEY (location_id) REFERENCES locations(id) ON DELETE CASCADE,
  CONSTRAINT fk_glasses_user_assignment_station FOREIGN KEY (station_id) REFERENCES kds_stations(id) ON DELETE SET NULL,
  CONSTRAINT fk_glasses_user_assignment_actor FOREIGN KEY (assigned_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE glasses_vision_training_missions (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  organization_id BIGINT UNSIGNED NOT NULL,
  public_id VARCHAR(80) NOT NULL,
  title VARCHAR(190) NOT NULL,
  description VARCHAR(2000) NULL,
  mode VARCHAR(32) NOT NULL DEFAULT 'model_training',
  status VARCHAR(32) NOT NULL DEFAULT 'draft',
  source_type VARCHAR(40) NOT NULL DEFAULT 'manual',
  source_reference VARCHAR(190) NULL,
  location_id BIGINT UNSIGNED NULL,
  station_id BIGINT UNSIGNED NULL,
  assigned_user_id BIGINT UNSIGNED NULL,
  assigned_device_id BIGINT UNSIGNED NULL,
  target_samples INT UNSIGNED NOT NULL DEFAULT 0,
  target_positive INT UNSIGNED NOT NULL DEFAULT 0,
  target_negative INT UNSIGNED NOT NULL DEFAULT 0,
  target_hard_examples INT UNSIGNED NOT NULL DEFAULT 0,
  target_conditions_json JSON NULL,
  created_by BIGINT UNSIGNED NOT NULL,
  due_at DATETIME(6) NULL,
  started_at DATETIME(6) NULL,
  completed_at DATETIME(6) NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uq_glasses_vision_training_mission_public (organization_id,public_id),
  KEY idx_glasses_vision_training_mission_status (organization_id,status,due_at),
  KEY idx_glasses_vision_training_mission_user (organization_id,assigned_user_id,status),
  CONSTRAINT fk_glasses_vision_training_mission_org FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
  CONSTRAINT fk_glasses_vision_training_mission_location FOREIGN KEY (location_id) REFERENCES locations(id) ON DELETE SET NULL,
  CONSTRAINT fk_glasses_vision_training_mission_station FOREIGN KEY (station_id) REFERENCES kds_stations(id) ON DELETE SET NULL,
  CONSTRAINT fk_glasses_vision_training_mission_user FOREIGN KEY (assigned_user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_glasses_vision_training_mission_device FOREIGN KEY (assigned_device_id) REFERENCES glasses_devices(id) ON DELETE SET NULL,
  CONSTRAINT fk_glasses_vision_training_mission_creator FOREIGN KEY (created_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE glasses_vision_training_samples (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  organization_id BIGINT UNSIGNED NOT NULL,
  public_id VARCHAR(80) NOT NULL,
  mission_id BIGINT UNSIGNED NULL,
  observation_id BIGINT UNSIGNED NULL,
  source_type VARCHAR(40) NOT NULL,
  source_reference VARCHAR(190) NULL,
  wearer_assignment_id BIGINT UNSIGNED NULL,
  operator_user_id BIGINT UNSIGNED NULL,
  annotator_user_id BIGINT UNSIGNED NULL,
  reviewer_user_id BIGINT UNSIGNED NULL,
  adjudicator_user_id BIGINT UNSIGNED NULL,
  review_status VARCHAR(32) NOT NULL DEFAULT 'pending',
  review_outcome VARCHAR(32) NULL,
  canonical_label VARCHAR(190) NULL,
  annotation_json JSON NULL,
  provenance_json JSON NULL,
  notes VARCHAR(1000) NULL,
  reviewed_at DATETIME(6) NULL,
  created_by BIGINT UNSIGNED NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uq_glasses_vision_training_sample_public (organization_id,public_id),
  UNIQUE KEY uq_glasses_vision_training_observation (organization_id,observation_id),
  KEY idx_glasses_vision_training_sample_queue (organization_id,review_status,created_at),
  KEY idx_glasses_vision_training_sample_mission (organization_id,mission_id,review_status),
  CONSTRAINT fk_glasses_vision_training_sample_org FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
  CONSTRAINT fk_glasses_vision_training_sample_mission FOREIGN KEY (mission_id) REFERENCES glasses_vision_training_missions(id) ON DELETE SET NULL,
  CONSTRAINT fk_glasses_vision_training_sample_observation FOREIGN KEY (observation_id) REFERENCES glasses_build_observations(id) ON DELETE CASCADE,
  CONSTRAINT fk_glasses_vision_training_sample_wearer FOREIGN KEY (wearer_assignment_id) REFERENCES glasses_user_device_assignments(id) ON DELETE SET NULL,
  CONSTRAINT fk_glasses_vision_training_sample_operator FOREIGN KEY (operator_user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_glasses_vision_training_sample_annotator FOREIGN KEY (annotator_user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_glasses_vision_training_sample_reviewer FOREIGN KEY (reviewer_user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_glasses_vision_training_sample_adjudicator FOREIGN KEY (adjudicator_user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_glasses_vision_training_sample_creator FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE glasses_vision_dataset_versions (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  organization_id BIGINT UNSIGNED NOT NULL,
  public_id VARCHAR(80) NOT NULL,
  name VARCHAR(190) NOT NULL,
  version_label VARCHAR(80) NOT NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'draft',
  parent_dataset_id BIGINT UNSIGNED NULL,
  mission_id BIGINT UNSIGNED NULL,
  dataset_hash CHAR(64) NULL,
  row_count INT UNSIGNED NOT NULL DEFAULT 0,
  class_count INT UNSIGNED NOT NULL DEFAULT 0,
  quality_json JSON NULL,
  manifest_json JSON NULL,
  created_by BIGINT UNSIGNED NOT NULL,
  frozen_by BIGINT UNSIGNED NULL,
  frozen_at DATETIME(6) NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uq_glasses_vision_dataset_public (organization_id,public_id),
  UNIQUE KEY uq_glasses_vision_dataset_version (organization_id,name,version_label),
  CONSTRAINT fk_glasses_vision_dataset_org FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
  CONSTRAINT fk_glasses_vision_dataset_parent FOREIGN KEY (parent_dataset_id) REFERENCES glasses_vision_dataset_versions(id) ON DELETE SET NULL,
  CONSTRAINT fk_glasses_vision_dataset_mission FOREIGN KEY (mission_id) REFERENCES glasses_vision_training_missions(id) ON DELETE SET NULL,
  CONSTRAINT fk_glasses_vision_dataset_creator FOREIGN KEY (created_by) REFERENCES users(id),
  CONSTRAINT fk_glasses_vision_dataset_freezer FOREIGN KEY (frozen_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE glasses_vision_dataset_items (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  organization_id BIGINT UNSIGNED NOT NULL,
  dataset_id BIGINT UNSIGNED NOT NULL,
  sample_id BIGINT UNSIGNED NOT NULL,
  split_name VARCHAR(16) NOT NULL DEFAULT 'train',
  class_label VARCHAR(190) NULL,
  source_hash CHAR(64) NOT NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uq_glasses_vision_dataset_item (dataset_id,sample_id),
  KEY idx_glasses_vision_dataset_split (organization_id,dataset_id,split_name),
  CONSTRAINT fk_glasses_vision_dataset_item_org FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
  CONSTRAINT fk_glasses_vision_dataset_item_dataset FOREIGN KEY (dataset_id) REFERENCES glasses_vision_dataset_versions(id) ON DELETE CASCADE,
  CONSTRAINT fk_glasses_vision_dataset_item_sample FOREIGN KEY (sample_id) REFERENCES glasses_vision_training_samples(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
