-- Baseline permission and allergen seed data.
-- Replace organization IDs and owner credentials through the installation workflow.

INSERT INTO permissions (permission_key, name, description, category) VALUES
('dashboard.view','View dashboard','View permitted training dashboards.','Dashboard'),
('agent.owner_view','View owner system agent','View organization-wide training and resume intelligence.','Agent'),
('agent.employee_view','Use employee training agent','Use the employee-scoped menu training agent.','Agent'),
('users.view','View accounts','View user accounts.','Accounts'),
('users.create','Create accounts','Create user accounts and invitations.','Accounts'),
('users.edit','Edit accounts','Edit account profiles and status.','Accounts'),
('users.suspend','Suspend accounts','Suspend and reactivate user access.','Accounts'),
('users.assign_roles','Assign roles','Assign account types to users.','Accounts'),
('roles.view','View account types','View roles and permissions.','Permissions'),
('roles.create','Create account types','Create custom organization roles.','Permissions'),
('roles.edit','Edit account types','Edit custom roles.','Permissions'),
('roles.assign_permissions','Assign permissions','Grant permissions to organization roles.','Permissions'),
('training.self_view','View own training','View personal assignments, scores, and certifications.','Training'),
('training.assign','Assign training','Assign training requirements to users.','Training'),
('training.view_employee_progress','View employee progress','View progress for assigned employees.','Training'),
('training.view_all_progress','View all progress','View organization-wide training records.','Training'),
('training.issue_certifications','Issue certifications','Issue and revoke training certifications.','Training'),
('resumes.view','View resumes','View resume submissions.','Hiring'),
('jobs.view','View jobs','View job openings and publishing status.','Hiring'),
('jobs.create','Create jobs','Create restaurant job openings.','Hiring'),
('jobs.edit','Edit jobs','Edit job content and requirements.','Hiring'),
('jobs.publish','Publish jobs','Publish, pause, and archive job openings.','Hiring'),
('resumes.review','Review resumes','Change resume status and reviewer assignment.','Hiring'),
('resumes.add_notes','Add resume notes','Add private hiring notes.','Hiring'),
('resumes.convert_to_employee','Convert applicants','Create employee accounts from approved resumes.','Hiring'),
('forms.view','View forms','View form definitions and versions.','Content'),
('forms.create','Create forms','Create organization forms.','Content'),
('forms.edit','Edit forms','Edit and publish form versions.','Content'),
('public_pages.view','View public pages','View public page configuration.','Content'),
('public_pages.edit','Edit public pages','Edit and publish public page sections.','Content'),
('brand.view','View brand settings','View organization identity settings.','Organization'),
('brand.edit','Edit brand settings','Edit branding and public contact settings.','Organization'),
('reports.view','View reports','View training and hiring reports.','Organization'),
('settings.self_edit','Edit own profile','Edit personal profile settings.','Organization'),
('settings.organization_edit','Edit organization settings','Edit organization-wide settings.','Organization'),
('audit.view','View audit log','View privileged activity history.','Organization');

INSERT INTO allergen_tags (code, name, description, is_major_us_allergen) VALUES
('milk','Milk','Milk and milk-derived ingredients.',1),
('egg','Egg','Egg and egg-derived ingredients.',1),
('fish','Fish','Fish and fish-derived ingredients.',1),
('crustacean_shellfish','Crustacean Shellfish','Crab, lobster, shrimp, and related shellfish.',1),
('tree_nuts','Tree Nuts','Tree nuts and tree-nut-derived ingredients.',1),
('peanuts','Peanuts','Peanuts and peanut-derived ingredients.',1),
('wheat','Wheat','Wheat and wheat-derived ingredients.',1),
('soy','Soybeans','Soy and soy-derived ingredients.',1),
('sesame','Sesame','Sesame and sesame-derived ingredients.',1);
