<?php
declare(strict_types=1);
require_once __DIR__.'/purchasing-core.php';

function purchasing_save_vendor_item(PDO $pdo,int $org,array $in,int $uid):array{
    $vendor=purchasing_vendor($pdo,$org,trim((string)($in['vendorId']??'')));if(!$vendor)throw new InvalidArgumentException('Vendor not found.');
    $q=$pdo->prepare('SELECT * FROM inventory_items WHERE organization_id=? AND public_id=? AND archived_at IS NULL LIMIT 1');$q->execute([$org,trim((string)($in['inventoryId']??''))]);$item=$q->fetch();if(!$item)throw new InvalidArgumentException('Inventory item not found.');
    $public=trim((string)($in['id']??''));$price=($in['pricePerPack']??'')!==''?(float)$in['pricePerPack']:null;$pack=($in['packSize']??'')!==''?(float)$in['packSize']:null;$preferred=!empty($in['preferred'])?1:0;
    if($preferred)$pdo->prepare('UPDATE inventory_vendor_items SET is_preferred=0 WHERE organization_id=? AND inventory_item_id=?')->execute([$org,(int)$item['id']]);
    if($public===''){$public=purchasing_public_id('vitem');$pdo->prepare('INSERT INTO inventory_vendor_items (organization_id,inventory_item_id,vendor_id,public_id,vendor_sku,vendor_item_name,pack_size,pack_unit,units_per_pack,price_per_pack,price_effective_at,is_preferred,notes,created_by,updated_by) VALUES (?,?,?,?,?,?,?,?,?,?,NOW(6),?,?,?,?)')->execute([$org,(int)$item['id'],(int)$vendor['id'],$public,trim((string)($in['vendorSku']??''))?:null,trim((string)($in['vendorItemName']??''))?:$item['name'],$pack,trim((string)($in['packUnit']??''))?:$item['base_unit'],($in['unitsPerPack']??'')!==''?(float)$in['unitsPerPack']:null,$price,$preferred,trim((string)($in['notes']??''))?:null,$uid,$uid]);}
    else{$pdo->prepare('UPDATE inventory_vendor_items SET vendor_sku=?,vendor_item_name=?,pack_size=?,pack_unit=?,units_per_pack=?,price_per_pack=?,price_effective_at=NOW(6),is_preferred=?,notes=?,updated_by=?,updated_at=NOW(6) WHERE organization_id=? AND public_id=?')->execute([trim((string)($in['vendorSku']??''))?:null,trim((string)($in['vendorItemName']??''))?:$item['name'],$pack,trim((string)($in['packUnit']??''))?:$item['base_unit'],($in['unitsPerPack']??'')!==''?(float)$in['unitsPerPack']:null,$price,$preferred,trim((string)($in['notes']??''))?:null,$uid,$org,$public]);}
    if($price!==null)$pdo->prepare("INSERT INTO vendor_price_history (organization_id,vendor_id,inventory_item_id,vendor_item_id,price_per_pack,pack_size,unit,source_type,source_public_id,created_by) SELECT organization_id,vendor_id,inventory_item_id,id,price_per_pack,pack_size,pack_unit,'catalog',public_id,? FROM inventory_vendor_items WHERE organization_id=? AND public_id=?")->execute([$uid,$org,$public]);
    if($preferred){$unitCost=$price!==null&&$pack!==null&&$pack>0?$price/$pack:null;$pdo->prepare('UPDATE inventory_items SET vendor_name=?,vendor_sku=?,unit_cost=COALESCE(?,unit_cost),updated_by=?,updated_at=NOW(6) WHERE organization_id=? AND id=?')->execute([(string)$vendor['name'],trim((string)($in['vendorSku']??''))?:null,$unitCost,$uid,$org,(int)$item['id']]);}
    foreach(purchasing_vendor_catalog($pdo,$org,(string)$vendor['public_id']) as $row)if((string)$row['public_id']===$public)return $row;return [];
}
function purchasing_suggestions(PDO $pdo,int $org):array{
    $q=$pdo->prepare("SELECT i.*,COALESCE(MAX(CASE WHEN p.plan_date BETWEEN CURDATE() AND DATE_ADD(CURDATE(),INTERVAL 7 DAY) AND p.status IN ('draft','published') THEN f.restock_quantity ELSE 0 END),0) forecast_restock FROM inventory_items i LEFT JOIN inventory_forecasts f ON f.inventory_item_id=i.id LEFT JOIN prep_plans p ON p.id=f.plan_id WHERE i.organization_id=? AND i.archived_at IS NULL AND i.status='active' GROUP BY i.id ORDER BY i.name");$q->execute([$org]);$rows=[];
    $map=$pdo->prepare("SELECT vi.*,v.public_id vendor_public_id,v.name vendor_name,v.minimum_order_amount,v.lead_time_days,v.delivery_days_json,v.cutoff_time FROM inventory_vendor_items vi JOIN vendors v ON v.id=vi.vendor_id WHERE vi.organization_id=? AND vi.inventory_item_id=? AND vi.archived_at IS NULL AND vi.status='active' AND v.status='active' ORDER BY vi.is_preferred DESC,vi.price_per_pack IS NULL,vi.price_per_pack LIMIT 1");
    $ordered=$pdo->prepare("SELECT COALESCE(SUM(GREATEST(0,poi.ordered_base_quantity-poi.received_base_quantity)),0) FROM purchase_order_items poi JOIN purchase_orders po ON po.id=poi.purchase_order_id AND po.organization_id=poi.organization_id WHERE poi.organization_id=? AND poi.inventory_item_id=? AND po.archived_at IS NULL AND po.status IN ('draft','submitted','partially_received')");
    foreach($q->fetchAll() as $r){$parNeed=$r['par_level']!==null?max(0,(float)$r['par_level']-(float)$r['on_hand_quantity']):0;$reorderNeed=($r['reorder_point']!==null&&(float)$r['on_hand_quantity']<=(float)$r['reorder_point'])?max($parNeed,(float)$r['reorder_point']-(float)$r['on_hand_quantity']):0;$gross=max($parNeed,$reorderNeed,(float)$r['forecast_restock']);$ordered->execute([$org,(int)$r['id']]);$openQty=(float)$ordered->fetchColumn();$need=max(0,$gross-$openQty);if($need<=0)continue;$map->execute([$org,(int)$r['id']]);$m=$map->fetch()?:null;$pack=$m&&$m['pack_size']!==null?(float)$m['pack_size']:0;$rows[]=['inventoryId'=>$r['public_id'],'name'=>$r['name'],'unit'=>$r['base_unit'],'onHand'=>(float)$r['on_hand_quantity'],'par'=>$r['par_level']!==null?(float)$r['par_level']:null,'forecastRestock'=>(float)$r['forecast_restock'],'openOrderQuantity'=>$openQty,'grossNeedQuantity'=>$gross,'needQuantity'=>$need,'vendor'=>$m?['id'=>$m['vendor_public_id'],'name'=>$m['vendor_name'],'vendorItemId'=>$m['public_id'],'sku'=>$m['vendor_sku'],'packSize'=>$pack,'packUnit'=>$m['pack_unit'],'pricePerPack'=>$m['price_per_pack']!==null?(float)$m['price_per_pack']:null,'preferred'=>(bool)$m['is_preferred'],'minimumOrderAmount'=>$m['minimum_order_amount']!==null?(float)$m['minimum_order_amount']:null,'leadTimeDays'=>(int)$m['lead_time_days'],'deliveryDays'=>$m['delivery_days_json']?json_decode((string)$m['delivery_days_json'],true):[],'cutoffTime'=>$m['cutoff_time']]:null,'suggestedPacks'=>$pack>0?(float)ceil($need/$pack):$need];}
    usort($rows,static fn($a,$b)=>$b['needQuantity']<=>$a['needQuantity']);return $rows;
}
function purchasing_orders(PDO $pdo,int $org,string $status=''):array{$where='po.organization_id=? AND po.archived_at IS NULL';$p=[$org];if($status!==''){$where.=' AND po.status=?';$p[]=$status;}$q=$pdo->prepare("SELECT po.*,v.name vendor_name,(SELECT COUNT(*) FROM purchase_order_items x WHERE x.purchase_order_id=po.id) item_count FROM purchase_orders po JOIN vendors v ON v.id=po.vendor_id WHERE {$where} ORDER BY FIELD(po.status,'draft','submitted','partially_received','received','cancelled'),COALESCE(po.expected_delivery_date,'9999-12-31'),po.created_at DESC");$q->execute($p);return $q->fetchAll();}
function purchasing_order(PDO $pdo,int $org,string $publicId):?array{$q=$pdo->prepare('SELECT po.*,v.name vendor_name,v.public_id vendor_public_id,v.minimum_order_amount,v.lead_time_days,v.cutoff_time FROM purchase_orders po JOIN vendors v ON v.id=po.vendor_id WHERE po.organization_id=? AND po.public_id=? AND po.archived_at IS NULL LIMIT 1');$q->execute([$org,$publicId]);$po=$q->fetch();if(!$po)return null;$i=$pdo->prepare('SELECT poi.*,inv.public_id inventory_public_id,inv.name inventory_name FROM purchase_order_items poi JOIN inventory_items inv ON inv.id=poi.inventory_item_id WHERE poi.organization_id=? AND poi.purchase_order_id=? ORDER BY poi.id');$i->execute([$org,(int)$po['id']]);$po['items']=$i->fetchAll();$e=$pdo->prepare('SELECT event_type,summary,created_at FROM purchase_order_events WHERE organization_id=? AND purchase_order_id=? ORDER BY id DESC LIMIT 40');$e->execute([$org,(int)$po['id']]);$po['events']=$e->fetchAll();$po['documents']=purchasing_documents_for_order($pdo,$org,(int)$po['id']);return $po;}
function purchasing_recalc(PDO $pdo,int $org,int $poId):void{$q=$pdo->prepare('SELECT COALESCE(SUM(line_total),0) FROM purchase_order_items WHERE organization_id=? AND purchase_order_id=?');$q->execute([$org,$poId]);$subtotal=(float)$q->fetchColumn();$pdo->prepare('UPDATE purchase_orders SET subtotal=?,total_amount=?+tax_amount+shipping_amount,updated_at=NOW(6) WHERE organization_id=? AND id=?')->execute([$subtotal,$subtotal,$org,$poId]);}
function purchasing_create_order(PDO $pdo,int $org,string $vendorPublic,array $lines,int $uid,?string $expected=null,string $notes=''):array{
    $vendor=purchasing_vendor($pdo,$org,$vendorPublic);if(!$vendor)throw new InvalidArgumentException('Vendor not found.');if(!$lines)throw new InvalidArgumentException('At least one purchase-order line is required.');$public=purchasing_public_id('po');$number='PO-'.date('ymd').'-'.strtoupper(substr(bin2hex(random_bytes(4)),0,6));$pdo->beginTransaction();try{$pdo->prepare('INSERT INTO purchase_orders (organization_id,public_id,vendor_id,order_number,expected_delivery_date,notes,created_by,updated_by) VALUES (?,?,?,?,?,?,?,?)')->execute([$org,$public,(int)$vendor['id'],$number,$expected?:null,$notes?:null,$uid,$uid]);$poId=(int)$pdo->lastInsertId();$inventory=$pdo->prepare('SELECT * FROM inventory_items WHERE organization_id=? AND public_id=? AND archived_at IS NULL LIMIT 1');$mapping=$pdo->prepare("SELECT * FROM inventory_vendor_items WHERE organization_id=? AND vendor_id=? AND inventory_item_id=? AND archived_at IS NULL AND status='active' ORDER BY is_preferred DESC,price_per_pack IS NULL LIMIT 1");$ins=$pdo->prepare('INSERT INTO purchase_order_items (organization_id,purchase_order_id,inventory_item_id,vendor_item_id,public_id,description,ordered_packs,pack_size,unit,ordered_base_quantity,price_per_pack,line_total,notes) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)');foreach(array_slice($lines,0,100) as $line){$inventory->execute([$org,(string)($line['inventoryId']??'')]);$item=$inventory->fetch();if(!$item)throw new InvalidArgumentException('An inventory item in the order was not found.');$mapping->execute([$org,(int)$vendor['id'],(int)$item['id']]);$m=$mapping->fetch()?:null;$packs=max(0.001,(float)($line['packs']??1));$pack=isset($line['packSize'])&&is_numeric($line['packSize'])?(float)$line['packSize']:($m&&$m['pack_size']!==null?(float)$m['pack_size']:1.0);$price=isset($line['pricePerPack'])&&$line['pricePerPack']!==''?(float)$line['pricePerPack']:($m&&$m['price_per_pack']!==null?(float)$m['price_per_pack']:null);$base=$packs*$pack;$ins->execute([$org,$poId,(int)$item['id'],$m?(int)$m['id']:null,purchasing_public_id('poi'),$item['name'],$packs,$pack,$m['pack_unit']??$item['base_unit'],$base,$price,$price!==null?round($price*$packs,2):0,trim((string)($line['notes']??''))?:null]);}purchasing_recalc($pdo,$org,$poId);purchasing_event($pdo,$org,$poId,'created','Purchase order created as draft.',$uid,['vendor'=>$vendor['name']]);$pdo->commit();return purchasing_order($pdo,$org,$public)??[];}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}}
function purchasing_submit(PDO $pdo,int $org,string $publicId,int $uid):array{$po=purchasing_order($pdo,$org,$publicId);if(!$po)throw new RuntimeException('Purchase order not found.');if($po['status']!=='draft')throw new InvalidArgumentException('Only draft purchase orders can be submitted.');if((float)$po['minimum_order_amount']>0&&(float)$po['total_amount']<(float)$po['minimum_order_amount'])throw new InvalidArgumentException('This purchase order is below the vendor minimum of $'.number_format((float)$po['minimum_order_amount'],2).'.');$pdo->prepare("UPDATE purchase_orders SET status='submitted',submitted_at=NOW(6),submitted_by=?,updated_by=?,updated_at=NOW(6) WHERE organization_id=? AND id=?")->execute([$uid,$uid,$org,(int)$po['id']]);purchasing_event($pdo,$org,(int)$po['id'],'submitted','Purchase order marked submitted.',$uid);return purchasing_order($pdo,$org,$publicId)??[];}
function purchasing_price_compare(PDO $pdo,int $org,string $query):array{$like='%'.trim($query).'%';$q=$pdo->prepare("SELECT i.public_id inventory_id,i.name inventory_name,v.public_id vendor_id,v.name vendor_name,vi.vendor_sku,vi.pack_size,vi.pack_unit,vi.price_per_pack,CASE WHEN vi.pack_size>0 AND vi.price_per_pack IS NOT NULL THEN vi.price_per_pack/vi.pack_size ELSE NULL END unit_price,vi.is_preferred FROM inventory_vendor_items vi JOIN inventory_items i ON i.id=vi.inventory_item_id JOIN vendors v ON v.id=vi.vendor_id WHERE vi.organization_id=? AND vi.archived_at IS NULL AND vi.status='active' AND v.status='active' AND i.name LIKE ? ORDER BY unit_price IS NULL,unit_price,v.name LIMIT 40");$q->execute([$org,$like]);return $q->fetchAll();}
function purchasing_summary(PDO $pdo,int $org):array{$s=purchasing_suggestions($pdo,$org);$q=$pdo->prepare("SELECT SUM(status='draft') drafts,SUM(status IN ('submitted','partially_received')) open_orders,COALESCE(SUM(CASE WHEN status IN ('submitted','partially_received') THEN total_amount ELSE 0 END),0) committed FROM purchase_orders WHERE organization_id=? AND archived_at IS NULL");$q->execute([$org]);$r=$q->fetch()?:[];return ['suggestions'=>count($s),'unmapped'=>count(array_filter($s,static fn($x)=>empty($x['vendor']))),'drafts'=>(int)($r['drafts']??0),'openOrders'=>(int)($r['open_orders']??0),'committed'=>(float)($r['committed']??0)];}
