<?php
declare(strict_types=1);
require __DIR__ . '/../includes/bootstrap.php';
require __DIR__ . '/../includes/catering-brain.php';

$user=app_require_permission($_SERVER['REQUEST_METHOD']==='GET'?'catering.view':'catering.manage');
$pdo=app_pdo();$organizationId=(int)$user['organization_id'];
$stages=['new','qualified','menu_proposal','tasting','quoted','contracted','deposit_paid','confirmed','completed','lost'];
if(!catering_brain_ready($pdo))app_json_response(['ok'=>false,'message'=>'Catering pipeline migration is not installed. Run upgrade.php.'],503);

function catering_public_row(array $row):array{return [
'id'=>(string)$row['public_id'],'companyName'=>(string)($row['company_name']??''),'contactName'=>(string)$row['contact_name'],'email'=>(string)$row['email'],'phone'=>(string)($row['phone']??''),'eventType'=>(string)$row['event_type'],'eventDate'=>$row['event_date'],'startTime'=>$row['start_time'],'endTime'=>$row['end_time'],'guestCount'=>$row['guest_count']!==null?(int)$row['guest_count']:null,'venueName'=>(string)($row['venue_name']??''),'venueAddress'=>(string)($row['venue_address']??''),'serviceStyle'=>(string)($row['service_style']??''),'menuInterests'=>(string)($row['menu_interests']??''),'dietaryRequirements'=>(string)($row['dietary_requirements']??''),'beverageService'=>(string)($row['beverage_service']??''),'staffingNeeds'=>(string)($row['staffing_needs']??''),'rentalsNeeds'=>(string)($row['rentals_needs']??''),'budgetRange'=>(string)($row['budget_range']??''),'fulfillmentPreference'=>(string)($row['fulfillment_preference']??''),'notes'=>(string)($row['notes']??''),'stage'=>(string)$row['pipeline_stage'],'estimatedValue'=>$row['estimated_value']!==null?(float)$row['estimated_value']:null,'probability'=>(int)$row['probability_percent'],'assignedTo'=>$row['assigned_to']!==null?(int)$row['assigned_to']:null,'assignedName'=>(string)($row['assigned_name']??''),'nextFollowupAt'=>$row['next_followup_at'],'lastContactAt'=>$row['last_contact_at'],'lossReason'=>(string)($row['loss_reason']??''),'source'=>(string)$row['source'],'createdAt'=>$row['created_at'],'updatedAt'=>$row['updated_at']];}

if($_SERVER['REQUEST_METHOD']==='GET'){
 $action=(string)($_GET['action']??'list');
 if($action==='list'){$q=trim((string)($_GET['q']??''));$stage=trim((string)($_GET['stage']??''));$params=[$organizationId];$where='c.organization_id=? AND c.archived_at IS NULL';if($stage!==''&&in_array($stage,$stages,true)){$where.=' AND c.pipeline_stage=?';$params[]=$stage;}if($q!==''){$where.=' AND (c.company_name LIKE ? OR c.contact_name LIKE ? OR c.email LIKE ? OR c.event_type LIKE ? OR c.venue_name LIKE ? OR c.menu_interests LIKE ? OR c.notes LIKE ?)';$like='%'.$q.'%';array_push($params,$like,$like,$like,$like,$like,$like,$like);}$statement=$pdo->prepare("SELECT c.*,u.display_name AS assigned_name FROM catering_leads c LEFT JOIN users u ON u.id=c.assigned_to WHERE {$where} ORDER BY CASE c.pipeline_stage WHEN 'new' THEN 1 WHEN 'qualified' THEN 2 WHEN 'menu_proposal' THEN 3 WHEN 'tasting' THEN 4 WHEN 'quoted' THEN 5 WHEN 'contracted' THEN 6 WHEN 'deposit_paid' THEN 7 WHEN 'confirmed' THEN 8 WHEN 'completed' THEN 9 WHEN 'lost' THEN 10 ELSE 11 END,c.event_date IS NULL,c.event_date,c.updated_at DESC LIMIT 300");$statement->execute($params);app_json_response(['ok'=>true,'stages'=>$stages,'leads'=>array_map('catering_public_row',$statement->fetchAll())]);}
 if($action==='detail'){$id=trim((string)($_GET['id']??''));$statement=$pdo->prepare("SELECT c.*,u.display_name AS assigned_name FROM catering_leads c LEFT JOIN users u ON u.id=c.assigned_to WHERE c.organization_id=? AND c.public_id=? AND c.archived_at IS NULL LIMIT 1");$statement->execute([$organizationId,$id]);$row=$statement->fetch();if(!$row)app_json_response(['ok'=>false,'message'=>'Catering opportunity not found.'],404);$activities=$pdo->prepare("SELECT a.*,u.display_name AS createdByName FROM catering_lead_activities a LEFT JOIN users u ON u.id=a.created_by WHERE a.organization_id=? AND a.catering_lead_id=? ORDER BY a.created_at DESC,a.id DESC LIMIT 150");$activities->execute([$organizationId,(int)$row['id']]);app_json_response(['ok'=>true,'lead'=>catering_public_row($row),'activities'=>$activities->fetchAll()]);}
 if($action==='summary'){$users=$pdo->prepare("SELECT DISTINCT u.id,u.display_name FROM users u INNER JOIN organization_memberships om ON om.user_id=u.id AND om.organization_id=? WHERE u.status='active' AND u.archived_at IS NULL ORDER BY u.display_name");$users->execute([$organizationId]);app_json_response(['ok'=>true,'summary'=>catering_brain_summary($pdo,$organizationId),'upcoming'=>catering_brain_upcoming($pdo,$organizationId,30),'users'=>$users->fetchAll(),'stages'=>$stages]);}
 app_json_response(['ok'=>false,'message'=>'Unsupported catering action.'],422);
}

if($_SERVER['REQUEST_METHOD']!=='POST'){header('Allow: GET, POST');app_json_response(['ok'=>false,'message'=>'Method not allowed.'],405);}
$input=app_json_input();app_verify_request_csrf($input);$action=(string)($input['action']??'');$publicId=trim((string)($input['id']??''));$statement=$pdo->prepare('SELECT * FROM catering_leads WHERE organization_id=? AND public_id=? AND archived_at IS NULL LIMIT 1');$statement->execute([$organizationId,$publicId]);$lead=$statement->fetch();if(!$lead)app_json_response(['ok'=>false,'message'=>'Catering opportunity not found.'],404);$leadId=(int)$lead['id'];

if($action==='stage'){$stage=(string)($input['stage']??'');if(!in_array($stage,$stages,true))app_json_response(['ok'=>false,'message'=>'Invalid catering stage.'],422);$probMap=['new'=>10,'qualified'=>25,'menu_proposal'=>40,'tasting'=>50,'quoted'=>65,'contracted'=>80,'deposit_paid'=>90,'confirmed'=>100,'completed'=>100,'lost'=>0];$update=$pdo->prepare("UPDATE catering_leads SET pipeline_stage=?,probability_percent=?,quoted_at=IF(?='quoted',COALESCE(quoted_at,NOW(6)),quoted_at),booked_at=IF(? IN ('contracted','deposit_paid','confirmed','completed'),COALESCE(booked_at,NOW(6)),booked_at),completed_at=IF(?='completed',COALESCE(completed_at,NOW(6)),NULL),lost_at=IF(?='lost',COALESCE(lost_at,NOW(6)),NULL),updated_at=NOW(6) WHERE id=? AND organization_id=?");$update->execute([$stage,$probMap[$stage],$stage,$stage,$stage,$stage,$leadId,$organizationId]);$activity=$pdo->prepare("INSERT INTO catering_lead_activities (organization_id,catering_lead_id,activity_type,summary,created_by) VALUES (?,?,'stage',?,?)");$activity->execute([$organizationId,$leadId,'Pipeline moved from '.$lead['pipeline_stage'].' to '.$stage,(int)$user['id']]);catering_brain_sync($pdo,$organizationId,$leadId,(int)$user['id']);app_audit($pdo,$organizationId,(int)$user['id'],'catering.stage_changed','catering_lead',$publicId,['stage'=>$lead['pipeline_stage']],['stage'=>$stage]);app_json_response(['ok'=>true,'message'=>'Catering stage updated.']);}

if($action==='update'){
 $estimatedValue=$input['estimatedValue']??null;if($estimatedValue!==null&&$estimatedValue!==''&&!is_numeric($estimatedValue))app_json_response(['ok'=>false,'message'=>'Estimated value must be numeric.'],422);$probability=max(0,min(100,(int)($input['probability']??$lead['probability_percent'])));$assignedTo=isset($input['assignedTo'])&&$input['assignedTo']!==''?(int)$input['assignedTo']:null;$nextFollowup=trim((string)($input['nextFollowupAt']??''));if($nextFollowup!==''){$dt=DateTimeImmutable::createFromFormat('Y-m-d\TH:i',$nextFollowup);if(!$dt)app_json_response(['ok'=>false,'message'=>'Follow-up date is invalid.'],422);$nextFollowup=$dt->format('Y-m-d H:i:s');}else $nextFollowup=null;
 $eventDate=trim((string)($input['eventDate']??$lead['event_date']??''));if($eventDate!==''){$date=DateTimeImmutable::createFromFormat('Y-m-d',$eventDate);if(!$date||$date->format('Y-m-d')!==$eventDate)app_json_response(['ok'=>false,'message'=>'Event date is invalid.'],422);}else $eventDate=null;
 $guestCount=($input['guestCount']??$lead['guest_count']??'')!==''?(int)($input['guestCount']??$lead['guest_count']):null;if($guestCount!==null&&($guestCount<1||$guestCount>10000))app_json_response(['ok'=>false,'message'=>'Guest count must be between 1 and 10,000.'],422);
 if($assignedTo){$check=$pdo->prepare("SELECT COUNT(*) FROM users u INNER JOIN organization_memberships om ON om.user_id=u.id WHERE u.id=? AND om.organization_id=? AND u.status='active' AND u.archived_at IS NULL");$check->execute([$assignedTo,$organizationId]);if(!(int)$check->fetchColumn())app_json_response(['ok'=>false,'message'=>'Assignee is not an active organization user.'],422);}
 $fields=['companyName'=>['company_name',200],'eventType'=>['event_type',100],'venueName'=>['venue_name',220],'venueAddress'=>['venue_address',500],'serviceStyle'=>['service_style',120],'menuInterests'=>['menu_interests',5000],'dietaryRequirements'=>['dietary_requirements',4000],'beverageService'=>['beverage_service',160],'staffingNeeds'=>['staffing_needs',180],'rentalsNeeds'=>['rentals_needs',3000],'budgetRange'=>['budget_range',120],'fulfillmentPreference'=>['fulfillment_preference',100],'notes'=>['notes',10000],'lossReason'=>['loss_reason',500]];$values=[];foreach($fields as $key=>[$column,$max])$values[$column]=mb_substr(trim((string)($input[$key]??$lead[$column]??'')),0,$max,'UTF-8');
 $update=$pdo->prepare("UPDATE catering_leads SET company_name=?,event_type=?,event_date=?,guest_count=?,venue_name=?,venue_address=?,service_style=?,menu_interests=?,dietary_requirements=?,beverage_service=?,staffing_needs=?,rentals_needs=?,budget_range=?,fulfillment_preference=?,notes=?,loss_reason=?,estimated_value=?,probability_percent=?,assigned_to=?,next_followup_at=?,updated_at=NOW(6) WHERE id=? AND organization_id=?");$update->execute([$values['company_name']?:null,$values['event_type']?:$lead['event_type'],$eventDate,$guestCount,$values['venue_name']?:null,$values['venue_address']?:null,$values['service_style']?:null,$values['menu_interests']?:null,$values['dietary_requirements']?:null,$values['beverage_service']?:null,$values['staffing_needs']?:null,$values['rentals_needs']?:null,$values['budget_range']?:null,$values['fulfillment_preference']?:null,$values['notes']?:null,$values['loss_reason']?:null,$estimatedValue===''?null:$estimatedValue,$probability,$assignedTo,$nextFollowup,$leadId,$organizationId]);catering_brain_sync($pdo,$organizationId,$leadId,(int)$user['id']);app_audit($pdo,$organizationId,(int)$user['id'],'catering.updated','catering_lead',$publicId,null,['eventDate'=>$eventDate,'guestCount'=>$guestCount,'estimatedValue'=>$estimatedValue,'probability'=>$probability,'assignedTo'=>$assignedTo]);app_json_response(['ok'=>true,'message'=>'Catering opportunity updated.']);
}

if($action==='activity'){$type=trim((string)($input['activityType']??'note'));$allowed=['note','call','email','meeting','site_visit','tasting','menu','quote','contract','deposit','followup','operations'];if(!in_array($type,$allowed,true))$type='note';$summary=mb_substr(trim((string)($input['summary']??'')),0,500,'UTF-8');$details=mb_substr(trim((string)($input['details']??'')),0,10000,'UTF-8');if($summary==='')app_json_response(['ok'=>false,'message'=>'Enter an activity summary.'],422);$insert=$pdo->prepare("INSERT INTO catering_lead_activities (organization_id,catering_lead_id,activity_type,summary,details,created_by) VALUES (?,?,?,?,?,?)");$insert->execute([$organizationId,$leadId,$type,$summary,$details?:null,(int)$user['id']]);$pdo->prepare('UPDATE catering_leads SET last_contact_at=NOW(6),updated_at=NOW(6) WHERE id=? AND organization_id=?')->execute([$leadId,$organizationId]);catering_brain_sync($pdo,$organizationId,$leadId,(int)$user['id']);app_audit($pdo,$organizationId,(int)$user['id'],'catering.activity_added','catering_lead',$publicId,null,['activityType'=>$type,'summary'=>$summary]);app_json_response(['ok'=>true,'message'=>'Catering activity added.']);}
if($action==='archive'){$pdo->prepare('UPDATE catering_leads SET archived_at=NOW(6),updated_at=NOW(6) WHERE id=? AND organization_id=?')->execute([$leadId,$organizationId]);if(restaurant_brain_table_ready($pdo,'agent_knowledge_records')){$pdo->prepare("UPDATE agent_knowledge_records SET status='archived',updated_at=NOW(6) WHERE organization_id=? AND source_type='catering_lead' AND source_public_id=?")->execute([$organizationId,$publicId]);}app_audit($pdo,$organizationId,(int)$user['id'],'catering.archived','catering_lead',$publicId);app_json_response(['ok'=>true,'message'=>'Catering opportunity archived.']);}
app_json_response(['ok'=>false,'message'=>'Unsupported catering action.'],422);
