<?php
declare(strict_types=1);
require __DIR__.'/../includes/bootstrap.php';
require_once __DIR__.'/../includes/glasses-vision-lab.php';
require_once __DIR__.'/../includes/glasses-vision-active-learning.php';
require_once __DIR__.'/../includes/glasses-vision-dataset-intelligence.php';
require_once __DIR__.'/../includes/glasses-vision-training-media.php';
require_once __DIR__.'/../includes/glasses-vision-curation.php';
require_once __DIR__.'/../includes/glasses-vision-balance.php';
require_once __DIR__.'/../includes/glasses-vision-annotation-qa.php';
require_once __DIR__.'/../includes/glasses-vision-training-release.php';
require_once __DIR__.'/../includes/glasses-vision-training-qualification.php';
require_once __DIR__.'/../includes/glasses-vision-lineage.php';
require_once __DIR__.'/../includes/glasses-vision-feedback.php';
require_once __DIR__.'/../includes/glasses-vision-failure-analysis.php';
require_once __DIR__.'/../includes/glasses-vision-mining.php';
require_once __DIR__.'/../includes/glasses-vision-retraining.php';
require_once __DIR__.'/../includes/glasses-vision-experiments.php';
require_once __DIR__.'/../includes/glasses-vision-evidence-review.php';
require_once __DIR__.'/../includes/glasses-vision-promotion.php';
require_once __DIR__.'/../includes/glasses-vision-model-health.php';
require_once __DIR__.'/../includes/glasses-vision-context-drift.php';
require_once __DIR__.'/../includes/glasses-vision-calibration-profiles.php';
require_once __DIR__.'/../includes/glasses-vision-confidence-policy.php';
require_once __DIR__.'/../includes/glasses-vision-active-perception.php';
require_once __DIR__.'/../includes/glasses-vision-fleet-health.php';
require_once __DIR__.'/../includes/glasses-vision-autonomy-audit.php';
require_once __DIR__.'/../includes/glasses-vision-scene.php';
require_once __DIR__.'/../includes/glasses-vision-step-recognition.php';
require_once __DIR__.'/../includes/glasses-vision-ingredient-prevention.php';
require_once __DIR__.'/../includes/glasses-vision-quantity-verification.php';
require_once __DIR__.'/../includes/glasses-vision-quality-verification.php';
require_once __DIR__.'/../includes/glasses-vision-final-validation.php';
require_once __DIR__.'/../includes/glasses-vision-handoff-confirmation.php';
require_once __DIR__.'/../includes/glasses-vision-rework.php';
require_once __DIR__.'/../includes/glasses-vision-kitchen-outcomes.php';
require_once __DIR__.'/../includes/glasses-production-pilot.php';
require_once __DIR__.'/../includes/glasses-training-identity.php';
require_once __DIR__.'/../includes/glasses-production-evidence.php';
require_once __DIR__.'/../includes/glasses-annotation-workbench.php';
require_once __DIR__.'/../includes/glasses-v11-mining.php';
require_once __DIR__.'/../includes/glasses-v11-dataset-assembly.php';
require_once __DIR__.'/../includes/glasses-v11-training-runs.php';
require_once __DIR__.'/../includes/glasses-v11-model-evaluation.php';
require_once __DIR__.'/../includes/glasses-v11-model-release-candidates.php';
require_once __DIR__.'/../includes/glasses-v11-shadow-validation.php';
require_once __DIR__.'/../includes/glasses-v11-canary-release.php';
$user=app_require_auth();$pdo=app_pdo();$org=(int)$user['organization_id'];
if(!app_has_permission('glasses.view',$user))app_json_response(['ok'=>false,'message'=>'AR glasses permission required.'],403);
try{
 if($_SERVER['REQUEST_METHOD']==='GET'){$catalog=glasses_vision_lab_catalog($pdo,$user);$catalog['activeLearning']=glasses_vision_active_learning_catalog($pdo,$org);$catalog['datasetIntelligence']=glasses_vision_dataset_intelligence_catalog($pdo,$org);$catalog['trainingMedia']=glasses_vision_training_media_catalog($pdo,$org);$catalog['curation']=glasses_vision_curation_catalog($pdo,$org);$catalog['balance']=glasses_vision_balance_catalog($pdo,$org);$catalog['annotationQa']=glasses_vision_annotation_qa_catalog($pdo,$org);$catalog['trainingReleases']=glasses_vision_training_release_catalog($pdo,$org);$catalog['trainingQualification']=glasses_vision_training_qualification_catalog($pdo,$org);$catalog['lineage']=glasses_vision_lineage_catalog($pdo,$org);$catalog['productionFeedback']=glasses_vision_feedback_catalog($pdo,$org);$catalog['failureAnalysis']=glasses_vision_failure_analysis_catalog($pdo,$org);$catalog['hardExampleMining']=glasses_vision_mining_catalog($pdo,$org);$catalog['retrainingCandidates']=glasses_vision_retraining_catalog($pdo,$org);$catalog['modelExperiments']=glasses_vision_experiment_catalog($pdo,$org);$catalog['evidenceReviews']=glasses_vision_evidence_review_catalog($pdo,$org);$catalog['promotions']=glasses_vision_promotion_catalog($pdo,$org);$catalog['modelHealth']=glasses_vision_model_health_catalog($pdo,$org);$catalog['contextDrift']=glasses_vision_context_drift_catalog($pdo,$org);$catalog['calibrationProfiles']=glasses_vision_calibration_profile_catalog($pdo,$org);$catalog['confidencePolicies']=glasses_vision_confidence_policy_catalog($pdo,$org);$catalog['activePerception']=glasses_vision_active_perception_catalog($pdo,$org);$catalog['fleetHealth']=glasses_vision_fleet_health_catalog($pdo,$org);$catalog['autonomyAudits']=glasses_vision_autonomy_catalog($pdo,$org);$catalog['liveScenes']=glasses_vision_scene_recent($pdo,$org,50);$catalog['stepRecognitions']=glasses_vision_step_recent($pdo,$org,50);$catalog['ingredientPreventions']=glasses_vision_ingredient_guard_recent($pdo,$org,50);$catalog['quantityVerifications']=glasses_vision_quantity_recent($pdo,$org,50);$catalog['qualityVerifications']=glasses_vision_quality_recent($pdo,$org,50);$catalog['finalValidations']=glasses_vision_final_recent($pdo,$org,50);$catalog['handoffConfirmations']=glasses_vision_handoff_confirmation_recent($pdo,$org,50);$catalog['reworkCases']=glasses_vision_rework_recent($pdo,$org,50);$catalog['kitchenOutcomes']=glasses_vision_kitchen_outcome_catalog($pdo,$org);$catalog['productionPilots']=glasses_production_pilot_catalog($pdo,$org);$catalog['glassesTraining']=glasses_training_catalog($pdo,$org);$catalog['productionEvidence']=glasses_v11_production_evidence_catalog($pdo,$org,100);$catalog['annotationWorkbench']=glasses_v11_annotation_catalog($pdo,$org,100);$catalog['v11Mining']=glasses_v11_mining_catalog($pdo,$org);$catalog['v11Datasets']=glasses_v11_dataset_catalog($pdo,$org);$catalog['trainingRunsV11']=glasses_v11_training_run_catalog($pdo,$org);$catalog['modelBenchmarksV11']=glasses_v11_model_evaluation_catalog($pdo,$org);$catalog['modelReleaseCandidatesV11']=glasses_v11_model_rc_catalog($pdo,$org);$catalog['shadowValidationsV11']=glasses_v11_shadow_catalog($pdo,$org);$catalog['canaryReleaseV11']=glasses_v11_canary_catalog($pdo,$org);app_json_response(['ok'=>true,'catalog'=>$catalog]);}
 if($_SERVER['REQUEST_METHOD']!=='POST'){header('Allow: GET, POST');app_json_response(['ok'=>false,'message'=>'Method not allowed.'],405);}
 if(!app_has_permission('glasses.manage',$user))app_json_response(['ok'=>false,'message'=>'AR glasses management permission required.'],403);
 $in=app_json_input();app_verify_request_csrf($in);$action=(string)($in['action']??'');$actor=(int)$user['id'];
 if($action==='canary_stage.evaluate')app_json_response(['ok'=>true,'stageValidation'=>glasses_v11_canary_stage_evaluate($pdo,$org,(string)($in['rolloutPublicId']??''),$in,$actor)],201);
 if($action==='production_acceptance.create')app_json_response(['ok'=>true,'productionAcceptance'=>glasses_v11_production_accept($pdo,$org,(string)($in['rolloutPublicId']??''),$actor)],201);
 if($action==='shadow_validation.evaluate')app_json_response(['ok'=>true,'shadowValidation'=>glasses_v11_shadow_validate($pdo,$org,(string)($in['rolloutPublicId']??''),$in,$actor)],201);
 if($action==='model_rc.create')app_json_response(['ok'=>true,'releaseCandidate'=>glasses_v11_model_rc_create($pdo,$org,$in,$actor)],201);
 if($action==='model_rc.approve')app_json_response(['ok'=>true,'releaseCandidate'=>glasses_v11_model_rc_approve($pdo,$org,(string)($in['publicId']??''),$actor)]);
 if($action==='model_rc.reject')app_json_response(['ok'=>true,'releaseCandidate'=>glasses_v11_model_rc_reject($pdo,$org,(string)($in['publicId']??''),(string)($in['reason']??''),$actor)]);
 if($action==='model_rc.verify')app_json_response(['ok'=>true,'verification'=>glasses_v11_model_rc_verify($pdo,$org,(string)($in['publicId']??''))]);
 if($action==='model_benchmark.run')app_json_response(['ok'=>true,'benchmark'=>glasses_v11_model_evaluation_run($pdo,$org,(string)($in['experimentPublicId']??''),$in,$actor)],201);
 if($action==='training_run.create')app_json_response(['ok'=>true,'trainingRun'=>glasses_v11_training_run_create($pdo,$org,$in,$actor)],201);
 if($action==='training_run.start')app_json_response(['ok'=>true,'trainingRun'=>glasses_v11_training_run_start($pdo,$org,(string)($in['publicId']??''),$actor)]);
 if($action==='training_run.complete')app_json_response(['ok'=>true,'trainingRun'=>glasses_v11_training_run_complete($pdo,$org,(string)($in['publicId']??''),$in,$actor)]);
 if($action==='training_run.fail')app_json_response(['ok'=>true,'trainingRun'=>glasses_v11_training_run_fail($pdo,$org,(string)($in['publicId']??''),is_array($in['failure']??null)?$in['failure']:[],$actor)]);
 if($action==='training_run.cancel')app_json_response(['ok'=>true,'trainingRun'=>glasses_v11_training_run_cancel($pdo,$org,(string)($in['publicId']??''),(string)($in['reason']??''),$actor)]);
 if($action==='training_run.rerun')app_json_response(['ok'=>true,'trainingRun'=>glasses_v11_training_run_rerun($pdo,$org,(string)($in['publicId']??''),$in,$actor)],201);
 if($action==='training_run.compare')app_json_response(['ok'=>true,'comparison'=>glasses_v11_training_run_compare($pdo,$org,(string)($in['fromPublicId']??''),(string)($in['toPublicId']??''))]);
 if($action==='dataset.assemble')app_json_response(['ok'=>true,'dataset'=>glasses_v11_dataset_assemble($pdo,$org,$in,$actor)],201);
 if($action==='dataset.freeze')app_json_response(['ok'=>true,'dataset'=>glasses_vision_lab_freeze_dataset($pdo,$org,(string)($in['datasetPublicId']??''),$actor)]);
 if($action==='mining.run')app_json_response(['ok'=>true,'run'=>glasses_v11_mining_run($pdo,$org,is_array($in['policy']??null)?$in['policy']:[],$actor)],201);
 if($action==='mining.dismiss')app_json_response(['ok'=>true,'candidate'=>glasses_v11_mining_dismiss($pdo,$org,(string)($in['candidatePublicId']??''),(string)($in['reason']??''),$actor)]);
 if($action==='annotation.submit')app_json_response(['ok'=>true,'correction'=>glasses_v11_annotation_submit($pdo,$org,$in,$actor)],201);
 if($action==='annotation.review')app_json_response(['ok'=>true,'correction'=>glasses_v11_annotation_review($pdo,$org,(string)($in['correctionPublicId']??''),(string)($in['decision']??''),(string)($in['notes']??''),$actor)]);
 if($action==='annotation.adjudicate')app_json_response(['ok'=>true,'correction'=>glasses_v11_annotation_adjudicate($pdo,$org,(string)($in['correctionPublicId']??''),(string)($in['decision']??''),(string)($in['notes']??''),$actor)]);
 if($action==='training.evidence_eligibility')app_json_response(['ok'=>true,'evidence'=>glasses_v11_production_evidence_set_eligibility($pdo,$org,(string)($in['evidencePublicId']??''),(string)($in['eligibility']??'review'),(string)($in['reason']??''),$actor)]);
 if($action==='training.program_create')app_json_response(['ok'=>true,'program'=>glasses_training_program_create($pdo,$org,$in,$actor)],201);
 if($action==='training.assignment_create')app_json_response(['ok'=>true,'assignment'=>glasses_training_assignment_create($pdo,$org,$in,$actor)],201);
 if($action==='training.session_end')app_json_response(['ok'=>true,'session'=>glasses_training_session_end($pdo,$org,(string)($in['sessionPublicId']??''),(string)($in['status']??'completed'),(string)($in['reason']??''),$actor)]);
 if($action==='pilot.create')app_json_response(['ok'=>true,'pilot'=>glasses_production_pilot_create($pdo,$org,$in,$actor)],201);
 if($action==='pilot.activate')app_json_response(['ok'=>true,'pilot'=>glasses_production_pilot_set_status($pdo,$org,(string)($in['pilotPublicId']??''),'active',(string)($in['reason']??''),$actor)]);
 if($action==='pilot.pause')app_json_response(['ok'=>true,'pilot'=>glasses_production_pilot_set_status($pdo,$org,(string)($in['pilotPublicId']??''),'paused',(string)($in['reason']??''),$actor)]);
 if($action==='pilot.stop')app_json_response(['ok'=>true,'pilot'=>glasses_production_pilot_set_status($pdo,$org,(string)($in['pilotPublicId']??''),'stopped',(string)($in['reason']??''),$actor)]);
 if($action==='pilot.kill_switch')app_json_response(['ok'=>true,'pilot'=>glasses_production_pilot_kill_switch($pdo,$org,(string)($in['pilotPublicId']??''),!empty($in['enabled']),(string)($in['reason']??''),$actor)]);
 if($action==='pilot.rollback_rollout')app_json_response(['ok'=>true,'result'=>glasses_production_pilot_rollback_rollout($pdo,$org,(string)($in['pilotPublicId']??''),(string)($in['reason']??''),$actor)]);
 if($action==='pilot.device_enroll')app_json_response(['ok'=>true,'readiness'=>glasses_production_pilot_enroll($pdo,$org,(string)($in['pilotPublicId']??''),(string)($in['devicePublicId']??''),$actor)],201);
 if($action==='pilot.device_evaluate')app_json_response(['ok'=>true,'readiness'=>glasses_production_pilot_evaluate($pdo,$org,(string)($in['pilotPublicId']??''),(string)($in['devicePublicId']??''),is_array($in['runtime']??null)?$in['runtime']:[],$actor)]);
 if($action==='pilot.device_enable')app_json_response(['ok'=>true,'result'=>glasses_production_pilot_set_device_status($pdo,$org,(string)($in['pilotPublicId']??''),(string)($in['devicePublicId']??''),'enabled','',$actor,is_array($in['runtime']??null)?$in['runtime']:[])]);
 if($action==='pilot.device_disable')app_json_response(['ok'=>true,'result'=>glasses_production_pilot_set_device_status($pdo,$org,(string)($in['pilotPublicId']??''),(string)($in['devicePublicId']??''),'disabled',(string)($in['reason']??''),$actor)]);
 if($action==='pilot.device_remove')app_json_response(['ok'=>true,'result'=>glasses_production_pilot_set_device_status($pdo,$org,(string)($in['pilotPublicId']??''),(string)($in['devicePublicId']??''),'removed',(string)($in['reason']??''),$actor)]);
 if($action==='outcomes.sync')app_json_response(['ok'=>true,'result'=>glasses_vision_kitchen_outcome_sync($pdo,$org,$actor,(int)($in['limit']??500))]);
 if($action==='assignment.create')app_json_response(['ok'=>true,'assignment'=>glasses_vision_lab_assign_device($pdo,$org,(string)($in['devicePublicId']??''),(int)($in['userId']??0),(string)($in['role']??'operator'),(string)($in['source']??'manual'),$actor)],201);
 if($action==='assignment.release')app_json_response(['ok'=>true,'assignment'=>glasses_vision_lab_release_device($pdo,$org,(string)($in['publicId']??''),(string)($in['reason']??''),$actor)]);
 if($action==='mission.create')app_json_response(['ok'=>true,'mission'=>glasses_vision_lab_create_mission($pdo,$org,$in,$actor)],201);
 if($action==='sample.queue_observation')app_json_response(['ok'=>true,'sample'=>glasses_vision_lab_queue_observation($pdo,$org,(string)($in['observationKey']??''),!empty($in['missionPublicId'])?(string)$in['missionPublicId']:null,$actor)],201);
 if($action==='sample.import_corrected')app_json_response(['ok'=>true,'result'=>glasses_vision_lab_import_corrected($pdo,$org,!empty($in['missionPublicId'])?(string)$in['missionPublicId']:null,$actor,(int)($in['limit']??500))]);
 if($action==='sample.review'){$sample=glasses_vision_lab_review_sample($pdo,$org,(string)($in['publicId']??''),$in,$actor);$multi=glasses_vision_dataset_intelligence_record_review($pdo,$org,(string)($in['publicId']??''),$actor,(string)($in['decision']??''),isset($in['canonicalLabel'])?(string)$in['canonicalLabel']:null,(string)($in['notes']??''));app_json_response(['ok'=>true,'sample'=>$sample,'reviewConsensus'=>$multi]);}
 if($action==='dataset.create')app_json_response(['ok'=>true,'dataset'=>glasses_vision_lab_create_dataset($pdo,$org,$in,$actor)],201);
 if($action==='dataset.add_sample')app_json_response(['ok'=>true,'dataset'=>glasses_vision_lab_add_dataset_sample($pdo,$org,(string)($in['datasetPublicId']??''),(string)($in['samplePublicId']??''),(string)($in['split']??'train'))]);
 if($action==='dataset.freeze')app_json_response(['ok'=>true,'dataset'=>glasses_vision_lab_freeze_dataset($pdo,$org,(string)($in['publicId']??''),$actor)]);
 if($action==='active_learning.scan')app_json_response(['ok'=>true,'scan'=>glasses_vision_active_learning_scan($pdo,$org,$actor,(string)($in['triggerSource']??'manual'))]);
 if($action==='active_learning.create_mission')app_json_response(['ok'=>true,'mission'=>glasses_vision_active_learning_create_mission($pdo,$org,(string)($in['publicId']??''),$actor)],201);
 if($action==='active_learning.dismiss')app_json_response(['ok'=>true,'candidate'=>glasses_vision_active_learning_dismiss($pdo,$org,(string)($in['publicId']??''),(string)($in['reason']??''),$actor)]);
 if($action==='dataset_intelligence.analyze')app_json_response(['ok'=>true,'analysis'=>glasses_vision_dataset_intelligence_analyze($pdo,$org,!empty($in['datasetPublicId'])?(string)$in['datasetPublicId']:null,$actor,(int)($in['minimumPerClass']??20))]);
 if($action==='dataset_intelligence.plan')app_json_response(['ok'=>true,'plan'=>glasses_vision_dataset_intelligence_collection_plan($pdo,$org,(string)($in['snapshotPublicId']??''),(string)($in['title']??'Vision collection plan'),$actor)],201);
 if($action==='dataset_intelligence.accept_plan')app_json_response(['ok'=>true,'plan'=>glasses_vision_dataset_intelligence_accept_plan($pdo,$org,(string)($in['publicId']??''),$actor)]);
 if($action==='dataset_intelligence.set_split')app_json_response(['ok'=>true,'coverage'=>glasses_vision_dataset_intelligence_set_split($pdo,$org,(string)($in['datasetPublicId']??''),(string)($in['samplePublicId']??''),(string)($in['split']??''))]);
 if($action==='dataset_intelligence.consolidate_build_split')app_json_response(['ok'=>true,'result'=>glasses_vision_dataset_intelligence_consolidate_build_split($pdo,$org,(string)($in['datasetPublicId']??''),(string)($in['buildPublicId']??''),(string)($in['split']??''))]);
 if($action==='curation.rows')app_json_response(['ok'=>true,'rows'=>glasses_vision_curation_rows($pdo,$org,(string)($in['datasetPublicId']??'')),'plans'=>glasses_vision_curation_split_plans($pdo,$org,(string)($in['datasetPublicId']??''))]);
 if($action==='curation.decide')app_json_response(['ok'=>true,'decision'=>glasses_vision_curation_decide($pdo,$org,(string)($in['datasetPublicId']??''),(string)($in['samplePublicId']??''),(string)($in['decision']??''),(string)($in['reason']??''),$actor)]);
 if($action==='curation.plan_split')app_json_response(['ok'=>true,'plan'=>glasses_vision_curation_create_split_plan($pdo,$org,(string)($in['datasetPublicId']??''),$in,$actor)],201);
 if($action==='curation.apply_split')app_json_response(['ok'=>true,'plan'=>glasses_vision_curation_apply_split_plan($pdo,$org,(string)($in['publicId']??''),$actor)]);
 if($action==='balance.analyze')app_json_response(['ok'=>true,'analysis'=>glasses_vision_balance_analyze($pdo,$org,(string)($in['datasetPublicId']??''),$in)]);
 if($action==='annotation_qa.analyze')app_json_response(['ok'=>true,'analysis'=>glasses_vision_annotation_qa_analyze($pdo,$org,!empty($in['datasetPublicId'])?(string)$in['datasetPublicId']:null)]);
 if($action==='training_release.build')app_json_response(['ok'=>true,'release'=>glasses_vision_training_release_build($pdo,$org,(string)($in['datasetPublicId']??''),(string)($in['trainingProfile']??'yolo11n_640'),$actor)],201);
 if($action==='training_qualification.run')app_json_response(['ok'=>true,'qualification'=>glasses_vision_training_qualification_run($pdo,$org,(string)($in['releasePublicId']??''),is_array($in['policy']??null)?$in['policy']:[],$actor)],201);
 if($action==='lineage.training_run.register')app_json_response(['ok'=>true,'trainingRun'=>glasses_vision_lineage_register_training_run($pdo,$org,$in,$actor)],201);
 if($action==='lineage.model.bind')app_json_response(['ok'=>true,'edge'=>glasses_vision_lineage_bind_model($pdo,$org,(string)($in['trainingRunPublicId']??''),(string)($in['modelPackagePublicId']??''),$actor)],201);
 if($action==='lineage.model.trace')app_json_response(['ok'=>true,'trace'=>glasses_vision_lineage_model_trace($pdo,$org,(string)($in['modelPackagePublicId']??''))]);
 if($action==='lineage.sample.trace')app_json_response(['ok'=>true,'trace'=>glasses_vision_lineage_sample_trace($pdo,$org,(string)($in['samplePublicId']??''))]);
 if($action==='lineage.dataset.diff')app_json_response(['ok'=>true,'diff'=>glasses_vision_lineage_dataset_diff($pdo,$org,(string)($in['fromDatasetPublicId']??''),(string)($in['toDatasetPublicId']??''))]);
 if($action==='production_error.record')app_json_response(['ok'=>true,'event'=>glasses_vision_feedback_record($pdo,$org,$in,$actor)],201);
 if($action==='production_error.sync_corrections')app_json_response(['ok'=>true,'result'=>glasses_vision_feedback_sync_corrections($pdo,$org,$actor,(int)($in['limit']??500))]);
 if($action==='failure_analysis.run')app_json_response(['ok'=>true,'analysis'=>glasses_vision_failure_analysis_run($pdo,$org,$in,$actor)],201);
 if($action==='hard_example.mine')app_json_response(['ok'=>true,'run'=>glasses_vision_mining_run($pdo,$org,is_array($in['policy']??null)?$in['policy']:[],$actor)],201);
 if($action==='hard_example.dismiss')app_json_response(['ok'=>true,'candidate'=>glasses_vision_mining_dismiss($pdo,$org,(string)($in['publicId']??''),(string)($in['reason']??''),$actor)]);
 if($action==='retraining_candidate.prepare')app_json_response(['ok'=>true,'batch'=>glasses_vision_retraining_prepare($pdo,$org,(string)($in['miningRunPublicId']??''),is_array($in['policy']??null)?$in['policy']:[],$actor)],201);
 if($action==='retraining_candidate.review')app_json_response(['ok'=>true,'batch'=>glasses_vision_retraining_review($pdo,$org,(string)($in['batchPublicId']??''),(string)($in['itemPublicId']??''),(string)($in['decision']??''),(string)($in['reason']??''),$actor)]);
 if($action==='retraining_candidate.build_dataset')app_json_response(['ok'=>true,'result'=>glasses_vision_retraining_build_dataset($pdo,$org,(string)($in['batchPublicId']??''),(string)($in['name']??''),(string)($in['versionLabel']??''),$actor)],201);
 if($action==='model_experiment.create')app_json_response(['ok'=>true,'experiment'=>glasses_vision_experiment_create($pdo,$org,$in,$actor)],201);
 if($action==='model_experiment.start')app_json_response(['ok'=>true,'experiment'=>glasses_vision_experiment_start($pdo,$org,(string)($in['publicId']??''),$actor)]);
 if($action==='model_experiment.attach_run')app_json_response(['ok'=>true,'experiment'=>glasses_vision_experiment_attach_run($pdo,$org,(string)($in['publicId']??''),(string)($in['trainingRunPublicId']??''),$actor)]);
 if($action==='model_experiment.bind_challenger')app_json_response(['ok'=>true,'experiment'=>glasses_vision_experiment_bind_challenger($pdo,$org,(string)($in['publicId']??''),(string)($in['modelPackagePublicId']??''),$actor)]);
 if($action==='evidence_review.run')app_json_response(['ok'=>true,'review'=>glasses_vision_evidence_review_run($pdo,$org,(string)($in['experimentPublicId']??''),$in,$actor)],201);
 if($action==='promotion.authorize')app_json_response(['ok'=>true,'promotion'=>glasses_vision_promotion_authorize($pdo,$org,(string)($in['evidenceReviewPublicId']??''),$in,$actor)],201);
 if($action==='promotion.create_rollout')app_json_response(['ok'=>true,'promotion'=>glasses_vision_promotion_create_rollout($pdo,$org,(string)($in['publicId']??''),$actor)],201);
 if($action==='model_health.snapshot')app_json_response(['ok'=>true,'snapshot'=>glasses_vision_model_health_snapshot($pdo,$org,$in,$actor)],201);
 if($action==='model_health.verify')app_json_response(['ok'=>true,'verification'=>glasses_vision_model_health_verify($pdo,$org,(string)($in['publicId']??''))]);
 if($action==='context_drift.analyze')app_json_response(['ok'=>true,'analysis'=>glasses_vision_context_drift_analyze($pdo,$org,(string)($in['healthSnapshotPublicId']??''),$actor)],201);
 if($action==='context_drift.verify')app_json_response(['ok'=>true,'verification'=>glasses_vision_context_drift_verify($pdo,$org,(string)($in['publicId']??''))]);
 if($action==='calibration_profile.create')app_json_response(['ok'=>true,'profile'=>glasses_vision_calibration_profile_create($pdo,$org,$in,$actor)],201);
 if($action==='calibration_profile.activate')app_json_response(['ok'=>true,'profile'=>glasses_vision_calibration_profile_set_status($pdo,$org,(string)($in['publicId']??''),'active',$actor)]);
 if($action==='calibration_profile.retire')app_json_response(['ok'=>true,'profile'=>glasses_vision_calibration_profile_set_status($pdo,$org,(string)($in['publicId']??''),'retired',$actor)]);
 if($action==='calibration_profile.select')app_json_response(['ok'=>true,'selection'=>glasses_vision_calibration_profile_select($pdo,$org,$in,$actor)],201);
 if($action==='calibration_profile.verify')app_json_response(['ok'=>true,'verification'=>glasses_vision_calibration_profile_verify($pdo,$org,(string)($in['publicId']??''))]);
 if($action==='calibration_selection.verify')app_json_response(['ok'=>true,'verification'=>glasses_vision_calibration_selection_verify($pdo,$org,(string)($in['publicId']??''))]);
 if($action==='confidence_policy.create')app_json_response(['ok'=>true,'policy'=>glasses_vision_confidence_policy_create($pdo,$org,$in,$actor)],201);
 if($action==='confidence_policy.activate')app_json_response(['ok'=>true,'policy'=>glasses_vision_confidence_policy_status($pdo,$org,(string)($in['publicId']??''),'active',$actor)]);
 if($action==='confidence_policy.retire')app_json_response(['ok'=>true,'policy'=>glasses_vision_confidence_policy_status($pdo,$org,(string)($in['publicId']??''),'retired',$actor)]);
 if($action==='confidence_policy.verify')app_json_response(['ok'=>true,'verification'=>glasses_vision_confidence_policy_verify($pdo,$org,(string)($in['publicId']??''))]);
 if($action==='confidence_policy.decide')app_json_response(['ok'=>true,'decision'=>glasses_vision_confidence_decide($pdo,$org,$in,$actor)],201);
 if($action==='confidence_decision.verify')app_json_response(['ok'=>true,'verification'=>glasses_vision_confidence_decision_verify($pdo,$org,(string)($in['publicId']??''))]);
 if($action==='active_perception.resolve_human')app_json_response(['ok'=>true,'actionRecord'=>glasses_vision_active_perception_resolve_human($pdo,$org,(string)($in['publicId']??''),(string)($in['resolution']??''),(string)($in['notes']??''),$actor)]);
 if($action==='active_perception.verify')app_json_response(['ok'=>true,'verification'=>glasses_vision_active_perception_verify($pdo,$org,(string)($in['publicId']??''))]);
 if($action==='fleet_health.analyze')app_json_response(['ok'=>true,'analysis'=>glasses_vision_fleet_health_analyze($pdo,$org,$in,$actor)],201);
 if($action==='fleet_health.verify')app_json_response(['ok'=>true,'verification'=>glasses_vision_fleet_health_verify($pdo,$org,(string)($in['publicId']??''))]);
 if($action==='fleet_health.rollback')app_json_response(['ok'=>true,'result'=>glasses_vision_fleet_health_execute_rollback($pdo,$org,(string)($in['publicId']??''),(string)($in['reason']??''),$actor)]);
 if($action==='fleet_health.action.verify')app_json_response(['ok'=>true,'verification'=>glasses_vision_fleet_health_action_verify($pdo,$org,(string)($in['publicId']??''))]);
 if($action==='autonomy_audit.capture')app_json_response(['ok'=>true,'audit'=>glasses_vision_autonomy_capture($pdo,$org,$in,$actor)],201);
 if($action==='autonomy_audit.verify')app_json_response(['ok'=>true,'verification'=>glasses_vision_autonomy_verify($pdo,$org,(string)($in['publicId']??''))]);
 if($action==='autonomy_audit.replay')app_json_response(['ok'=>true,'replay'=>glasses_vision_autonomy_replay($pdo,$org,(string)($in['publicId']??''))]);
 if($action==='scene.verify')app_json_response(['ok'=>true,'verification'=>glasses_vision_scene_verify($pdo,$org,(string)($in['publicId']??''))]);
 if($action==='step.recognize')app_json_response(['ok'=>true,'stepRecognition'=>glasses_vision_step_recognize($pdo,$org,(string)($in['scenePublicId']??''))],201);
 if($action==='step.verify')app_json_response(['ok'=>true,'verification'=>glasses_vision_step_verify($pdo,$org,(string)($in['publicId']??''))]);
 if($action==='ingredient_guard.assess')app_json_response(['ok'=>true,'ingredientPrevention'=>glasses_vision_ingredient_guard_assess($pdo,$org,(string)($in['scenePublicId']??''))],201);
 if($action==='ingredient_guard.verify')app_json_response(['ok'=>true,'verification'=>glasses_vision_ingredient_guard_verify($pdo,$org,(string)($in['publicId']??''))]);
 if($action==='quantity.verify_scene')app_json_response(['ok'=>true,'quantityVerification'=>glasses_vision_quantity_verify_scene($pdo,$org,(string)($in['scenePublicId']??''))],201);
 if($action==='quantity.verify')app_json_response(['ok'=>true,'verification'=>glasses_vision_quantity_verify($pdo,$org,(string)($in['publicId']??''))]);
 if($action==='quality.verify_scene')app_json_response(['ok'=>true,'qualityVerification'=>glasses_vision_quality_verify_scene($pdo,$org,(string)($in['scenePublicId']??''))],201);
 if($action==='quality.verify')app_json_response(['ok'=>true,'verification'=>glasses_vision_quality_verify($pdo,$org,(string)($in['publicId']??''))]);
 if($action==='final.validate_scene')app_json_response(['ok'=>true,'finalValidation'=>glasses_vision_final_validate_scene($pdo,$org,(string)($in['scenePublicId']??''))],201);
 if($action==='final.verify')app_json_response(['ok'=>true,'verification'=>glasses_vision_final_verify($pdo,$org,(string)($in['publicId']??''))]);
 app_json_response(['ok'=>false,'message'=>'Unsupported Vision Lab action.'],422);
}catch(InvalidArgumentException $e){app_json_response(['ok'=>false,'message'=>$e->getMessage()],422);}catch(Throwable $e){error_log('[gelato-vision-lab] '.$e->getMessage());app_json_response(['ok'=>false,'message'=>'Vision Lab request could not be completed.'],500);}
