<?php
declare(strict_types=1);
require __DIR__ . '/../includes/bootstrap.php';
require __DIR__ . '/../includes/operations-core.php';

$user=app_require_auth();$pdo=app_pdo();$organizationId=(int)$user['organization_id'];$userId=(int)$user['id'];
if(!operations_core_ready($pdo))app_json_response(['ok'=>false,'message'=>'Operations Core migration is not installed. Run upgrade.php.'],503);

function ops_can(array $user,string $permission):bool{return app_has_permission($permission,$user);}
function ops_require(array $user,string $permission):void{if(!ops_can($user,$permission))app_json_response(['ok'=>false,'message'=>'Permission required: '.$permission],403);}
function ops_users(PDO $pdo,int $organizationId):array{$stmt=$pdo->prepare("SELECT DISTINCT u.id,u.display_name,om.job_title FROM users u INNER JOIN organization_memberships om ON om.user_id=u.id AND om.organization_id=? WHERE u.status='active' AND u.archived_at IS NULL ORDER BY u.display_name");$stmt->execute([$organizationId]);return $stmt->fetchAll();}
function ops_categories(PDO $pdo,int $organizationId):array{$stmt=$pdo->prepare("SELECT * FROM task_categories WHERE organization_id=? AND archived_at IS NULL ORDER BY status<>'active',sort_order,name");$stmt->execute([$organizationId]);return $stmt->fetchAll();}
function ops_task_assigned(PDO $pdo,int $organizationId,string $publicId,int $userId):bool{$stmt=$pdo->prepare("SELECT COUNT(*) FROM restaurant_tasks t INNER JOIN restaurant_task_assignments a ON a.task_id=t.id WHERE t.organization_id=? AND t.public_id=? AND a.user_id=? AND t.archived_at IS NULL");$stmt->execute([$organizationId,$publicId,$userId]);return (int)$stmt->fetchColumn()>0;}
function ops_datetime(mixed $value):?string{$value=trim((string)$value);if($value==='')return null;$dt=DateTimeImmutable::createFromFormat('Y-m-d\TH:i',$value)?:DateTimeImmutable::createFromFormat('Y-m-d H:i:s',$value);if(!$dt)app_json_response(['ok'=>false,'message'=>'Invalid date/time value.'],422);return $dt->format('Y-m-d H:i:s');}

if($_SERVER['REQUEST_METHOD']==='GET'){
    $action=(string)($_GET['action']??'summary');
    if($action==='summary'){if(!ops_can($user,'tasks.view')&&!ops_can($user,'inventory.view'))app_json_response(['ok'=>false,'message'=>'Operations view permission required.'],403);app_json_response(['ok'=>true,'summary'=>operations_core_summary($pdo,$organizationId),'categories'=>ops_can($user,'tasks.view')?ops_categories($pdo,$organizationId):[],'users'=>ops_can($user,'tasks.manage')?ops_users($pdo,$organizationId):[]]);}
    if($action==='inventory'){ops_require($user,'inventory.view');$rows=operations_inventory_list($pdo,$organizationId,(string)($_GET['q']??''),(string)($_GET['low']??'0')==='1',750);app_json_response(['ok'=>true,'items'=>$rows]);}
    if($action==='inventory_sources'){ops_require($user,'inventory.view');$id=trim((string)($_GET['id']??''));$item=$pdo->prepare('SELECT * FROM inventory_items WHERE organization_id=? AND public_id=? AND archived_at IS NULL LIMIT 1');$item->execute([$organizationId,$id]);$row=$item->fetch();if(!$row)app_json_response(['ok'=>false,'message'=>'Inventory item not found.'],404);$stmt=$pdo->prepare('SELECT * FROM inventory_item_sources WHERE organization_id=? AND inventory_item_id=? ORDER BY source_type,source_name');$stmt->execute([$organizationId,(int)$row['id']]);$tx=$pdo->prepare('SELECT * FROM inventory_transactions WHERE organization_id=? AND inventory_item_id=? ORDER BY created_at DESC LIMIT 100');$tx->execute([$organizationId,(int)$row['id']]);app_json_response(['ok'=>true,'item'=>$row,'sources'=>$stmt->fetchAll(),'transactions'=>$tx->fetchAll()]);}
    if($action==='tasks'){ops_require($user,'tasks.view');$filters=['category'=>(string)($_GET['category']??''),'status'=>(string)($_GET['status']??''),'query'=>(string)($_GET['q']??'')];if((string)($_GET['mine']??'0')==='1')$filters['userId']=$userId;app_json_response(['ok'=>true,'tasks'=>operations_task_list($pdo,$organizationId,$filters)]);}
    if($action==='task'){ops_require($user,'tasks.view');$task=operations_task_detail($pdo,$organizationId,trim((string)($_GET['id']??'')));if(!$task)app_json_response(['ok'=>false,'message'=>'Task not found.'],404);app_json_response(['ok'=>true,'task'=>$task]);}
    if($action==='categories'){ops_require($user,'tasks.view');app_json_response(['ok'=>true,'categories'=>ops_categories($pdo,$organizationId)]);}
    app_json_response(['ok'=>false,'message'=>'Unsupported Operations Core action.'],422);
}

if($_SERVER['REQUEST_METHOD']!=='POST'){header('Allow: GET, POST');app_json_response(['ok'=>false,'message'=>'Method not allowed.'],405);}
$input=app_json_input();app_verify_request_csrf($input);$action=(string)($input['action']??'');

if($action==='inventory_sync'){
    ops_require($user,'inventory.manage');$result=operations_sync_inventory_sources($pdo,$organizationId,$userId);app_audit($pdo,$organizationId,$userId,'inventory.sources_synced','inventory','all',null,$result);app_json_response(['ok'=>true,'result'=>$result,'message'=>'Inventory source list synchronized from the menu ingredient catalog and active recipes.']);
}
if($action==='inventory_save'){
    ops_require($user,'inventory.manage');$id=trim((string)($input['id']??''));$stmt=$pdo->prepare('SELECT * FROM inventory_items WHERE organization_id=? AND public_id=? AND archived_at IS NULL LIMIT 1');$stmt->execute([$organizationId,$id]);$item=$stmt->fetch();if(!$item)app_json_response(['ok'=>false,'message'=>'Inventory item not found.'],404);$name=mb_substr(trim((string)($input['name']??$item['name'])),0,220,'UTF-8');if($name==='')app_json_response(['ok'=>false,'message'=>'Inventory name is required.'],422);$pdo->prepare('UPDATE inventory_items SET name=?,category=?,base_unit=?,storage_location=?,vendor_name=?,vendor_sku=?,par_level=?,reorder_point=?,unit_cost=?,updated_by=?,updated_at=NOW(6) WHERE id=? AND organization_id=?')->execute([$name,($input['category']??'')?:null,($input['baseUnit']??'')?:null,($input['storageLocation']??'')?:null,($input['vendorName']??'')?:null,($input['vendorSku']??'')?:null,($input['parLevel']??'')!==''?(float)$input['parLevel']:null,($input['reorderPoint']??'')!==''?(float)$input['reorderPoint']:null,($input['unitCost']??'')!==''?(float)$input['unitCost']:null,$userId,(int)$item['id'],$organizationId]);app_audit($pdo,$organizationId,$userId,'inventory.item_updated','inventory_item',$id,null,['name'=>$name]);app_json_response(['ok'=>true,'message'=>'Inventory item updated.']);
}
if($action==='inventory_adjust'){
    ops_require($user,'inventory.manage');$id=trim((string)($input['id']??''));$type=(string)($input['type']??'adjust');if(!isset($input['quantity'])||!is_numeric($input['quantity']))app_json_response(['ok'=>false,'message'=>'A numeric quantity is required.'],422);$item=operations_inventory_adjust($pdo,$organizationId,$id,(float)$input['quantity'],$type,$userId,trim((string)($input['note']??'')));app_audit($pdo,$organizationId,$userId,'inventory.stock_changed','inventory_item',$id,null,['type'=>$type,'quantity'=>$input['quantity'],'result'=>$item['on_hand_quantity']]);app_json_response(['ok'=>true,'item'=>$item,'message'=>'Inventory quantity updated.']);
}
if($action==='category_save'){
    ops_require($user,'tasks.manage');$id=trim((string)($input['id']??''));$name=mb_substr(trim((string)($input['name']??'')),0,140,'UTF-8');if($name==='')app_json_response(['ok'=>false,'message'=>'Category name is required.'],422);if($id===''){$category=operations_create_category($pdo,$organizationId,$name,$userId,mb_substr(trim((string)($input['description']??'')),0,500,'UTF-8'));}else{$stmt=$pdo->prepare('SELECT * FROM task_categories WHERE organization_id=? AND public_id=? AND archived_at IS NULL LIMIT 1');$stmt->execute([$organizationId,$id]);$category=$stmt->fetch();if(!$category)app_json_response(['ok'=>false,'message'=>'Task category not found.'],404);$pdo->prepare('UPDATE task_categories SET name=?,description=?,status=?,sort_order=?,updated_by=?,updated_at=NOW(6) WHERE id=? AND organization_id=?')->execute([$name,mb_substr(trim((string)($input['description']??'')),0,500,'UTF-8')?:null,in_array(($input['status']??'active'),['active','inactive'],true)?$input['status']:'active',(int)($input['sortOrder']??$category['sort_order']),$userId,(int)$category['id'],$organizationId]);$category=operations_category_by_slug($pdo,$organizationId,(string)$category['slug']);}app_audit($pdo,$organizationId,$userId,'tasks.category_saved','task_category',(string)$category['public_id'],null,['name'=>$name]);app_json_response(['ok'=>true,'category'=>$category,'message'=>'Task category saved.']);
}
if($action==='category_archive'){
    ops_require($user,'tasks.manage');$id=trim((string)($input['id']??''));$stmt=$pdo->prepare("UPDATE task_categories SET status='inactive',archived_at=NOW(6),updated_by=?,updated_at=NOW(6) WHERE organization_id=? AND public_id=? AND slug NOT IN ('prep','general')");$stmt->execute([$userId,$organizationId,$id]);if(!$stmt->rowCount())app_json_response(['ok'=>false,'message'=>'Category not found or is a protected system category.'],422);app_audit($pdo,$organizationId,$userId,'tasks.category_archived','task_category',$id);app_json_response(['ok'=>true,'message'=>'Task category archived.']);
}
if($action==='task_save'){
    ops_require($user,'tasks.manage');$id=trim((string)($input['id']??''));$assigneeIds=array_values(array_unique(array_filter(array_map('intval',(array)($input['assigneeIds']??[])))));if($id===''){$payload=$input;$payload['dueAt']=ops_datetime($input['dueAt']??'');$payload['assigneeIds']=$assigneeIds;$task=operations_create_task($pdo,$organizationId,$payload,$userId);app_audit($pdo,$organizationId,$userId,'tasks.created','restaurant_task',(string)$task['public_id'],null,['title'=>$task['title']]);app_json_response(['ok'=>true,'task'=>$task,'message'=>'Task created.'],201);}
    $task=operations_task_by_public_id($pdo,$organizationId,$id);if(!$task)app_json_response(['ok'=>false,'message'=>'Task not found.'],404);$category=operations_category_by_slug($pdo,$organizationId,(string)($input['category']??$task['category_slug']??'general'));if(!$category)app_json_response(['ok'=>false,'message'=>'Task category not found.'],422);$title=mb_substr(trim((string)($input['title']??$task['title'])),0,240,'UTF-8');if($title==='')app_json_response(['ok'=>false,'message'=>'Task title is required.'],422);$priority=(string)($input['priority']??$task['priority']);if(!in_array($priority,['low','normal','high','critical'],true))$priority='normal';$pdo->prepare('UPDATE restaurant_tasks SET category_id=?,title=?,description=?,quantity=?,unit=?,station=?,priority=?,due_at=?,estimated_minutes=?,requires_photo=?,requires_verification=?,updated_by=?,updated_at=NOW(6) WHERE id=? AND organization_id=?')->execute([(int)$category['id'],$title,($input['description']??'')?:null,($input['quantity']??'')!==''?(float)$input['quantity']:null,($input['unit']??'')?:null,($input['station']??'')?:null,$priority,ops_datetime($input['dueAt']??''),($input['estimatedMinutes']??'')!==''?(int)$input['estimatedMinutes']:null,!empty($input['requiresPhoto'])?1:0,!empty($input['requiresVerification'])?1:0,$userId,(int)$task['id'],$organizationId]);$pdo->prepare('DELETE FROM restaurant_task_assignments WHERE organization_id=? AND task_id=?')->execute([$organizationId,(int)$task['id']]);$assign=$pdo->prepare("INSERT IGNORE INTO restaurant_task_assignments (organization_id,task_id,user_id,assignment_role,assigned_by) SELECT ?,?,u.id,'assignee',? FROM users u INNER JOIN organization_memberships om ON om.user_id=u.id AND om.organization_id=? WHERE u.id=? AND u.status='active' AND u.archived_at IS NULL");foreach($assigneeIds as $assigned)$assign->execute([$organizationId,(int)$task['id'],$userId,$organizationId,$assigned]);operations_task_event($pdo,$organizationId,(int)$task['id'],'updated','Task details updated',$userId,['assignees'=>$assigneeIds]);app_audit($pdo,$organizationId,$userId,'tasks.updated','restaurant_task',$id);app_json_response(['ok'=>true,'message'=>'Task updated.']);
}
if($action==='task_status'){
    $id=trim((string)($input['id']??''));$canManage=ops_can($user,'tasks.manage');$canSelf=ops_can($user,'tasks.self')&&ops_task_assigned($pdo,$organizationId,$id,$userId);if(!$canManage&&!$canSelf)app_json_response(['ok'=>false,'message'=>'You can only update tasks assigned to you.'],403);$status=(string)($input['status']??'');if($status==='verified'&&!$canManage)app_json_response(['ok'=>false,'message'=>'Manager verification permission required.'],403);$task=operations_task_by_public_id($pdo,$organizationId,$id);if(!$task)app_json_response(['ok'=>false,'message'=>'Task not found.'],404);if($status==='completed'&&(int)$task['requires_photo']===1){$stmt=$pdo->prepare('SELECT COUNT(*) FROM restaurant_task_proofs WHERE organization_id=? AND task_id=?');$stmt->execute([$organizationId,(int)$task['id']]);if((int)$stmt->fetchColumn()===0)app_json_response(['ok'=>false,'message'=>'Photo proof is required before completing this task.'],422);}operations_task_set_status($pdo,$organizationId,$id,$status,$userId);app_audit($pdo,$organizationId,$userId,'tasks.status_changed','restaurant_task',$id,null,['status'=>$status]);app_json_response(['ok'=>true,'message'=>'Task status updated.']);
}
if($action==='task_timer'){
    $id=trim((string)($input['id']??''));$canManage=ops_can($user,'tasks.manage');$canSelf=ops_can($user,'tasks.self')&&ops_task_assigned($pdo,$organizationId,$id,$userId);if(!$canManage&&!$canSelf)app_json_response(['ok'=>false,'message'=>'You can only track time on tasks assigned to you.'],403);$start=(string)($input['mode']??'start')==='start';$task=operations_task_timer($pdo,$organizationId,$id,$userId,$start);app_json_response(['ok'=>true,'task'=>$task,'message'=>$start?'Task timer started.':'Task timer stopped.']);
}
if($action==='task_delete'){
    ops_require($user,'tasks.manage');$id=trim((string)($input['id']??''));$task=operations_task_by_public_id($pdo,$organizationId,$id);if(!$task)app_json_response(['ok'=>false,'message'=>'Task not found.'],404);if($task['source_type'])app_json_response(['ok'=>false,'message'=>'Source-linked tasks cannot be deleted; cancel them instead.'],422);$pdo->prepare('UPDATE restaurant_tasks SET archived_at=NOW(6),status="cancelled",updated_by=?,updated_at=NOW(6) WHERE id=? AND organization_id=?')->execute([$userId,(int)$task['id'],$organizationId]);operations_task_event($pdo,$organizationId,(int)$task['id'],'archived','Task archived',$userId);app_audit($pdo,$organizationId,$userId,'tasks.archived','restaurant_task',$id);app_json_response(['ok'=>true,'message'=>'Task archived.']);
}
app_json_response(['ok'=>false,'message'=>'Unsupported Operations Core action.'],422);
