<?php
declare(strict_types=1);
require __DIR__.'/../includes/bootstrap.php';
require __DIR__.'/../includes/timeclock-voice-core.php';
require_once __DIR__.'/../includes/prep-intelligence-core.php';
require_once __DIR__.'/../includes/purchasing-proactive.php';
require_once __DIR__.'/../includes/employee-home-core.php';
require_once __DIR__.'/../includes/employee-shift-communications.php';
$user=app_require_auth();$pdo=app_pdo();$org=(int)$user['organization_id'];$uid=(int)$user['id'];if(!tv_ready($pdo))app_json_response(['ok'=>false,'message'=>'Time Clock + Voice Agent migration is not installed. Run upgrade.php.'],503);if(!app_has_permission('agent.proactive',$user))app_json_response(['ok'=>false,'message'=>'Proactive Agent permission required.'],403);
function pa_preferences(PDO $pdo,int $org,int $uid):array{$q=$pdo->prepare('SELECT * FROM proactive_agent_preferences WHERE organization_id=? AND user_id=?');$q->execute([$org,$uid]);$r=$q->fetch();if($r)return $r;$pdo->prepare('INSERT IGNORE INTO proactive_agent_preferences (organization_id,user_id) VALUES (?,?)')->execute([$org,$uid]);$q->execute([$org,$uid]);return $q->fetch()?:[];}
function pa_put(PDO $pdo,int $org,int $uid,string $type,string $priority,string $message,string $dedupe,string $url='',array $meta=[]):void{$pdo->prepare("INSERT INTO proactive_agent_events (organization_id,user_id,public_id,event_type,priority,message,action_url,dedupe_key,metadata_json) VALUES (?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE message=VALUES(message),priority=VALUES(priority),action_url=VALUES(action_url),metadata_json=VALUES(metadata_json)")->execute([$org,$uid,tv_public_id('proactive'),$type,$priority,mb_substr($message,0,1000,'UTF-8'),$url?:null,$dedupe,$meta?json_encode($meta,JSON_UNESCAPED_UNICODE):null]);}
function pa_generate(PDO $pdo,int $org,int $uid,array $prefs,array $user):void{
 $now=new DateTimeImmutable('now');$today=$now->format('Y-m-d');$name=trim((string)($user['first_name']??''))?:trim((string)($user['display_name']??'there'));
 if(!empty($prefs['shift_reminders'])){$q=$pdo->prepare("SELECT public_id,title,starts_at FROM schedule_shifts WHERE organization_id=? AND user_id=? AND archived_at IS NULL AND status<>'cancelled' AND starts_at BETWEEN NOW(6) AND DATE_ADD(NOW(6),INTERVAL 90 MINUTE) ORDER BY starts_at LIMIT 1");$q->execute([$org,$uid]);if($s=$q->fetch()){$mins=max(0,(int)round(((new DateTimeImmutable((string)$s['starts_at']))->getTimestamp()-$now->getTimestamp())/60));pa_put($pdo,$org,$uid,'shift.upcoming','normal',$name.', your '.$s['title'].' shift starts in about '.$mins.' minutes.','shift:'.$s['public_id'].':'.$today,'scheduling.php',['shiftId'=>$s['public_id']]);}}
 if(!empty($prefs['task_reminders'])){try{$q=$pdo->prepare("SELECT t.public_id,t.title,t.due_at,t.priority FROM restaurant_tasks t INNER JOIN restaurant_task_assignments a ON a.task_id=t.id AND a.user_id=? WHERE t.organization_id=? AND t.archived_at IS NULL AND t.status NOT IN ('completed','verified','cancelled') AND t.due_at IS NOT NULL AND t.due_at<=DATE_ADD(NOW(6),INTERVAL 120 MINUTE) ORDER BY t.due_at LIMIT 5");$q->execute([$uid,$org]);foreach($q->fetchAll() as $t){$over=strtotime((string)$t['due_at'])<time();pa_put($pdo,$org,$uid,$over?'task.overdue':'task.due',$over?'high':'normal',($over?'Overdue: ':'Coming up: ').$t['title'].'.','task:'.$t['public_id'].':'.$today,'operations.php',['taskId'=>$t['public_id']]);}}catch(Throwable){}}
 $clock=tv_open_clock($pdo,$org,$uid);if($clock&&!empty($prefs['break_reminders'])){$elapsed=(time()-strtotime((string)$clock['clocked_in_at']))/3600;if($elapsed>=4){$b=$pdo->prepare('SELECT COUNT(*) FROM time_clock_breaks WHERE time_clock_entry_id=?');$b->execute([(int)$clock['id']]);if((int)$b->fetchColumn()===0)pa_put($pdo,$org,$uid,'break.reminder','normal',$name.', you have been clocked in for more than four hours. Check your break plan.','break:'.$clock['public_id'],'timeclock.php');}}
 if(app_has_permission('attendance.view',$user)){foreach(tv_no_shows($pdo,$org) as $s)pa_put($pdo,$org,$uid,'attendance.no_show','high',$s['display_name'].' has not clocked in for '.$s['title'].'.','noshow:'.$s['public_id'].':'.$today,'timeclock.php',['employeeUserId'=>(int)$s['user_id']]);}
 if(employee_home_ready($pdo)&&(app_has_permission('employee.self',$user)||app_has_permission('schedule.self',$user)||app_has_permission('training.self_view',$user)||app_has_permission('tasks.self',$user)||app_has_permission('agent.employee_view',$user))){
   try{
     $ann=employee_home_announcements($pdo,$org,$uid);foreach(array_slice($ann,0,5) as $r){if(empty($r['read_at'])&&in_array((string)$r['priority'],['urgent','high'],true))pa_put($pdo,$org,$uid,'employee.announcement',(string)$r['priority']==='urgent'?'high':'normal','Restaurant update: '.$r['title'].'.','employee-announcement:'.$r['public_id'],'employee-home.php',['announcementId'=>$r['public_id']]);}
     $policies=employee_home_policies($pdo,$org,$uid);foreach(array_slice($policies,0,5) as $r){if((int)$r['requires_acknowledgement']===1&&empty($r['acknowledged_at']))pa_put($pdo,$org,$uid,'employee.policy_ack','normal','Employee policy awaiting acknowledgement: '.$r['title'].' v'.$r['version_label'].'.','employee-policy:'.$r['public_id'].':'.$r['version_label'],'employee-home.php',['policyId'=>$r['public_id']]);}
     $check=employee_home_checklist($pdo,$org,$uid,false);foreach(array_slice($check,0,5) as $r){if(!$r['due_at'])continue;$due=strtotime((string)$r['due_at']);if($due<=time()+86400){$over=$due<time();pa_put($pdo,$org,$uid,'employee.checklist_due',$over?'high':'normal',($over?'Employee checklist overdue: ':'Employee checklist due soon: ').$r['title'].'.','employee-checklist:'.$r['public_id'].':'.date('Y-m-d',$due),'employee-home.php',['checklistId'=>$r['public_id']]);}}
     $training=employee_home_training($pdo,$org,$uid);foreach($training['certifications'] as $r){if((string)$r['status']!=='issued'||!$r['expires_at']||$r['revoked_at'])continue;$expires=strtotime((string)$r['expires_at']);$days=(int)ceil(($expires-time())/86400);if($days>=0&&$days<=30)pa_put($pdo,$org,$uid,'employee.certification_expiring',$days<=7?'high':'normal',$r['certification_type'].' certification expires in '.$days.' day'.($days===1?'':'s').'.','employee-cert:'.$r['id'].':'.date('Y-m-d',$expires),'employee-home.php',['certificationId'=>(int)$r['id'],'days'=>$days]);}
     if(employee_shift_comms_ready($pdo)&&(app_has_permission('employee.handoffs.view',$user)||app_has_permission('employee.self',$user))){
       $messages=employee_shift_messages_for_user($pdo,$org,$uid);foreach(array_slice($messages,0,8) as $r){if(empty($r['read_at'])&&in_array((string)$r['priority'],['urgent','high'],true))pa_put($pdo,$org,$uid,'employee.handoff',(string)$r['priority']==='urgent'?'high':'normal','Shift handoff: '.$r['title'].'.','employee-handoff:'.$r['public_id'],'employee-home.php',['handoffId'=>$r['public_id']]);}
       $brief=employee_shift_arrival_brief($pdo,$org,$uid);$bs=$brief['summary']??[];$count=(int)($bs['unreadHandoffs']??0)+(int)($bs['unreadAnnouncements']??0)+(int)($bs['openTasks']??0);if(!empty($brief['active'])&&$count>0){$clockKey=$clock['public_id']??null;$shiftKey=$brief['shift']['public_id']??$today;$key=$clockKey?:$shiftKey;$parts=[];if((int)($bs['unreadHandoffs']??0)>0)$parts[]=(int)$bs['unreadHandoffs'].' unread handoff'.((int)$bs['unreadHandoffs']===1?'':'s');if((int)($bs['unreadAnnouncements']??0)>0)$parts[]=(int)$bs['unreadAnnouncements'].' unread update'.((int)$bs['unreadAnnouncements']===1?'':'s');if((int)($bs['openTasks']??0)>0)$parts[]=(int)$bs['openTasks'].' open task'.((int)$bs['openTasks']===1?'':'s');pa_put($pdo,$org,$uid,'employee.arrival_brief',(int)($bs['highPriority']??0)>0?'high':'normal',$name.', your arrival brief is ready: '.implode(', ',$parts).'.','employee-arrival:'.$key,'employee-home.php',['shiftId'=>$brief['shift']['public_id']??null,'summary'=>$bs]);}
     }
   }catch(Throwable){}
 }
 if(prep_intelligence_ready($pdo)&&app_has_permission('prep.intelligence.view',$user)){
   try{
     $canPrepForecast=app_has_permission('inventory.forecast.view',$user)||app_has_permission('inventory.view',$user);
     $q=$pdo->prepare("SELECT * FROM prep_plans WHERE organization_id=? AND plan_date=? ORDER BY FIELD(service_period,'all','lunch','dinner','morning','closing') LIMIT 1");$q->execute([$org,$today]);$plan=$q->fetch();
     if($plan){$detail=prep_plan_detail($pdo,$org,(string)$plan['public_id']);if($canPrepForecast){$flagged=array_values(array_filter($detail['forecasts'],static fn(array $f):bool=>(float)$f['shortage_quantity']>0||(float)$f['restock_quantity']>0));if($flagged){$names=array_slice(array_column($flagged,'inventory_name'),0,4);pa_put($pdo,$org,$uid,'inventory.shortage_forecast','high','Prep forecast flags '.count($flagged).' inventory item(s) for shortage or restock: '.implode(', ',$names).'.','prep-shortage:'.$plan['public_id'].':'.$plan['revision'],'prep-intelligence.php',['planId'=>$plan['public_id'],'count'=>count($flagged)]);}}$pending=count(array_filter($detail['recommendations'],static fn(array $r):bool=>in_array($r['status'],['proposed','accepted'],true)));if((string)$plan['status']==='draft'&&$pending>0)pa_put($pdo,$org,$uid,'prep.plan_ready','normal',$pending.' prep recommendation(s) are ready for review before publishing.','prep-ready:'.$plan['public_id'].':'.$plan['revision'],'prep-intelligence.php',['planId'=>$plan['public_id'],'recommendations'=>$pending]);}
     elseif(app_has_permission('prep.intelligence.manage',$user)&&(int)$now->format('G')>=7)pa_put($pdo,$org,$uid,'prep.plan_missing','normal','Today does not have a Prep Intelligence plan yet. Ask “Hey Gelato, what should we prep today?” to build one from history.','prep-missing:'.$today,'prep-intelligence.php',['date'=>$today]);
   }catch(Throwable){}
 }
 if(app_has_permission('purchasing.view',$user)&&purchasing_ready($pdo)){try{foreach(purchasing_proactive_signals($pdo,$org) as $signal)pa_put($pdo,$org,$uid,$signal['type'],$signal['priority'],$signal['message'],$signal['key'],$signal['url'],$signal['meta']);}catch(Throwable){}}
}
if($_SERVER['REQUEST_METHOD']==='GET'){$prefs=pa_preferences($pdo,$org,$uid);if(empty($prefs['listening_enabled']))app_json_response(['ok'=>true,'preferences'=>$prefs,'events'=>[]]);pa_generate($pdo,$org,$uid,$prefs,$user);$q=$pdo->prepare("SELECT public_id,event_type,priority,message,action_url,created_at FROM proactive_agent_events WHERE organization_id=? AND user_id=? AND status='pending' ORDER BY FIELD(priority,'high','normal','low'),created_at LIMIT 10");$q->execute([$org,$uid]);$events=$q->fetchAll();if($events){$ids=array_column($events,'public_id');$marks=implode(',',array_fill(0,count($ids),'?'));$pdo->prepare("UPDATE proactive_agent_events SET status='delivered',delivered_at=NOW(6) WHERE organization_id=? AND public_id IN ($marks)")->execute(array_merge([$org],$ids));}app_json_response(['ok'=>true,'preferences'=>$prefs,'events'=>$events]);}
if($_SERVER['REQUEST_METHOD']!=='POST'){header('Allow: GET, POST');app_json_response(['ok'=>false,'message'=>'Method not allowed.'],405);} $in=app_json_input();app_verify_request_csrf($in);$action=(string)($in['action']??'');if($action==='preferences'){$enabled=!empty($in['listeningEnabled'])?1:0;$voice=!empty($in['proactiveVoiceEnabled'])?1:0;$wake=mb_substr(trim((string)($in['wakePhrase']??'Hey Gelato')),0,120,'UTF-8')?:'Hey Gelato';$pdo->prepare("INSERT INTO proactive_agent_preferences (organization_id,user_id,listening_enabled,proactive_voice_enabled,wake_phrase,last_enabled_at) VALUES (?,?,?,?,?,IF(?=1,NOW(6),NULL)) ON DUPLICATE KEY UPDATE listening_enabled=VALUES(listening_enabled),proactive_voice_enabled=VALUES(proactive_voice_enabled),wake_phrase=VALUES(wake_phrase),last_enabled_at=IF(VALUES(listening_enabled)=1,NOW(6),last_enabled_at),updated_at=NOW(6)")->execute([$org,$uid,$enabled,$voice,$wake,$enabled]);app_audit($pdo,$org,$uid,'agent.listening_preferences','user',(string)$uid,null,['listening'=>$enabled,'voice'=>$voice]);app_json_response(['ok'=>true,'preferences'=>pa_preferences($pdo,$org,$uid),'message'=>$enabled?'Listening Mode enabled with visible browser controls.':'Listening Mode disabled.']);}if($action==='acknowledge'){$id=trim((string)($in['id']??''));$pdo->prepare("UPDATE proactive_agent_events SET status='acknowledged',acknowledged_at=NOW(6) WHERE organization_id=? AND user_id=? AND public_id=?")->execute([$org,$uid,$id]);app_json_response(['ok'=>true]);}app_json_response(['ok'=>false,'message'=>'Unsupported proactive Agent action.'],422);
