<?php
declare(strict_types=1);
require __DIR__ . '/../includes/bootstrap.php';
require __DIR__ . '/../includes/restaurant-brain.php';

if ($_SERVER['REQUEST_METHOD'] !== 'POST') { header('Allow: POST'); app_json_response(['ok'=>false,'message'=>'Method not allowed.'],405); }
app_boot_session();
$input=app_json_input();app_verify_request_csrf($input);
$now=time();$window=array_values(array_filter((array)($_SESSION['wholesale_submit_times']??[]),static fn($ts):bool=>(int)$ts>$now-3600));if(count($window)>=5){header('Retry-After: 3600');app_json_response(['ok'=>false,'message'=>'Too many wholesale requests were submitted from this browser. Please try again later.'],429);}if(trim((string)($input['website_check']??''))!=='')app_json_response(['ok'=>true,'message'=>'Thank you. Your wholesale request was received.']);
$businessName=trim((string)($input['businessName']??''));$contactName=trim((string)($input['contactName']??''));$email=strtolower(trim((string)($input['email']??'')));$phone=trim((string)($input['phone']??''));$website=trim((string)($input['website']??''));$businessType=trim((string)($input['businessType']??''));$location=trim((string)($input['location']??''));$volume=trim((string)($input['estimatedMonthlyVolume']??''));$frequency=trim((string)($input['orderFrequency']??''));$packageSizes=array_values(array_unique(array_filter(array_map(static fn($value):string=>mb_substr(trim((string)$value),0,80,'UTF-8'),(array)($input['packageSizes']??[])))));$flavors=trim((string)($input['flavorsInterest']??''));$privateLabel=!empty($input['privateLabelInterest']);$freezerCapacity=trim((string)($input['freezerCapacity']??''));$fulfillment=trim((string)($input['fulfillmentPreference']??''));$startDate=trim((string)($input['desiredStartDate']??''));$currentSupplier=trim((string)($input['currentSupplier']??''));$notes=trim((string)($input['notes']??''));$consent=!empty($input['consent']);
$errors=[];if($businessName===''||mb_strlen($businessName,'UTF-8')>200)$errors[]='Enter the business name.';if($contactName===''||mb_strlen($contactName,'UTF-8')>180)$errors[]='Enter a contact name.';if(!filter_var($email,FILTER_VALIDATE_EMAIL)||strlen($email)>254)$errors[]='Enter a valid email address.';if($phone!==''&&mb_strlen($phone,'UTF-8')>50)$errors[]='Phone number is too long.';if($website!==''&&(!filter_var($website,FILTER_VALIDATE_URL)||strlen($website)>500))$errors[]='Enter a valid website URL including https://.';if(!$consent)$errors[]='Confirm that we may contact you about wholesale gelato.';if($startDate!==''){$parsed=DateTimeImmutable::createFromFormat('Y-m-d',$startDate);if(!$parsed||$parsed->format('Y-m-d')!==$startDate)$errors[]='Desired start date is invalid.';}if(count($packageSizes)>12)$errors[]='Too many package sizes were selected.';if($errors)app_json_response(['ok'=>false,'message'=>implode(' ',array_unique($errors))],422);
try{$pdo=app_pdo();if(!restaurant_brain_table_ready($pdo,'wholesale_leads'))app_json_response(['ok'=>false,'message'=>'Wholesale intake is being upgraded. Please try again shortly.'],503);$orgId=(int)$pdo->query("SELECT id FROM organizations WHERE status='active' ORDER BY id ASC LIMIT 1")->fetchColumn();if($orgId<1)throw new RuntimeException('No active restaurant organization is configured.');$publicId=restaurant_brain_public_id('wholesale');$statement=$pdo->prepare("INSERT INTO wholesale_leads (organization_id,public_id,business_name,contact_name,email,phone,website,business_type,location_text,estimated_monthly_volume,order_frequency,package_sizes_json,flavors_interest,private_label_interest,freezer_capacity,fulfillment_preference,desired_start_date,current_supplier,notes,source,pipeline_stage,probability_percent) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,'public_wholesale_form','new',10)");$statement->execute([$orgId,$publicId,$businessName,$contactName,$email,$phone?:null,$website?:null,$businessType?:null,$location?:null,$volume?:null,$frequency?:null,json_encode($packageSizes,JSON_THROW_ON_ERROR),$flavors?:null,$privateLabel?1:0,$freezerCapacity?:null,$fulfillment?:null,$startDate?:null,$currentSupplier?:null,$notes?:null]);$leadId=(int)$pdo->lastInsertId();$activity=$pdo->prepare("INSERT INTO wholesale_lead_activities (organization_id,wholesale_lead_id,activity_type,summary,details) VALUES (?,?,'submission','Public wholesale inquiry submitted',?)");$activity->execute([$orgId,$leadId,'Source: wholesale form']);restaurant_brain_sync_wholesale($pdo,$orgId,$leadId,null);app_audit($pdo,$orgId,null,'wholesale.submitted','wholesale_lead',$publicId,null,['businessName'=>$businessName,'contactName'=>$contactName,'businessType'=>$businessType,'pipelineStage'=>'new']);$window[]=$now;$_SESSION['wholesale_submit_times']=$window;app_json_response(['ok'=>true,'id'=>$publicId,'message'=>'Thanks — your wholesale request is in our review pipeline. We will follow up with you directly.'],201);}catch(PDOException $error){app_json_response(['ok'=>false,'message'=>'Wholesale intake is unavailable until the latest database upgrade is installed.'],503);}catch(Throwable $error){app_json_response(['ok'=>false,'message'=>'Your wholesale request could not be saved. Please try again.'],500);}
