<?php
declare(strict_types=1);
require __DIR__.'/../includes/bootstrap.php';
require_once __DIR__.'/../includes/purchasing-receiving.php';
$user=app_require_auth();$pdo=app_pdo();$org=(int)$user['organization_id'];$uid=(int)$user['id'];
if(!purchasing_ready($pdo))app_json_response(['ok'=>false,'message'=>'Purchasing + Receiving migration is not installed. Run upgrade.php.'],503);
function pur_require(array $user,string $permission):void{if(!app_has_permission($permission,$user))app_json_response(['ok'=>false,'message'=>'Permission required: '.$permission],403);}
function pur_inventory(PDO $pdo,int $org):array{$q=$pdo->prepare("SELECT public_id,name,base_unit,on_hand_quantity,par_level,reorder_point,storage_location FROM inventory_items WHERE organization_id=? AND archived_at IS NULL AND status='active' ORDER BY name");$q->execute([$org]);return $q->fetchAll();}
if($_SERVER['REQUEST_METHOD']==='GET'){
    $action=(string)($_GET['action']??'bootstrap');
    if($action==='bootstrap'){pur_require($user,'purchasing.view');app_json_response(['ok'=>true,'summary'=>purchasing_summary($pdo,$org),'vendors'=>app_has_permission('vendors.view',$user)?purchasing_vendors($pdo,$org):[],'contacts'=>app_has_permission('vendors.view',$user)?purchasing_vendor_contacts($pdo,$org):[],'suggestions'=>purchasing_suggestions($pdo,$org),'orders'=>purchasing_orders($pdo,$org),'receipts'=>app_has_permission('receiving.view',$user)?purchasing_receipts($pdo,$org,40):[],'inventory'=>app_has_permission('vendors.manage',$user)?pur_inventory($pdo,$org):[],'canManage'=>app_has_permission('purchasing.manage',$user),'canVendors'=>app_has_permission('vendors.manage',$user),'canReceive'=>app_has_permission('receiving.manage',$user)]);}
    if($action==='vendors'){pur_require($user,'vendors.view');app_json_response(['ok'=>true,'vendors'=>purchasing_vendors($pdo,$org)]);}
    if($action==='contacts'){pur_require($user,'vendors.view');app_json_response(['ok'=>true,'contacts'=>purchasing_vendor_contacts($pdo,$org,trim((string)($_GET['vendor']??'')))]);}
    if($action==='catalog'){pur_require($user,'vendors.view');app_json_response(['ok'=>true,'items'=>purchasing_vendor_catalog($pdo,$org,trim((string)($_GET['vendor']??'')))]);}
    if($action==='suggestions'){pur_require($user,'purchasing.view');app_json_response(['ok'=>true,'suggestions'=>purchasing_suggestions($pdo,$org)]);}
    if($action==='orders'){pur_require($user,'purchasing.view');app_json_response(['ok'=>true,'orders'=>purchasing_orders($pdo,$org,trim((string)($_GET['status']??'')))]);}
    if($action==='order'){pur_require($user,'purchasing.view');$row=purchasing_order($pdo,$org,trim((string)($_GET['id']??'')));if(!$row)app_json_response(['ok'=>false,'message'=>'Purchase order not found.'],404);app_json_response(['ok'=>true,'order'=>$row]);}
    if($action==='receipts'){pur_require($user,'receiving.view');app_json_response(['ok'=>true,'receipts'=>purchasing_receipts($pdo,$org)]);}
    if($action==='prices'){pur_require($user,'purchasing.view');app_json_response(['ok'=>true,'prices'=>purchasing_price_compare($pdo,$org,trim((string)($_GET['q']??'')))]);}
    app_json_response(['ok'=>false,'message'=>'Unsupported purchasing action.'],422);
}
if($_SERVER['REQUEST_METHOD']!=='POST'){header('Allow: GET, POST');app_json_response(['ok'=>false,'message'=>'Method not allowed.'],405);} $in=app_json_input();app_verify_request_csrf($in);$action=(string)($in['action']??'');
try{
    if($action==='vendor_save'){pur_require($user,'vendors.manage');$v=purchasing_save_vendor($pdo,$org,$in,$uid);app_audit($pdo,$org,$uid,'purchasing.vendor_saved','vendor',(string)$v['public_id']);app_json_response(['ok'=>true,'vendor'=>$v,'message'=>'Vendor saved.']);}
    if($action==='vendor_contact_save'){pur_require($user,'vendors.manage');$c=purchasing_save_vendor_contact($pdo,$org,$in,$uid);app_audit($pdo,$org,$uid,'purchasing.vendor_contact_saved','vendor_contact',(string)($c['public_id']??''),null,['vendorId'=>$c['vendor_public_id']??null]);app_json_response(['ok'=>true,'contact'=>$c,'message'=>'Vendor contact saved.']);}
    if($action==='vendor_item_save'){pur_require($user,'vendors.manage');$row=purchasing_save_vendor_item($pdo,$org,$in,$uid);app_audit($pdo,$org,$uid,'purchasing.vendor_item_saved','inventory_vendor_item',(string)($row['public_id']??''));app_json_response(['ok'=>true,'item'=>$row,'message'=>'Vendor catalog item saved.']);}
    if($action==='po_create'){pur_require($user,'purchasing.manage');$po=purchasing_create_order($pdo,$org,trim((string)($in['vendorId']??'')),(array)($in['lines']??[]),$uid,trim((string)($in['expectedDeliveryDate']??''))?:null,trim((string)($in['notes']??'')));app_audit($pdo,$org,$uid,'purchasing.po_created','purchase_order',(string)$po['public_id']);app_json_response(['ok'=>true,'order'=>$po,'message'=>'Draft purchase order created.'],201);}
    if($action==='po_submit'){pur_require($user,'purchasing.manage');$po=purchasing_submit($pdo,$org,trim((string)($in['id']??'')),$uid);app_audit($pdo,$org,$uid,'purchasing.po_submitted','purchase_order',(string)$po['public_id']);app_json_response(['ok'=>true,'order'=>$po,'message'=>'Purchase order marked submitted.']);}
    if($action==='po_cancel'){pur_require($user,'purchasing.manage');$id=trim((string)($in['id']??''));$po=purchasing_order($pdo,$org,$id);if(!$po)throw new RuntimeException('Purchase order not found.');if(in_array($po['status'],['received','cancelled'],true))throw new InvalidArgumentException('A received or already-cancelled purchase order cannot be cancelled.');$pdo->prepare("UPDATE purchase_orders SET status='cancelled',cancelled_at=NOW(6),updated_by=?,updated_at=NOW(6) WHERE organization_id=? AND id=?")->execute([$uid,$org,(int)$po['id']]);purchasing_event($pdo,$org,(int)$po['id'],'cancelled','Purchase order cancelled.',$uid);app_audit($pdo,$org,$uid,'purchasing.po_cancelled','purchase_order',$id);app_json_response(['ok'=>true,'message'=>'Purchase order cancelled.']);}
    if($action==='receive'){pur_require($user,'receiving.manage');$r=purchasing_receive($pdo,$org,trim((string)($in['id']??'')),(array)($in['lines']??[]),$uid,trim((string)($in['invoiceNumber']??'')),trim((string)($in['notes']??'')));app_audit($pdo,$org,$uid,'receiving.goods_received','purchase_order',trim((string)($in['id']??'')),null,['receiptId'=>$r['receiptId'],'status'=>$r['status']]);app_json_response(['ok'=>true]+$r+['message'=>'Receiving posted to inventory.']);}
    app_json_response(['ok'=>false,'message'=>'Unsupported purchasing action.'],422);
}catch(Throwable $e){app_json_response(['ok'=>false,'message'=>$e->getMessage()],422);}
