<?php
declare(strict_types=1);
require __DIR__.'/../includes/bootstrap.php';
require_once __DIR__.'/../includes/purchasing-receiving.php';
$user=app_require_auth();$pdo=app_pdo();$org=(int)$user['organization_id'];$uid=(int)$user['id'];
if(!app_has_permission('purchasing.agent',$user)||!app_has_permission('purchasing.view',$user))app_json_response(['ok'=>false,'message'=>'Purchasing Agent permission required.'],403);
if(!purchasing_ready($pdo))app_json_response(['ok'=>false,'message'=>'Purchasing + Receiving migration is not installed. Run upgrade.php.'],503);
function pur_agent_answer_suggestions(PDO $pdo,int $org):array{$rows=purchasing_suggestions($pdo,$org);if(!$rows)return ['skill'=>'purchasing.suggestions','answer'=>'Inventory is currently above the purchasing thresholds I can verify from pars, reorder points and the next seven days of prep forecasts.','data'=>[],'sources'=>[]];$top=array_slice($rows,0,12);$parts=array_map(static function($r){$vendor=$r['vendor']?' from '.$r['vendor']['name']: ' with no vendor mapped';return $r['name'].': '.round((float)$r['needQuantity'],2).' '.($r['unit']?:'units').$vendor;},$top);return ['skill'=>'purchasing.suggestions','answer'=>'I found '.count($rows).' item(s) with purchasing pressure. '.implode('; ',$parts).'.','data'=>$rows,'sources'=>array_column($rows,'inventoryId')];}
function pur_agent_vendor_by_name(PDO $pdo,int $org,string $text):?array{foreach(purchasing_vendors($pdo,$org) as $v){if($v['status']==='active'&&preg_match('/\b'.preg_quote((string)$v['name'],'/').'\b/iu',$text))return $v;}return null;}
if($_SERVER['REQUEST_METHOD']==='GET')app_json_response(['ok'=>true,'skill'=>'purchasing.summary','summary'=>purchasing_summary($pdo,$org),'alerts'=>array_slice(purchasing_suggestions($pdo,$org),0,8)]);
if($_SERVER['REQUEST_METHOD']!=='POST'){header('Allow: GET, POST');app_json_response(['ok'=>false,'message'=>'Method not allowed.'],405);} $in=app_json_input();app_verify_request_csrf($in);$message=trim((string)($in['message']??''));if($message===''||mb_strlen($message,'UTF-8')>4000)app_json_response(['ok'=>false,'message'=>'Enter a purchasing request no longer than 4,000 characters.'],422);$text=mb_strtolower(preg_replace('/^hey\s+gelato[,\s]*/iu','',$message)??$message,'UTF-8');
try{
    if(preg_match('/\b(?:what|which).*(?:order|buy)|\bneed\s+to\s+order\b|\bpurchase suggestions?\b|\brestock\b/u',$text)){$r=pur_agent_answer_suggestions($pdo,$org);app_audit($pdo,$org,$uid,'agent.purchasing_skill_used','agent_skill',$r['skill'],null,['message'=>mb_substr($message,0,500,'UTF-8')]);app_json_response(['ok'=>true]+$r);}
    if(preg_match('/\b(?:cheapest|best price|compare price|price comparison|who has)\b(?:.*?)([a-z][a-z0-9 \-]{2,})$/u',$text,$m)){$q=trim(preg_replace('/\b(?:cheapest|best price|compare price|price comparison|who has|right now|for|on)\b/u',' ',$m[1]??$text)??'');$rows=purchasing_price_compare($pdo,$org,$q);$answer=$rows?'Best current mapped price for '.$rows[0]['inventory_name'].' is '.$rows[0]['vendor_name'].' at $'.number_format((float)$rows[0]['price_per_pack'],2).' per pack.':'I do not have comparable vendor pricing for that ingredient yet.';app_json_response(['ok'=>true,'skill'=>'purchasing.price_compare','answer'=>$answer,'data'=>$rows,'sources'=>array_values(array_unique(array_column($rows,'inventory_id')))]);}
    if(preg_match('/\b(?:create|build|make)\b.*\b(?:purchase order|po|order)\b/u',$text)){
        if(!app_has_permission('purchasing.manage',$user))app_json_response(['ok'=>false,'message'=>'Purchasing management permission is required to create a purchase order.'],403);$vendor=pur_agent_vendor_by_name($pdo,$org,$message);if(!$vendor)app_json_response(['ok'=>false,'message'=>'Tell me which mapped vendor should receive the draft order. I will create a draft, not transmit it externally.'],422);$rows=array_values(array_filter(purchasing_suggestions($pdo,$org),static fn($r)=>($r['vendor']['id']??'')===$vendor['public_id']));if(!$rows)app_json_response(['ok'=>false,'message'=>'I do not have any current purchasing suggestions mapped to '.$vendor['name'].'.'],422);$po=purchasing_create_order($pdo,$org,(string)$vendor['public_id'],array_map(static fn($r)=>['inventoryId'=>$r['inventoryId'],'packs'=>$r['suggestedPacks'],'packSize'=>$r['vendor']['packSize'],'pricePerPack'=>$r['vendor']['pricePerPack']],$rows),$uid,null,'Draft created by Restaurant Agent from current purchasing suggestions.');app_audit($pdo,$org,$uid,'agent.purchase_order_drafted','purchase_order',(string)$po['public_id'],null,['vendor'=>$vendor['name'],'message'=>$message]);app_json_response(['ok'=>true,'skill'=>'purchasing.create_draft','answer'=>'I created draft '.$po['order_number'].' for '.$vendor['name'].' with '.count($po['items']).' item(s). It has not been submitted or sent to the vendor.','data'=>$po,'sources'=>[(string)$po['public_id']]]);
    }
    if(preg_match('/\b(?:purchase orders?|open orders?|submitted orders?|po status|orders due)\b/u',$text)){$rows=purchasing_orders($pdo,$org);$open=array_values(array_filter($rows,static fn($r)=>in_array($r['status'],['draft','submitted','partially_received'],true)));$answer=$open?'There are '.count($open).' open purchase order(s), including '.implode(', ',array_slice(array_map(static fn($r)=>$r['order_number'].' '.$r['vendor_name'].' ('.$r['status'].')',$open),0,10)).'.':'There are no open purchase orders.';app_json_response(['ok'=>true,'skill'=>'purchasing.orders','answer'=>$answer,'data'=>$open,'sources'=>array_column($open,'public_id')]);}
    if(preg_match('/\b(?:receiving|received|deliveries|receipts)\b/u',$text)){if(!app_has_permission('receiving.view',$user))app_json_response(['ok'=>false,'message'=>'Receiving view permission required.'],403);$rows=purchasing_receipts($pdo,$org,30);$answer=$rows?'The latest receipt is '.$rows[0]['receipt_number'].' from '.$rows[0]['vendor_name'].' on '.$rows[0]['received_at'].'.':'No receiving records are available yet.';app_json_response(['ok'=>true,'skill'=>'receiving.history','answer'=>$answer,'data'=>$rows,'sources'=>array_column($rows,'public_id')]);}
    $s=purchasing_summary($pdo,$org);app_json_response(['ok'=>true,'skill'=>'purchasing.summary','answer'=>'Purchasing snapshot: '.$s['suggestions'].' suggested item(s), '.$s['unmapped'].' without a mapped vendor, '.$s['drafts'].' draft PO(s), '.$s['openOrders'].' open order(s), and $'.number_format($s['committed'],2).' committed.','data'=>$s,'sources'=>[]]);
}catch(Throwable $e){app_json_response(['ok'=>false,'message'=>$e->getMessage()],422);}
