<?php
declare(strict_types=1);
require __DIR__.'/../includes/bootstrap.php';
require_once __DIR__.'/../includes/purchasing-receiving.php';
$user=app_require_auth();$pdo=app_pdo();$org=(int)$user['organization_id'];$uid=(int)$user['id'];
if($_SERVER['REQUEST_METHOD']!=='POST'){header('Allow: POST');app_json_response(['ok'=>false,'message'=>'Method not allowed.'],405);}app_verify_request_csrf();
if(!purchasing_ready($pdo)||!purchasing_documents_ready($pdo))app_json_response(['ok'=>false,'message'=>'Purchasing document migration is not installed. Run upgrade.php.'],503);
$targetType=(string)($_POST['targetType']??'purchase_order');$targetId=trim((string)($_POST['targetId']??''));$documentType=(string)($_POST['documentType']??'invoice');if(!in_array($documentType,['invoice','receipt','packing_slip','credit','other'],true))$documentType='other';
$po=null;$receipt=null;if($targetType==='purchase_order'){if(!app_has_permission('purchasing.manage',$user))app_json_response(['ok'=>false,'message'=>'Purchasing management permission required.'],403);$po=purchasing_order($pdo,$org,$targetId);if(!$po)app_json_response(['ok'=>false,'message'=>'Purchase order not found.'],404);}elseif($targetType==='receipt'){if(!app_has_permission('receiving.manage',$user))app_json_response(['ok'=>false,'message'=>'Receiving management permission required.'],403);$q=$pdo->prepare('SELECT r.*,po.public_id purchase_order_public_id FROM goods_receipts r INNER JOIN purchase_orders po ON po.id=r.purchase_order_id AND po.organization_id=r.organization_id WHERE r.organization_id=? AND r.public_id=? LIMIT 1');$q->execute([$org,$targetId]);$receipt=$q->fetch();if(!$receipt)app_json_response(['ok'=>false,'message'=>'Receiving record not found.'],404);$po=purchasing_order($pdo,$org,(string)$receipt['purchase_order_public_id']);}else app_json_response(['ok'=>false,'message'=>'Invalid purchasing document target.'],422);
if(!isset($_FILES['document'])||!is_array($_FILES['document']))app_json_response(['ok'=>false,'message'=>'Choose an invoice, receipt, packing slip, or related document.'],422);$file=$_FILES['document'];if((int)($file['error']??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_OK)app_json_response(['ok'=>false,'message'=>'The purchasing document upload failed.'],422);$size=(int)($file['size']??0);if($size<1||$size>10*1024*1024)app_json_response(['ok'=>false,'message'=>'Purchasing documents must be 10 MB or smaller.'],422);$tmp=(string)($file['tmp_name']??'');if($tmp===''||!is_uploaded_file($tmp))app_json_response(['ok'=>false,'message'=>'The uploaded purchasing document is invalid.'],422);
$finfo=new finfo(FILEINFO_MIME_TYPE);$mime=(string)$finfo->file($tmp);$allowed=['image/jpeg'=>'jpg','image/png'=>'png','image/webp'=>'webp','application/pdf'=>'pdf'];if(!isset($allowed[$mime]))app_json_response(['ok'=>false,'message'=>'Use a JPEG, PNG, WebP, or PDF purchasing document.'],422);$bytes=file_get_contents($tmp);if(!is_string($bytes)||$bytes==='')app_json_response(['ok'=>false,'message'=>'The uploaded purchasing document could not be read.'],422);
$checksum=hash('sha256',$bytes);$stored='purchasing-'.bin2hex(random_bytes(16)).'.'.$allowed[$mime];$privateRoot=dirname(RESTAURANT_APP_ROOT).'/gelato-private-storage';$relative='purchasing-documents/'.$org.'/'.$stored;$absolute=$privateRoot.'/'.$relative;$directory=dirname($absolute);if(!is_dir($directory)&&!mkdir($directory,0700,true)&&!is_dir($directory))app_json_response(['ok'=>false,'message'=>'Private purchasing-document storage could not be created outside the public application root.'],500);@chmod($privateRoot,0700);@chmod(dirname($directory),0700);@chmod($directory,0700);if(file_put_contents($absolute,$bytes,LOCK_EX)===false)app_json_response(['ok'=>false,'message'=>'The purchasing document could not be stored.'],500);@chmod($absolute,0600);
try{$pdo->beginTransaction();$insert=$pdo->prepare("INSERT INTO files (organization_id,storage_driver,storage_path,original_name,stored_name,mime_type,file_size,checksum_sha256,uploaded_by,visibility) VALUES (?,'local_private',?,?,?,?,?,?,?,'organization_private')");$insert->execute([$org,$relative,mb_substr((string)($file['name']??'purchasing-document'),0,255,'UTF-8'),$stored,$mime,$size,$checksum,$uid]);$fileId=(int)$pdo->lastInsertId();$public=purchasing_public_id('pdoc');$pdo->prepare('INSERT INTO purchasing_documents (organization_id,public_id,purchase_order_id,goods_receipt_id,file_id,document_type,notes,created_by) VALUES (?,?,?,?,?,?,?,?)')->execute([$org,$public,(int)$po['id'],$receipt?(int)$receipt['id']:null,$fileId,$documentType,mb_substr(trim((string)($_POST['notes']??'')),0,1000,'UTF-8')?:null,$uid]);purchasing_event($pdo,$org,(int)$po['id'],'document_uploaded',ucwords(str_replace('_',' ',$documentType)).' uploaded',$uid,['documentId'=>$public,'receiptId'=>$receipt['public_id']??null,'mime'=>$mime]);$pdo->commit();}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();@unlink($absolute);app_json_response(['ok'=>false,'message'=>'The purchasing document record could not be saved.'],500);}
app_audit($pdo,$org,$uid,'purchasing.document_uploaded','purchase_order',(string)$po['public_id'],null,['documentId'=>$public,'documentType'=>$documentType,'receiptId'=>$receipt['public_id']??null]);app_json_response(['ok'=>true,'documentId'=>$public,'message'=>'Purchasing document uploaded privately.'],201);
