<?php
declare(strict_types=1);
require __DIR__.'/../includes/bootstrap.php';
require_once __DIR__.'/../includes/sales-intelligence-core.php';

$user=app_require_auth();$pdo=app_pdo();$org=(int)$user['organization_id'];$uid=(int)$user['id'];
if(!app_has_permission('sales.view',$user)||!app_has_permission('sales.agent',$user))app_json_response(['ok'=>false,'message'=>'Sales Agent permission required.'],403);
if($_SERVER['REQUEST_METHOD']!=='POST'){header('Allow: POST');app_json_response(['ok'=>false,'message'=>'Method not allowed.'],405);}if(!sales_intelligence_ready($pdo))app_json_response(['ok'=>false,'message'=>'Sales Intelligence migration is not installed. Run upgrade.php.'],503);
$in=app_json_input();app_verify_request_csrf($in);$message=trim((string)($in['message']??''));if($message===''||mb_strlen($message,'UTF-8')>2000)app_json_response(['ok'=>false,'message'=>'Enter a sales request no longer than 2,000 characters.'],422);$text=mb_strtolower(preg_replace('/^hey\s+gelato[,\s]*/iu','',$message)??$message,'UTF-8');

function sales_agent_dates(string $text): array
{
    $today=new DateTimeImmutable('today');if(preg_match('/\byesterday\b/u',$text)){$d=$today->modify('-1 day');return [$d->format('Y-m-d'),$d->format('Y-m-d')];}if(preg_match('/\bthis week\b/u',$text)){$start=$today->modify('monday this week');return [$start->format('Y-m-d'),$today->format('Y-m-d')];}if(preg_match('/\blast week\b/u',$text)){$start=$today->modify('monday last week');return [$start->format('Y-m-d'),$start->modify('+6 days')->format('Y-m-d')];}if(preg_match('/\bthis month\b/u',$text))return [$today->format('Y-m-01'),$today->format('Y-m-d')];if(preg_match('/\blast month\b/u',$text)){$d=$today->modify('first day of last month');return [$d->format('Y-m-01'),$d->format('Y-m-t')];}if(preg_match('/\b(\d{4}-\d{2}-\d{2})\b/',$text,$m))return [$m[1],$m[1]];return [$today->format('Y-m-d'),$today->format('Y-m-d')];
}
function sales_agent_forecast_date(string $text): string
{
    $today=new DateTimeImmutable('today');if(preg_match('/\btomorrow\b/u',$text))return $today->modify('+1 day')->format('Y-m-d');if(preg_match('/\b(\d{4}-\d{2}-\d{2})\b/',$text,$m))return $m[1];$days=['monday'=>1,'tuesday'=>2,'wednesday'=>3,'thursday'=>4,'friday'=>5,'saturday'=>6,'sunday'=>7];foreach($days as $name=>$n)if(preg_match('/\b'.$name.'\b/u',$text)){$delta=($n-(int)$today->format('N')+7)%7;if($delta===0)$delta=7;return $today->modify('+'.$delta.' days')->format('Y-m-d');}return $today->modify('+1 day')->format('Y-m-d');
}
function sales_agent_service(string $text): string { foreach(['morning','lunch','dinner','closing'] as $s)if(preg_match('/\b'.$s.'\b/u',$text))return $s;return 'all'; }

try{
    if(preg_match('/\b(forecast|projected|project|expect|demand|staffing capacity|labor need|labor needs|how busy|what will .* look like)\b/u',$text)){
        $date=sales_agent_forecast_date($text);$service=sales_agent_service($text);$forecast=sales_forecast($pdo,$org,$date,$service,null,$uid,8);$f=$forecast['forecast'];$parts=[];$parts[]=$date.' '.($service==='all'?'full day':$service).' forecast: $'.number_format((float)$f['projected_net_sales'],0).' net sales';if($f['projected_covers']!==null)$parts[]=number_format((float)$f['projected_covers'],0).' covers';if($f['projected_labor_hours']!==null)$parts[]=number_format((float)$f['projected_labor_hours'],1).' estimated labor hours versus '.number_format((float)$f['scheduled_labor_hours'],1).' currently scheduled';$gap=$f['projected_labor_hours']!==null?(float)$f['scheduled_labor_hours']-(float)$f['projected_labor_hours']:null;if($gap!==null)$parts[]=$gap<0?number_format(abs($gap),1).' fewer scheduled hours than the historical demand ratio suggests':number_format($gap,1).' more scheduled hours than the historical demand ratio suggests';$parts[]='Confidence '.number_format((float)$f['confidence']*100,0).'% from '.(int)$f['sample_count'].' comparable dates.';$parts[]='This is a position/daypart capacity signal only; Gelato does not decide which employee should gain or lose a shift.';app_audit($pdo,$org,$uid,'agent.sales_forecast_used','sales_forecast',(string)$f['public_id'],null,['date'=>$date,'service'=>$service]);app_json_response(['ok'=>true,'skill'=>'sales.forecast','answer'=>implode('. ',$parts),'data'=>$forecast,'sources'=>['sales-intelligence.php']]);
    }
    [$from,$to]=sales_agent_dates($text);$data=sales_dashboard($pdo,$org,$from,$to,null);$t=$data['totals'];
    if(preg_match('/\b(top|best selling|best-selling|item mix|items|menu item|menu items|products)\b/u',$text)){$items=array_slice($data['items'],0,10);$answer=$items?implode('; ',array_map(static fn(array $r):string=>$r['item_name'].' — '.number_format((float)$r['quantity'],1).' sold / $'.number_format((float)$r['net_sales'],2),$items)):'No item-level sales rows are recorded for that range.';app_json_response(['ok'=>true,'skill'=>'sales.item_mix','answer'=>$answer,'data'=>['from'=>$from,'to'=>$to,'items'=>$items],'sources'=>['sales-intelligence.php']]);}
    if(preg_match('/\b(labor percent|labor percentage|sales per labor hour|labor cost|labor efficiency)\b/u',$text)){$answer='From '.$from.' through '.$to.': $'.number_format((float)$t['netSales'],2).' net sales, '.number_format((float)$t['actualLaborHours'],1).' actual labor hours and $'.number_format((float)$t['actualLaborCost'],2).' recorded labor cost.';if($t['laborPercent']!==null)$answer.=' Labor cost is '.number_format((float)$t['laborPercent'],1).'% of net sales.';if($t['salesPerLaborHour']!==null)$answer.=' Sales per labor hour are $'.number_format((float)$t['salesPerLaborHour'],2).'.';app_json_response(['ok'=>true,'skill'=>'sales.labor','answer'=>$answer,'data'=>['from'=>$from,'to'=>$to,'totals'=>$t],'sources'=>['sales-intelligence.php']]);}
    $answer='From '.$from.' through '.$to.', recorded net sales are $'.number_format((float)$t['netSales'],2).' across '.number_format((int)$t['tickets']).' tickets';if($t['covers']>0)$answer.=' and '.number_format((int)$t['covers']).' covers';if($t['averageCheck']!==null)$answer.='. Average check is $'.number_format((float)$t['averageCheck'],2);$answer.='.';app_json_response(['ok'=>true,'skill'=>'sales.summary','answer'=>$answer,'data'=>['from'=>$from,'to'=>$to,'dashboard'=>$data],'sources'=>['sales-intelligence.php']]);
}catch(InvalidArgumentException $e){app_json_response(['ok'=>false,'message'=>$e->getMessage()],422);}catch(Throwable $e){app_json_response(['ok'=>false,'message'=>$e->getMessage()],500);}
