<?php
declare(strict_types=1);
require __DIR__.'/../includes/bootstrap.php';
require_once __DIR__.'/../includes/sales-cost-core.php';

$user=app_require_auth();$pdo=app_pdo();$org=(int)$user['organization_id'];$uid=(int)$user['id'];
if(!(app_has_permission('sales.costs.view',$user)||app_has_permission('sales.view',$user))||!app_has_permission('sales.agent',$user))app_json_response(['ok'=>false,'message'=>'Sales cost Agent permission required.'],403);
if($_SERVER['REQUEST_METHOD']!=='POST'){header('Allow: POST');app_json_response(['ok'=>false,'message'=>'Method not allowed.'],405);}if(!sales_cost_ready($pdo))app_json_response(['ok'=>false,'message'=>'Sales Cost Intelligence migration is not installed. Run upgrade.php.'],503);
$in=app_json_input();app_verify_request_csrf($in);$message=trim((string)($in['message']??''));if($message===''||mb_strlen($message,'UTF-8')>2000)app_json_response(['ok'=>false,'message'=>'Enter a cost or margin request no longer than 2,000 characters.'],422);$text=mb_strtolower(preg_replace('/^hey\s+gelato[,\s]*/iu','',$message)??$message,'UTF-8');

function sales_cost_agent_dates(string $text): array {
    $today=new DateTimeImmutable('today');if(preg_match('/\byesterday\b/u',$text)){$d=$today->modify('-1 day');return [$d->format('Y-m-d'),$d->format('Y-m-d')];}if(preg_match('/\bthis week\b/u',$text))return [$today->modify('monday this week')->format('Y-m-d'),$today->format('Y-m-d')];if(preg_match('/\blast week\b/u',$text)){$d=$today->modify('monday last week');return [$d->format('Y-m-d'),$d->modify('+6 days')->format('Y-m-d')];}if(preg_match('/\bthis month\b/u',$text))return [$today->format('Y-m-01'),$today->format('Y-m-d')];if(preg_match('/\blast month\b/u',$text)){$d=$today->modify('first day of last month');return [$d->format('Y-m-01'),$d->format('Y-m-t')];}return [$today->modify('-29 days')->format('Y-m-d'),$today->format('Y-m-d')];
}

try{
    [$from,$to]=sales_cost_agent_dates($text);$r=sales_cost_report($pdo,$org,$from,$to,null);$t=$r['totals'];$answer='';$skill='sales.cost.summary';
    if(preg_match('/\b(rising|increase|increasing|price drift|cost drift|vendor price|prices up|costs up)\b/u',$text)){$skill='sales.cost.drift';$rows=array_slice($r['priceDrift'],0,8);$answer=$rows?implode('; ',array_map(static fn($x)=>$x['inventoryItem'].' '.($x['changePercent']>=0?'+':'').number_format((float)$x['changePercent'],1).'%',$rows)):'No comparable vendor price-history pairs are available yet.';}
    elseif(preg_match('/\b(best margin|highest margin|most profitable|profitability|item margin|item margins)\b/u',$text)){$skill='sales.cost.items';$rows=array_values(array_filter($r['items'],static fn($x)=>$x['grossMarginPercent']!==null));usort($rows,static fn($a,$b)=>(float)$b['grossMarginPercent']<=>(float)$a['grossMarginPercent']);$rows=array_slice($rows,0,8);$answer=$rows?implode('; ',array_map(static fn($x)=>$x['itemName'].' '.number_format((float)$x['grossMarginPercent'],1).'% gross margin before labor/overhead',$rows)):'No sold items have enough mapped cost data for a margin comparison yet.';}
    elseif(preg_match('/\b(waste|spoilage)\b/u',$text)){$skill='sales.cost.waste';$answer='Recorded waste is '.number_format((int)$r['waste']['transactions']).' transactions with an estimated current-cost value of $'.number_format((float)$r['waste']['currentCost'],2).'. This values waste using current inventory unit cost, not historical lot cost.';}
    elseif(preg_match('/\b(purchase|purchases|receipts|receiving|bought|spend)\b/u',$text)){$skill='sales.cost.purchasing';$answer='Recognized received-purchase spend is $'.number_format((float)$r['purchaseSpend']['recognizedSpend'],2).' across '.number_format((int)$r['purchaseSpend']['pricedLines']).' priced receipt lines'.((int)$r['purchaseSpend']['unpricedLines']>0?', with '.(int)$r['purchaseSpend']['unpricedLines'].' unpriced lines':'').'. Purchase spend is inventory inflow and is not treated as period COGS.';}
    else{$coverage=(float)$t['costCoveragePercent'];$answer='For '.$from.' through '.$to.': net sales $'.number_format((float)$t['netSales'],2).'; cost-mapped item sales $'.number_format((float)$t['costedItemSales'],2).' of $'.number_format((float)$t['trackedItemSales'],2).' tracked item sales ('.number_format($coverage,1).'% coverage); known-item theoretical COGS $'.number_format((float)$t['theoreticalCogsKnownItems'],2).'; known-item gross margin '.($t['grossMarginKnownItemsPercent']===null?'not available':number_format((float)$t['grossMarginKnownItemsPercent'],1).'%').' before labor and overhead. Purchase receipts were $'.number_format((float)$t['purchaseReceipts'],2).' and recorded waste at current cost was $'.number_format((float)$t['wasteCurrentCost'],2).'.';}
    app_audit($pdo,$org,$uid,'agent.sales_cost_used','sales_cost_report',$from.'_'.$to,null,['skill'=>$skill]);app_json_response(['ok'=>true,'skill'=>$skill,'answer'=>$answer,'data'=>['from'=>$from,'to'=>$to,'totals'=>$t],'sources'=>['sales-cost-intelligence.php']]);
}catch(Throwable $e){app_json_response(['ok'=>false,'message'=>$e->getMessage()],$e instanceof InvalidArgumentException?422:500);}
