<?php
declare(strict_types=1);
require __DIR__.'/../includes/bootstrap.php';
require __DIR__.'/../includes/scheduling-core.php';

$user=app_require_auth();$pdo=app_pdo();$organizationId=(int)$user['organization_id'];$userId=(int)$user['id'];
if(!scheduling_core_ready($pdo))app_json_response(['ok'=>false,'message'=>'Staff Scheduling migration is not installed. Run upgrade.php.'],503);
if(!app_has_permission('schedule.agent',$user))app_json_response(['ok'=>false,'message'=>'Scheduling Agent permission required.'],403);
if($_SERVER['REQUEST_METHOD']!=='POST'){header('Allow: POST');app_json_response(['ok'=>false,'message'=>'Method not allowed.'],405);}
$input=app_json_input();app_verify_request_csrf($input);$message=trim((string)($input['message']??''));if($message==='')app_json_response(['ok'=>false,'message'=>'Ask Gelato a scheduling question.'],422);$week=scheduling_week_start((string)($input['week']??''));

function sa_staff_match(array $staff,string $query):?array{$query=mb_strtolower(trim($query),'UTF-8');if($query==='')return null;$exact=[];$partial=[];foreach($staff as $s){foreach(array_filter([(string)($s['preferred_name']??''),(string)($s['display_name']??''),(string)($s['first_name']??'')]) as $name){$n=mb_strtolower($name,'UTF-8');if($n===$query)$exact[]=$s;elseif(str_contains($n,$query)||str_contains($query,$n))$partial[]=$s;}}return $exact[0]??($partial[0]??null);}
function sa_day_date(string $text,string $week):?string{$days=['monday'=>0,'tuesday'=>1,'wednesday'=>2,'thursday'=>3,'friday'=>4,'saturday'=>5,'sunday'=>6];foreach($days as $name=>$offset)if(preg_match('/\b'.$name.'\b/i',$text))return (new DateTimeImmutable($week))->modify('+'.$offset.' days')->format('Y-m-d');if(preg_match('/\b(20\d{2}-\d{2}-\d{2})\b/',$text,$m))return $m[1];return null;}
function sa_time(string $raw,bool $end=false):?string{$raw=strtolower(trim($raw));if(!preg_match('/^(\d{1,2})(?::(\d{2}))?\s*(am|pm)?$/',$raw,$m))return null;$h=(int)$m[1];$min=(int)($m[2]??0);$ap=$m[3]??'';if($ap==='pm'&&$h<12)$h+=12;if($ap==='am'&&$h===12)$h=0;if($ap===''&&$h<=10&&$end)$h+=12;if($ap===''&&$h>=1&&$h<=8&&!$end)$h+=12;if($h>23||$min>59)return null;return sprintf('%02d:%02d',$h,$min);}
function sa_staff_schedule_answer(PDO $pdo,int $org,string $week,array $staffRow):string{$rows=scheduling_shifts($pdo,$org,$week,(int)$staffRow['user_id']);if(!$rows)return ($staffRow['preferred_name']?:$staffRow['display_name']).' has no shifts scheduled for the week of '.$week.'.';$parts=[];foreach($rows as $s)$parts[]=date('D M j',strtotime($s['starts_at'])).' '.date('g:i A',strtotime($s['starts_at'])).'–'.date('g:i A',strtotime($s['ends_at'])).' '.$s['title'];return ($staffRow['preferred_name']?:$staffRow['display_name']).': '.implode('; ',$parts).'.';}

try{
    $staff=scheduling_staff($pdo,$organizationId);$lower=mb_strtolower($message,'UTF-8');$skill='schedule.summary';$answer='';
    if(preg_match('/\b(schedule|assign)\s+(.+?)\s+(monday|tuesday|wednesday|thursday|friday|saturday|sunday|20\d{2}-\d{2}-\d{2})\s+(?:from\s+)?([0-9: ]+(?:am|pm)?)\s+(?:to|-)\s+([0-9: ]+(?:am|pm)?)/i',$message,$m)){
        if(!app_has_permission('schedule.manage',$user))app_json_response(['ok'=>false,'message'=>'Schedule manage permission is required for Agent shift creation.'],403);$person=sa_staff_match($staff,trim($m[2]));if(!$person)throw new InvalidArgumentException('I could not match that employee name.');$date=sa_day_date($m[3],$week);$start=sa_time(trim($m[4]),false);$end=sa_time(trim($m[5]),true);if(!$date||!$start||!$end)throw new InvalidArgumentException('I could not parse the requested shift date/time. Try “schedule Anthony Friday 4 pm to 10 pm”.');$shift=scheduling_shift_save($pdo,$organizationId,['title'=>($person['job_title']?:'Shift'),'startsAt'=>$date.' '.$start.':00','endsAt'=>$date.' '.$end.':00','userId'=>(int)$person['user_id'],'status'=>'scheduled','enforceAvailability'=>true],$userId);$skill='schedule.shift_create';$answer='Scheduled '.($person['preferred_name']?:$person['display_name']).' on '.date('l M j',strtotime($shift['starts_at'])).' from '.date('g:i A',strtotime($shift['starts_at'])).' to '.date('g:i A',strtotime($shift['ends_at'])).'.';app_audit($pdo,$organizationId,$userId,'schedule.agent_shift_created','schedule_shift',(string)$shift['public_id'],null,['transcript'=>$message]);
    } elseif(preg_match('/\b(who\s+(?:is\s+)?works?|who\s+is\s+working|working)\b/i',$message)&&($date=sa_day_date($message,$week))){
        $rows=array_values(array_filter(scheduling_shifts($pdo,$organizationId,$week),fn($s)=>substr((string)$s['starts_at'],0,10)===$date&&$s['status']!=='cancelled'));$skill='schedule.day_roster';if(!$rows)$answer='No shifts are scheduled for '.date('l M j',strtotime($date)).'.';else{$parts=[];foreach($rows as $s)$parts[]=($s['display_name']?:'Open shift').' '.date('g:i A',strtotime($s['starts_at'])).'–'.date('g:i A',strtotime($s['ends_at'])).($s['position_name']?' '.$s['position_name']:'');$answer=date('l M j',strtotime($date)).': '.implode('; ',$parts).'.';}
    } elseif(preg_match('/\b(open|unassigned)\s+shifts?\b/i',$message)){
        $rows=array_values(array_filter(scheduling_shifts($pdo,$organizationId,$week),fn($s)=>!$s['user_id']&&$s['status']==='open'));$skill='schedule.open_shifts';if(!$rows)$answer='There are no open shifts for the week of '.$week.'.';else{$parts=[];foreach($rows as $s)$parts[]=date('D M j',strtotime($s['starts_at'])).' '.date('g:i A',strtotime($s['starts_at'])).'–'.date('g:i A',strtotime($s['ends_at'])).' '.$s['title'];$answer=count($rows).' open shift'.(count($rows)===1?'':'s').': '.implode('; ',$parts).'.';}
    } elseif(preg_match('/\b(coverage|short staffed|short-staffed|staffing gap|staffing gaps)\b/i',$message)){
        $coverage=scheduling_coverage($pdo,$organizationId,$week);$gaps=array_values(array_filter($coverage,fn($x)=>(int)$x['gap']>0));$skill='schedule.coverage';if(!$gaps)$answer='No minimum-staff coverage gaps are detected for the week of '.$week.'.';else{$parts=[];foreach($gaps as $x)$parts[]=date('D M j',strtotime($x['date'])).' '.$x['label'].' is '.$x['gap'].' short ('.$x['scheduled'].' scheduled / '.$x['minimum'].' minimum)';$answer='Coverage gaps: '.implode('; ',$parts).'.';}
    } elseif(preg_match('/\b(workload|task hours|prep hours|labor hours)\b/i',$message)){
        $summary=scheduling_summary($pdo,$organizationId,$week);$skill='schedule.workload';$answer='Week of '.$week.': '.$summary['scheduledHours'].' scheduled labor hours, '.$summary['taskHours'].' open task/prep hours, '.$summary['shiftCount'].' shifts, '.$summary['openShifts'].' open shifts, and '.$summary['coverageGaps'].' coverage gaps.';
    } elseif(preg_match('/\b(available|availability)\b/i',$message)&&($date=sa_day_date($message,$week))){
        $skill='schedule.availability';$available=[];foreach($staff as $s){$ok=scheduling_availability_check($pdo,$organizationId,(int)$s['user_id'],$date.' 16:00:00',$date.' 22:00:00');if($ok['ok'])$available[]=$s['preferred_name']?:$s['display_name'];}$answer=$available?'Available for a 4 PM–10 PM check on '.date('l M j',strtotime($date)).': '.implode(', ',$available).'.':'No staff match the recorded availability for 4 PM–10 PM on '.date('l M j',strtotime($date)).'.';
    } else {
        $matched=null;foreach($staff as $s){$names=array_filter([(string)($s['preferred_name']??''),(string)($s['display_name']??''),(string)($s['first_name']??'')]);foreach($names as $name)if($name!==''&&preg_match('/\b'.preg_quote($name,'/').'\b/i',$message)){$matched=$s;break 2;}}
        if($matched&&preg_match('/\b(schedule|shifts?|working)\b/i',$message)){$skill='schedule.employee';$answer=sa_staff_schedule_answer($pdo,$organizationId,$week,$matched);}else{$summary=scheduling_summary($pdo,$organizationId,$week);$skill='schedule.summary';$answer='Week of '.$week.': '.$summary['scheduledHours'].' labor hours across '.$summary['shiftCount'].' shifts, '.$summary['openShifts'].' open shifts, '.$summary['scheduledStaff'].' scheduled staff, '.$summary['coverageGaps'].' coverage gaps, and '.$summary['taskHours'].' open task hours.';}
    }
    app_audit($pdo,$organizationId,$userId,'schedule.agent_skill_used','schedule',$skill,null,['message'=>$message]);app_json_response(['ok'=>true,'skill'=>$skill,'answer'=>$answer,'week'=>$week]);
}catch(Throwable $e){app_json_response(['ok'=>false,'message'=>$e->getMessage()],$e instanceof InvalidArgumentException?422:500);}
