<?php
declare(strict_types=1);
require __DIR__ . '/../includes/bootstrap.php';
require __DIR__ . '/../includes/operations-core.php';
$user=app_require_auth();$pdo=app_pdo();$organizationId=(int)$user['organization_id'];$userId=(int)$user['id'];
if($_SERVER['REQUEST_METHOD']!=='POST'){header('Allow: POST');app_json_response(['ok'=>false,'message'=>'Method not allowed.'],405);}app_verify_request_csrf();
if(!operations_core_ready($pdo))app_json_response(['ok'=>false,'message'=>'Operations Core migration is not installed. Run upgrade.php.'],503);
$taskId=trim((string)($_POST['taskId']??''));$task=operations_task_by_public_id($pdo,$organizationId,$taskId);if(!$task)app_json_response(['ok'=>false,'message'=>'Task not found.'],404);
$canManage=app_has_permission('tasks.manage',$user);$assigned=false;$stmt=$pdo->prepare('SELECT COUNT(*) FROM restaurant_task_assignments WHERE organization_id=? AND task_id=? AND user_id=?');$stmt->execute([$organizationId,(int)$task['id'],$userId]);$assigned=(int)$stmt->fetchColumn()>0;
if(!$canManage&&!(app_has_permission('tasks.proof',$user)&&$assigned))app_json_response(['ok'=>false,'message'=>'You can only upload proof to tasks assigned to you.'],403);
if(!isset($_FILES['image'])||!is_array($_FILES['image']))app_json_response(['ok'=>false,'message'=>'Choose a task proof image.'],422);$file=$_FILES['image'];if((int)($file['error']??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_OK)app_json_response(['ok'=>false,'message'=>'The task proof upload failed.'],422);$size=(int)($file['size']??0);if($size<1||$size>10*1024*1024)app_json_response(['ok'=>false,'message'=>'Task proof images must be 10 MB or smaller.'],422);$tmp=(string)($file['tmp_name']??'');if($tmp===''||!is_uploaded_file($tmp))app_json_response(['ok'=>false,'message'=>'The uploaded task proof is invalid.'],422);$finfo=new finfo(FILEINFO_MIME_TYPE);$mime=(string)$finfo->file($tmp);$allowed=['image/jpeg'=>'jpg','image/png'=>'png','image/webp'=>'webp'];if(!isset($allowed[$mime]))app_json_response(['ok'=>false,'message'=>'Use a JPEG, PNG, or WebP proof image.'],422);$bytes=file_get_contents($tmp);if(!is_string($bytes)||$bytes==='')app_json_response(['ok'=>false,'message'=>'The uploaded image could not be read.'],422);
$checksum=hash('sha256',$bytes);$stored='task-proof-'.bin2hex(random_bytes(16)).'.'.$allowed[$mime];$relative='storage/task-proofs/'.$organizationId.'/'.$stored;$absolute=RESTAURANT_APP_ROOT.'/'.$relative;$directory=dirname($absolute);if(!is_dir($directory)&&!mkdir($directory,0700,true)&&!is_dir($directory))app_json_response(['ok'=>false,'message'=>'Private task-proof storage could not be created.'],500);if(file_put_contents($absolute,$bytes,LOCK_EX)===false)app_json_response(['ok'=>false,'message'=>'The task proof could not be stored.'],500);@chmod($absolute,0600);
try{$pdo->beginTransaction();$insert=$pdo->prepare("INSERT INTO files (organization_id,storage_driver,storage_path,original_name,stored_name,mime_type,file_size,checksum_sha256,uploaded_by,visibility) VALUES (?,'local_private',?,?,?,?,?,?,?,'organization_private')");$insert->execute([$organizationId,$relative,mb_substr((string)($file['name']??'task-proof'),0,255,'UTF-8'),$stored,$mime,$size,$checksum,$userId]);$fileId=(int)$pdo->lastInsertId();$caption=mb_substr(trim((string)($_POST['caption']??'')),0,500,'UTF-8');$proof=$pdo->prepare("INSERT INTO restaurant_task_proofs (organization_id,task_id,file_id,caption,uploaded_by) VALUES (?,?,?,?,?)");$proof->execute([$organizationId,(int)$task['id'],$fileId,$caption?:null,$userId]);$proofId=(int)$pdo->lastInsertId();operations_task_event($pdo,$organizationId,(int)$task['id'],'proof_uploaded','Photo proof uploaded',$userId,['proofId'=>$proofId,'mime'=>$mime]);$pdo->commit();}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();@unlink($absolute);app_json_response(['ok'=>false,'message'=>'The task proof record could not be saved.'],500);}app_audit($pdo,$organizationId,$userId,'tasks.proof_uploaded','restaurant_task',$taskId,null,['proofId'=>$proofId]);app_json_response(['ok'=>true,'proofId'=>$proofId,'message'=>'Task proof uploaded.'],201);
