<?php
declare(strict_types=1);
require __DIR__.'/../includes/bootstrap.php';
require __DIR__.'/../includes/timeclock-voice-core.php';
$user=app_require_auth();$pdo=app_pdo();$org=(int)$user['organization_id'];$uid=(int)$user['id'];
if(!tv_ready($pdo))app_json_response(['ok'=>false,'message'=>'Time Clock + Voice Agent migration is not installed. Run upgrade.php.'],503);
function tc_can(array $u,string $p):bool{return app_has_permission($p,$u);}function tc_need(array $u,string $p):void{if(!tc_can($u,$p))app_json_response(['ok'=>false,'message'=>'Permission required: '.$p],403);}function tc_error(Throwable $e):never{$s=$e instanceof InvalidArgumentException?422:($e instanceof RuntimeException?403:500);app_json_response(['ok'=>false,'message'=>$e->getMessage()],$s);}
if($_SERVER['REQUEST_METHOD']==='GET'){
  $action=(string)($_GET['action']??'bootstrap');$date=(string)($_GET['date']??date('Y-m-d'));$manager=tc_can($user,'timeclock.view')||tc_can($user,'timeclock.manage')||tc_can($user,'attendance.view');$self=tc_can($user,'timeclock.self');if(!$manager&&!$self)app_json_response(['ok'=>false,'message'=>'Time clock permission required.'],403);
  if($action==='bootstrap'){$profile=tv_voice_profile($pdo,$org,$uid,false);$snapshot=tv_self_snapshot($pdo,$org,$uid);$snapshot['currentBreak']=null;if(!empty($snapshot['clock']['id'])){$b=$pdo->prepare('SELECT id,started_at,break_type,source FROM time_clock_breaks WHERE organization_id=? AND time_clock_entry_id=? AND ended_at IS NULL ORDER BY started_at DESC LIMIT 1');$b->execute([$org,(int)$snapshot['clock']['id']]);$snapshot['currentBreak']=$b->fetch()?:null;}app_json_response(['ok'=>true,'date'=>$date,'self'=>$snapshot,'entries'=>tv_clock_rows($pdo,$org,$date,$manager?null:$uid),'summary'=>$manager?tv_daily_summary($pdo,$org,$date):null,'noShows'=>tc_can($user,'attendance.view')?tv_no_shows($pdo,$org):[],'voiceProfile'=>$profile,'permissions'=>['self'=>$self,'view'=>tc_can($user,'timeclock.view'),'manage'=>tc_can($user,'timeclock.manage'),'attendance'=>tc_can($user,'attendance.view'),'voiceSelf'=>tc_can($user,'voice.self'),'voiceManage'=>tc_can($user,'voice.manage'),'voiceAgent'=>tc_can($user,'voice.agent'),'proactive'=>tc_can($user,'agent.proactive')]]);}
  if($action==='entries'){app_json_response(['ok'=>true,'entries'=>tv_clock_rows($pdo,$org,$date,$manager?null:$uid)]);}
  if($action==='summary'){tc_need($user,'attendance.view');app_json_response(['ok'=>true,'summary'=>tv_daily_summary($pdo,$org,$date),'noShows'=>tv_no_shows($pdo,$org)]);}
  app_json_response(['ok'=>false,'message'=>'Unsupported time clock action.'],422);
}
if($_SERVER['REQUEST_METHOD']!=='POST'){header('Allow: GET, POST');app_json_response(['ok'=>false,'message'=>'Method not allowed.'],405);} $in=app_json_input();app_verify_request_csrf($in);$action=(string)($in['action']??'');
try{
  if(in_array($action,['clock_in','clock_out','break_start','break_end'],true)){tc_need($user,'timeclock.self');$source=(string)($in['source']??'manual');if(!in_array($source,['manual','voice','agent'],true))$source='manual';if($source==='agent')$source='manual';$voice=(string)($in['voiceEventId']??'');$note=(string)($in['note']??'');if($action==='clock_in')$row=tv_clock_in($pdo,$org,$uid,$uid,$source,$note,$voice);elseif($action==='clock_out')$row=tv_clock_out($pdo,$org,$uid,$uid,$source,$note,$voice);else$row=tv_break_action($pdo,$org,$uid,$uid,$action==='break_start'?'start':'end',$source,$voice);app_audit($pdo,$org,$uid,'timeclock.'.$action,'user',(string)$uid,null,['source'=>$source]);app_json_response(['ok'=>true,'result'=>$row,'message'=>str_replace('_',' ',ucfirst($action)).' complete.']);}
  if($action==='correct'){tc_need($user,'timeclock.manage');$id=trim((string)($in['id']??''));$reason=trim((string)($in['reason']??''));if($reason==='')throw new InvalidArgumentException('A correction reason is required.');$cin=trim((string)($in['clockedInAt']??''));$cout=trim((string)($in['clockedOutAt']??''));try{$a=new DateTimeImmutable($cin);$b=new DateTimeImmutable($cout);}catch(Throwable){throw new InvalidArgumentException('Correction times are invalid.');}if($b<=$a)throw new InvalidArgumentException('Clock-out must be after clock-in.');$q=$pdo->prepare('SELECT * FROM time_clock_entries WHERE organization_id=? AND public_id=? LIMIT 1');$q->execute([$org,$id]);$row=$q->fetch();if(!$row)throw new InvalidArgumentException('Time entry not found.');$before=['clocked_in_at'=>$row['clocked_in_at'],'clocked_out_at'=>$row['clocked_out_at']];$pdo->prepare("UPDATE time_clock_entries SET clocked_in_at=?,clocked_out_at=?,status='corrected',corrected_by=?,correction_reason=?,updated_by=?,updated_at=NOW(6) WHERE organization_id=? AND id=?")->execute([$a->format('Y-m-d H:i:s'),$b->format('Y-m-d H:i:s'),$uid,mb_substr($reason,0,1000,'UTF-8'),$uid,$org,(int)$row['id']]);tv_attendance_event($pdo,$org,(int)$row['user_id'],'clock.corrected','Manager corrected a time entry.','warning',$row['schedule_shift_id']?(int)$row['schedule_shift_id']:null,(int)$row['id'],$uid,['before'=>$before,'after'=>['clocked_in_at'=>$a->format('Y-m-d H:i:s'),'clocked_out_at'=>$b->format('Y-m-d H:i:s')],'reason'=>$reason]);app_audit($pdo,$org,$uid,'timeclock.corrected','time_clock_entry',$id,$before,['reason'=>$reason]);app_json_response(['ok'=>true,'message'=>'Time entry corrected with audit history.']);}
  app_json_response(['ok'=>false,'message'=>'Unsupported time clock action.'],422);
}catch(Throwable $e){tc_error($e);}