<?php
declare(strict_types=1);
require __DIR__.'/../includes/bootstrap.php';
require __DIR__.'/../includes/timeclock-voice-core.php';
$user=app_require_auth();$pdo=app_pdo();$org=(int)$user['organization_id'];$uid=(int)$user['id'];if(!tv_ready($pdo))app_json_response(['ok'=>false,'message'=>'Time Clock + Voice Agent migration is not installed. Run upgrade.php.'],503);if(!app_has_permission('timeclock.agent',$user))app_json_response(['ok'=>false,'message'=>'Time-clock Agent permission required.'],403);if($_SERVER['REQUEST_METHOD']!=='POST'){header('Allow: POST');app_json_response(['ok'=>false,'message'=>'Method not allowed.'],405);} $in=app_json_input();app_verify_request_csrf($in);$message=trim((string)($in['message']??''));if($message==='')app_json_response(['ok'=>false,'message'=>'Ask Gelato a time-clock or attendance question.'],422);$lower=mb_strtolower($message,'UTF-8');$voiceEvent=(string)($in['voiceEventId']??'');$voice=!empty($in['voice']);
function ta_fmt_minutes(int $m):string{return intdiv($m,60).'h '.($m%60).'m';}
try{
 $skill='timeclock.self';$answer='';
 if(preg_match('/\bclock\s+(?:me\s+)?in\b/',$lower)){if(!app_has_permission('timeclock.self',$user))app_json_response(['ok'=>false,'message'=>'Personal time-clock permission required.'],403);$row=tv_clock_in($pdo,$org,$uid,$uid,$voice?'voice':'manual','Agent command',$voiceEvent);$skill='timeclock.clock_in';$answer='You are clocked in'.(!empty($row['shift_title'])?' for '.$row['shift_title']:'').'.';}
 elseif(preg_match('/\bclock\s+(?:me\s+)?out\b/',$lower)){if(!app_has_permission('timeclock.self',$user))app_json_response(['ok'=>false,'message'=>'Personal time-clock permission required.'],403);tv_clock_out($pdo,$org,$uid,$uid,$voice?'voice':'manual','Agent command',$voiceEvent);$skill='timeclock.clock_out';$answer='You are clocked out.';}
 elseif(preg_match('/\b(start|take|begin)\s+(?:my\s+)?break\b/',$lower)){if(!app_has_permission('timeclock.self',$user))app_json_response(['ok'=>false,'message'=>'Personal time-clock permission required.'],403);tv_break_action($pdo,$org,$uid,$uid,'start',$voice?'voice':'manual',$voiceEvent);$skill='timeclock.break_start';$answer='Your break has started.';}
 elseif(preg_match('/\b(end|finish|stop)\s+(?:my\s+)?break\b/',$lower)){if(!app_has_permission('timeclock.self',$user))app_json_response(['ok'=>false,'message'=>'Personal time-clock permission required.'],403);tv_break_action($pdo,$org,$uid,$uid,'end',$voice?'voice':'manual',$voiceEvent);$skill='timeclock.break_end';$answer='Your break has ended.';}
 elseif(preg_match('/\b(when do i work|my schedule|next shift|when am i scheduled)\b/',$lower)){$snapshot=tv_self_snapshot($pdo,$org,$uid);$up=array_values(array_filter($snapshot['shifts'],fn($s)=>strtotime((string)$s['ends_at'])>=time()));usort($up,fn($a,$b)=>strcmp((string)$a['starts_at'],(string)$b['starts_at']));$skill='schedule.self_context';$answer=$up?'Your next shift is '.date('l M j, g:i A',strtotime((string)$up[0]['starts_at'])).'–'.date('g:i A',strtotime((string)$up[0]['ends_at'])).' for '.$up[0]['title'].'.':'You have no remaining published shifts this week.';}
 elseif(preg_match('/\b(my tasks|what.*prep|what do i need to do|assigned to me)\b/',$lower)){$snapshot=tv_self_snapshot($pdo,$org,$uid);$skill='tasks.self_context';$answer=$snapshot['tasks']?'You have '.count($snapshot['tasks']).' open assigned task'.(count($snapshot['tasks'])===1?'':'s').': '.implode('; ',array_map(fn($t)=>$t['title'].($t['due_at']?' due '.date('D g:i A',strtotime((string)$t['due_at'])):''),array_slice($snapshot['tasks'],0,6))).'.':'You have no open assigned tasks.';}
 elseif(preg_match('/\b(who.*clocked in|clocked in now|on the clock)\b/',$lower)){if(!app_has_permission('timeclock.view',$user))app_json_response(['ok'=>false,'message'=>'Time-clock view permission required.'],403);$q=$pdo->prepare("SELECT u.display_name,t.clocked_in_at,s.title shift_title FROM time_clock_entries t INNER JOIN users u ON u.id=t.user_id LEFT JOIN schedule_shifts s ON s.id=t.schedule_shift_id WHERE t.organization_id=? AND t.status='open' AND t.clocked_out_at IS NULL ORDER BY t.clocked_in_at");$q->execute([$org]);$rows=$q->fetchAll();$skill='timeclock.active_staff';$answer=$rows?count($rows).' employee'.(count($rows)===1?' is':'s are').' clocked in: '.implode('; ',array_map(fn($r)=>$r['display_name'].' since '.date('g:i A',strtotime((string)$r['clocked_in_at'])).($r['shift_title']?' — '.$r['shift_title']:''),$rows)).'.':'No employees are currently clocked in.';}
 elseif(preg_match('/\b(late|no.?show|missing.*shift|attendance)\b/',$lower)){if(!app_has_permission('attendance.view',$user))app_json_response(['ok'=>false,'message'=>'Attendance permission required.'],403);$rows=tv_no_shows($pdo,$org);$skill='attendance.exceptions';$answer=$rows?'Potential no-shows: '.implode('; ',array_map(fn($r)=>$r['display_name'].' — '.$r['title'].' started '.date('g:i A',strtotime((string)$r['starts_at'])),$rows)).'.':'No current no-shows are detected.';}
 elseif(preg_match('/\b(actual labor|scheduled.*actual|labor today|labor hours today)\b/',$lower)){if(!app_has_permission('attendance.view',$user))app_json_response(['ok'=>false,'message'=>'Attendance permission required.'],403);$s=tv_daily_summary($pdo,$org,date('Y-m-d'));$skill='attendance.labor';$answer='Today has '.ta_fmt_minutes($s['scheduledMinutes']).' scheduled labor and '.ta_fmt_minutes($s['actualMinutes']).' actual clocked labor so far. '.$s['clockedInEmployees'].' employee'.($s['clockedInEmployees']===1?' is':'s are').' currently clocked in.';}
 else{$snap=tv_self_snapshot($pdo,$org,$uid);$skill='timeclock.context';$answer=$snap['clock']?'You are clocked in since '.date('g:i A',strtotime((string)$snap['clock']['clocked_in_at'])).'. Ask me about your schedule, assigned tasks, break, or clocking out.':'You are not clocked in. Ask me about your schedule, assigned tasks, or say “clock me in.”';}
 app_audit($pdo,$org,$uid,'agent.timeclock_skill_used','user',(string)$uid,null,['skill'=>$skill,'voice'=>$voice,'transcript'=>$message]);app_json_response(['ok'=>true,'skill'=>$skill,'answer'=>$answer]);
}catch(Throwable $e){$status=$e instanceof InvalidArgumentException?422:($e instanceof RuntimeException?403:500);app_json_response(['ok'=>false,'message'=>$e->getMessage()],$status);}